client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
There is several spelling mistakes, it's a little confusing and i think we should fix them,like this one :
```java
if (null == prevBrokerLiveInfo) {
log.info("new broker registerd, {} HAServer: {}", brokerAddr, haServerAddr);
}
```
and here is the JIRA link of this issue : https://issues.apache.org/jira/browse/ROCKETMQ-207 ,thanks for your time
=> [ROCKETMQ-207]Correct spelling mistake in RouteInfoManager.java

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/RemotingClient.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java
Currently, the async call back will be executed in a public executor which is mainly used in CHECK_TRANSACTION_STATE, NOTIFY_CONSUMER_IDS_CHANGED, CONSUME_MESSAGE_DIRECTLY, etc. More details please refer to MQClientAPIImpl.
Should expose an interface for the client to specify the independent call back executor.
Add an interface `setCallbackExecutor` in RemotingClient.java and DefaultMQProducer.java
Run the unit tests to verify.
=> [ROCKETMQ-324] Expose an interface for client to specify the async call back executor

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstractTest.java
Currently, the async semaphore will be released before invoking the callback, if the callback is a heavy task which is not recommended, lots of async requests will be queued in `publicExecutor` thread pool, may cause OOM or FGC.
Adjust the release order between callback and response future, release semaphore after callback being finished for async invoke.
Run the provided unit tests.
=> [ROCKETMQ-323] Release semaphore after callback being finished for async invoke

store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java
To resolve the issue [ROCKETMQ-270](https://issues.apache.org/jira/browse/ROCKETMQ-270).
Slave Broker can't flush data to disk normally if the master broker has been cleaned commit log. 
When the flush position is zero and the first MappedFile's start offset is non-zero, move it forward to the first MappedFile's start offset. Otherwise, slave broker can't flush data to disk normally.
1. Start master broker, and write lots of messages until broker starts cleaning commit log.
2. When the first commit log file isn't 00000000000000, start slave broker.
3. Slave broker now can flush data normally.
=> [ROCKETMQ-270] Move flush position forward to first MappedFile whose start offset is non-zero

broker/src/main/java/org/apache/rocketmq/broker/latency/BrokerFastFailure.java, broker/src/test/java/org/apache/rocketmq/broker/latency/BrokerFastFailureTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
Now, the broker will reject send message requests when the waiting time is too long at send queue, pull requests have the same problem and also need fast failure to protect the server.
1. Add a switch `brokerFastFailureEnable` to decide whether supports fast failure and can be changed dynamically
2. Broker fast failure mechanism will cover pull requests queue.
1. Run the unit tests `BrokerFastFailureTest` to verify.
2. Or start the server and accumulate tons of pull requests and observe the effect. 
=> [ROCKETMQ-311] Add pull request fast failure mechanism for broker

store/src/main/java/org/apache/rocketmq/store/MappedFile.java, store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java
Avoid deleting files in the middle.
=> [ROCKETMQ-321] Fix deleting files in the middle

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
Increasing name server component network socket buffer size, improve broker register speed, resolve the issue [ROCKETMQ-308](https://issues.apache.org/jira/browse/ROCKETMQ-308)
delete `NamesrvStartup ` set network socket buffer code,using default value. 
delete code
```java
if (null == System.getProperty(NettySystemConfig.COM_ROCKETMQ_REMOTING_SOCKET_SNDBUF_SIZE)) {
NettySystemConfig.socketSndbufSize = 4096;
}
if (null == System.getProperty(NettySystemConfig.COM_ROCKETMQ_REMOTING_SOCKET_RCVBUF_SIZE)) {
NettySystemConfig.socketRcvbufSize = 4096;
}
```
=> [ROCKETMQ-308] Increasing name server component network socket buffer size

store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java
Fix concurrent bug in MappedFileQueue#findMappedFileByOffset, which may cause message loss
The `findmappedfilebyoffset` method may return the wrong mapped file or null if the delete behavior occurs concurrently.
So change the find process:
1. Find the target mapped file by calculated index.
2. Verify the target mapped file is right.
3. Iterate the whole list and find the right mapped file.
In most cases, it's a O(1) method and will be degrade to O(n) if the concurrent issue occurs.
Review the source code and run the unit/it tests
=> [ROCKETMQ-332] MappedFileQueue#findMappedFileByOffset is not thread safe, which will cause message loss.

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
Standardize the structure of the XxxStartup classes.
Divide current code into multiple methods so that NamesrvStartup has the same batch of methods as BrokerStartup
Nothing breaks after applying this changes
- [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x ] Run `mvn -B clean …
=> [ROCKETMQ-387]Standardize the startup class structure

tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java
#Resolve two coding errors：
path     : package org.apache.rocketmq.tools.command;
class    : MQAdminStartup.java
remove duplicates initCommand at line  158, remove "initCommand(new QueryMsgByUniqueKeySubCommand());"
path     : package org.apache.rocketmq.tools.command.topic;
class    : UpdateTopicSubCommand .java
Add tag ")" behind of  “true|false” in  lines 70/74/78
=> [Minor Fix] Modify Project Tools : remove duplicates initCommand and missing tag ")"

store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java, store/src/test/java/org/apache/rocketmq/store/StoreStatsServiceTest.java
Fix Concurrent issue of StoreStatsService
StoreStatsService#getSinglePutMessageTopicSizeTotal and StoreStatsService#getSinglePutMessageTopicTimesTotal are not thread safe which could return a different instance under high concurrent scenario ,normally this won't happen ,because the cost of creating a AtomicLong and put it into a map can be ignored ,but when that happens, Stats could be inaccuracy
Fix Concurrent issue of StoreStatsService
=> [ISSUE #260] Fix Concurrent issue of StoreStatsService

.travis.yml, test/src/test/java/org/apache/rocketmq/test/client/consumer/balance/NormalMsgDynamicBalanceIT.java
Message will be consumed repeatedly when send before rebalance work finish. Adding a time delay before producer send message is necessary in the integration-test.
Adding a thread-sleep after consumer group enlarged to finish rebalance
=> [ISSUE #354]Add thread-sleep for rebalance before producer send in the integration-test

client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/ResponseFuture.java
JIRA:https://issues.apache.org/jira/browse/ROCKETMQ-184?jql=project%20%3D%20ROCKETMQ
Problem, no listener is triggered when Chanel is close. 
When async command sent to the server, and the server is crash before sending response to client, the callback can not be invoked in time. Instead, the callback can only be triggered by the timeout scan service. 
This is obvious for pulling message since the timeout is by default 30 seconds. So if master crashes before process response to the client, the client can not repull until scan service tell it, which takes at most 30 seconds. And repull will have 3 seconds delay, so the HA to read from slave has to take 3-33 seconds when this problem occurs.
=> [ROCKETMQ-184]-It takes too long(3-33 seconds) to switch to read from slave when master crashes

store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
when run DefaultMessageStoreTest::testPullSize, it should wait  more time to build consume queue.
The sleep time should be greater than commit log flush interval plus consume queue flush interval.
=> [ROCKETMQ-296] fix DefaultMessageStoreTest bug: wait more time for consume queue build

store/src/main/java/org/apache/rocketmq/store/ha/HAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java, store/src/test/java/org/apache/rocketmq/store/ha/WaitNotifyObjectTest.java
Fix the memory leak problem in org.apache.rocketmq.store.ha.WaitNotifyObject#waitingThreadTable
Remove item from WaitNotifyObject#waitingThreadTable when a slave disconnect from master.
This is a trivial change.
=> [ROCKETMQ-290] Fix memory leak in WaitNotifyObject#waitingThreadTable

broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
When sending a transaction check request, ProducerManager returned available connection is not the current connection, but the next connection.
XX
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily.
=> [ISSUE #367]Fix the get connection bug when sending transactional check request

tools/src/main/java/org/apache/rocketmq/tools/command/message/ConsumeMessageCommand.java, tools/src/test/java/org/apache/rocketmq/tools/command/message/ConsumeMessageCommandTest.java
FIX Admin subcommand consumeMessage should quit when catching an exception, see #377 for details.
make the method `pullMessageByQueue ` **return** when catching an exception.
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily.
=> [ISSUE #377] FIX Admin subcommand consumeMessage should quit when catching an exception

tools/src/main/java/org/apache/rocketmq/tools/command/message/ConsumeMessageCommand.java
FIX the issue described in  #379 .
Since the timestamp argument provided to the consumer(*beginTimestamp* or *endTimestamp*
) which is later than now is not valid, we should verify them before we actually pull a message from the broker.
And the following are corresponding changes:
- Add verification of command line argument *beginTimestamp* and *endTimestamp*
- exit the program if any of the arguments are invalid
By the way, I think we should print report messages in the same style, so I change the messages to capitalized.
Follow this checklist to help us incorporate your contribution quickly and easily.
=> [ISSUE #379] FIX admin subcommand consumeMessage can pull message with timestamp greater than now

pom.xml
fix #433
1、Delete maven-failsafe-plugin in plugins
2、Add excludes for maven-surefire-plugin
=> [ISSUE #433] Modify pom.xml to avoid run ntegration-test when "mvn clean install"

broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java
Avoid ClassCastException when get the instance of the store
1、Add method to base class of store;
2、Override method to all Inherited class of store
3、Modify cast in the ViewBrokerStatsData
XXXX
=> [ISSUE #411] Fixed ClassCastException when get the instance of the store

acl/src/main/java/org/apache/rocketmq/acl/AccessValidator.java, acl/src/main/java/org/apache/rocketmq/acl/common/AclClientRPCHook.java, acl/src/main/java/org/apache/rocketmq/acl/common/AclException.java, acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java, acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java, acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java, acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java, acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategy.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceTransferBean.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageTraceHookImpl.java, example/src/main/java/org/apache/rocketmq/example/simple/AclClient.java, example/src/main/java/org/apache/rocketmq/example/tracemessage/TracePushConsumer.java, pom.xml, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
I have already capitalized the first letter in comments and removed the unless comments for acl and msg trace feature codes.
The changed files is as follows.
I have already verified.
=> [ISSUE#662]capitalizing the first letter in comments and removing the unless comments for acl and msg trace feature codes.

remoting/src/main/java/org/apache/rocketmq/remoting/RemotingClientFactory.java, remoting/src/main/java/org/apache/rocketmq/remoting/RemotingServerFactory.java, remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/CodecHelper.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2ClientImpl.java, remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2ServerImpl.java, remoting/src/main/java/org/apache/rocketmq/remoting/util/ServiceProvider.java
resolve the codestyle issue and remoting modle can build successfully.
just adjust some unnecessary codes.
XXXX
=> resolve the codestyle issue.

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionLoaderTest.java
fix defaultTopicPerm and defaultGroupPerm values which are in yaml config file dosen't work.
I have just fixed the issue,and the adjusted code are as follows.
I have just fixed the code which are in the PlainPermissionLoader class file.
I have already verified the changed codes in local enviroment.
=> [issue#790]fix defaultTopicPerm and defaultGroupPerm values which are in yaml config file dosen't work.

store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java, store/src/test/java/org/apache/rocketmq/store/HATest.java
test  for CommitLog.handleHA
Add test case for CommitLog.handleHA
=> [RIP-10] test for CommitLog.handleHA

broker/src/test/java/org/apache/rocketmq/broker/BrokerStatsManagerTest.java, common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItemSet.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java, common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
Fix #515 
to solve multi-thread problem of StatsItemSet#getAndCreateStatsItem.
1. use putIfAbsent instead  #of put method of ConcurrentHashMap and 
2. if the prev is not null then use get method
to avoid multi-thread problem.
test case:
```
/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under …
```
=> [ISSUE#515]Solve multi-thread problem of StatsItemSet#getAndCreateStatsItem

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java, acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java, acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java, acl/src/test/resources/conf/plain_acl_incomplete.yml, common/src/main/java/org/apache/rocketmq/common/MixAll.java, distribution/conf/tools.yml, docs/cn/acl/user_guide.md, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
（1）Move the getAclRPCHook funtion to the Acl module.
（2）Optimize some codes.
（1）I have writes some test cases for my optimize codes.
（1）Move the getAclRPCHook funtion to the Acl module.
（2）Optimize some codes.
=> [ISSUE #1147]Broker will report Exception if open the aclEnable and enableDLegerCommitLog flag at the same time.

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
We use the consumer instance to consume the message from slave node when the master node has been already killed and the TPS of cluster is in the high level.
The consumer instance can consume the message from slave node when the master node has been already killed and the TPS of cluster is in the high level for producing and consuming messages
I have already fix the issue in my local enviroment.
=> [ISSUE #1164]Fix Consumer Instance can't consume message from slave when cluster is in the high level tps and master has been killed.

common/src/main/java/org/apache/rocketmq/common/MqttConfig.java, common/src/main/java/org/apache/rocketmq/common/service/NnodeService.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/client/IOTClientManagerImpl.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/client/InFlightMessage.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/client/InFlightPacket.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/client/MQTTSession.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/constant/MqttConstant.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/mqtthandler/impl/MqttSubscribeMessageHandler.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/service/impl/MqttScheduledServiceImpl.java, mqtt/src/main/java/org/apache/rocketmq/mqtt/task/MqttPushTask.java, mqtt/src/test/java/org/apache/rocketmq/mqtt/MqttPubackMessageHandlerTest.java, mqtt/src/test/java/org/apache/rocketmq/mqtt/MqttSubscribeMessageHandlerTest.java, mqtt/src/test/java/org/apache/rocketmq/mqtt/MqttUtilTest.java
add logic of resending messages when ack-timeout
add a DelayQueue to hold unacked messages, and start a schedule to scan and drain out all ack-timeout messages to do resend.
XXXX
- [√] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [√] Format the pull request title like `[ISSUE #123] Fix …
=> [RIP-11] add logic of resending messages when ack-timeout

distribution/bin/tools.cmd, distribution/bin/tools.sh
when JAVA_HOME is set to JRE, errors throw out as below:
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
org.apache.rocketmq.tools.command.SubCommandException: ClusterListSubCommand command failed
at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:93)
at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:135)
at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:86)
Caused by: org.apache.rocketmq.acl.common.AclException: [10015:signature-failed] unable to calculate a request signature. error=[10015:signaturerithm HmacSHA1 not …
```
=> FIX: HmacSHA1 not found if JAVA_HOME set to JRE

.travis.yml
Fix Travis-CI `Java 8` building environments.
https://github.com/apache/rocketmq/pull/1242
...
=>  [FIX] Travis-CI Java 8 building environments.

client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java
Delay plant log appender in client logger
Delay plant log appender in client logger
Delay plant log appender in client logger
=> Delay plant log appender in client loggger

example/src/main/java/org/apache/rocketmq/example/openmessaging/SimplePullConsumer.java, example/src/main/java/org/apache/rocketmq/example/openmessaging/SimplePushConsumer.java, openmessaging/src/main/java/io/openmessaging/rocketmq/MessagingAccessPointImpl.java, openmessaging/src/main/java/io/openmessaging/rocketmq/config/DefaultQueueMetaData.java, openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/LocalMessageCache.java, openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PullConsumerImpl.java, openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PushConsumerImpl.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/BytesMessageImpl.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/DefaultMessageFactory.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/DefaultMessageReceipt.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/DefaultQueueMetaData.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/MessageExtension.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/MessageExtensionHeader.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/MessageHeader.java, openmessaging/src/main/java/io/openmessaging/rocketmq/domain/NonStandardKeys.java, openmessaging/src/main/java/io/openmessaging/rocketmq/producer/AbstractOMSProducer.java, openmessaging/src/main/java/io/openmessaging/rocketmq/producer/ProducerImpl.java, openmessaging/src/main/java/io/openmessaging/rocketmq/utils/OMSClientUtil.java, openmessaging/src/main/java/io/openmessaging/rocketmq/utils/OMSUtil.java, openmessaging/src/test/java/io/openmessaging/rocketmq/consumer/LocalMessageCacheTest.java, openmessaging/src/test/java/io/openmessaging/rocketmq/consumer/PullConsumerImplTest.java, openmessaging/src/test/java/io/openmessaging/rocketmq/consumer/PushConsumerImplTest.java
#1199 Implement the 1.0.0 openmessaging new consumer API for rocketmq oms module
1、Adapt to the new consumer api
2、Adjust consumer example
3、Optimize consumer code implementation
4、Fix bug
=> [ISSUE #1199] Implement the 1.0.0 openmessaging new consumer API for rocketmq oms module

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDispatcher.java
Fix the bug when there are more than one producer (or consumer) , the Tracer can not show all trace infomation.
[ISSUE 1188](https://github.com/apache/rocketmq/issues/1188)
Set different ProducerGroup for different TraceProducer, the ProducerGroup will like `_INNER_TRACE_PRODUCER-user-specified-producer-group`
Produce and consume message for a same topic in the same process, the console show both produce and consume information.
=> [ISSSUE 1188]Fix the problem when more than one producer or consumer in the same process can trace only one

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyEncoder.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstractTest.java
According to the network topology of RocketMQ, it’s possible that a broker has hundreds of (even thousands of) netty channels established with members (especially consumers). If each stateless handler can be shared by all of these channels, memory should be saved slightly.
1. Annotate stateless netty handlers with @Sharable.
HandshakeHandler
NettyEncoder
NettyConnectManageHandler
NettyServerHandler
2. Share each single-instanced handler with all the server-side channels, instead of creating a new handler instance whenever a channel comes.
It functions well and passed all the unit tests after this change.
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not …
=> Enhance: share netty handler

client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumerScheduleService.java
Current, MQPullConsumerScheduleService has no ways to inject a custom RPCHook, this PR add RPCHook construct method for MQPullConsumerScheduleService,  used to set an RPChook when creating this service.
Add RPCHook construct method for MQPullConsumerScheduleService
XXXX
=> [#1315]Add RPCHook construct method for MQPullConsumerScheduleService

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/filter/CommitLogDispatcherCalcBitMap.java, common/src/main/java/org/apache/rocketmq/common/ServiceThread.java, common/src/main/java/org/apache/rocketmq/common/UtilAll.java, common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItem.java, common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItemSet.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java, common/src/test/java/org/apache/rocketmq/common/protocol/QueryConsumeTimeSpanBodyTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/common/ServiceThread.java, store/src/main/java/org/apache/rocketmq/store/AllocateMappedFileService.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MappedFile.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, store/src/main/java/org/apache/rocketmq/store/index/IndexFile.java
#1308
Fix some spelling errors of method names in file named 'UtilAll.java'
These changes seem trivial, but it's an international project and I think the right naming helps other developers understand it.
the UtilAll.computeEclipseTimeMilliseconds was modified to UtilAll.computeElapsedTimeMilliseconds
(I think this method is to calculate the elapsed time by giving the start time.)
'computNextMorningTimeMillis' was modified to 'computeNextMorningTimeMillis '
'computNextHourTimeMillis' was modified to 'computeNextHourTimeMillis '
'computNextMinutesTimeMillis' was modified to 'computeNextMinutesTimeMillis '
'computNextHalfHourTimeMillis' was modified to 'computeNextHalfHourTimeMillis '
Nothing.
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it …
=> [ISSUE #1308] Fix some spelling errors of method names.

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
When no message is sent, the master and slave connections are not frequently disconnected.
The logic of reporting heartbeat on slave has been adjusted to make it work better.
Adjusted lastWriteTimestamp of HAClient.
Start a master and slave in the default way. Whether or not a message is sent, the master will not disconnect from the slave unless there is an exception.
=> [ISSUE #1082] Fix disconnection of HA

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumerScheduleService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumer.java
Deprecated the DefaulteMQPull consumer, and recommend users to use LitePullConsumer.
XX
XXXX
=> Deprecated the DefaulteMQPull consumer 

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
Fix replica recover slow issue
In the current design, there is no way to update the Checkpoint PhysicMsgTimestamp for replica server, so the update logic for PhysicMsgTimestamp is added to the Reput logic.
=> [ISSUE #1456]Fix replica abnormal recover slow issue

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
fix bug: Concurrent problems with client-side connection creation
Modify a method createChannel
There will be no connection creation problem under multithreading.
=> [ISSUE #1108] Fix concurrent problems with client-side connection creation

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
In jepsen test, consumer lost messages when using the lite pull consumer. This is due to the incorrect setting of consume offset. Delete the wrong code to make it correct.
Delete the wrong code to make it correct.
Verified in jepsen test.
=> Fix(client): lite pull consumer lost messages in some scenario

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
fix #1491
If shutdown of the JVM in progress already, we don't need to remove the hook, just ignore the IllegalStateException.
Ignore IllegalStateException when remove shutdown hook
=> [ISSUE 1491] Ignore IllegalStateException when remove shutdown hook

client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
work for this [issue](https://github.com/apache/rocketmq/issues/1528), make the producer execute in expected logic.
mock function getTopicRouteInfoFromNameServer(), and modify the way mocking send function
=> [ISSUE #1528] mocking related functions to make producer get right topicrouteinfo and invoke callback functions

broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
Optimise performance/stability of  transaction message
1. Add -n (nameServer) option to benchmark consumer; Enable options(-n/-t/w/-s/-c/-r) to TransactionProducer
1. Fix bug that tx message will be checked even it has been committed or rollback.(Half message with unknown status may cause a lots of unnecessary check to half messages which send in 6 seconds before check startTime)
1. Fix problem when queue of transaction check ExecutorService is full
1. Optimise transaction check performance: fix problem that processed opOffset not add to doneOpOffset
1. Change log level, optimise performance of endTransaction and txCheckTask.(This may cause rate limit for endTransaction operation, but send half message is not limited so lots of commit/rollback operations lost)
=> [ISSUE #1519]Optimise performance/stability of  transaction message

broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java, broker/src/test/java/org/apache/rocketmq/broker/client/ProducerManagerTest.java
work for this [issue](https://github.com/apache/rocketmq/issues/670),  avoid ConcurrentModificationException which caused by access groupChannelTable and newGroupChannelTable at the same time
modify the way to create newGroupChannelTable in fuction getGroupChannelTable()
XXXX
=> [issue #670]change the way to create newGroupChannelTable

example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java, srvutil/src/main/java/org/apache/rocketmq/srvutil/ServerUtil.java
I enhanced the tx benchmark producer,  it can detect unexpected tx check and duplicated tx check.
usage:
```
usage: TransactionProducer [-b <arg>] [-cr <arg>] [-cu <arg>] [-h] [-i <arg>] [-n <arg>] [-s <arg>] [-sr
<arg>] [-su <arg>] [-t <arg>] [-w <arg>]
-b,--test batch id <arg>          test batch id, Default: System.currentMillis()
-cr,--check rollback rate <arg>   Check rollback rate, Default: 0.0
-cu,--check unknown rate <arg>    Check unknown rate, Default: 0.0
-h,--help                         Print help
-i,--send interval <arg>          sleep interval in millis between messages, Default: 0
-n,--namesrvAddr <arg>            Name server address list, eg: 192.168.0.1:9876;192.168.0.2:9876
-s,--messageSize <arg>            Message Size, Default: 2048
-sr,--send rollback rate <arg> …
```
=> Optimise tx benchmark producer

store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
Fix problem that a message loop between SCHEDULE_TOPIC_XXXX and RMQ_SYS_TRANS_HALF_TOPIC for ever util reach transactionCheckMax.
=> Avoid delay message in schedule queue enter half message queue

client/src/main/java/org/apache/rocketmq/client/Validators.java, client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java
Fix #1110 
Max topic length in `org.apache.rocketmq.client.Validators#checkTopic` is 255, but is `Byte.MAX_VALUE`(127) in `org.apache.rocketmq.store.DefaultMessageStore#putMessage`.
Sending message with topic length between 128 and 255 will get a error with code 13.
It's better to reject the message when topic length is bigger than 127.
Change max topic length in client validators to 127.
=> [ISSUE #1110] Fix wrong topic max length in rocketmq client.

tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/CheckMsgSendRTCommand.java
mqadmin tools with command clusterRT/checkMsgSendRT, there are
spell error for message amount in long format option type.
=> [ISSUE #1620]fix #1620 amout spell error

common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java, common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
Fix bug: The stats data could be inaccurate of first minute/hour/day
Fix ISSUE#1656: The stats data could be inaccurate of first minute/hour/day
Before we add the first real CallSnapshot, we should initialize a snapshot with a timestamp ahead of one sampling period, values of 0, and put it in the first.
yes
=> [ISSUE #1656] Fix StatsItem bug

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
fix typo
Fix [Issue](https://github.com/apache/rocketmq/issues/1724)
fix typo 
XXXX
=> [ISSUE # 1724]typo fix

example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
Optimise benchmark consumer, add consume fail rate option.
So we can mock some failure of consumer.
=> optimise benchmark consumer, add consume fail rate option

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
Fix the bug when use queryMsgByKey or queryMsgByUniqueKey command in aclEnable = true
Filter out the UNIQUE_MSG_QUERY_FLAG attribute when constructing the authentication content to compute the signature
=> [ISSUE #1409] Fix the bug when use queryMsgByKey or queryMsgByUniqueKey command in aclEnable = true

store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
In DefaultMessageStoreCleanFilesTest, there is no IndexFile clean, this pr adds it.
=> Add delete IndexFile unit test

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
close [issue](https://github.com/apache/rocketmq/issues/1879)
XX
XXXX
=> [ISSUE #1879] Prevent blocked by group transfer service

filter/src/main/java/org/apache/rocketmq/filter/expression/BooleanConstantExpression.java, filter/src/main/java/org/apache/rocketmq/filter/expression/ComparisonExpression.java, filter/src/main/java/org/apache/rocketmq/filter/expression/ConstantExpression.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java
Referencing subclass BooleanConstantExpression from superclass ConstantExpression initializer might lead to class loading deadlock
=> [ISSUE #1906] The BooleanConstantExpression might lead to class loading deadlock

pom.xml
Fastjson has a serious security problem in 1.2.62,which will cause RCE
Fix https://github.com/apache/rocketmq/issues/2007
Fastjson has a serious security problem in 1.2.62,which will cause RCE
Fastjson has a serious security problem in 1.2.62,which will cause RCE
Fastjson has a serious security problem in 1.2.62,which will cause RCE
=> [ISSUE #2007]Fastjson has a serious security problem in 1.2.62,which will cause RCE

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItemSet.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java, common/src/test/java/org/apache/rocketmq/common/BrokerConfigTest.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java, store/src/test/java/stats/BrokerStatsManagerTest.java
Fix ISSUE 1689, remove unused statsItems when topic or group deleted.
XX
XXXX
=> [ISSUE #1689]add interfaces to remove unused statsItems in BrokerStatsManager

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
work for this [issue](https://github.com/apache/rocketmq/issues/1400), add a thread to do disk space detection
add another ScheduledExecutorService to do disk space detection
XXXX
=> [ISSUE #1400]do disk space detection in another thread

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
fix npe problem
```
ProcessQueue processQueue = assignedMessageQueue.getProcessQueue(messageQueue);
//  "processQueue" is nullable here. line 653
if (processQueue == null && processQueue.isDropped()) {
log.info("The message queue not be able to poll, because it's dropped. group={}, messageQueue={}", defaultLitePullConsumer.getConsumerGroup(), this.messageQueue);
return;
}
```
change to 
```
ProcessQueue processQueue = assignedMessageQueue.getProcessQueue(messageQueue);
//  "processQueue" is nullable here. line 653
if (processQueue != null && processQueue.isDropped()) {
log.info("The message queue not be able to poll, because it's dropped. group={}, messageQueue={}", defaultLitePullConsumer.getConsumerGroup(), this.messageQueue);
return;
}
```
```
ProcessQueue processQueue = …
```
=> [ISSUE #2044] Fix DefaultLitePullConsumerImpl NPE

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
fix bug: doAfterRpcHooks execute twice.
bug fix
doAfterRpcHooks only called in callback
=> [ISSUE #1931]duplicate doAfterRpcHooks bugfix

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
Issue :  #2085 
For now, RocketMQ does not support a graceful shutdown for push consumer, which means that when a user shutdown a push consumer, the threadpool will shutdown but rocketmq client will not wait for the existing task to be completed, which may cause 
1. Error is found when shutdown. Since the application since application may shutdown some external source like datasource when application shutdowns, so the existing task may fail.
2. Message duplication. Even though the task can be completed, since rocketmq will update consumer offset after the shutdown method returns, so the latest consumer offset should be updated after the remaining tasks are completed
Add a parameter awaitTerminationMillisWhenShutdown(default is 0), to determine how long should the rocketmq client to await …
=> [ISSUE#2085]support graceful shutdown push consumer

common/src/main/java/org/apache/rocketmq/common/protocol/NamespaceUtil.java
replace  StringBuffer to StringBulder
replace  StringBuffer to StringBulder
replace  StringBuffer to StringBulder
=> [ISSUE #2082] Use StringBuilder instead of StringBuffer.

client/src/main/java/org/apache/rocketmq/client/stat/ConsumerStatsManager.java, common/src/main/java/org/apache/rocketmq/common/stats/RTStatsItem.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java, common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java, common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
fix issue #2088, to make the log output of RT stat makes sense.
Change the log output format for RT stat
Start consumer and consume message. After a few minutes, check the log output, the stat of RT should be like 
[CONSUME_RT] [topic_xxxx@xxxx-consumer] Stats In One Minute, TIMES: 256807  AVGRT: 812.68
=> [ISSUE #2088] Optimize rocketmq client's stats of RT to make sense

broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java, broker/src/test/java/org/apache/rocketmq/broker/client/ProducerManagerTest.java
spelling mistake  and code optimization
1. change the method name from "getAvaliableChannel" to "getAvailableChannel"
2. change the field name from "GET_AVALIABLE_CHANNEL_RETRY_COUNT" to "GET_AVAILABLE_CHANNEL_RETRY_COUNT"
3. optimizing “getAvailableChannel” 
```java
List<Channel> channelList = new ArrayList<Channel>();
ConcurrentHashMap<Channel, ClientChannelInfo> channelClientChannelInfoHashMap = groupChannelTable.get(groupId);
if (channelClientChannelInfoHashMap != null) {
for (Channel channel : channelClientChannelInfoHashMap.keySet()) {
channelList.add(channel);
}
} else {
log.warn("Check transaction failed, channel table is empty. groupId={}", groupId);
return null;
}
```
with
```java
List<Channel> channelList;
ConcurrentHashMap<Channel, ClientChannelInfo> …
```
=> [ISSUE #2283] Fix the spelling mistake in ProducerManager & some code optimization（CodeStyle）

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java
提交主要在修改函数名的英文单词拼写错误。
第一个修改为org.apache.rocketmq.client.impl.consumer.PullAPIWrapper#computePullFromWhichFilterServer函数，该函数为private类型，不会对用户使用造成影响。
第二个修改为org.apache.rocketmq.client.impl.consumer.ProcessQueue#makeMessageToConsumeAgain函数，该函数为public类型，其引用位置也一并修改了，用于指定消息的回滚操作。
第三个修改为org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#pullMessage函数，在从Broker拉取到消息后的回调方法pullCallback.onSuccess()中，NO_NEW_MSG和NO_MATCHED_MSG类型的处理逻辑完全一致，可以合并case。
=> [ISSUE #2272] Fix  spelling mistakes

client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/producer/MQProducer.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
Add some asynchronous API for batch messages
Add some asynchronous API for batch messages
XXXX
=> [ISSUE #2219]  Add some asynchronous API for batch messages

broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Polish the log and response remark when service not available
XX
XXXX
=> [ISSUE #2334] Polish the log and response remark when service not available

client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByMachineRoom.java
fix the allocate algorithm in AllocateMessageQueueByMachineRoom，then consumer will only consume messages in designated idcs
use premqAll to allocate
when we use AllocateMessageQueueByMachineRoom in DefaultMQPushConsumer，the consumer should only consume messages in consumeridcs configed in AllocateMessageQueueByMachineRoom.
=> [ISSUE #2477] Fix allocate algorithm in AllocateMessageQueueByMachineRoom

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
=> [ISSUE #1904] Print log when flush timeout

broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
registerBrokerResultList will invoke add in separate threads, therefore it's not safe to use ArrayList,  fix #1678
Follow existing code pattern https://github.com/apache/rocketmq/blob/master/broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java#L268 
to use thread-safe CopyOnWriteArrayList 
XXXX
=> [ISSUE #1678] Use thread safe CopyOnWriteArrayList for registerBrokerResultList

.travis.yml
More and more software development is being done on ARM64 CPU architecture.
It would be good if RocketMQ is being regularly tested on ARM64.
Add a TravisCI job that runs the build on ARM64 architecture.
The ARM64 nodes at TravisCI are available only for Ubuntu 18.04+, i.e. `bionic` and `focal`. 
There is no `jdk: oraclejdk8` for `bionic` so I needed to install it manually from Ubuntu repositories. The extra benefit is the newer JDK build. Travis `oraclejdk8` image comes with 1.8.0_151, while the Ubuntu repository installs 1.8.0_275 (the latest available at the moment). 
I've also added caching for the downloaded Maven dependencies. This reduces a bit the job execution time.
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful …
=> [ISSUE #2541] Add a TravisCI job to build and test on ARM64

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Fix #2133 
The DefaultMessageStore.cleanUnusedTopic should not delete RMQ_SYS_TRANS_OP_HALF_TOPIC
XXXX
=> [ISSUE #2133] Fix RMQ_SYS_TRANS_OP_HALF_TOPIC be deleted when deleting topic/group.

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
fix thread problem
fix: resetOffset simultaneously will cause each message consume more than once
=> [ISSUE #2449]  fix: resetOffset simultaneously will cause each message consume more than once

tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java
https://github.com/apache/rocketmq/issues/2670
When there is no `-s true` in command ConsumerProgress,  the `N/A`s may make people confused. This change is to hiding `Client IP` when not necessary.
Hide` Client IP` when no `-s true`  appeared in command ConsumerProgress.
=> [ISSUE #2670]Hide Client IP when there's no `-s true`  in command ConsumerProgress

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, common/src/main/java/org/apache/rocketmq/common/filter/FilterAPI.java, common/src/test/java/org/apache/rocketmq/common/filter/FilterAPITest.java
The buildSubscriptionData function in FilterAPI. java  is used to build the SubscriptionData object, and the parameter of this function contains the ConsumerGroup, Topic and Substring. But the SubscriptionData does not have the ConsumerGroup property, and this parameter is not used in this function, so I deleted this parameter and changed the place where the  buildSubscriptionData function is called
#2710
=> [ISSUE #2710] Delete unused parameters

remoting/src/main/java/org/apache/rocketmq/remoting/netty/TlsHelper.java
fix #1233
Tested with OpenSSL 1.1.1
before fixing：
openssl s_client -connect 172.16.41.1:9876
...
R
RENEGOTIATING
depth=0 CN = example.com
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = example.com
verify return:1
after fixing：
openssl s_client -connect 172.16.41.1:9876
...
R
RENEGOTIATING
140672690749888:error:1409444C:SSL routines:ssl3_read_bytes:tlsv1 alert no renegotiation:../ssl/record/rec_layer_s3.c:1528:SSL alert number 100
=> [ISSUE #1233] Fix CVE-2011-1473

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java, common/src/main/java/org/apache/rocketmq/common/PopAckConstants.java, common/src/main/java/org/apache/rocketmq/common/constant/ConsumeInitMode.java, common/src/main/java/org/apache/rocketmq/common/constant/LoggerName.java, common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java, common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java, common/src/main/java/org/apache/rocketmq/common/message/MessageQueueAssignment.java, common/src/main/java/org/apache/rocketmq/common/message/MessageRequestMode.java, common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java, common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/ConsumerRunningInfo.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/PopProcessQueueInfo.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/QueryAssignmentRequestBody.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/QueryAssignmentResponseBody.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/SetMessageRequestModeRequestBody.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/AckMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ChangeInvisibleTimeRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ChangeInvisibleTimeResponseHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ExtraInfoUtil.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PopMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PopMessageResponseHeader.java, common/src/main/java/org/apache/rocketmq/common/utils/DataConverter.java
This is "common" submodule of contribution for RIP-19
Add some necessary codes to support RIP-19
=> [RIP-19] Pop Consuming (submodule "common")

broker/pom.xml, broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/BrokerPathConfigHelper.java, broker/src/main/java/org/apache/rocketmq/broker/loadbalance/AssignmentManager.java, broker/src/main/java/org/apache/rocketmq/broker/loadbalance/MessageRequestModeManager.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/NotifyMessageArrivingListener.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopRequest.java, broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/util/MsgUtil.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AckMessageProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopBufferMergeServiceTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessorTest.java, client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragely.java, client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragelyByCircle.java, distribution/conf/logback_broker.xml, pom.xml, remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java, store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java
This is "broker" submodule of contribution for RIP-19
- Add QueryAssignment processor to control whether using pop mode or not.
- Add core Pop/Ack/ChangeInvisible interface
- Add pop consuming implementation using ScheduleService of store
=> [RIP-19] Pop Consuming (submodule "broker")

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java, common/src/test/java/org/apache/rocketmq/common/utils/NameServerAddressUtilsTest.java
=> [ISSUE #2803] Fix the endpoint cannot get instanceId without http

store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
=> [ISSUE #2811] Fix the wrong topic was consumed in the DefaultMessageStoreTest test program

store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
Overriding the ServiceThread#shutdown in HAClient class, In order to call closeMaster method after HAClient#shutdown is called
for issue #2821
=> [ISSUE #2821] Overriding the ServiceThread#shutdown in HAClient class, In order to call closeMaster method after HAClient#shutdown is called

client/src/main/java/org/apache/rocketmq/client/hook/EndTransactionContext.java, client/src/main/java/org/apache/rocketmq/client/hook/EndTransactionHook.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceBean.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionTraceHookImpl.java, client/src/test/java/org/apache/rocketmq/client/trace/TraceDataEncoderTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java
In order to send commit/rollback trace data, add "EndTransactionHook", and register the hook if enableMsgTrace is true.
Add a new type of trace data, "EndTransaction"  to indicate that a commit/rollback is sent
XXXX
- [y] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR …
=> [ISSUE #2833] Support trace for TranscationProducer

client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
see issue #2732 
this commit will help reproduce the bug : https://github.com/areyouok/rocketmq/commit/a54599ec45f2473acb647d2e7b15eb55983607d7
1. method updatePullOffset should check proccessQueue is valid.
2. if proccessQueue is invalid, skip pull task
=> [ISSUE #2732] Fix message loss problem when rebalance with LitePullConsumer

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java, example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java
=> fix some nonconformity after checkstyle

client/pom.xml, client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageOpenTracingHookImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionOpenTracingHookImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageOpenTracingHookImpl.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java, example/pom.xml, example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingProducer.java, example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingPushConsumer.java, example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java
support opentracing for rocketmq client
- [ :heavy_check_mark:] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ :heavy_check_mark:] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit …
=>  [ISSUE  #2860]  support opentracing for rocketmq client

broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
1. **Change log level to debug: "Half offset {} has been committed/rolled back"**
2. Optimise lock in WaitNotifyObject
3. Remove lock in HAService
4. Remove lock in GroupCommitService
5. Eliminate array copy in HA
7. Change default value of some parameters: sendMessageThreadPoolNums/useReentrantLockWhenPutMessage/flushCommitLogTimed/endTransactionThreadPoolNums
=> [ISSUE #2883] [Part A] Improve produce performance in M/S mode.

example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java
=> [ISSUE #2898] Resolve rocketmq-example project failed during checkstyle execution.

client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/impl/factory/MQClientInstanceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java, client/src/test/resources/log4j2.xml, example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java, logging/src/main/java/org/apache/rocketmq/logging/inner/SysLogger.java, pom.xml
Improve unit test stability. `mvn clean package` sometimes will fail with strange issues, and retry will solve it. So i try to fix and stabilize these issues.
I found the main issue is caused by powermock & mockito compatibility which results strange mock problems, so i remove powermock dependency.
XXXX
=> Fix unit test stability

remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
To filter out docker0 when finding a local address
If the address of docker0 bridge was set as brokerIP1 or brokerIP2 of the master node, the client or slave couldn't establish a connection with it.
Filter out docker0 when finding a local address
=> [ISSUE #1057]Filter out docker0 when finding a local address

docs/cn/RocketMQ_Example.md
As the test results showed, the message delay period starts from the `bornTimestamp`, not from `storeTimestamp`.
经过测试，delay的计算是根据`bornTimestamp`，而不是`storeTimestamp`。
=> [ISSUE# XXXX] Change the message delay starts point

example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
1. Set the default value of isSuffixEnable which belong to benchmark`s consumer to false.
2. Update the help info abou isSuffixEnable
=> [ISSUE #2607] Set benchmark`s consumer isSuffixEnable default false and update help info

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
[#2863]  fix the problem of potential NPE in ACL plain and revise codeStyle
=> fix the problem of potential NPE in ACL plain

store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
When the master change occurs in the DLedger mode, a large number of delay messages and retry messages will be consumed repeatedly due to no delay offset reloading.
Reload the delay offset when master changed
Verified in my environment
=> [ISSUE #2357] Reload the delay offset when ScheduleMessageService start

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java
when user has multi producer with same group name in project, only first can register trace producer. Others will occur "trace dispatcher start failed. The producer group[_INNER_TRACE_PRODUCER-groupName-PRODUCE] has been created before"
=> [ISSUE #3004] Fix AsyncTraceDispatcher unique groupName

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
1. Change log level to debug: "Half offset {} has been committed/rolled back"
2. Optimise lock in WaitNotifyObject
3. Remove lock in HAService
4. Remove lock in GroupCommitService
5. Eliminate array copy in HA
7. **Change default value of some parameters: sendMessageThreadPoolNums/useReentrantLockWhenPutMessage/flushCommitLogTimed/endTransactionThreadPoolNums**
=> [ISSUE #2883] [Part D] Improve produce performance in M/S mode. 

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
#3118 
- Solve the problem of abnormal type conversion when batch sending triggers pending full.
- First judge whether pendingFull is triggered, and then turn to BatchAppendFuture when append is normal
XXXX
=> [ISSUE #3118] Fix type conversion exception

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/ha/HAService.java, store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java
1. Change log level to debug: "Half offset {} has been committed/rolled back"
2. **Optimise lock in WaitNotifyObject**
3. **Remove lock in HAService**
4. **Remove lock in GroupCommitService**
5. Eliminate array copy in HA
7. Change default value of some parameters: sendMessageThreadPoolNums/useReentrantLockWhenPutMessage/flushCommitLogTimed/endTransactionThreadPoolNums
=> [ISSUE #2883] [Part B] Improve produce performance in M/S mode. 

broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
1. Change log level to debug: "Half offset {} has been committed/rolled back"
2. Optimise lock in WaitNotifyObject
3. Remove lock in HAService
4. Remove lock in GroupCommitService
5. **Eliminate array copy in HA**
7. Change default value of some parameters: sendMessageThreadPoolNums/useReentrantLockWhenPutMessage/flushCommitLogTimed/endTransactionThreadPoolNums
=> [ISSUE #2883] [Part C] Improve produce performance in M/S mode. 

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java
=> [ISSUE #3123]fix namesrv endpoint

docs/cn/best_practice.md, docs/en/best_practice.md
Update the docs
docs remove obsolete/error configuration
XXXX
=> [ISSUE #3097] docs remove obsolete/error configuration

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
issue #3021
In different consumption modes, the meaning of maxReconsumeTimes being -1 is not the same.
In concurrently mode, -1 means 16. In orderly mode, -1 means Integer.MAX_VALUE.
It can give users or source code readers better guidance.
Improve the comment of maxReconsumeTimes.
=> [ISSUE #3021] Improve the comment of maxReconsumeTimes.

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyClientConfigTest.java
#2715
expose the netty parameters  by system property
- i ignore channelNotActiveInterval and clientPooledByteBufAllocatorEnable because there are used nowhere
-  i ignore clientCallbackExecutorThreads and useTLS because they can configured in ClientConfig
XXXX
=> [ISSUE #2715] make netty parameter configure by system property

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java, common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java, store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
1. Change log level to debug: "Half offset {} has been committed/rolled back"
2. Optimise lock in WaitNotifyObject
3. Remove lock in HAService
4. Remove lock in GroupCommitService
5. Eliminate array copy in HA
7. Change default value of some parameters: sendMessageThreadPoolNums/useReentrantLockWhenPutMessage/flushCommitLogTimed/endTransactionThreadPoolNums
12. fix ipv6 problem introduced in …
=> [ISSUE #2883] [Part F] Improve produce performance in M/S mode.

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, client/src/main/java/org/apache/rocketmq/client/producer/RequestFutureTable.java
Fix the issue of check style in client and broker modules.
Fix the issue of check style in client and broker modules.
I have already run the maven build command in my local enviroments.
=> [Issue3205]Fix the issue of check style in client and broker modules.

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java, store/src/test/java/org/apache/rocketmq/store/StoreStatsServiceTest.java
Use LongAdder instead of AtomicLong in BrokerStatsService to improve performance.
Test shows that this commit improved 5.4% tps for little messages (about 300 bytes) .
=> [ISSUE 3194] [PART A] Use LongAdder instead of AtomicLong in BrokerStatsService to improve performance.

example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
=> [ISSUE #3284]Optimize the buildMessage method

client/pom.xml, client/src/main/java/org/apache/rocketmq/client/trace/TraceView.java, client/src/test/java/org/apache/rocketmq/client/trace/TraceViewTest.java
https://github.com/apache/rocketmq/issues/3333
There is only one class (org.apache.commons.codec.Charsets) of commons-codec is used in rocketmq, which can be replaced with java.nio.charset.StandardCharsets (java 7).
So the commons-codec can be removed.
=> [ISSUE #3333] Remove commons-codes dependency

docs/cn/operation.md, docs/en/operation.md
=> [ISSUE #3339] (doc)fix typo in update operation.md

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
There are some hard code timeout in MQClientInstance mqClientApiImpl request, such as 3 * 1000 following
```java
public boolean updateTopicRouteInfoFromNameServer(final String topic, boolean isDefault,
DefaultMQProducer defaultMQProducer) {
try {
if (this.lockNamesrv.tryLock(LOCK_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)) {
try {
TopicRouteData topicRouteData;
if (isDefault && defaultMQProducer != null) {
topicRouteData = this.mQClientAPIImpl.getDefaultTopicRouteInfoFromNameServer(defaultMQProducer.getCreateTopicKey(),
3 * 1000);
if (topicRouteData != null) {
for (QueueData data : topicRouteData.getQueueDatas()) {
int queueNums = Math.min(defaultMQProducer.getDefaultTopicQueueNums(), data.getReadQueueNums());
data.setReadQueueNums(queueNums);
data.setWriteQueueNums(queueNums);
}
}
```
=> [ISSUE #3314] Make mqClientApi request timeout settable

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
1. use local variable save remote addr. avoid double parse create too much string.
=> [ISSUE #3346]Avoid double parse remoteAddr in rpcHook call

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/DefaultTransactionalMessageCheckListener.java
Broker use Math.abs(random.nextInt() % 99999999) to choose a queue for message, which is not necessary
It can be replaced with ThreadLocalRandom.current().nextInt(99999999) for higher performance
=> [ISSUE #3225]change Random to ThreadLocalRandom in broker

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/UtilAll.java, common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java, tools/src/main/java/org/apache/rocketmq/tools/command/acl/DeleteAccessConfigSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/acl/UpdateGlobalWhiteAddrSubCommand.java
#3281 fix fail to delete topic perm list 
#3128 still cant delete global white address 
- the pr #3132 missed the client side, and its still sending null, resulting in global white address not updated
#3177 updateAclConfig in all brokers
- the pr #3184 only chages updateAclConfig, missed deleteAccessConfig and updateGlobalWhiteAddr
XX
XXXX
=> [ISSUE #3281 ][acl] fix fail to delete topic perm list and global white address(#3128)

docs/cn/RocketMQ_Example.md
当使用 4.3.0 版本依赖时，当调用同步发送消息代码时，提示：Exception in thread "main" org.apache.rocketmq.client.exception.MQClientException: No route info of this topic，修改为当前最新版本 4.9.1 后问题解决。
=> [ISSUE #XXXX] Update rocketmq client maven version

example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
最近使用RocketMQ pull API做了消息同步的功能，也就是将指定topic消息从一个集群同步到另外一个集群。
考虑到性能因素，第一印象就是使用pull API。
这个功能在编写的过程中，发现simple里的demo并不适用于生产环境。
使用PULL API应该考虑一下几点：
1.消息队列的负载均衡
2.消费进度的存储
3.PullResult的处理
4.性能监控
性能测试结果：
条件：
1. 配置为2c 4g容器
2. 消息大小500字节
3. 注册了16个topic
4. 从一个mq集群拉取消息发送到另外一个集群
结果：tps 10w+
注：
RocketMQ压测时发现：
1.当内存有消息堆积时也就是free接近0，大部分内存都被pagecache占用时，发送性能会产生波动。
这个时候内存free的空间可能在zone 的min watermark和low watermark之间此时触发kswapd异步回收空间；
也可能在min watermark之下 此时会触发direct reclaim（同步等待内存回收，然后完成内存分配，耗时操作应用阻塞）。
建议适适当调整sysctl -w vm.min_free_kbytes=524288参数，让free稳定在一个可接受的水平提升mq性能的稳定性。
2.拉取消息时，如果是从磁盘拉取，一次只能返回8个消息。
=> [ISSUE #3308] production level pull api demo

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, common/src/main/java/org/apache/rocketmq/common/UtilAll.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/main/java/org/apache/rocketmq/store/MultiPathMappedFileQueue.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java, store/src/test/java/org/apache/rocketmq/store/MultiPathMappedFileQueueTest.java
Follow up PR of #3348 
Update according to  comments, see change log
1. remove isMultiCommitlogPathEnable
2. In org.apache.rocketmq.store.DefaultMessageStore.CleanCommitLogService#isSpaceToDelete, use minPhysicRatio to determin when the broker's disk is full. And mark all store path when it's full.
3. In org.apache.rocketmq.store.MultiPathMappedFileQueue#tryCreateMappedFile, we ignore readonly paths and  paths marked full in step 2.
=> RIP-7 Multiple Directories Storage Support

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/GetMessageResult.java
Avoid unnecessary object allocation when getMessage.
GetMessageResult will create double ArrayList with 100 initialCapacity.
the pullBatchSize in consumer is 32 which means in default config. then 100 initialCapacity is unnecessary.
And when message not found. the allocation is also can be avoided.
1. lazy init GetMessageResult only when find message.
2. adjust ArrayList initialCapacity in GetMessageResult to avoid object allocation
=> [ISSUE #3375] Lazy init GetMessageResult only when find message.

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
#2667 
- Ensure that the commitlog and consumequeue paths exist when the service starts
XXXX
=> [ISSUE #2667] Repair 'file doesn't exist on this path'

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
#3384
- Add SendBack message to SCHEDULE_TOPIC_XXXX stats
XXXX
=> [ISSUE #3384] Add SendBack message to SCHEDULE_TOPIC_XXXX stats

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
#3459
1. Reset the param of "beginTimeInLock" to 0 in "finally" condition.
2. Remove the redundancy declaration for "beginTimeInLock = 0".
=> [ISSUE #3459] Fix the problem of Put messages to commitLog always failure after encountering any exception

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
The other check is used in sendDefaultImpl
so there is no need to chekMessage in this
=> Validators.checkMessage() is used twice.

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
#3463 
- Need to determine whether the DLedger mode is turned on, and choose a different submission log path
- Fix-1
- Fix-2
=> [ISSUE #3463] Fix the issue of commitLog path error

store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
#3286
- By replacing Timer with ScheduledExecutorService, all queue threads can send messages concurrently.
- Messages of 18 delay levels are delivered at the same time, and the delivery of TPS is about 1w, which is in line with expectations
=> [ISSUE #3286] replace Timer with ScheduledExecutorService

namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessorTest.java
add defaultRequestProcessor test
=> add defaultRequestProcessor test

docs/cn/client/java/API_Reference_DefaultMQProducer.md
The optimization is for DefaultMQProducer's api reference purpose. 
The path of api reference is "rocketmq/docs/cn/client/java/API_Reference_DefaultMQProducer.md". 
Word "消息追踪器" will be changed to  "基于RPCHooK实现的消息轨迹插件".
Thx for RocketMQ community. Pls feel free to check.
=> DefaultMQProducer's API reference optimization

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/DeleteTopicFromNamesrvRequestHeader.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
The header of request code DELETE_TOPIC_IN_NAMESRV(216) is not same in client and the server, It will not cause problems, but should be fixed.
The naming of DeleteTopicInNamesrvRequestHeader should be DeleteTopicFromNamesrvRequestHeader, delete from , not delete in
=> Fix some request header setting errors and naming issues

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyServerConfigTest.java
for issue: https://github.com/apache/rocketmq/issues/3528  
Make the `backlog` to be configurable, for compatibility with previous versions, it default value is 1024. 
The behavior of the `backlog` argument on TCP sockets changed with Linux 2.2.  Now it specifies the queue length for **completely established sockets** waiting to be accepted, instead of the number of **incomplete connection** requests. see: https://man7.org/linux/man-pages/man2/listen.2.html
This commit has unit tests.
=> [ISSUE #3528] fix: The value of ChannelOption.SO_BACKLOG should not be hard-coded.

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/test/java/org/apache/rocketmq/broker/BrokerControllerTest.java
fix bug : https://github.com/apache/rocketmq/issues/2516
1. According to the idea between the original issue author and @RongtongJin , 
optimizing the method: `BrokerController#headSlowTimeMillss(BlockingQueue<Runnable> q)`
2. Iterate over the `BrokerController#sendThreadPoolQueue` and find the first element that meets the conditions (or NULL)to cacluete the time instead of the [`sendThreadPoolQueue#peek()`] method (think about the impact of concurrency,  `BrokerController#sendThreadPoolQueue` is polled by thread in `BrokerController#sendMessageExecutor`). 
3. However, for monitoring purposes, I think it's better to count the distribution of this value over each time interval, just like `StoreStatsService#putMessageDistributeTime`, …
=> [ISSUE #2516]: Fix the value of sendThreadPoolQueueHeadWaitTimeMills is 0 most of the time

docs/cn/best_practice.md, docs/en/Configuration_Client.md
For issue #3567 
Keep the value of configuration item (PushConsumer#consumeThreadMin) in document and code is same.
XXXX
=> [ISSUE #3567] fix: The default value of configuration item (PushConsumer#consumeThreadMin) in document and code is different.

srvutil/src/main/java/org/apache/rocketmq/srvutil/ServerUtil.java
#3564 
add single quotes for namesrvAddr option example, to avoid command splits caused by semicolons
=> [Issue #3564] Enclose namesrvAddr in example of mqadmin tool by quotation marks

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionTraceHookImpl.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQLitePullConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java, example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
Fix spelling mistake in getter/setter method of mQClientFactory
Change all getter/setter method to getMqClientFactory / setMqClientFactory in RebalanceImpl / DefaultMQPushConsumerImpl / DefaultMQProducerImpl
=> [Issue #3579]：Fix spelling mistake in getter/setter method of mQClientFactory

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
This problem introduced since 4.9.1, may cause tag incorrect.
in https://github.com/apache/rocketmq/pull/2961 MessageDecoder.messageProperties2String remove last separator. MessageDecoder.string2messageProperties can parse the string with or without last separator, but CommitLog.MessageExtEncoder.encode(MessageExtBatch, PutMessageContext) force append some properties without separator.
This problem need fix in broker side. since different client may send messages in different format.
I will check compatibility of this commit tomorrow.
=> [Issue #3476] Fix last separator of properties string is missing when using batch send

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java, acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, tools/src/main/java/org/apache/rocketmq/tools/command/queue/QueryConsumeQueueCommand.java
In method private Long getLong(String s) and private Integer getInt(String s) of org.apache.rocketmq.broker.transaction.queue.TransactionalMessageServiceImpl, a boxed numeric primitive is created from String, and then unboxed.
For example, v = Integer.valueOf(s) (v is of type int), it would be more efficient to use Integer.parseInt(), which returns a primitive value directly.
=> Unnecessary boxing of primitives

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
In Dledger Commitlog, put batch msg stats is incorrect.
fix the stats bug.
=> [ISSUE #3601] Fix dledger put batch msg stats bug

broker/src/main/java/org/apache/rocketmq/broker/filter/ConsumerFilterManager.java, broker/src/main/java/org/apache/rocketmq/broker/filter/MessageEvaluationContext.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearby.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java, common/src/main/java/org/apache/rocketmq/common/Configuration.java, openmessaging/src/main/java/io/openmessaging/rocketmq/utils/BeanUtils.java, test/src/main/java/org/apache/rocketmq/test/message/MessageQueueMsg.java, test/src/main/java/org/apache/rocketmq/test/util/FileUtil.java, test/src/main/java/org/apache/rocketmq/test/util/MQAdmin.java, tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java, tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerConfigCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/consumer/GetConsumerConfigSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportConfigsCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/GetNamesrvConfigCommand.java
There are several inefficient iterations of Map, in such code, keySet() is retrieved from Map firstly, and values are got in each iteration by key. In my opinion, entrySet() should be used, so that keys and values can be fetched in one time.
=> [ISSUE #3593] entrySet() replace keySet()

client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/RequestFutureHolder.java, client/src/main/java/org/apache/rocketmq/client/producer/RequestFutureTable.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
=> [ISSUE #3453]Producer cannot shutdown completely

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java, docs/cn/architecture.md, docs/cn/client/java/API_Reference_DefaultMQProducer.md
=> Polish the doc for tracing parts.

pom.xml
fix the log4j 2 security issue
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-3201?filter=allissues
=> bump up Log4j-core version to 2.15.0

common/src/main/java/org/apache/rocketmq/common/message/MessageExt.java
MessageExt.getBornHostNameString() called InetAddress.getHostName(), which may case reverse DNS lookup.
MessageExt.getBornHostNameString() is used in broker side, so we use InetSocketAddress.getHostString() instead it.
=> [ISSUE 3585] [Part A] eliminate reverse DNS lookup in MessageExt

common/src/main/java/org/apache/rocketmq/common/UtilAll.java, common/src/main/java/org/apache/rocketmq/common/message/MessageClientIDSetter.java, common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Improve performance of createUniqID().
From 2.41% to 0.42% in flame graph of producer side.
=> [ISSUE 3585] [Part D] improve performance of createUniqID()

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
Fix-#2535
Use one variable value to log info when eventQueue's size more than 10000.
=> [ISSUE #2535] Use one variable value to log info when eventQueue's size more than 10000.

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
this commit eliminate this method from flame graph in producer side.
=> [ISSUE 3585] [Part E] eliminate duplicated getNamespace() call when where is no namespace

client/pom.xml
log4j is not used in rocketmq-client, it is better to remove it to avoid security scans.
remove log4j dependency in client pom
=> [ISSUE #3635] remove log4j dependency in client pom

store/src/test/java/org/apache/rocketmq/store/ScheduleMessageServiceTest.java
Expect value and actual value need to be exchanged in ScheduleMessageServiceTest#testCorrectDelayOffset_whenInit line 69
=> [ISSUE #3644] exchange parameters

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/BrokerControllerTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
Fix the bug that the broker will hang after polish the headWaitTimeMills method
#3630 
#3509 
1. Revert the headWaitTimeMills method
2. Use thread pool isolation to fix the issue of headWaitTimeMills error
XXXX
=> [ISSUE #3630] Fix the bug that the broker will hang after polish the headWaitTimeMills method

pom.xml
fix the log4j 2 security issue
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-3201?filter=allissues
=> bump up log4j-slf4j-impl version to 2.15.0

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java
fix #3651 
add netty channel option WRITE_BUFFER_WATER_MARK to reduce the risk of memory leaks
=> [ISSUE #3651] for add netty channel option WRITE_BUFFER_WATER_MARK

.travis.yml, test/src/test/java/org/apache/rocketmq/test/client/producer/exception/msg/MessageExceptionIT.java
Polish travis.yml to run integration tests
#3654
1.Make travis to run integration tests
2.Fix running testSynSendNullMessage failed
XXXX
=> [ISSUE #3654] Polish travis.yml to run integration tests

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/command/broker/CleanUnusedTopicCommand.java
Fixes #1486 
1）update defaultMQAdminExt.cleanUnusedTopicByAddr(addr) to defaultMQAdminExt.cleanUnusedTopic(cluster) in CleanUnusedTopicCommand line 69
2）update defaultMQAdminExtImpl.cleanUnusedTopicByAddr(addr) to defaultMQAdminExtImpl.cleanUnusedTopic(cluster) in DefaultMQAdminExt line 402
run testcase in DefaultMQAdminExtTest#testCleanUnusedTopic
=> [ISSUE #1486] fix CleanUnusedTopicCommand performs wrong

remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
cache the result of parseChannelRemoteAddr() and eliminate this method in flame graph. 
used 4.84% cpu before this commit in producer side
=> [ISSUE 3585] [Part C] cache the result of parseChannelRemoteAddr()

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
producer send message to retry topic directly, broker will panic
because maxReconsumeTimes is null and convert to int.
add null check for maxReconsumeTimes
Closes #1843
=> [ISSUE #1843] Fix broker error when producer send to retry topic

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Trivial fix
1. Fix spelling error in `DefaultMessageStore#CleanCommitLogService#excuteDeleteFilesManualy`
2. Use getServiceName for GroupCommitService logging
=> Fix spelling error in DefaultMessageStore

remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
Optimize RemotingHelper#parseSocketAddressAddr
=> Optimize RemotingHelper#parseSocketAddressAddr

tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/offset/SkipAccumulationSubCommand.java, tools/src/test/java/org/apache/rocketmq/tools/command/offset/SkipAccumulationCommandTest.java
=> [ISSUE #2969] Add a skip accumulation message command in mqadmin.

docs/cn/client/java/API_Reference_ DefaultPullConsumer.md
add DefaultPullConsumer doc
add DefaultPullConsumer doc
XXXX
=> [RIP-9] add DefaultPullConsumer api  doc

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, distribution/conf/logback_broker.xml
=> [ISSUE #3173]Isolate Broker logs when multiple Broker services are deployed on the same machine.

store/pom.xml
Upgrade dledger version to 0.2.3
Upgrade dledger version to 0.2.3
XXXX
=> [ISSUE #3733] Upgrade dledger version to 0.2.3

docs/en/best_practice.md
=> [ISSUE #3728] docs: Make the 'Uses of keys' entry in the document 'Best practices' more complete.

store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
=> [ISSUE #3738]Remove redundant callee of String.valueOf

broker/pom.xml, distribution/benchmark/runclass.sh, distribution/bin/runbroker.cmd, distribution/bin/runbroker.sh, distribution/bin/runserver.cmd, distribution/bin/runserver.sh, distribution/bin/tools.cmd, distribution/bin/tools.sh, namesrv/pom.xml, pom.xml
fix #3223 
support start namesrv/broker using later jdk version (9,10,11,15,16)
1. use java classpath instead of -Djava.ext.dirs
2. use BouncyCastle because java 15 removed `sun.security.x509` package.
3. use different java options in different java version
tested in centos 7, using java version (8, 9, 10, 11, 15, 16).
=> [ISSUE #3223]Optimize  startup script to support greater jdk version

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionTraceHookImpl.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQLitePullConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java, example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
[#3581](https://github.com/apache/rocketmq/pull/3581) this PR solves the nonstandard spelling problem of [Issue #3579](https://github.com/apache/rocketmq/issues/3579)
but it also modified the method declared public, which may lead to incompatible problem for the client. It is better to rollback the change.
=> [Issue #3579] rollback spelling fix to avoid incompatible problem

docs/en/Configuration_Client.md
For issue #3751 
Fix typos and other little error in the document 'Configuration_Client.md'.
=> [ISSUE #3751] docs: Fix typos and other little error in the document 'Configuration_Client.md'

test/src/main/java/org/apache/rocketmq/test/lmq/benchmark/BenchLmqStore.java, test/src/test/java/org/apache/rocketmq/test/lmq/TestBenchLmqStore.java
fix build error in RIP-28 at getmQClientFactory
change to getmQclientFactory
ci pass
=> fix build error in RIP-28 at getmQClientFactory

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
=> [ISSUE #2580] Check producerTable or consumerTable is empty when updateTopicRouteInfoFromNameServer

client/pom.xml, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/RequestFutureHolder.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageOpenTracingHookImpl.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java
=> [ISSUE #3684] change client jdk version to 1.6

tools/src/main/java/org/apache/rocketmq/tools/command/offset/ResetOffsetByTimeCommand.java
fix issue #951
variable "timestamp" should be -1 when the timestamp parameter is set to "now".
When we execute the ResetOffsetByTimeCommand command with parameter "-s now", the offset of the consumer is expected to be the latest, so it's better to get the max offset in the queue instead of looking up the offset with timestamp, which would return a incorrect offset (1 less than the expected value).
=> [ISSUE #951]Fixed an incorrect offset problem in the ResetOffsetByTimeCommand

common/src/main/java/org/apache/rocketmq/common/ConfigManager.java, common/src/main/java/org/apache/rocketmq/common/sysflag/TopicSysFlag.java
=> Remove useless code

docs/cn/best_practice.md, docs/en/Configuration_Client.md
For issue #3782 
Fix the default value of parameter '**sendMsgTimeout**' in documents.
=> [ISSUE #3782] docs: Fix the default value of parameter 'sendMsgTimeout'.

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
If there is no explanation, you need to explicitly specify the replacement class
=> DefaultMQPullConsumer document specification

common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java
avoid multiple expansion when the number of elements in the `org.apache.rocketmq.common.message.MessageConst` class is determined
#3720
=> [ISSUE #3720]perf: avoid multiple expansion when the number of elements in the `MessageConst` class is determined

docs/en/CLITools.md
=> [ISSUE #3801] Polish the document 'CLITools.md'.

pom.xml
[due to a CVE](https://github.com/apache/rocketmq/issues/3814)
upgrade snakeyaml to a secure version
upgrade pom
CI build
=> [Issue-3814] use snakeyaml 1.30

pom.xml
https://github.com/apache/rocketmq/issues/3818
guava 19.0 has a CVE
pom change
CI build
=> [Issue-3818] guava 31.0.1-jre

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/LocalTransactionExecuter.java, client/src/main/java/org/apache/rocketmq/client/producer/TransactionCheckListener.java
Guaranteed readable code style.
=> [ISSUE #3797] Improve DefaultMQProducerImpl code

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java, store/src/main/java/org/apache/rocketmq/store/ha/HAConnection.java
For more informance see https://github.com/apache/rocketmq/issues/3825
=> [ISSUE 3825] Use default SO_SNDBUF/SO_RCVBUF/WRITE_BUFFER_WATER_MARK value

client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragelyByCircleTest.java
=> [ISSUE #3674]Add unit test for AllocateMessageQueueAveragelyByCircle

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyService.java
=> [ISSUE #3779] Add hook to execute after consume for pop

.travis.yml
Some time ago I have enabled testing on Linux ARM64 with https://github.com/apache/rocketmq/commit/98aca7ffcbf282b2885ad4b9c433927a5ac0e78b
I see that it has been disabled with https://github.com/apache/rocketmq/commit/360b616b6fc2e137f30340c87314b4c65a1750b2 because the builds were unstable (timing out).
With this PR I suggest to re-enable it but this time using AWS Graviton2 nodes at TravisCI because they are more stable than Equinix Metal ones (`arch: arm64`) and run it on Ubuntu 20.04 instead of 18.04.
Re-enable testing on Linux ARM64 at TravisCI
TravisCI build should pass!
=> Re-enable testing on ARM64

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Separate InterruptedException from others, because it will be Interrupted when seek offset in MessageQueue. 
https://github.com/apache/rocketmq/issues/3853
=> [ISSUE #3853]add log for interruptedException

store/src/test/java/org/apache/rocketmq/store/StoreTestUtil.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java
Fix https://github.com/apache/rocketmq/issues/2993
After messageStore shutting down, release dledger mapped files, then these files will be deletable.
=> [ISSUE #2993] fix testTruncateCQ on Windows by releasing mapped files.

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, docs/cn/Deployment.md
There are some spell error in cn docs, fix them.
fix some cn docs eror
XXXX
=> fix some docs error

common/src/test/java/org/apache/rocketmq/common/filter/FilterAPITest.java
**Description**
The test `org.apache.rocketmq.common.filter.FilterAPITest.testBuildTagSome` may fail 
since `getTagsSet()` returns a `HashSet` that has undetermined iteration order. One can check for that using the [NonDex](https://github.com/TestingResearchIllinois/NonDex).
**Reproduce the failure**
```
mvn install -pl common -am -DskipTests
mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -pl common -Dtest=org.apache.rocketmq.common.filter.FilterAPITest#testBuildTagSome
```
**Solution**
Use `containsExactlyInAnyOrder()` instead of `containsExactly()` for the failing AssertJ assertion.
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 …
=> fix a flaky test

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Just delete useless check in SendMessageProcessor.preSend()
=> [ISSUE #3955] delete useless check

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
For #3983 
Remove duplicated warn log in class DefaultMQProducerImpl.
XXXX
=> [ISSUE#3983] Duplicated warn log in class DefaultMQProducerImpl is unnecessary.

client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java
For #3985 
Remove shuffle operation before sorting the list of 'FaultItem'.
XXXX
=> [ISSUE #3985] Remove shuffle operation before sorting the list of 'FaultItem'.

distribution/benchmark/shutdown.sh
Add shutdown script for batchproducer.sh in shutdown.sh
XX
XXXX
=> Add shutdown script for batchproducer.sh

store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
Fix case of dirty data in deliverPendingTable
Initialize deliverPendingTable, When the ScheduleService is started
Before
After
=> [ISSUE #4004] Initialize deliverPendingTable, When the ScheduleService is started

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
It should use endTransactionExecutor for EndTransactionProcessor. So fix it in this pr.
XX
XXXX
=> Use the right executor for EndTransactionProcessor

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
=> [Minor] RemotingCommandException is not thrown in a method

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/kvconfig/KVConfigManager.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/NamesrvControllerTest.java
=> [ISSUE #4053] NamesrvController code optimization

docs/cn/operation.md, docs/en/CLITools.md
=> [ISSUE #4054] fix doc format

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopOrderlyService.java
=> [ISSUE #4050] 5.0.0-alpha (Pop): Missing origin message id from dead letter message 

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
=> [ISSUE #4050] fix origin messsage id missing from dead leetter meessage

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
=> [ISSUE #4065] Fix brokerName of msg is null in same case

container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java, container/src/main/java/org/apache/rocketmq/container/logback/BrokerLogbackConfigurator.java, container/src/test/java/org/apache/rocketmq/container/BrokerContainerTest.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/command/container/RemoveBrokerSubCommand.java
=> [ISSUE #3798] Support container in DLedger.

broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
When the MAC 12 system uses the request reply function, the response time of the producer is very long,  so the response time should be optimized
#3933
=> fix mac 12+ slow bug

acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
=> [ISSUE #4155] fix system property setting causing data conflicts in acl test

common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java, common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java, store/src/main/java/org/apache/rocketmq/store/MappedFile.java
Adjusted multiple calls of `UtilAll.string2bytes` and `subString` to one call
=> Optimize the logic of MessageDecoder#decodeMessageId method

common/src/main/java/org/apache/rocketmq/common/message/Message.java
=> [ISSUE #4103] Simplify string-list-join in `Message`

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Fix `DefaultMessageStore#getEarliestMessageTime()` bug in Dledger mode
DLedgerCommitLog's body start from position 48,
=> Bugfix DefaultMessageStore#getEarliestMessageTime() bug in Dledger mode

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
=> [ISSUE #4127]  [BrokerOuterAPI] Anonymous new Runnable() can be replaced with lambda

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java
=> [ISSUE #3914] Support multi dirs storage in DLedger

client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
For #4147 
- Update javadoc of class `DefaultMQProducer`.
- Fix the problem described in the warning message prompted by the IDE.
XXXX
=> [ISSUE #4147] javadoc: Fix the problem described in the warning message prompted by the IDE.

common/src/main/java/org/apache/rocketmq/common/stats/Stats.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java, store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java, store/src/test/java/stats/BrokerStatsManagerTest.java, tools/pom.xml, tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetricsCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/stats/StatsAllSubCommand.java
#4107 
rocketmq-tools is the admin client module, it should not depend on rocketmq-store, which is broker storage module.
XXXXX
XX
XXXX
=> [ISSUE #4107] rocketmq-tools should not depend on rocketmq-store

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
Details in https://github.com/apache/rocketmq/pull/4099#issuecomment-1099351837. Given the details for convenience.
该 PR 目的是优化轨迹消息发送模块性能，详情讨论见 https://github.com/apache/rocketmq/pull/4099#issuecomment-1099351837 。为 review 方便此处给出设计详情和背景。
1. 业务线程调用`AsyncTraceDispatcher#append`向任务元数据队列`traceContextQueue`添加`TraceContext`；
2.  `worker`线程循环从`traceContextQueue`中获取`TraceContext`、并包装为任务`AsyncAppenderRequest`，由线程池`traceExecutor`执行；
3. `AsyncAppenderRequest#sendTraceData`中将`TraceContext`转换为可计量大小的`TraceTransferBean`，并按照按照**topic+regionId**对`TraceTransferBean`进行分组、获取结构为`Map<String, List<TraceTransferBean>>`的数据；
4. 将`TraceTransferBean`按照`maxMsgSize`进行分批次的发送，根据`AsyncTraceDispatcher#accessChannel`决定发送到`rmq_sys_TRACE_DATA_${regionId}`还是轨迹消息队列(默认为`RMQ_SYS_TRACE_TOPIC`) 。 …
=> [ISSUE #4099]Optimized the performance of sending traceMessage in `AsyncTraceDispatcher`

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java
=> [ISSUE #4130] Remove the exception which will never be thrown by method from method signature

namesrv/src/main/java/org/apache/rocketmq/namesrv/kvconfig/KVConfigManager.java
format code KVConfigManager
format code KVConfigManager.java
format code KVConfigManager.java
import org.apache.rocketmq.namesrv.NamesrvController;
public class KVConfigManager {
change to
import org.apache.rocketmq.namesrv.NamesrvController;
public class KVConfigManager {
=> format code KVConfigManager

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
In  DefaultMessageStore.java ，There is the following code：
else if (offset > maxOffset) {
status = GetMessageStatus.OFFSET_OVERFLOW_BADLY;
if (0 == minOffset) {
nextBeginOffset = nextOffsetCorrection(offset, minOffset);
} else {
nextBeginOffset = nextOffsetCorrection(offset, maxOffset);
}
It can be seen that if minOffset=0.Consumption will start from 0.
I suggest modifying to:
else if (offset > maxOffset) {
status = GetMessageStatus.OFFSET_OVERFLOW_BADLY;
nextBeginOffset = nextOffsetCorrection(offset, maxOffset);
}
=> [ISSUE #4215] OFFSET_OVERFLOW_BADLY will lead to consumption from begin, a large number of repeated consumption

common/src/main/java/org/apache/rocketmq/common/EpochEntry.java, common/src/main/java/org/apache/rocketmq/common/utils/CheckpointFile.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java, store/src/main/java/org/apache/rocketmq/store/ha/HAService.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/EpochFileCache.java, store/src/main/java/org/apache/rocketmq/store/ha/io/AbstractHAReader.java, store/src/main/java/org/apache/rocketmq/store/ha/io/HAReadHook.java, store/src/main/java/org/apache/rocketmq/store/ha/io/HAWriteHook.java, store/src/main/java/org/apache/rocketmq/store/ha/io/HAWriter.java, store/src/test/java/org/apache/rocketmq/store/ha/EpochFileCacheTest.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
We want unified log replication, using rocketmq's original HaService instead of dledger mode.
Previously, i have done the following job with @RongtongJin 
1. Add statemachine mode for dledger: https://github.com/openmessaging/dledger/pull/128
2. Embed a strongly consistent controller based on dledger implementation in name-srv: https://github.com/apache/rocketmq/pull/4195
In this pr, I added a haService - AutoSwitchHAService that can switch role, this ha can cooperate with the controller to achieve master-slave switching
In the follow-up work, I will modify the code of the broker to fully realize the master-slave switch
The ha service protocol is:
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the …
=> [Summer of Code] Support switch role for ha service

common/src/main/java/org/apache/rocketmq/common/sysflag/MessageSysFlag.java, test/src/test/java/org/apache/rocketmq/test/smoke/NormalMessageSendAndRecvIT.java
fix ISSUE #4251
add two sys flag in MessageSysFlag
=> [ISSUE-#4251]Add batch flag

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
use function computeIfAbsent replace if #4254
use function computeIfAbsent replace if #4254
use function computeIfAbsent replace if #4254
=> [ISSUE #4254] use function computeIfAbsent replace if 

tools/src/main/java/org/apache/rocketmq/tools/command/topic/DeleteTopicSubCommand.java
=> [ISSUE#4263]Fix the issue that DeleteTopicSubCommand does't call the correct deleteTopicInNameServer method in 5.0.0-beta.

store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java, store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeQueueTest.java
https://github.com/apache/rocketmq/issues/4070
There's no need to binary search offset if the target timestamp is larger than the  batchConsumeQueue's max timestamp. So if target timestamp is larger than max timestamp, return max offset directly.
* before:
We will get "-1" when we getOffsetInQueueByTime if the target timestamp is larger than the max queue unit timestamp.
The result as follows:
* after :
After fix that:
=> [ISSUE #4070] bugfix : Returning min queue offset when timestamp is larger than queue-unit max timestamp

broker/src/main/java/org/apache/rocketmq/broker/util/ServiceProvider.java
**Optimize ServiceProvider's code**
XX
XXXX
=> [ISSUE #4310] Optimize serviceProvider's code

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
[Issue](https://github.com/apache/rocketmq/issues/4308)
XX
XXXX
=> [ISSUE # 4308] Make some variables to be final in brokerController

README.md
Add a rough guide for RocketMQ deployment, include three different environments:
- Run RocketMQ locally
- Run RocketMQ in Docker
- Run RocketMQ in Kubernetes
add a rough guide for quick start
XXXX
=> Add a rough guide for quick start

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
=> [ISSUE #4325] Remove redundant exception to improve readability

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/SyncStateSet.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/GetReplicaInfoRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/GetReplicaInfoResponseHeader.java, container/src/main/java/org/apache/rocketmq/container/InnerBrokerController.java, controller/src/main/java/org/apache/rocketmq/controller/Controller.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DledgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerInfo.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
When the controller is deployed independently, let the broker send the heartbeat to the controller.
XXXX
=> [Summer of code] Let broker send heartbeat to controller

common/src/main/java/org/apache/rocketmq/common/TopicAttributes.java, common/src/main/java/org/apache/rocketmq/common/TopicConfig.java, common/src/main/java/org/apache/rocketmq/common/attribute/TopicMessageType.java, common/src/main/java/org/apache/rocketmq/common/subscription/CustomizedRetryPolicy.java, common/src/main/java/org/apache/rocketmq/common/subscription/ExponentialRetryPolicy.java, common/src/main/java/org/apache/rocketmq/common/subscription/GroupRetryPolicy.java, common/src/main/java/org/apache/rocketmq/common/subscription/GroupRetryPolicyType.java, common/src/main/java/org/apache/rocketmq/common/subscription/SubscriptionGroupConfig.java, common/src/test/java/org/apache/rocketmq/common/TopicConfigTest.java, tools/src/main/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupSubCommand.java
Topic and Group are important concepts in RocketMQ, but they are too simple to provide detailed information and more management ability. Therefore, there is a proposal to expand RocketMQ Topic/Group attributes.
Add attributes below:
* Topic Message Type
* Consume Timeout for PushConsumer
* Consume Retry Policy
* Max Retry Times
* Group Fifo Consume Flag
=> [ISSUE #4384] Expand RocketMQ Topic/Group attributes

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/EpochEntry.java, common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/EpochEntryCache.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/InSyncStateData.java, controller/src/main/java/org/apache/rocketmq/controller/Controller.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DledgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/event/ControllerResult.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ControllerRequestProcessor.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerEpochCacheCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/ha/SyncStateDataCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/ha/SyncStateSetCommand.java
Add two admin tools for controller mode:
XXXX
=> [Summer of code] Add admin tools for controller mode

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerStartup.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/main/java/org/apache/rocketmq/store/ha/io/HAWriter.java
Fix some bugs for controller mode.
XXXX
=> [Summer of code] Fix controller bugs

store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java
Fix allAckSyncStateSet not working
Replace clientAddress to slaveAddress.
XXXX
=> [Summer of code] Fix allAckSyncStateSet not working

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
=> Polish switching logic and auto switch ha code

common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
remove useless check about "properties"
XXXXX
XX
XXXX
=> [ISSUE #4410] Optimize method org.apache.rocketmq.common.message.MessageDecoder#messageProperties2String, remove useless check

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, example/src/main/java/org/apache/rocketmq/example/rpc/RequestProducer.java
fix : #2435 
1.  Add the default namesrvAddr to the RequestProducer example
2.  Solve the synchronization wait timeout problem because the semaphore does not decrease after DefaultMQProducer#request() message is sent successfully
3. Solve the problem that the callback method is not called after the DefaultMQProducer#request() message is sent successfully
=> [ISSUE #2435] Solve the problem that DefaultMQProducer#request() sends messages and waits for timeout synchronously

distribution/bin/tools.sh
add find_java_home function to avoid error: Algorithm HmacSHA1 not available
Solve error Algorithm HmacSHA1 not available when your java_home is not found by adding find_java_home function to tools.sh
Solve error Algorithm HmacSHA1 not available when your java_home is not found by adding find_java_home function to tools.sh
eg: 172.17.0.2 is you rmqnamesrv ip address
you can use this command(`docker exec -it rmqbroker ./mqadmin clusterList -n 172.17.0.2:9876`) to  verify if RocketMQ broker works now.
#23 Deploy broker with docker-compose returns NoSuchAlgorithmException
=> [ISSUE #23] solve error Algorithm HmacSHA1 not available when your java_home is not found

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/DeleteTopicFromNamesrvRequestHeader.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/command/topic/DeleteTopicSubCommand.java
=> [ISSUE#4263]Delete topic route info based on cluster when delete topic.

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java
Ensure that new messages cannot be written to messagestore during role change
XX
XXXX
=> Ensure that new messages cannot be written to messagestore during role change

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, remoting/pom.xml, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingSerializable.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RemotingSerializableTest.java
=> Let name server generate valid JSON response when process topic route queries

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java
Let broker register to controller again when master not existed.
XXXX
=> [Summer of code] Let broker register to controller again when master not existed.

client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java, client/src/test/java/org/apache/rocketmq/client/common/ThreadLocalIndexTest.java
See https://github.com/apache/rocketmq/issues/4349
In ThreadLocalIndex.java, when the random index increase to Integer.MAX_VALUE(2147483647), the next increment value is Integer.MIN_VALUE(-2147483648). And the code `Math.abs(index)` will also return the same negatice value Integer.MIN_VALUE(-2147483648)
```java
/**
* Returns the absolute value of an {@code int} value.
* If the argument is not negative, the argument is returned.
* If the argument is negative, the negation of the argument is returned.
*
* <p>Note that if the argument is equal to the value of
* {@link Integer#MIN_VALUE}, the most negative representable
* {@code int} value, the result is that same value, which is
* negative.
*
* @param   a   the argument whose absolute value is to be determined
* @return  the absolute value …
```
=> [ISSUE #4349] fix negative index when index reach Integer.MAX_VALUE

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
Use confirm offset in ReputMessageService
XXXX
=> [Summer of code] Use confirm offset in ReputMessageService

common/src/main/java/org/apache/rocketmq/common/protocol/header/PullMessageRequestHeader.java
Change PullMessageRequestHeader maxMsgNums to CFNullable to ensure protocol compatibility.
See https://github.com/apache/rocketmq/blob/82a48be00a6d9def14abb871a40cb68cf8a041e9/remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java#L277
=> Change PullMessageRequestHeader maxMsgNums to CFNullable

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
Controller模式在网络分区双主场景下切换时，confirmOffset的更新，cq的构建，recover topicQueueTable数据的节点要相互配合，否则会丢失消息
Update the logic of confirmOffset and recover topicQueueTable to prevent message loss
XXXX
=> Update the logic of confirmOffset and recover topicQueueTable to prevent message loss when broker role change

broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java
Polish the logic of change to master
broker和controller网络分区恢复时，有可能新选的master仍然时以前的，则changeToMaster时可以避免一些操作
Polish the logic of change to master
XXXX
=> Polish the logic of change to master

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Fix bug for putting duplicated messsages while sending batch message 
Remove the redundant code
=> Fix bug for putting duplicated messsages while sending batch message

acl/src/main/java/org/apache/rocketmq/acl/common/AclClientRPCHook.java, acl/src/test/java/org/apache/rocketmq/acl/common/AclClientRPCHookTest.java, client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java, common/src/main/java/org/apache/rocketmq/common/rpchook/StreamTypeRPCHook.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestType.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RequestTypeTest.java
Mark stream-related request by RequestType
1. Plan to add a RequestType in remoting protocol to indicate stream requests including requests driven by PullConsumer and LitePullConsumer.
2. Stream is an important part of rocketmq and it is not marked and distinguished with the messaging-related requests by now. It is helpful for observability and other features to mark it explicitly
=> [ISSUE #3906] Mark stream-related request by RequestType

common/src/main/java/org/apache/rocketmq/common/subscription/CustomizedRetryPolicy.java, common/src/main/java/org/apache/rocketmq/common/subscription/ExponentialRetryPolicy.java, common/src/main/java/org/apache/rocketmq/common/subscription/RetryPolicy.java, common/src/test/java/org/apache/rocketmq/common/subscription/CustomizedRetryPolicyTest.java, common/src/test/java/org/apache/rocketmq/common/subscription/ExponentialRetryPolicyTest.java
Expand RocketMQ Topic/Group attributes
Remove TimeUnit in nextDelayDuration
=> [ISSUE #4384] Remove TimeUnit in nextDelayDuration

acl/src/main/java/org/apache/rocketmq/acl/common/AclClientRPCHook.java, broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, remoting/src/main/java/org/apache/rocketmq/remoting/RPCHook.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, test/src/test/java/org/apache/rocketmq/test/container/BrokerFailoverIT.java
Remove useless doAfterRpcFailure method in RPCHook
Remove useless doAfterRpcFailure method in RPCHook
XXXX
=> Remove useless doAfterRpcFailure method in RPCHook

distribution/conf/logback_broker.xml, distribution/conf/logback_namesrv.xml, distribution/conf/logback_tools.xml
=> [ISSUE #4461] Support to change the logger level dynamically

common/src/main/java/org/apache/rocketmq/common/protocol/route/BrokerData.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
I'm reading the sourcecode of store module and there are some cpde snippets  in class org.apache.rocketmq.store.DefaultMessageStore that I think need to be fixed.
- **code snippet 1**: redundant code  and  unreachable statement (`match`   is always true)
- code snippet 2 : replacing with `enhanced for` to Improve code readability
=> [ISSUE #4531] fix unreachable statement, redundant code and code style 

client/src/main/java/org/apache/rocketmq/client/producer/ProduceAccumulator.java
The MessageBatch packaged with the autoBatch function is not very compatible with batchConsumeQueue, so to fix this.
XX
XXXX
=> Fix autoBatch not compatible with batchConsumeQueue

client/src/main/java/org/apache/rocketmq/client/producer/ProduceAccumulator.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
=> Fix the problem of abnormal statistics under Bcq

test/src/test/java/org/apache/rocketmq/test/smoke/NormalMessageSendAndRecvIT.java, test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
Fix the bug in examineConsumeStats
For static topics, the physical consumer offsets need to be translated to logic offsets, which is done in DefaultAdminExt.
But it does not handle the case when the topicQueueMapping is null, which means it is a normal topic.
=> Fix examine consume stats for none static topic

pom.xml
Upgrade dledger version to 0.2.7
Upgrade dledger version to 0.2.7
XXXX
=> [ISSUE #4576] Upgrade dledger version to 0.2.7

client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java, client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java, client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java, tools/src/test/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtTest.java
Support `bname` in request protocol.
Support `bname` for request: `PULL_MESSAGE`, `UPDATE_CONSUMER_OFFSET`, `QUERY_CONSUMER_OFFSET`, `SEARCH_OFFSET_BY_TIMESTAMP`, `GET_MIN_OFFSET`, `GET_MAX_OFFSET`.
=> [ISSUE #3905] Support bname in protocol

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
**Bug Report**
There is bug in LMQ moudle when checking multiple dispatch queue.
if (prop == null && pro.isEmpty()) {
.......
}
It will cause an exception.
=> [ISSUE #4628] Fix bug in LMQ when checking multiple Dispatch Queue 

tools/src/main/java/org/apache/rocketmq/tools/command/topic/DeleteTopicSubCommand.java
mqadmin deleteTopic only request master brokers
`org.apache.rocketmq.tools.command.topic.DeleteTopicSubCommand#deleteTopic`
-- Set brokerAddressSet = CommandUtil.fetchMasterAndSlaveAddrByClusterName(adminExt, clusterName);
-- adminExt.deleteTopicInBroker(brokerAddressSet, topic);
++ Set masterBrokerAddressSet = CommandUtil.fetchMasterAddrByClusterName(adminExt, clusterName);
++ adminExt.deleteTopicInBroker(masterBrokerAddressSet, topic);
create branch `develop-deleteTopic-command-fix` based on branch `develop`
Run `mvn -Prelease-all -DskipTests clean package -U` and deploy it by old config.but it cannot run. 
```shell
Caused by: java.lang.ClassNotFoundException: com.alibaba.arthas.deps.ch.qos.logback.core.rolling.RollingFileAppender
```
So …
=> [ISSUE #4644] Fix mqadmin deleteTopic bug when command exec on slave broker

docs/cn/dledger/quick_start.md, docs/en/dledger/quick_start.md
=> [ISSUE #4673] DLedger quick start document optimize

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/channel/GrpcClientChannel.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/ProxyClientRemotingProcessor.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/mqclient/ProxyClientRemotingProcessorTest.java
For gprc observer is not thread-safe, we need call onNext in lock
XX
XXXX
=> fix: write TelemetryCommand observer in writeLock

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivityTest.java
…e if not null
When handle has been renewed by proxy, should use handle saved in receiptHandleProcessor to changeInvisibleTime
XX
XXXX
=> fix: use handle saved in receiptHandleProcessor to changeInvisibleTime

distribution/conf/controller/cluster-3n-independent/controller-n0.conf, distribution/conf/controller/cluster-3n-independent/controller-n1.conf, distribution/conf/controller/cluster-3n-independent/controller-n2.conf, distribution/conf/controller/controller-standalone.conf
Fix #4746 
- add controller stand-alone and cluster 3 nodes config file
XXXX
=> [ISSUE #4746] add controller stand-alone and cluster 3 nodes config file

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java, tools/src/main/java/org/apache/rocketmq/tools/command/cluster/ClusterListSubCommand.java
Add TimerMessageStore runtime info in ClusterListSubCommand
Add TimerMessageStore runtime info in ClusterListSubCommand
XXXX
=> [ISSUE #4739] Add TimerMessageStore runtime info in ClusterListSubCommand

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java, common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java, controller/src/main/java/org/apache/rocketmq/controller/Controller.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, distribution/conf/controller/cluster-3n-independent/controller-n0.conf, distribution/conf/controller/cluster-3n-independent/controller-n1.conf, distribution/conf/controller/cluster-3n-independent/controller-n2.conf, distribution/conf/controller/controller-standalone.conf, distribution/conf/controller/quick-start/broker-n0.conf, distribution/conf/controller/quick-start/broker-n1.conf, distribution/conf/controller/quick-start/namesrv.conf, style/rmq_checkstyle.xml, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerEpochSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerConfigSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerMetaDataSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/UpdateControllerConfigSubCommand.java
Add getControllerConfig and updateControllerConfig command for admin CLI
Add getControllerConfig and updateControllerConfig command for admin CLI
XXXX
=> [ISSUE #4792] Add getControllerConfig and updateControllerConfig command for admin CLI

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
There are several typos in the code.
Like TIMER_WHELL_TTL_DAY in class TimerMessageStore.
=> [ISSUE #4810] Correction of spelling mistakes in TimerMessageStore

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyService.java
fix #4815 
Getting delay level from beginning of `org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#popDelayLevel`, instead of from the 4th element (120s).
XXXX
=> [ISSUE #4815] fix reconsuming messages in POP mode taking at least 2min

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, broker/src/test/java/org/apache/rocketmq/broker/controller/ReplicasManagerTest.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/BrokerHeartbeatRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/RegisterBrokerToControllerRequestHeader.java, controller/src/main/java/org/apache/rocketmq/controller/BrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/BrokerLiveInfo.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/elect/ElectPolicy.java, controller/src/main/java/org/apache/rocketmq/controller/elect/impl/DefaultElectPolicy.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/pojo/BrokerLiveInfo.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DefaultBrokerHeartbeatManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
1. add epoch and maxOffset in heartbeat.
2. refactor elect logic, now we
elect a new master by elect policy(can expand).
3. add some unit tests
issue link: https://github.com/apache/rocketmq/issues/4813
XX
XXXX
=> [ISSUE #4813] Add elect policy for controller

broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java, test/src/test/java/org/apache/rocketmq/test/container/PopSlaveActingMasterIT.java
fix #4821 
Add `PopSlaveActingMasterIT` and fix some bugs found.
XXXX
=> [ISSUE #4821] Add some integration tests for POP consumption in slave-acting-master mode

store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
Fix #4851 
-  Fix HAService implement class some method miss @Override annotation
XXXX
=> [ISSUE #4851] Fix HAService implement class some method miss @Override annotation

example/src/main/java/org/apache/rocketmq/example/schedule/TimerMessageConsumer.java, example/src/main/java/org/apache/rocketmq/example/schedule/TimerMessageProducer.java
Add example of timing messages with arbitrary time delay 
Add example of timing messages with arbitrary time delay 
XXXX
=> [ISSUE #4855] Add example of timing messages with arbitrary time delay 

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/ConsumerRunningInfo.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByIdSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByUniqueKeySubCommand.java
#4858 Add consumer type check when call consumeMessageDirectly
1. Add check for QueryMsgByUniqueKeySubCommand and QueryMsgByIdSubCommand.
2. Add type checking when call the org.apache.rocketmq.client.impl.factory.MQClientInstance#consumeMessageDirectly.
XXXX
=> [ISSUE apache#4858] add consumer type check for message direct push

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
close #4913 
-ReplicasManager#schedulingSyncControllerMetadata update controller metadata again after a while
XXXX
=> [ISSUE #4913] ReplicasManager#schedulingSyncControllerMetadata update controller metadata again after a while

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
Remove useless log output after the master and slave broker are started on the empty disk in controller mode
XX
XXXX
=> [ISSUE #4936] Remove useless log output after the master and slave broker are started on the empty disk in controller mode

acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
Fix #4987 
-  fix test case:PlainAccessValidatorTest#testUpdateSpecifiedAclFileGlobalWhiteAddrsConfig
XXXX
=> [ISSUE #4987] fix test case:PlainAccessValidatorTest#testUpdateSpecifiedAclFileGlobalWhiteAddrsConfig

test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
Related to [issue-4949](https://github.com/apache/rocketmq/issues/4949)
Fixed the port occupancy problem caused by the different order of shutdown calls
=> [ISSUE#4949] fix Address already in use

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
=> [ISSUE#5015]Fix typo of getAllCongestNum in TimerMessageStore

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java
close #5013 
Add a new configuration item "bindIP" to make rocketmq only bind to a specific IP.
Does this pr affect the original behavior?
No. The default value of the new config is 0.0.0.0, which means binding all network interfaces.
What are the limitations of the new configuration items?
It must be "0.0.0.0" or any IP assigned to a network interface. And if it's not 0.0.0.0, it needs to be the same as brokerIP1 to avoid potential network problems.
=> [ISSUE #5013] allow broker to bind specified network interface

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
close #5040 
-  Optimize AutoSwitchHAService#truncateInvalidMsg logic
XXXX
=> [ISSUE #5040] Optimize AutoSwitchHAService#truncateInvalidMsg logic

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
Close #5079 
Fix too many useless logs when the broker runs normally
Fix too many useless logs when the broker runs normally
XXXX
=> [ISSUE #5079 ] Fix too many useless logs when the broker runs normally

common/src/main/java/org/apache/rocketmq/common/UtilAll.java, pom.xml
=> [ISSUE #5097] Fix illegal reflective access

acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java, broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, common/src/main/java/org/apache/rocketmq/common/DataVersion.java, common/src/main/java/org/apache/rocketmq/common/filter/impl/PolishExpr.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/ConsumerRunningInfo.java, common/src/main/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingDetail.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java, logging/src/main/java/org/apache/rocketmq/logging/inner/LoggingBuilder.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java, openmessaging/src/main/java/io/openmessaging/rocketmq/promise/DefaultPromise.java, pom.xml, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java, store/src/main/java/org/apache/rocketmq/store/index/IndexFile.java, store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/stats/StatsAllSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateStaticTopicSubCommand.java
=> [ISSUE #5108] Bump checkstyle to 3.2.0

store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java, store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java
Close #5100 
Recover the optimization of pull request #2885
Recover the optimization of pull request #2885
XXXX
=> [ISSUE #5100] Recover the optimization of pull request #2885

common/src/main/java/org/apache/rocketmq/common/BrokerIdentity.java
1. fix the issue#5039 by initializing the local host name when BrokerIdentity class loading to avoid the InetAddress#getLocalHost() to be called too many times.
issue: https://github.com/apache/rocketmq/issues/5039
XXXXX
XX
XXXX
=> [ISSUE#5039] localHostName() get stuck when constructing the BrokerIdentity object

example/src/main/java/org/apache/rocketmq/example/namespace/ProducerWithNamespace.java
Fixed #5131
Close the producer after the message is sent.
XX
XXXX
=> [ISSUE #5131] Close the producer after the message is sent

example/src/main/java/org/apache/rocketmq/example/simple/OnewayProducer.java
Use StandardCharsets.UTF_8 as default charset in oneway producer demo
=> [ISSUE #5133] Use StandardCharsets.UTF_8 as default charset in oneway producer demo

store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java
Place a safepoint before the loop, the processing effect takes precedence over sleep
=> [ISSUE 4902]fix-warmMappedFile：Place a safepoint before the loop, the processing effect takes precedence over sleep

broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java, client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/CheckTransactionStateRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ConsumerSendMsgBackRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/EndTransactionRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/GetEarliestMsgStoretimeRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/GetMaxOffsetRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/GetMinOffsetRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PullMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/QueryConsumerOffsetRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ReplyMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/SearchOffsetRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/SendMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/SendMessageRequestHeaderV2.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/UpdateConsumerOffsetRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/rpc/RpcRequestHeader.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
Backport 5.0 bname protocol for 4.9.x client
See [this issue](https://github.com/apache/rocketmq/issues/3905) for more information
=> [ISSUE #3905] Support bname in protocol for 4.9.x client

.asf.yaml
=> Disable merge button

.github/asf-deploy-settings.xml, .github/workflows/snapshot-automation.yml
Support auto snapshot deployment of Apache RocketMQ daily.
This pull request is to fix https://github.com/apache/rocketmq/issues/5121
The snapshot deployment job will be triggered by Jenkins under two conditions:
- Check if there's any update in RocketMQ Git repo every 2 hours, it will start working if there are new commits.
- Run without commit check every 12 hours (in case the first rule has been triggered but the CI is still pending)
The Jenkins will do the following steps:
1. Check if the current commit has already been deployed.
2. Check the current commit has passed the CI.
3. Check the current project is using the snapshot version.
4. Do snapshot deployment.
5. Save the current commit id.
Follow this checklist to help us incorporate …
=> [ISSUE #5121]Add GitHub Action Pipeline to automate release of RocketMQ Snapshots

broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/topic/LmqTopicConfigManager.java, broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
close #5200 
In RocketMQ 4.9.3，the interface updateConsumerOffset does not check whether the topic exists or not. But in RocketMQ 5.0 do the check. LMQ's topic will not register to namesv， so it will throw error when save offset in rocketmq-mqtt.
https://github.com/apache/rocketmq-mqtt/issues/150
add containsTopic interface in TopicConfigManager, when enable lmq it will use LmqTopicConfigManager#containsTopic which process LMQ Topic
=> [ISSUE #5214] compatible rocketmq-mqtt save offset

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
=> [ISSUE #5231] Optimize reput message code.

common/src/main/java/org/apache/rocketmq/common/utils/ServiceProvider.java
issue:
[#5263](https://github.com/apache/rocketmq/issues/5236)
=> [ISSUE #5236] fix  ServiceProvider loading class 

common/src/main/java/org/apache/rocketmq/common/utils/ServiceProvider.java
[issue](https://github.com/apache/rocketmq/issues/5254)
=> [ISSUE #5254] Stream close optimization

test/src/main/java/org/apache/rocketmq/test/lmq/benchmark/BenchLmqStore.java, test/src/test/java/org/apache/rocketmq/test/lmq/TestBenchLmqStore.java
Fix issue https://github.com/apache/rocketmq/issues/5272
XX
XXXX
=> [ISSUE #5272]Fix NPE in CI

proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/AbstractStartAndShutdown.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/StartAndShutdown.java
Add preShutdown for grace shutdown
This is to fix https://github.com/apache/rocketmq/issues/5311
Add the preShutdown to do grace shutdown work before real shutdown logic.
=> [ISSUE #5311] Add preShutdown for grace shutdown

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java, broker/src/test/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessorTest.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/ContextVariable.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/ProxyContext.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/channel/GrpcChannelManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/channel/GrpcClientChannel.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ClientProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/MessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/test/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroupTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/mqclient/ProxyClientRemotingProcessorTest.java
Optimize proxy module ReceiptHandleProcessor and GrpcChannelManager methods
* Use channel to manage MessageReceiptHandle
* Remove group in GrpcChannelManager
* Add get method for ReceiptHandleGroup
=> [ISSUE #5313] Optimize ReceiptHandleProcessor and GrpcChannelManager

broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/CheckTransactionStateRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/EndTransactionRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ReplyMessageRequestHeader.java
Remove unused header fields to keep compatible with develop
* including `CheckTransactionStateRequestHeader`, `EndTransactionRequestHeader`, `ReplyMessageRequestHeader`
=>  [ISSUE #3905] Remove unused header fields

broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/AckMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ChangeInvisibleTimeRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/CheckTransactionStateRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ConsumerSendMsgBackRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/EndTransactionRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/NotificationRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PeekMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PollingInfoRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/PopMessageRequestHeader.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/SendMessageRequestHeaderV2.java
Support bname in protocol for 5.0 client
* add `bname` for `CheckTransactionStateRequestHeader`, `ConsumerSendMsgBackRequestHeader`, `EndTransactionRequestHeader`, `SendMessageRequestHeader`
=> [ISSUE #3905] Support bname in protocol for 5.0 client

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
close #5332 
- Remove DefaultMessageStore's private field printTimes that is never used
XXXX
=> [ISSUE #5332]Remove DefaultMessageStore's private field printTimes that is never used

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
add extra output infomation when start the namesrv 
Fixes #5373 
before the changes,the output is "The Name Server boot success. serializeType=JSON"
after:
The Name Server boot success. serializeType=JSON, address 0.0.0.0:9876
=> [ISSUE #5373]output namesrv bindaddress when starting

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
=> [ISSUE #5390] not to print some useless log in PopReviveService

broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
[issue](https://github.com/apache/rocketmq/issues/5424)
=> [ISSUE #5424]fix null exception and array overflow bug exist in getHalfMsg method

broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java
[issue](https://github.com/apache/rocketmq/issues/5415)
=> [ISSUE #5415]fix duplicate records

store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java
Link https://github.com/apache/rocketmq/issues/5331
```
Failed tests: 
CompactionLogTest.testReplaceFiles:259->lambda$testReplaceFiles$3:260
```
https://github.com/apache/rocketmq/actions/runs/3335676387/jobs/5520208604
XX
XXXX
=> [ISSUE#5331] Fix windows can't move file when mmapped.

broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopBufferMergeServiceTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/transaction/TransactionDataManagerTest.java
Remove the null check for topicData in HookUtils. Fix the typo for variable tranformRes to transformRes.
Resolves https://github.com/apache/rocketmq/issues/5430.
Remove redundant null check and fix typo.
This pr does not change logic, it only contains small code improvements.
=> [ISSUE #5430] Remove redundant null check

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
closes https://github.com/apache/rocketmq/issues/5437
=> [ISSUE #5437] Add log info for push consumer when execute hook failed

broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, common/src/main/java/org/apache/rocketmq/common/utils/ServiceProvider.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQNormalConsumer.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopConsumer.java, test/src/main/java/org/apache/rocketmq/test/factory/ConsumerFactory.java, test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java, test/src/test/java/org/apache/rocketmq/test/offset/OffsetResetForPopIT.java, tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java
[RIP-48] Support reset offset in server-side for pop message
=> [RIP-48] Support reset offset in server-side for pop message

client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java
The variable whichItemWorst name is ambiguous, so I modify variable name whichItemWorst to randomItem to resolve ambiguity.
modify variable name whichItemWorst to randomItem to resolve ambiguity
Trivial changes: This pr only changes the variable name and does not involve logic code modification.
I have run `mvn clean install -DskipITs` to make sure unit-test pass.
=> [ISSUE#5404] modify variable name whichItemWorst to randomItem to resolve ambiguity

common/src/main/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingUtils.java
closes https://github.com/apache/rocketmq/issues/5493
=> [ISSUE #5493] fix : npe caused by get item by logic offset if the target logicQueueMappingItem was out of date

example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
=> [ISSUE #5281]Optimize the output of pressure results

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ProcessQueueTest.java
=> [ISSUE #5481] Decrease the repeated consumption probability of expired message

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
InterruptedException should not be ignored  
print InterruptedException  message and  Restore interrupted state
InterruptedException should not be ignored
print InterruptedException  message and  Restore interrupted state
try {
scheduledExecutorService.awaitTermination(5000, TimeUnit.MILLISECONDS);
} catch (InterruptedException ignore) {
BrokerController.LOG.warn("shutdown ScheduledExecutorService was Interrupted!  ", ignore);
Thread.currentThread().interrupt();
}
=> InterruptedException should not be ignored

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
Make getClazzFields obtain super class field to support bname. And it's backported from 5.0.0.
Make getClazzFields obtain super class field
=>  Make getClazzFields obtain super class field

controller/src/main/java/org/apache/rocketmq/controller/elect/impl/DefaultElectPolicy.java
Fix some comments in DefaultElectPolicy
Fix some comments in DefaultElectPolicy
=> [Issue #4330]Fix some comments in DefaultElectPolicy

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/RegisterBrokerBody.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RegisterBrokerBodyTest.java
fixes https://github.com/apache/rocketmq/issues/5536
Make the new name srv compatible with the old broker.
While broker configure compressedRegister=true，if we update the cluster by rolling, upgrading broker after upgrading name server or vice versa, would cause exception as follows:
So, we should consider the broker version to decode the register broker body
=> [ISSUE #5536] fix:new version name server should be compatible with old version broker

WORKSPACE, acl/BUILD.bazel, acl/pom.xml, broker/BUILD.bazel, broker/pom.xml, client/BUILD.bazel, client/pom.xml, common/BUILD.bazel, common/pom.xml, container/BUILD.bazel, controller/BUILD.bazel, namesrv/BUILD.bazel, pom.xml, proxy/BUILD.bazel, proxy/pom.xml, remoting/BUILD.bazel, srvutil/BUILD.bazel, store/BUILD.bazel, test/BUILD.bazel, test/pom.xml, tools/BUILD.bazel
Since we have moved https://github.com/aliyun-mq/rocketmq-logging to https://github.com/aliyunmq/rocketmq-logging, the groupId of rocketmq-logging should be updated
=> Update group id of rocketmq logging

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
#5303 
In #5304 , there were two failed CI projects below, but they could not be reexecuted and one was resubmitted
XX
XXXX
=> [ISSUE #5303]Resolved the invalid authentication problem of sending batch messages

proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/ClusterMessageService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIExt.java
Optimize proxy interface and method
* Add popMessage AddressableMessageQueue interface
* Change ClusterMessageService field to protected
* Add notification in MQClientAPIExt
=> Optimize proxy interface and method

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/LitePullConsumer.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerAssign.java, example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerAssignWithSubExpression.java
Close #5639 
Deprecated the ambiguous methods of lite pull consumer
XX
XXXX
=> [ISSUE #5639] Deprecated the ambiguous methods of lite pull consumer

proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java
Close #5659 
Since printStackTrace() is also an err stream output, duplicate log prints are removed
XXXX
=> [ISSUE #5659] Remove redundant error log output

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java
Fix #5631 
- Fix ReplicasInfoManager#registerBroker not check master is alive
XXXX
=> [ISSUE #5631]optimize ReplicasInfoManager#registerBroker logic

docs/cn/README.md
=> [ISSUE #5732]Fix StaticTopic link not found in cn README.md

WORKSPACE, broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, broker/src/main/java/org/apache/rocketmq/broker/processor/DefaultPullMessageResultHandler.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/failover/EscapeBridgeTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PullMessageProcessorTest.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java, common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/DispatchRequest.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java, store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java, store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java, store/src/main/java/org/apache/rocketmq/store/plugin/AbstractPluginMessageStore.java, store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java, test/BUILD.bazel
=> [ISSUE #5754] [RIP-57] Add asynchronous interfaces to MessageStore

common/src/main/java/org/apache/rocketmq/common/UtilAll.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializable.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializableTest.java
=> [ISSUE #5699] remove duplicate code definition of UtilAll.isBlank

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcValidator.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcValidatorTest.java
For #5776 , remove repeated empty string checks for `topic` and `group`, and add unit tests.
org.apache.rocketmq.client.Validators#checkTopic：
org.apache.rocketmq.client.Validators#checkGroup：
=> [ISSUE #5776] Remove duplicate empty string checks

docs/cn/QuorumACK.md, docs/en/QuorumACK.md
close #5793 
- Translation QuorumACK.md chinese document to english document
- polish QuorumACK.md  cn document
XXXX
=> [ISSUE #5793]Translation QuorumACK.md chinese document to english document and polish cn document

store/src/main/java/org/apache/rocketmq/store/GetMessageResult.java, store/src/test/java/org/apache/rocketmq/store/GetMessageResultTest.java
=> [ISSUE  #5830] fix bug in GetMessageResult#getMessageCount

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> fix restNum calculation in pop consumption mode

common/src/main/java/org/apache/rocketmq/common/attribute/AttributeParser.java
close #5507 
- Improve the speed of AttributeParser#parseToMap parsing
- Polish code
XXXX
=> [ISSUE #5507]Improve the speed of AttributeParser#parseToMap parsing

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/RemotingProtocolServer.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/pipeline/AuthenticationPipeline.java
=> [ISSUE #5852] Don't create PlainAccessValidator when enable proxy and aclEnable is false

common/src/main/java/org/apache/rocketmq/common/UtilAll.java
fix #5740
According to RFC 1122, { 127, any } are reserved for internal host loopback address.So `isInternalIP` function return true when ip is between 127.0.0.0~127.255.255.255.
And now it prefers LAN ip to localhost(internal host loopback address).
XXXX
=> [ISSUE #5740] Fix util.getIP sometimes choose localhost over LAN ip.

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
close #5859 
- Optimize String#format in DefaultMQProducerImpl
XXXX
=> [ISSUE #5859]Optimize String#format in DefaultMQProducerImpl

client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
=> [ISSUE #5876] fix resource leak in DefaultLitePullConsumerTest

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
Close #5921 
Support domain resolution to obtain the controller address
Support domain resolution to obtain the controller address
XXXX
=> [ISSUE #5921] Support domain resolution to obtain the controller address

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicQueueMappingInfo.java
close #5949 
- Remove TopicQueueMappingInfo class duplicate licenses
XXXX
=> [ISSUE #5949]Remove TopicQueueMappingInfo class duplicate licenses

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #5953] calculate retry message throughput in pop consumption mode

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
close #5939 
- Adjust the MQClientInstance#sendHeartbeatToAllBroker catch code block log print level from info to warn
XXXX
=> [ISSUE #5939]Adjust the MQClientInstance#sendHeartbeatToAllBroker catch code block log print level from info to warn

broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
close #5986 
optimize the BrokerOuterAPITest class code
XXXX
=> [ISSUE #5986] optimize the BrokerOuterAPITest class code

broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
Add checkBlock for hasMsgFromQueue
Add checkBlock for hasMsgFromQueue for fifo message notification.
=> [ISSUE #5847] Add checkBlock for hasMsgFromQueue

client/src/main/java/org/apache/rocketmq/client/trace/TraceContext.java
close #6033 
modify TraceContext toString method
XXXX
=> [ISSUE #6033] modify TraceContext toString method

docs/cn/README.md, docs/cn/proxy/deploy_guide.md
=> [ISSUE #5927]Add Proxy deploy guide cn document

.github/workflows/pr-ci.yml, .github/workflows/pr-e2e-test.yml, .github/workflows/push-ci.yml, README.md
- Add new CI config to run e2e test(apache/rocketmq-e2e) when PUSH or PR.
1. New CI provides an independent RocketMQ environment for E2E testing by using the Alibaba Cloud ASK capability for each PUSH and PR, and deploys using the helm chart (apache/rocketmq-docker), and the mirror image is the submitted code.
2. The test report is visualized, and the report of each UT and E2E test is displayed visually on the current execution page of CI, no need to check the log, which is convenient for troubleshooting.
3. Compatibility testing is supported, and testing of multiple OS and JDK versions can be performed concurrently.
4. Due to security considerations, the PR and PUSH action CIs are separated into two pipelines.
- PUSH: …
=> [RIP-41] Add E2E test to CI

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/route/BrokerData.java
close #5947 
- Optimize RouteInfoManager#pickupTopicRouteData create BrokerData code
XXXX
=> [ISSUE #5947]Optimize RouteInfoManager#pickupTopicRouteData create BrokerData code

acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
=> [ISSUE #6112] Fix typos in RemoteAddressStrategyFactory

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/container/TieredContainerManager.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/container/TieredFileQueue.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/util/TieredStoreUtil.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredDispatcherTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageFetcherTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageStoreTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredStoreTestUtil.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/container/TieredContainerManagerTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/container/TieredFileQueueTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/container/TieredIndexFileTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/container/TieredMessageQueueContainerTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/metadata/MetadataStoreTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManagerTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/mock/MemoryFileSegmentWithoutCheck.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegmentTest.java
=> [ISSUE #6123] Fix flaky test in tiered storage

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
=> [ISSUE #6092] fix: wrong brokerConfigPath when init configuration

proxy/src/main/java/org/apache/rocketmq/proxy/common/MessageReceiptHandle.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java
=> [ISSUE #6149] remove handle when exceed renewMaxTimeMillis

broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
=> [ISSUE #6141] validate group when auto create subscription group

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
=> [ISSUE #6087] fix typos

common/src/main/java/org/apache/rocketmq/common/constant/LoggerName.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProtocolProxyHandler.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProxyBackendHandler.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProxyFrontendHandler.java, remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java, remoting/src/main/java/org/apache/rocketmq/remoting/common/ServiceThread.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyDecoder.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyEncoder.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/TlsHelper.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
=> Polish the unified remoting logger name.

store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/FlowMonitor.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java
close: https://github.com/apache/rocketmq/issues/6121
fix #<xxx> 
XX
XXXX
=> [ISSUE #6121] Optimize some code style in store module

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java
=> [ISSUE #6185] Fix It does not take effect when acl is enabled in the proxy

broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopRequest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicQueueMappingUtils.java, remoting/src/main/java/org/apache/rocketmq/remoting/rpc/ClientMetadata.java, test/src/main/java/org/apache/rocketmq/test/schema/SchemaTools.java, test/src/main/java/org/apache/rocketmq/test/util/TestUtil.java, test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
close #6145 
modify Collections.sort usage
XXXX
=> [ISSUE #6145] modify Collections.sort usage

test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
fix #6060 
- Optimize AutoSwitchRoleBase#nextPort method
XXXX
=> [ISSUE #6060]Optimize AutoSwitchRoleBase#nextPort method

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/SyncStateInfo.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAConnection.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
fix #6226
Shutdown flowMonitor when connection disconnect
XXXX
=> [ISSUE #6226] Shutdown flowMonitor when connection disconnect

.github/ISSUE_TEMPLATE/issue_template.md
fix #6244 
- Fix issue template feature request order incorrect
XXXX
=> [ISSUE #6244]Fix issue template feature request order incorrect

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
Change-Id: I665c5b9d7e96c5b7ccd035b32272be7223d7f454
The dledger commit log currently did not override the new getData method, while using dledger mode it will cause the read failed. In timer store it will get commit log using this method.
XX
XXXX
=> [ISSUE #5883] Dledger commit log should override the getData

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java
=> [ISSUE #6230] Optimizes ScheduleMessageService code and logic

distribution/bin/runserver.sh
`sed -r` is not compatible with MacOS, replace it by `awk`.
related issue: #6026
=> [ISSUE #6026] Remove uncompatible sed in runserver.sh

broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java
=> [ISSUE #6213] fix: when subscriptionGroupConfig is null ,we do not register consumer

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerControllerStateMachine.java
=> [ISSUE #6285] Polish the DLedgerControllerStateMachine log output to help troubleshoot

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java, broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
fix #6316
在Nameserver broker注册逻辑中，已经有以下逻辑保证多个master出现时选topicConfig中stateVersion更大的
因此在Controller模式中，当角色发生变化时，会利用epoch当作stateVersion当作版本号
XXXX
=> [ISSUE #6316] Nameserver should choose a master with a larger epoch when there are two masters in controller mode

client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java
fix #6272 
- Add judgment for SendLatencyFault in MQFaultStrategy#selectOneMessageQueue
XXXX
=> [ISSUE #6272]Add judgment for SendLatencyFault in MQFaultStrategy#selectOneMessageQueue

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/filter/FilterAPI.java
fix #6333 
- Simplify the logic of the FilterAPI#buildSubscriptionData method
- remove some useless method
XXXX
=> [ISSUE #6333]Simplify the logic of the FilterAPI#buildSubscriptionData method

example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
closes #6215 
We could use benchmark like this to compress message body which is larger than 2 KB with "ZSTD" compress algorithm:
```sh producer.sh -n namesrv -t topic -c true -ct ZSTD -cl 5 -ch 2048```
=> [ISSUE #6215]Make benchmark cover compress msg situation

WORKSPACE, broker/BUILD.bazel, broker/pom.xml, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/resources/rmq.broker.logback.xml, common/pom.xml, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, pom.xml, proxy/BUILD.bazel, proxy/pom.xml, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/metrics/ProxyMetricsManager.java, proxy/src/main/resources/rmq.proxy.logback.xml
I have completed the issue #5678 @ShadowySpirits , now broker and proxy could export metrics in terminal.
=> [ISSUE #5678] Add logging exporter for metrics

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/test/java/org/apache/rocketmq/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/ControllerTestBase.java, controller/src/test/java/org/apache/rocketmq/controller/impl/DLedgerControllerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManagerTest.java
1. support asynchronous notify brokers when roles changed
fix #6346 
XX
XXXX
=> [ISSUE #6346] Support asynchronously notify brokers when their roles has been changed

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
fix #6343
delete consumeQueueExtDir when deleting topics
Set enableConsumeQueueExt to true, create a topic then delete it. Check the consume queue ext directory.
=> [ISSUE #6343] fix(store): fix consumeQueueExtDir not deleted when deleting topic

proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/SendMessageActivityTest.java
=> [ISSUE #6203] Allow to publish delay message with arbitrary timestamp

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionStore.java
=> [ISSUE #6497] flush in compactionTopic

.asf.yaml, .github/workflows/maven.yaml
We will upgrade it with the latest operating system image later.
related issue: #6560
=> Temporary removal of required maven-compile status check

store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java, store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueInterface.java, store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java
close #6525
we are typecasting here
```
private FileQueueLifeCycle getLifeCycle(String topic, int queueId) {
return (FileQueueLifeCycle) findOrCreateConsumeQueue(topic, queueId);
}
```
but interface is not extending FileQueueLifeCycle.
So it will throw typecast error.
=> [ISSUE #6525]Make ConsumeQueueInterface extends from FileQueueLifeCycle

client/src/main/java/org/apache/rocketmq/client/MqClientAdmin.java, client/src/main/java/org/apache/rocketmq/client/impl/admin/MqClientAdminImpl.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIExt.java, remoting/src/main/java/org/apache/rocketmq/remoting/RemotingClient.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java
close #6644
Add future interface for admin methods
=> [ISSUE #6644] Add admin client future interface

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
Fixes #6662
Determine whether all brokers in syncStateSet have established connections. If not, the confirmOffset cannot be updated.
判断syncStateSet中的broker是否都建立有连接。如果没有，则无法更新confirmOffset.
using openchaos. 
So far no messages have been lost.
=> [ISSUE #6662] Optimize the process of HA's confirmOffset calculation

broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManagerLockFreeNotifyTest.java, broker/src/test/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManagerTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/PopMessageRequestHeader.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BasePopOrderly.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopOrderlyIT.java, test/src/test/java/org/apache/rocketmq/test/offset/OffsetResetForPopIT.java
=> [ISSUE #6691] Support reentrant pop orderly for broker

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
Fixes #6703 
Fix the incorrect of confirmOffset when recovering abnormally caused by message loss due to asynchronous flushing after restarting
=> [ISSUE #6703] Fix the incorrect of confirmOffset when recovering abnormally caused by message loss due to asynchronous flushing after restarting

.github/workflows/codeql_analysis.yml
Fixes #6708 
Enable GitHub cache for CodeQL to ensure the success of maven dependencies' download
I have tested it in my fork.
=> [ISSUE #6708] Use GitHub cache for CodeQL

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PollingHeader.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PollingResult.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopLongPollingService.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopRequest.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExt.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/NotificationIT.java
Fixes #6699
Move long-polling related code from PopMessageProcessor into PopLongPollingService like wakeup()
Use PollingResult enum to replace int value
NotificationProcessor use PopLongPollingService to implement long-polling.
Add a NotificationIT
=> [ISSUE #6699] Make NotificationProcessor use PopLongPollingService

broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
Fixes #6712 
-Remove useless method BrokerOuterAPI#pullMessageFromSpecificBroker
=> [ISSUE #6712]Remove useless method BrokerOuterAPI#pullMessageFromSpecificBroker

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java, example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingPushConsumer.java, openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PushConsumerImpl.java
Fixes #6714 
-Replace the deprecated method DefaultMQPushConsumer#getDefaultMQPushConsumerImpl
=> [ISSUE #6714]Replace the deprecated method DefaultMQPushConsumer#getDefaultMQPushConsumerImpl

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
[ISSUE #6728] Compute the confirmOffset without considering new connections.
Fixes #6728 
1. When calculate the newConfirmOffset, skip those connections with -1 ackOffset value.
2. Add a new method, getConfirmOffsetDirectly(). This method will only return the confirmOffset without checking and re-computing. Because in some cases (If set confirmOffset wrongly) endless calling will occur between the getConfirmOffset() and computeConfirmOffset().
=> [ISSUE #6728] Compute the confirmOffset without considering new connections

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, controller/src/test/java/org/apache/rocketmq/controller/ControllerRequestProcessorTest.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java
=> Make configPath unable to update at runtime

broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/NotificationRequestHeader.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/NotificationIT.java
=> [ISSUE #6761] Support reentrant notification orderly for broker

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
Fixes #6789
Modify placeholder in DefaultMQProducerImpl.
1. Start a producer
2. Produce message synchronously
=> [ISSUE #6789] modify placeholder in DefaultMQProducerImpl

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
…long time
Fixes #6792
Change the log level to debug.
1. Start a producer
2. Produce message synchronously with a relatively large message body
=> [ISSUE #6792] Fix the bug that send method blocked on log.warn for a long time

proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncer.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncerTest.java
=> [ISSUE #6785] Isolate the remoteChannel by group

docs/en/operation.md
The word ‘fomat’ in [docs/en/operation.md] is wrong.So change it to 'format'.And also add a missing white space.
=> doc: fix typo in operation.md

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
=> [ISSUE#6595] fix NPE and repeat access key log

store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java
Fix #6849 
Solve the discussion #6839 
The confirmation of the three copies may not be as timely, and there is no need to wait for 1 second when entering the second round of confirmation. 
Just wait for 1 second.
Use the checkMsgSendRT:
=> [ISSUE #6849] Fix the issue of increasing RT in three replicators

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
Fixes #6779
Don't dispatch message to LMQ when the message is scheduled message.
1. Start a consumer to consume a LMQ
2. Send a message with delay level or delay time
3. The message consumed at scheduled time
=> [ISSUE #6779] Support scheduled message for LMQ

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/OptionalSSLProtocolNegotiator.java
Support dynamic modification of grpc TLS mode to improve the scalability of ProtocolNegotiator
Fixes #6866
Support dynamic modification of grpc TLS mode to improve the scalability of ProtocolNegotiator
Yes.
=> [ISSUE #6866] Move the judgment logic of grpc TLS mode to improve the scalability of ProtocolNegotiator

.github/workflows/pr-e2e-test.yml, .github/workflows/push-ci.yml
=> [ISSUE #6824] Add golang e2e test

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java
https://github.com/apache/rocketmq/issues/6881
scheduled messages are replayed bug
=> [ISSUE #6881] Fix scheduled messages are replayed bug

broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java, broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java, broker/src/test/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManagerTest.java, broker/src/test/java/org/apache/rocketmq/broker/topic/TopicConfigManagerTest.java, common/src/main/java/org/apache/rocketmq/common/SubscriptionGroupAttributes.java, common/src/main/java/org/apache/rocketmq/common/attribute/AttributeUtil.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java, tools/src/main/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupSubCommand.java
Fixes #6889
Add attribute for SubscriptionGroupConfig like TopicConfig
Unit test
=> Add attribute for SubscriptionGroupConfig

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/test/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManagerTest.java
Fixes #6900
Add attributesBuilderSupplier for BrokerMetricsManager for the extension.
Unit test
=> Add attributesBuilderSupplier for BrokerMetricsManager

proxy/src/main/java/org/apache/rocketmq/proxy/service/route/ClusterTopicRouteService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/MessageQueueView.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/route/ClusterTopicRouteServiceTest.java
Fixes [#6908](https://github.com/apache/rocketmq/issues/6908)
Fix the problem that the proxy in the cluster mode obtains the wrong address of broker.
I have tested it.
=> Fix the problem that the proxy in the cluster mode obtains the wrong address of broker

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopInflightMessageCounter.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AckMessageProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopInflightMessageCounterTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/BitSetSerializerDeserializer.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/BatchAck.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/BatchAckMessageRequestBody.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ExtraInfoUtil.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/body/BatchAckTest.java
Fixes #6841
Currently, the POP consumer can pull up to 32 messages in batch, but after consuming one message, it needs to immediately ack once without achieving batching, which is inefficient and consumes bandwidth and CPU resources for both consumers and brokers.
To address this issue, we propose a solution of POP batch ack.
See the issue #6841 for more details.
1. Added a large number of unit tests and almost covered the code changes.
2. Scenario simulation, sending and receiving a specified number of messages to ensure that consumption does not repeat.
=> [ISSUE #6841] new feature: pop batch ack for pushConsumer

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
Fixes #6926 
Fixing the error in the initialization order of replicasManager caused the controller mode to fail to start.
=> [ISSUE #6926] Fixing the error in the initialization order of replicasManager caused the controller mode to fail to start.

broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
Fixes #6931 
Set table reference the same object for setSubscriptionGroupTable method
=> [ISSUE #6931] Set table reference the same object for setSubscriptionGroupTable method

client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
=> [ISSUE #6917] fix cannot query all messages of the same msgId

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/BrokerIdentity.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerConfig.java
=> [ISSUE #6910] Extract the interval of fetchNameServerAddr
