- store/src/main/java/org/apache/rocketmq/store/PutMessageSpinLock.java
> Fixed typo

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreShuwDownTest.java
Avoid message loss when shutdown with dispatch behind
> [ROCKETMQ-320] Message loss when shutdown with dispatch behind

- 1
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- common/src/main/java/org/apache/rocketmq/common/MixAll.java
Remove the code that is not useful in the loop
> [ROCKETMQ-226]Remove the code that is not useful in the loop

- broker/pom.xml
- namesrv/pom.xml
Fix broker and nameserver startup of develop branch.More information see 
https://github.com/apache/rocketmq/issues/256
Add slf4j dependency to broker and nameserver.
There is no test case in this case.
> [ISSUE #256] Fix Broker and NameServer startup

- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
broker default broker  config forceRegister  value 
org.apache.rocketmq.common.BrokerConfig forceRegister 
> [ISSUE #270] Bbroker force register nameserver 

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullMessageService.java
Check pull request thread pool is not stopped before scheduling new tasking
Add guarding code to check 
Exceptions are no longer raised after applying this checking
> [ISSUE #276] Check if pull message service has shutdown before scheduling pull request

- .travis.yml
- test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQAsyncSendProducer.java
- test/src/test/java/org/apache/rocketmq/test/client/producer/async/AsyncSendWithMessageQueueIT.java
Fix RMQAsyncSendProducer thread-safe bugs caused by using ArrayList in the interface SendCallback.
Modify the ArrayList with thread-safe structure, and clear after used
This is a trivial change.
> [ISSUE #321]Fix RMQAsyncSendProducer thread-safe bugs

- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearby.java
- client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearByTest.java
JIRA: https://issues.apache.org/jira/browse/ROCKETMQ-203?jql=project%20%3D%20ROCKETMQ
> [ROCKETMQ-203]Support client to allocate message queue in machine room nearby priority

- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- broker/src/test/java/org/apache/rocketmq/broker/processor/SendMessageProcessorTest.java
- client/src/main/java/org/apache/rocketmq/client/Validators.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java
- common/src/main/java/org/apache/rocketmq/common/MixAll.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
JIRA: https://issues.apache.org/jira/browse/ROCKETMQ-223
> [ROCKETMQ-223]-Rename DEFAULT_TOPIC

- broker/src/main/java/org/apache/rocketmq/broker/latency/BrokerFastFailure.java
improve code for avoid ClassCastException 
sometimes  BrokerFastFailuru#castRunnable throw ClassCastException , so fix it . 
improve code for avoid ClassCastException 
> [ROCKETMQ-340] improve code for avoid ClassCastException.

- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearby.java
- remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstractTest.java
Fix conflict found in the merge process
XXXXX
XX
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily.
> [ISSUE #364]Fix conflict found in the merge process

- .github/PULL_REQUEST_TEMPLATE.md
- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
about issues https://github.com/apache/rocketmq/issues/408
> shutdown transactionalMessageCheckService

- tools/src/main/java/org/apache/rocketmq/tools/command/message/ConsumeMessageCommand.java
To fix problem of ConsumeMessageCommand -g setting
Modify commandLine getOption
XXXX
> [ISSUE #439] fix ConsumeMessageCommand -g option

- common/src/test/java/org/apache/rocketmq/common/MixAllTest.java
The case testGetLocalInetAddress sometimes failed in ubuntu machine，because InetAddress.getLocalHost().getHostAddress() may return 127.0.1.1 replace of local ip.
fix [issue490](https://github.com/apache/rocketmq/issues/490)
delete the check of local ip
> [ISSUE#490]testGetLocalInetAddress sometimes failed in ubuntu machine

- client/src/main/java/org/apache/rocketmq/client/consumer/MQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
fix [issue[461]](https://github.com/apache/rocketmq/issues/461)
1 add  @Deprecated in Class MQClientInstance 
2 add @Deprecated in Class ClientConfig
> [ISSUE #461]Purge filterserv related code in client

- example/src/main/java/org/apache/rocketmq/example/simple/AsyncProducer.java
Fix the issue [478](https://github.com/apache/rocketmq/issues/478)
> [ISSUE478]Polish async send message sample

- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
[Fix issue 406](https://github.com/apache/rocketmq/issues/406)
slove the NullPointerException
XXXX
> [ISSUE #406]Fix NPE exception

- README.md
- pom.xml
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
fix comment
fix comment，change "Enable transient commitLog store `poll`" to "Enable transient commitLog store `pool`"
> Fix the spelling error in comment

- broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
Fix issue [544](https://github.com/apache/rocketmq/issues/544)
Fixed the issue when using CHECK_IMMUNITY_TIME_IN_SECONDS properties, half message may be lostt under extreme condition.
Remove the repeat judge logic 
> [ISSUE #544]Fixed Transactional message will be lost under extreme condition

- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java
Fix issue 586, format output precision.
ConsumerProgressSubCommand.java
> [ISSUE #586] Format output number.

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
Fix [issue](https://github.com/apache/rocketmq/issues/604)
Release semaphore if timeout;
Change RemotingTooMuchRequestException to RemotingTimeoutException if timeout.
> [ISSUE #604]Fix semaphore problem

- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/main/java/org/apache/rocketmq/client/trace/core/common/TrackTraceConstants.java
- client/src/main/java/org/apache/rocketmq/client/trace/core/dispatch/impl/AsyncArrayDispatcher.java
- client/src/main/java/org/apache/rocketmq/client/trace/core/hook/SendMessageTrackHookImpl.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- common/src/test/java/org/apache/rocketmq/common/BrokerConfigTest.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/TraceProducer.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/TracePushConsumer.java
- logappender/src/main/java/org/apache/rocketmq/logappender/common/ProducerInstance.java
- logappender/src/test/java/org/apache/rocketmq/logappender/AbstractTestCase.java
- test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQNormalConsumer.java
- test/src/main/java/org/apache/rocketmq/test/factory/ProducerFactory.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByIdSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorService.java
Support the feature which trace topic name value can be configurable by users.
The change codes are as followers.Users can configure the trace topic name in broker sides.And then,they can use their predefined trace topic name to send or consumer the message.At last,they can use this trace topic name in the rocketmq's console project.Of course,they can use the default trace topic name value—"RMQ_SYS_TRACK_TRACE".
I have already test this change code in my rocketmq cluster enviroment. 
> [ISSUE #525] Support the message track,add the function which supports trace topic name value configurable by users.

- broker/src/test/java/org/apache/rocketmq/broker/BrokerControllerTest.java
- distribution/conf/plain_acl.yml
- example/pom.xml
- example/src/main/java/org/apache/rocketmq/example/simple/AclClient.java
to solve the unit test don't paas.
I add the plain_acl.yml file for acl_feature.
I have already verified in local machine.
> [ISSUE#403] add the conf/plain_acl.yml file for acl_feature.

- acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java
- acl/src/test/java/org/apache/rocketmq/acl/common/PermissionTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionLoaderTest.java
- distribution/conf/tools.yml
- tools/pom.xml
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
##What is the purpose of the change
Fix some bugs for acl feature.
##Brief changelog
(1)fix some logical Exception and optimize some codes for acl feature.
(2)add distribution/conf/tools.yaml  in distribution .
(3)fix some logical Exception in rocketmq tools module.
I have already verified this pr in rocketmq cluster enviroment and alibaba MQ cloud enviroment.
> [ISSUE#403] fix some bugs and Optimization code for rocketmq's acl feature.

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java
- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
(1)Add the switch variable(traceTopicEnable) to allow users to isolate the users' general topic from trace topic.And this flag variable default is false.
(2)Use the aclEnable switch variable rather than enableAcl,keep naming specification,such as clusterTopicEnable.
Changelog is as followe:
I have already verified this codes change in cluster and aliyun enviroment.
> [ISSUE#525]add a switch variable(traceTopicEnable) for making msg trace worked which is decided by users and rename enableAcl flag variable.

- acl/pom.xml
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionLoaderTest.java
- acl/src/test/resources/conf/watch/plain_acl_watch.yml
What is the purpose of the change
Fix some bugs for msg_track feature.
Brief changelog
(1)update PlainAccessValidator watchService  in rocketmq acl module.
(2)fix some logical Exception  for msg_track feature.
> [ISSUE#403] fix acl config file watch bug,clean and optimize the codes for acl feature.

- pom.xml
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2ServerImpl.java
- remoting/src/main/java/org/apache/rocketmq/remoting/util/ServiceProvider.java
- remoting/src/test/java/org/apache/rocketmq/remoting/RemotingHttp2InvokingTest.java
- remoting/src/test/java/org/apache/rocketmq/remoting/RemotingNettyInvokingTest.java
- remoting/src/test/java/org/apache/rocketmq/remoting/TlsTest.java
- remoting/src/test/resources/service/org.apache.rocketmq.remoting.RemotingClient
- remoting/src/test/resources/service/org.apache.rocketmq.remoting.RemotingServer
add http2 unit test case,fix http2 shutdown issue and adjust some codes
add http2 unit test case,fix http2 shutdown issue and adjust some codes
I have already verified the change codes in my local machine and passed the all of unit test cases in remoting module.
> add http2 unit test case,fix http2 shutdown issue and adjust some codes

- acl/pom.xml
- acl/src/main/java/org/apache/rocketmq/acl/AccessResource.java
- acl/src/main/java/org/apache/rocketmq/acl/AccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/common/AclClientRPCHook.java
- acl/src/main/java/org/apache/rocketmq/acl/common/AclException.java
- acl/src/main/java/org/apache/rocketmq/acl/common/AclSigner.java
- acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
- acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java
- acl/src/main/java/org/apache/rocketmq/acl/common/SessionCredentials.java
- acl/src/main/java/org/apache/rocketmq/acl/common/SigningAlgorithm.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategy.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- acl/src/test/java/org/apache/rocketmq/acl/common/AclSignerTest.java
- acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
- acl/src/test/java/org/apache/rocketmq/acl/common/PermissionTest.java
- acl/src/test/java/org/apache/rocketmq/acl/common/SessionCredentialsTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionLoaderTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyTest.java
- acl/src/test/resources/conf/plain_acl.yml
- acl/src/test/resources/conf/plain_acl_null.yml
- acl/src/test/resources/conf/watch/plain_acl_watch.yml
- acl/src/test/resources/logback-test.xml
- acl/src/test/resources/watch/conf/plain_acl.yml
add acl model to snode branch,adjust some codes and pass all of unit test cases in acl model.
add acl model to snode branch,adjust some codes and pass all of unit test cases in acl model.
I have already verified the change codes in my local machine and passed the all of unit test cases in acl module.
> [ISSUE 403]add acl model to snode branch,adjust some codes and pass all of unit test cases in acl model.

- docs/cn/acl/user_guide.md
adjust and solve the formate of RocketMQ acl doc part.
adjust and solve the formate of RocketMQ acl doc part.
> [RIP-9]adjust the formate of RocketMQ acl doc part.

- client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
Should not update offset to broker
Update offset to snode
- [] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
> [ISSUE #737]Polish Push Consumer

- remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2ClientImpl.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2Handler.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/http2/Http2ServerImpl.java
- remoting/src/test/java/org/apache/rocketmq/remoting/RemotingHttp2InvokingTest.java
Just adjust and polish codes for supporting Http2 protocol.
The part of remoting model in the rocketmq.
I have aleady verified unit test cases in remoting model.
> [ISSUE #743]adjust some codes of supporting Http2 for rocketmq.

- client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/consumer/store/OffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/exception/MQSnodeException.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStoreTest.java
- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
- snode/src/main/java/org/apache/rocketmq/snode/service/impl/NnodeServiceImpl.java
(1)fix codestype and some codes issues in the client module.
(1)fix some method name and some logs in the client model
(1)verified the change codes in my local machine.
> [ISSUE #743]fix codestyle issue and adjust some issues in client module for snode branch.

- docs/en/Example_Simple.md
Add description section for the basic samples to RocketMQ Develop Guide:
* Add description section for broker configuration to English RocketMQ Develop Guide
Browse the section 1 in the RocketMQ_Example.md
> [RIP-9] Add the introduction of the basic samples in RocketMQ

- docs/en/Example_Delay.md
Add a delay example
Add a delay example in RocketMQ
> [RIP-9] Add a delay example in RocketMQ

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceRealPushImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
Support real push consume message model
Support real push consume message model
> Support real push consume message model

- docs/en/Example_Transaction.md
RocketMQ Developer Guide doc
Organize the English translation of the RocketMQ transaction message sample into the doc/en directory
> [RIP-9] Added sample English documents of English transaction messages

- docs/en/Example_Batch.md
Add the introduction of the batch message samples in RocketMQ.
Add the introduction of the batch message samples in RocketMQ.
> [RIP-9] Add the introduction of the batch message samples in RocketMQ

- docs/en/Example_Filter.md
create the filter example in English for RocketMQ client using guide.
create doc Example_Filter.md.
> [RIP-9]Add the English docs for Filter Example of RocketMQ into the develop guide for users

- docs/en/Deployment.md
add the English description document for Deployment.md
Added the Deployment.md file to the rocketmq/docs/en directory
Check the corresponding Deployment.md file in the rocketmq/docs/en directory to verify the change.
> [RIP-9] Add the English description document for Deployment.md

- store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
Add test cases for DefaultMessageStore.putMessages
test for DefaultMessageStore.putMessages
> [RIP-10] Add test cases for DefaultMessageStore.putMessages

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
add test cases for DefaultMessageStore.lookMessageByOffset
1. tests for lookMessageByOffset
2. tests for getMessageIds
3. tests for getMessageTotalInQueue
4. tests for getOffsetInQueueByTime
5. tests for getMessageStoreTimeStamp
6. tests for getEarliestMessageTime
7. tests for getStoreTime, (ps: getStoreTime is private, so i change to protected for test)
8. fix DefaultMessageStore#getEarliestMessageTime because it's not work when CommitLog has't enough messages.
All tests include DefaultMessageStoreTest run pass.
> [RIP-10]Add test cases for DefaultMessageStore which methods read from CommitLog/ConsumeQueue

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePullImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
Recover pull request for old message queue that is allocated on rebalance
Recover pull request for old message queue that is allocated on rebalance
> [RIP-11] Recover pull request for old message queue that is allocated on rebalance.

- store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
1.test buildRunningStatsTest
2.test computeDeliverTimestampTest , just test delayLeve(1:5s, 2:10s)
3.test delayLevel2QueueIdTest
4.test deliverDelayedMessageTimerTaskTest,include :
* 4.1 send delay message, delayLevel=1(5s)
* 4.2 pull message direct
* 4.3 pull message wait 6 seconds
* 4.4 compare message
> [RIP-10] Add  test cases of  ScheduleMessageService

- store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
Optimize test batch send message use cases
Sleep 3s waiting from build consumerQueue
> [RIP-10] Optimize test batch send message use cases

- docs/en/acl/Operations_ACL.md
Add the introduction of the access control list in RocketMQ
Add the introduction of the access control list in RocketMQ,file path :docs/en/acl/Operations_ACL.md
just open this file and vertify the content 
> [RIP-9] Add the introduction of the access control list in RocketMQ

- docs/en/Example_Orderly.md
to translate Examples of Ordered Messages into English version.
add new file Example_Orderly.md in docs/en/
file content is ok in Markdown reader.
> [RIP-9]To add English version of Examples of Ordered Messages in docs/en/

- docs/en/Example_OpenMessaging.md
to translate Examples of OpenMessaging into English version.
add new file Example_OpenMessaging.md in docs/en/
> [RIP-9] Commit docs Example_OpenMessaging.md

- tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java
Fix issus #776 
make mqadmin usage information more friendly to user
XXXX
> [ISSUE #776] make mqadmin usage information more friendly to user

- common/src/test/java/org/apache/rocketmq/common/protocol/ClusterInfoTest.java
Add test cases of ClusterInfo
Add test cases of ClusterInfo
> [RIP-10] Add test cases for ClusterInfo

- common/src/test/java/org/apache/rocketmq/common/admin/TopicStatsTableTest.java
add test cases for TopicStatsTable.java
add test cases for TopicStatsTable.java
XXXX
> [RIP-10]  Add test cases for TopicStatsTable.java

- common/src/test/java/org/apache/rocketmq/common/protocol/body/KVTableTest.java
Add test case for org.apache.rocketmq.common.protocol.body.KVTable.java
Add test case for org.apache.rocketmq.common.protocol.body.KVTable.java
XXXX
> [RIP-10] Add test case for KVTable

- broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
Simplify transaction.log
change log level in TransactionalMessageServiceImpl
> [ISSUE #731] Change log level in TransactionalMessageServiceImpl

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQRealPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/MQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/MQRealPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQRealPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/MQPushConsumerInner.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullMessageService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceRealPushImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
- example/src/main/java/org/apache/rocketmq/example/simple/PushConsumer.java
Polish the push consumer to support 4.x
Polish the push consumer to support 4.x
> Polish the push consumer to support 4.x

- docs/en/Operations_Trace.md
[RIP-9] Add Operations_Trace.md in recketmq
[RIP-9] Add Operations_Trace.md in recketmq
GentleNi
>  [RIP-9] Add Operations_Trace.md in rocketmq

- docs/en/Configuration_Client.md
RocketMQ Developer Guide doc
Client configuration section of the RocketMQ documentation best practices.
> [RIP-9]Add the client configuration section of the RocketMQ documentation best practices.

- docs/en/Configuration_System.md
Add the Configuration_System in RocketMQ 
Add the English Document of Configuration_System in RocketMQ 
> [RIP-9] Add the Configuration_System in RocketMQ 

- docs/en/CLITools.md
Add a CLITools.md file to illustrate the use of the mqadmin tool.
Add a CLITools.md file to the directory of docs/en
Check the corresponding CLITools.md file in the rocketmq/docs/en directory to verify the change.
> [RIP-9] Add ta CLITools.md file to illustrate the use of  mqadmin management tools

- docs/en/Example_Delay.md
Change the Chinese punctuation in Example_Delay.md to English punctuation
Change the Chinese punctuation in Example_Delay.md to English punctuation
Change the Chinese punctuation in Example_Delay.md to English punctuation
> [RIP-9] Change the Chinese punctuation in Example_Delay.md to English punctuation

- docs/en/Troubleshoopting.md
- docs/en/best_practice.md
[RIP-9] update the en doc for Troubleshoopting.md #881
> [RIP-9] update the en doc for Troubleshoopting.md #881

- docs/en/Example_Orderly.md
Delete the number on the title
Delete the number on the title
Delete the number on the title
> [RIP-9] Delete the number on the title

- docs/en/Troubleshoopting.md
update incorrect symbol ”，“ to  ”,“
update incorrect symbol 
update incorrect symbol ”，“ to  ”,“
> [RIP-9] update incorrect symbol

- docs/cn/best_practice.md
1.1节，发送消息注意事项中对SLAVE_NOT_AVAILABLE的描述不准确，建议删除“此时消息已经进入Master服务器队列，只有Master服务器宕机，消息才会丢失。“
删除“此时消息已经进入Master服务器队列，只有Master服务器宕机，消息才会丢失。“
XXXX
> [RIP-9] enhance description about the state "SLAVE_NOT_AVAILABLE" in the chinese version of "best_practice.md"

- docs/en/Example_Transaction.md
hange the project number to a solid black dot
hange the project number to a solid black dot
> [RIP-9]Change the project number to a solid black dot

- store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
1.send delay message,then the msg.getTopic() will change topic_XXXX
so,I'dont get message By msg.getTopic()
2.queueId is dependence by delayLevel
3.consumer delay , inc sleep time
4.add delete file before
> [RIP-10]fix-bug: ScheduleMessageServiceTest

- docs/en/Example_Orderly.md
’2.1 produce ordered messages’  changed ‘1 produce ordered messages’
Modify English document for Example_Orderly.md
> [RIP-9] Modify English document for Example_Orderly.md

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
Add test cases for   ConsumeMessageConcurrentlyService consume success status
Add test cases for   ConsumeMessageConcurrentlyService consume success status
Add test cases for   ConsumeMessageConcurrentlyService consume success status
> [RIP-10]  Add test cases for   ConsumeMessageConcurrentlyService consume success status

- common/src/test/java/org/apache/rocketmq/common/protocol/body/SubscriptionGroupWrapperTest.java
Add test cases for SubscriptionGroupWrapper
Add test cases for SubscriptionGroupWrapper
> [RIP-10] Add test cases for SubscriptionGroupWrapper

- tools/src/test/java/org/apache/rocketmq/tools/command/namesrv/UpdateKvConfigCommandTest.java
[RIP-10]Add test cases for UpdateKvConfigCommandTest
Add test cases for org.apache.rocketmq.tools.command.namesrv.UpdateKvConfigCommandTest
Add test cases for org.apache.rocketmq.tools.command.namesrv.UpdateKvConfigCommandTest
XXXX
> [RIP-10] Add test cases for UpdateKvConfigCommand

- docs/en/Configuration_Client.md
Modify Chinese punctuation to English
Modify Chinese punctuation to English
Modify Chinese punctuation to English
> [RIP-9] Modify Chinese punctuation to English

- docs/en/Operations_Consumer.md
Add description section for the Operations_Consumer to RocketMQ Develop Guide:
* Add description section for Operations_Consumer to English RocketMQ Develop Guide
Browse the section 1 in the best_practice.md
> [RIP-9] Add the introduction of the Operations_Consumer in RocketMQ

- docs/en/Design_Trancation.md
Add the English docs for Design_Trancation.md into the develop guide for users
Add Design_Trancation.md to the directory of docs/en
Check the corresponding Design_Trancation.md file in the rocketmq/docs/en directory to verify the change.
> [RIP-9] Add English document for Design_Trancation.md

- store/src/test/java/org/apache/rocketmq/store/HATest.java
HA test case optimization and reduce the time spent
the optimization of the case which named HATest  and reduce the time spent
> [RIP-10]HA test case optimization and reduce the time spent

- docs/en/Example_Orderly.md
Polish docs/en/Example_Orderly.md
Set markdown code format to Java language
Verified
> [RIP-9] Polish Example_Orderly.md

- docs/en/Example_Filter.md
format readme, delete useless spaces symbol
format readme, delete useless spaces symbol
Verified
> [RIP-9] format readme, delete useless spaces symbol

- docs/en/Design_Trancation.md
"Transactional Message" changed to"Transaction Message"
Modify English document for Design_Trancation.md
Verified
> [RIP-9] Modify English document for Design_Trancation.md

- docs/en/Example_Transaction.md
Modify the wrong word usage in the document.
Modify `transactional ` to `transaction `.
Verified
> [RIP-9] Modify incorrect word

- docs/en/Design_Store.md
’1. Message Storage Architecture’ changed ‘1 Message Storage Architecture’
Modify English document for Design_Store.md
XXXX
> [RIP-9] Modify English document for Design_Store.md

- docs/en/Example_Orderly.md
’2.2 produce ordered messages’ changed ‘2 produce ordered messages’
Modify English document for Example_Orderly.md
> [RIP-9]Modify English document for Example_Orderly.md

- docs/en/Design_Store.md
[RIP-100] Modify the article layout format
> Modify the article layout format

- common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
modify test case for StatsItemSetTest,adjust param
modify test case for StatsItemSetTest,adjust param
> [RIP-10] modify test case for StatsItemSetTest

- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
optimization test case of DefaultMessageStore
optimization test case of DefaultMessageStore
XXXX
> [RIP-10] optimization test case of DefaultMessageStore

- docs/en/Configuration_System.md
> [RIP-9]Update Configuration_System.md

- docs/en/Design_Remoting.md
modify docs/en/Design_Remoting.md
modify "When message Producer sends a message as a client"
> [RIP-9] Modify Design_Remoting.md

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
ConsumeMessageConcurrentlyServiceTest maybe other case，Ignore testPullMessage_ConsumeSuccess
ConsumeMessageConcurrentlyServiceTest maybe other case，Ignore testPullMessage_ConsumeSuccess
XXXX
> [RIP-10]  ConsumeMessageConcurrentlyServiceTest maybe effect other case,Ignore part  test  function

- docs/en/Configuration_System.md
update docs/en/Configuration_System.md
'define how aggressive the kernel will swap memory pages' change to 'defines  how aggressive the kernel will swap memory pages'
> [RIP-9] Update Configuration_System.md

- docs/en/Configuration_Client.md
> [RIP-9] Number the titles of Configuration_Client.md

- docs/en/CLITools.md
> [RIP-9]Update CTLTools.md

- docs/en/Example_Delay.md
…racter
update document Example_Delay.md
delete some punctuation mark in docs/en/Example_Delay.md
> [RIP-9] update rocketmq/docs/en/Example_Delay.md

- docs/en/FAQ.md
[RIP-9] update FAQ.md in RocketMQ docs/en
> [RIP-9] update FAQ.md in RocketMQ docs/en

- docs/en/Deployment.md
[RIP-9] update the title and delete cluster setup
> [RIP-9] update the title and delete cluster setup

- docs/en/Troubleshoopting.md
Format the document "docs/en/Troubleshoopting.md"
Remove "." behind the number in each title
> [RIP-9] Remove "." behind the number in each title of "docs/en/Troubleshoopting.md"

- docs/en/Configuration_System.md
1. Remove '**' on both sides of the title 'The system configuration'.
2. Add an English stop at the end of 25 lines.
Modify English document for Configuration_System.md
> [RIP-9] Modify English document for Configuration_System.md

- docs/en/Operations_Producer.md
> [RIP-9] Add a period at the end of the first paragraph 

- docs/cn/concept.md
delete useless image references and correct the description
delete useless image references and correct the description
1.0
> [RIP-9] Modify Chinese document for Concept.md 

- docs/en/Example_Transaction.md
'Transaction message example'  was changed to 'Transaction Message Example'
Modify English document for Example_Transaction.md
> [RIP-9] Modify English document for Example_Transaction.md

- docs/en/Example_Delay.md
[RIP-77]Modify the last paragraph and rid of punctuation between each section number and title
XXXXX
XX
XXXX
> [RIP-9]Modify the error of the Example_Delay.md

- docs/en/CLITools.md
[RIP-9] Modify the numbering style of the first paragraph
[RIP-9] Modify the numbering style of the first paragraph
[RIP-9] Modify the numbering style of the first paragraph
> [RIP-9] Modify the numbering style of the first paragraph

- docs/en/CLITools.md
> [RIP-65] Delete chinese period in CLITools.md file

- docs/en/Feature.md
XXXXX
XX
Update Feature.md in RocketMQ/docs/en
> Update Feature.md in RocketMQ/docs/en

- common/src/test/java/org/apache/rocketmq/common/protocol/GroupListTest.java
[PIR-10] add test for GroupList
[PIR-10] add test for GroupList
GroupListTest
> [PIR-10] add test for GroupList

- docs/cn/RocketMQ_Example.md
Modify the numbering style
Modify the numbering style
Modify the numbering style
> [RIP-9] Modify the numbering style

- docs/en/Configuration_System.md
New Change Configuration_System 90 : We recommend set 655350 - We recommend setting 655350
XX
XXXX
> [RIP-9] New Change Configuration_System 90 : We recommend set 655350 - We recommend setting 655350

- docs/en/Design_Remoting.md
> [RIP-9] Modify English document for Design_Remoting.md

- docs/en/Design_LoadBlancing.md
> [RIP-9] update Design_loadBlancing.md

- docs/en/Design_Trancation.md
Normalize documents
Remove unnecessary dots for Design_Trancation.md
XXXX
> [RIP-9] Remove unnecessary dots for Design_Trancation.md

- docs/en/Feature.md
> [RIP-9] Update Future.md. Add Function Title Number

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionLoader.java
if the user is an admin, it should be able to access all resources according to the default distribution/conf/plain_acl.yml file.
but if the user is not an admin, should check the permission by default rather than throw a NullPointerException cause ownedPermMap is null.
NPE in PlainPermissionLoader if permissions are not configured.
reproduce the steps mentioned in #1086, the program will run correctly without throwing NullPointerException.
> [ISSUE #1086] Fix NullPointerException in PlainPermissionLoader if permissions are not configured(with or not with admin user).

- mqtt/src/main/java/org/apache/rocketmq/mqtt/mqtthandler/impl/MqttPingreqMessageHandler.java
- mqtt/src/main/java/org/apache/rocketmq/mqtt/processor/DefaultMqttMessageProcessor.java
- mqtt/src/test/java/org/apache/rocketmq/mqtt/MqttPingreqMessageHandlerTest.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/mqtt/dispatcher/EncodeDecodeDispatcher.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/mqtt/dispatcher/MqttPingReqEncodeDecode.java
- remoting/src/main/java/org/apache/rocketmq/remoting/transport/mqtt/dispatcher/MqttPingRespEncodeDecode.java
Implementation of handling MQTT client PINGREQ
- Add pingreq handler
- Add decoder and encoder
- Add UTs
XXXX
> Implementation of handling MQTT client PINGREQ

- docs/cn/best_practice.md
> Delete blank chart line

- distribution/pom.xml
- distribution/release-client.xml
- distribution/release.xml
Change the release package style to rocketmq-{version}
Change the release package style to rocketmq-{version}
Run "mvn -Prelease-all -DskipTests clean install -U"
Check the package name in the distribution direction.
> Change the release package style to rocketmq-{version}

- client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
Simplify Producer and Consumer to avoid potential risks mentioned in this [issue](https://github.com/apache/rocketmq/issues/1138)
（1）Deprecate admin interface exposed in producer/consumer
> [ISSUE #1138]Deprecate admin interface exposed in producer/consumer

- client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
- common/src/main/java/org/apache/rocketmq/common/utils/NameServerAddressUtils.java
Add nameserver host support
XX
XXXX
> [ISSUE #1147]Add name server domain host support

- example/src/main/java/org/apache/rocketmq/example/openmessaging/SimpleProducer.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/MessagingAccessPointImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/BytesMessageImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/MessageHeader.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/NonStandardKeys.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/RocketMQConstants.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/producer/AbstractOMSProducer.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/producer/ProducerImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/promise/DefaultPromise.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/utils/OMSUtil.java
- openmessaging/src/test/java/io/openmessaging/rocketmq/producer/ProducerImplTest.java
- openmessaging/src/test/java/io/openmessaging/rocketmq/promise/DefaultPromiseTest.java
1.Implement the 1.0.0 openmessaging producer API for rocketmq oms module.
1.Implement the 1.0.0 openmessaging producer API for rocketmq oms module.
> [ISSUE#1198]Implement the 1.0.0 openmessaging producer API for rocketmq oms module

- docs/en/Feature.md
Update Feature.md
Modify some word tenses and page layouts
> [RIP-9] Update Feature.md in docs/en

- common/src/test/java/org/apache/rocketmq/common/utils/IOTinyUtilsTest.java
Add test cases for IOTinyUtilsTest
Add test case for IOTinyUtilsTest
XXXX
> [RIP-10] Add test case for IOTinyUtils

- common/src/test/java/org/apache/rocketmq/common/protocol/QueryConsumeTimeSpanBodyTest.java
add test cases for QueryConsumeTimeSpanBody.java
add test cases for QueryConsumeTimeSpanBody.java
> [RIP-10] Add test cases for QueryConsumeTimeSpanBody.java

- common/src/test/java/org/apache/rocketmq/common/ServiceThreadTest.java
[RIP-10] Add test cases for ServiceThread
[RIP-10] Add test cases for ServiceThread
XXXX
> [RIP-10] Add test cases for ServiceThread

- common/src/test/java/org/apache/rocketmq/common/protocol/heartbeat/SubscriptionDataTest.java
add test case for SubscriptionData
add test case for SubscriptionData
> [RIP-10] Add test case for SubscriptionData

- common/src/test/java/org/apache/rocketmq/common/protocol/body/ConsumeMessageDirectlyResultTest.java
add test cases for ConsumeMessageDirectlyResult
add test cases for ConsumeMessageDirectlyResult
> [RIP-10] Add test cases for ConsumeMessageDirectlyResult

- common/src/test/java/org/apache/rocketmq/common/CountDownLatch2Test.java
add test cases for  CountDownLatch2
add test cases for  CountDownLatch2
add test cases for  CountDownLatch2
> [RIP-10]  Add test cases for CountDownLatch2

- common/src/test/java/org/apache/rocketmq/common/protocol/route/TopicRouteDataTest.java
add test cases for TopicRouteData
add test cases for TopicRouteData
XXXX
> [RIP-10] Add test cases for TopicRouteData

- common/src/test/java/org/apache/rocketmq/common/protocol/topic/OffsetMovedEventTest.java
[RIP-10] Add test cases for OffsetMovedEvent
[RIP-10] Add test cases for OffsetMovedEvent
ConsistentHashRouterTest
> [RIP-10] Add test cases for OffsetMovedEvent

- common/src/test/java/org/apache/rocketmq/common/ConfigManagerTest.java
Signed-off-by: mantoudev <mantoudev@163.com>
ConfigManagerTest
ConfigManagerTest
> [RIP-10]Add test cases for ConfigManager

- common/src/test/java/org/apache/rocketmq/common/protocol/body/QueryConsumeQueueResponseBodyTest.java
Add test class for QueryConsumeQueueResponseBody
QueryConsumeQueueResponseBodyTest
XXXX
> [RIP-10] Add test class for QueryConsumeQueueResponseBody

- common/src/test/java/org/apache/rocketmq/common/protocol/body/BrokerStatsDataTest.java
Add test cases for BrokerStatsData
Add test cases for BrokerStatsData
Add test cases for BrokerStatsData
XXXX
> [RIP-10]Add test cases for BrokerStatsData

- tools/src/main/java/org/apache/rocketmq/tools/command/broker/BrokerConsumeStatsSubCommad.java
- tools/src/test/java/org/apache/rocketmq/tools/command/broker/BrokerConsumeStatsSubCommadTest.java
modify test case of BrokerConsumeStatsSubCommanTest.java
1.modify the initialization method of BrokerConsumeStatsSubCommad#execute#DefaultMQAdminExt
2.modify test case of BrokerConsumeStatsSubCommanTest.java
XXXX
> [RIP-10] modify test case of BrokerConsumeStatsSubCommand

- client/src/main/java/org/apache/rocketmq/client/AccessChannel.java
- client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
- client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageTraceHookImpl.java
- client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageTraceHookImpl.java
(1) Polish message trace target channel 
(2) Fix the issue that consumes message with namespace trace cannot be found
> [ISSUE #1214]Polish message trace topic config implementation

- .travis.yml
> repair travis.yml

- openmessaging/src/main/java/io/openmessaging/rocketmq/MessagingAccessPointImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/config/DefaultQueueMetaData.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/LocalMessageCache.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PullConsumerImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/consumer/PushConsumerImpl.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/MessageHeader.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/domain/NonStandardKeys.java
- openmessaging/src/test/java/io/openmessaging/rocketmq/consumer/PullConsumerImplTest.java
- openmessaging/src/test/java/io/openmessaging/rocketmq/consumer/PushConsumerImplTest.java
- pom.xml
https://github.com/apache/rocketmq/issues/1199 Implement the 1.0.0 openmessaging consumer API for rocketmq oms module
1、Implement push consumer
2、Implement pull consumer
> [ISSUE #1199] Implement the 1.0.0 openmessaging consumer API for rocketmq oms module

- client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java
Add transaction namespace support
XX
XXXX
> [ISSUE #1253]Add transaction namespace support

- filter/pom.xml
- srvutil/pom.xml
- srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java
Optimize the codes for issue that Suggestion about the third part dependency of the RocketMQ client.
Optimize the codes for issue that Suggestion about the third part dependency of the RocketMQ client.
The issue's link is: https://github.com/apache/rocketmq/issues/1241
I have already verified in my local enviroments.
> [ISSUE #1241]Optimize the codes for issue that suggestion about the third part dependency of the RocketMQ client.

- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyTest.java
Requirements to achieve [issue](https://github.com/apache/rocketmq/issues/1290)
see RemoteAddressStrategyFactory.getRemoteAddressStrategy
see RangeRemoteAddressStrategy
run RemoteAddressStrategyTest.netaddressStrategyFactoryTest
run RemoteAddressStrategyTest.rangeNetaddressStrategyTest
- [√] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in …
> [ISSUE #1290] Matching range enhancement

- example/src/main/java/org/apache/rocketmq/example/ordermessage/Consumer.java
Set auto commit to true.
example/src/main/java/org/apache/rocketmq/example/ordermessage/Consumer.java
XXXX
> Set auto commit in order consumer example.

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLiteMQPullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/LiteMQPullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
- example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerTest.java
polish LitePullConsumer
(1) Modify the logic of committing consume offset.
(2) Fix some bugs.
> Polish LitePullConsumer

- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
Modify the incorrect comment of maxMessageSize in MessageStoreConfig.java
Change the comment 'The maximum size of a single log file,default is 512K' to 'The maximum size of message,default is 4M'.
#XXXX
> [ISSUE #1106] Modify the incorrect comment of maxMessageSize in MessageStoreConfig.java

- distribution/benchmark/runclass.sh
- distribution/bin/runbroker.sh
- distribution/bin/runserver.sh
Fix issue #1344 
1. If the current OS is Darwin, create ```RAMDisk``` as the substitute for ```/dev/shm``` to store gc log. On other systems, check if  ```/dev/shm``` exists. If ```/dev/shm``` does not exist, store gc log in ```${BASE_DIR}```.
2. Correct and unify the gc log file name.
3. Use ```UseGCLogFileRotation``` in ```runserver.sh``` because name service is also a long-lived service process
modified:   distribution/benchmark/runclass.sh
modified:   distribution/bin/runbroker.sh
modified:   distribution/bin/runserver.sh
Start the name service and broker on the MacOS and Linux Systems
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request …
> [ISSUE #1344] Fix /dev/shm not found on some OSs

- broker/src/test/java/org/apache/rocketmq/broker/processor/MQTTProcessorTest.java
Add mqttProcessor unit test
Add mqttProcessor unit test
XXXX
> [RIP-11]  Add mqttProcessor unit test

- client/src/main/java/org/apache/rocketmq/client/Validators.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
- example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerSubscribe.java
Polish lite pull consumer and fix bug
1. Fix the problem of seek function blocking.
2. Fix shutdown function bug.
3. Make the code cleaner
4. Add unit test.
XXXX
> Polish lite pull consumer and fix bug

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
Add unit test for lite pull consumer
1. Add unit test for lite pull consumer.
2. Add synchronized to poll function.
> Add unit test for lite pull consumer

- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
1.remove end of line comment 2.add override annotation when rewrite method
XXXXX
XX
XXXX
> Fix some typo

- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
> Revert "Fix some typo"

- docs/cn/operation.md
Fix issue #1435
modify docs/cn/operation.md
check the doc https://github.com/apache/rocketmq/blob/master/docs/cn/operation.md
> [ISSUE #1435]Fix discarded mqadmin subcommand document description

- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByIdSubCommand.java
Deleted redundant print information.
Deleted redundant print information in org.apache.rocketmq.tools.command.message.QueryMsgByIdSubCommand#printMsg line 63
run ./bin/mqadmin queryMsgById command
> [ISSUE #1483] fix bug in QueryMsgByIdSubCommand print OffsetID twice

- acl/src/main/java/org/apache/rocketmq/acl/AccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/AclConfig.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/GetBrokerClusterAclConfigResponseBody.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/GetBrokerClusterAclConfigResponseHeader.java
- docs/cn/acl/user_guide.md
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/acl/GetAccessConfigSubCommand.java
- tools/src/test/java/org/apache/rocketmq/tools/command/acl/GetAccessConfigSubCommandTest.java
GetAccessConfigSubCommand for ACL configuration
GetAccessConfigSubCommand for ACL configuration
XXXX
> GetAccessConfigSubCommand for ACL configuration (#1263)

- docs/cn/design.md
fix typo in #1503
fix some typo
done
> [ISSUES #1503] fix some typo in docs/cn/design.md

- tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicPermSubCommand.java
This pr will resolve the issue that updating broker's topic reading or writing perm fails.
The resolved of codes is in this pr.
I add the correct logical codes of udpating broker reading or writing perms.
> [ISSUE #1429]Update Broker's Topic Read or Write Perm failed.

- common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Fix MessageClientIDSetterTest unit test
XX
XXXX
> Fix MessageClientIDSetterTest unit test

- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
fix HA sync transfer timeout, see [issue 1535](https://github.com/apache/rocketmq/issues/1535)
change the way waitting transfer
XXXX
> [ISSUE #1535] Fix ha sync transfer timeout

- docs/cn/RocketMQ_Example.md
修复 [ #1537 ] 。
修复 文档中异步发送消息的代码案例运行时会因为提前关闭了 producer 实例而报错。
Done.
> [ISSUES #1537] Polish docs/cn/RocketMQ_Example.md producer example

- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
work for this [issue](https://github.com/apache/rocketmq/issues/1528), make the producer execute in expected logic.
modify the way mocking send function
> [ISSUE #1528]bug fix for unit tests of DefaultMQProducer 

- docs/cn/features.md
docs-cn description error
docs/cn features.md中特性第四条消息可靠性描述异常情况第一种应改为Broken非正常关闭
XXXX
> [ISSUE #1526]modify docs-cn description error

- docs/cn/README.md
> fix cacography

- broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java
- broker/src/test/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridgeTest.java
增加非空判断，防止空指针异常,导致循环事务 check
https://github.com/apache/rocketmq/issues/1568 修复，
修复，底层commitlog异常导致，消息丢失
XXXX
> [ISSUE #1568] rocketmq need enhance stability when commitlog broken

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
- common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java
- common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Fix the [issue](https://github.com/apache/rocketmq/issues/1564) of the IP filter logic in ipv6/ipv4 coexist environment
Excluded the ipv6 link-local address
XXXX
> [ISSUE #1564]Fix the ip filter logic in ipv6/ipv4 coexist environment

- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
work for this [issue](https://github.com/apache/rocketmq/issues/1528).
modify unit test
> [ISSUE #1528]modify unit test of producer

- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
There seems to be something wrong after relavent pull request merged. This pull request revert `testSendMessageAsync_Success` back to old version. After we make this problem clearly and solve it, we'll commit a new pull request.
XXXX
> [ISSUE #1528]modify testSendMessageAsync_Success

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/LitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
Add begin/end seek support for  pull consumer for this [issue](https://github.com/apache/rocketmq/issues/1612).
XX
XXXX
> [ISSUE #1612]Add begin/end seek support for  pull consumer

- broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicValidator.java
- broker/src/test/java/org/apache/rocketmq/broker/topic/TopicValidatorTest.java
- client/src/main/java/org/apache/rocketmq/client/Validators.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
> [ISSUE #1637]Fix 1637

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImpl.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
- common/src/main/java/org/apache/rocketmq/common/sysflag/PullSysFlag.java
- common/src/test/java/org/apache/rocketmq/common/sysflag/PullSysFlagTest.java
- example/src/main/java/org/apache/rocketmq/example/simple/LitePullConsumerSubscribe.java
Fix this [issue](https://github.com/apache/rocketmq/issues/1659) 
XX
XXXX
> Add pull request sysFlag and support consume from where in first startup

- common/src/main/java/org/apache/rocketmq/common/MixAll.java
> fix typo:highter

- common/src/main/java/org/apache/rocketmq/common/MixAll.java
- tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicPermSubCommand.java
`paramter ==》 parameter`
XX
XXXX
> fix typo: paramter

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
- client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java
- client/src/main/java/org/apache/rocketmq/client/trace/TraceDispatcher.java
Fix the bug when there are more than one producer (or consumer) , the Tracer can not show all trace infomation.
ISSUE 1188
Set different ProducerGroup for different TraceProducer, the ProducerGroup will like _INNER_TRACE_PRODUCER-user-specified-producer-group
Produce and consume message for a same topic in the same process, the console show both produce and consume information.
> [ISSSUE #1188]Fix the problem when more than one producer or consumer in the same process can trace only one

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
Fixed this [issue](https://github.com/apache/rocketmq/issues/1639)
XX
XXXX
> [ISSUE #1639] use ipv4 first when choosing local IP

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Fix #1701 
Delete nextPullBatchSize method
XXXX
> [ISSUE #1701] Delete invalid method to get next pullBatchSize

- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicValidator.java
- broker/src/test/java/org/apache/rocketmq/broker/topic/TopicValidatorTest.java
Fix wrong topic max length in TopicValidator when broker check topic length
link #1699 
XX
XXXX
> [ISSUE #1699] Fix wrong topic max length in TopicValidator 

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/AssignedMessageQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Fix issue  [1706](https://github.com/apache/rocketmq/issues/1706)
XX
XXXX
> [ISSUE #1706]feat(pull_consumer) refactor the consumer offset update logic

- broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
fix(transaction) fix the send back message sent into transaction half topic referred in this [issue](https://github.com/apache/rocketmq/issues/1648).
XXXXX
XX
XXXX
> [ISSUE #1648]Fix the send back message treated as transaction message

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
> correct spelling

- broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java
java.lang.Error may cause transaction check thread crash.
Change catch(Exception) to catch(Throwable) for TransactionalMessageServiceImpl.
> Improve exception handle of transaction check service

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Closes #1787
Set the result after the query
XXXX
> [ISSUE #1787] Fix the issue that queryCq command of mqadmin returned incorrect data

- pom.xml
Upgrade fastjson version
Closes #1794
Upgrade fastjson version
XXXX
> [ISSUE #1794] Upgrade fastjson version

- client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumerScheduleService.java
Fixed [the cannot find callback issue ](https://github.com/apache/rocketmq/issues/1805)when access namespace instance.
XX
XXXX
> fix(pull_schedual) add the namespace wrapper in callback

- common/src/main/java/org/apache/rocketmq/common/message/MessageClientIDSetter.java
- common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Fix the issue that MessageClientIDSetter#getIPFromID return wrong pid
closes #1821 
link #1821
XX
XXXX
> [ISSUE #1821]Fix the issue that MessageClientIDSetter#getIPFromID return wrong pid

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
Extract the code block copied three times into a separate method
> [ISSUE #1857] Refactor the duplicated code

- docs/cn/operation.md
- docs/en/CLITools.md
fix #1883 doc error about admin tool WipeWritePermSubCommand
> [ISSUE #1883]doc error about admin tool WipeWritePermSubCommand

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ProcessQueueTest.java
What is the purpose of the change
> [ISSUE #1741]feat(client): rename takeMessags to takeMessages

- docs/cn/RocketMQ_Example.md
- docs/en/Example_Batch.md
Fix the logic of ListSplitter in [issue #1505](https://github.com/apache/rocketmq/issues/1505)
1. Fix the problem that ListSplitter will return an invalid message which over 4M. The correct logic is to abandon it.
2. Choose the valid message index at the beginning. Not only bypasses messages over 4M but also avoids subsequent checks on individual messages.
> [ISSUE #1505]Fix the ListSplitter of batch sample in docs

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
> [ISSUE #1574] change GET_ROUTEINTO_BY_TOPIC to GET_ROUTEINFO_BY_TOPIC

- client/src/main/java/org/apache/rocketmq/client/consumer/listener/MessageListenerOrderly.java
> Correct the Java doc for MessageListenerOrderly.java

- .travis.yml
- README.md
- pom.xml
close #1859 ,chros(codecov): add codecov report for tests.
1. update jacoco version to 0.8.5
2. add codecov icon in the readme
3. add codecov report in Travis
> [ISSUE #1859] add codecov report for tests.

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
> [ISSUE #1895] Expose the flush disk timeout error

- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Fix #1901 
add cluster property to msgInner in asyncSendMessage method
XXXX
> [ISSUE #1901] Fix bug in sending request/reply message using broker 4.7.0

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
> [ISSUE #1912]Polish the commited offset logic

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/main/java/org/apache/rocketmq/client/producer/RequestResponseFuture.java
- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
- client/src/test/java/org/apache/rocketmq/client/producer/RequestResponseFutureTest.java
Fixed typo in RequestResponseFuture.
rename RequestResponseFuture.setSendReqeustOk to RequestResponseFuture.setSendRequestOk.
XXXX
> Fixed typo in RequestResponseFuture.

- docs/cn/operation.md
- docs/en/CLITools.md
fix #1964 Doc error: Connection related command instructions
> [ISSUE #1964]fix Doc error: Connection related command instructions

- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
fix #1957 DefaultMQProducer didn't shutdown completely
fix #1950
> [ISSUE 1950] fix DefaultMQProducer didn't shutdown completely

- broker/src/main/java/org/apache/rocketmq/broker/client/net/Broker2Client.java
There are several problems in Broker2Client which cause field miss in logs. 
Fix logs.
> [ISSUE #1992] fix Broker2Client logs

- store/src/main/java/org/apache/rocketmq/store/ha/WaitNotifyObject.java
> [ISSUE #705]WaitNotifyObject class has a wake up bug

- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
Remove MQClientInstance#datagramSocket Field
XX
XXXX
> Remove MQClientInstance#datagramSocket Field

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
> [ISSUE #2025] Refactor  MQClientAPIImpl#processSendResponse

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
1. use  wakeup() instead of repetitive code
XX
XXXX
> [ISSUE #2020] Use wakeup() instead of writing duplicate code

- store/src/main/java/org/apache/rocketmq/store/index/IndexFile.java
#1807
1. check before update `hashSlotCount`
The build process failed, but failed at a place not related to this change. Need to further look into it
XXXX
> [ISSUE #1807] only increase hashSlotCount when using slot for the first time

- docs/cn/RocketMQ_Example.md
> Fix typo in README

- docs/en/README.md
- docs/en/RocketMQ_Example.md
- docs/en/dledger/deploy_guide.md
- docs/en/dledger/quick_start.md
- docs/en/msg_trace/user_guide.md
- docs/en/operation.md
fix #2011  , add en README.md doc and its relevant  #docs.
add README.md, RocketMQ_Example.md, dledger/quick_start.md, dledger/deploy_guide.md, msg_trace/user_guide.md, operation.md under directory docs/en.
> [ISSUE #2011] Add en README.md doc 

- test/src/main/java/org/apache/rocketmq/test/listener/rmq/order/RMQOrderListener.java
Add @Override for RMQOrderListener.java
XX
XXXX
> Add @Override for RMQOrderListener.java

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
work for issue [#2042](https://github.com/apache/rocketmq/issues/2042)
Set `namesrvAddrChoosed ` to null to let client choose a new one when the new namesrvAddrList not contains the old namesrv choosed.
XXXX
> [ISSUE #2042]select a new namesrv when the old one removed from namesrvAddrList

- distribution/bin/mqadmin
- distribution/bin/tools.sh
use "$@" instead of #@ to make mutiple value parceled by quoted
available.
fix issue 1988
https://github.com/apache/rocketmq/issues/1988
use "$@" instead of #@ to make mutiple value parceled by quoted
available.
> [ISSUE #1988] Fix the issue that can not update messageDelay correctly with mqadmin updateBrokerConfig command 

- broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
> [ISSUE #2118] Fix AdminBrokerProcessorTest can not pass when machine's hostname contains illegal characters

- acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
Fix [#2171](https://github.com/apache/rocketmq/issues/2171)
XX
XXXX
> [ISSUE #2171] fix the spell error in ACL

- tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerConfigCommand.java
> [ISSUE #2162] Fix getBrokerConfig help info wrong description

- docs/cn/RocketMQ_Example.md
Just fixed some import mistakes
> [ISSUE #2190] Fix import mistakes in RocketMQ_Example.md

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
fix typo
fix typo
fix typo in DefaultMQProducerImpl class file
‘throwed’ -> 'threw'
> [ISSUE #2192] Typo fix in DefaultMQProducerImpl.java

- distribution/bin/runserver.sh
#2180 
choose diffrent java gc options base on java version
XXXX
> [ISSUE #2180] Start namesrv failed using obsolete jvm options

- README.md
Fix the typographical error in README.md
XX
XXXX
> Doc(readme): fix the typo

- acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
#2196
code style for acl module
XXXX
> [ISSUE #2196] code style(acl): correct spell mistake, remove redundant code

- client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java
> [ISSUE #1576] delete redundant if statment

- acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
fix the issue [#2716](https://github.com/apache/rocketmq/issues/2176)
XX
XXXX
> [ISSUE#2176] Fix the issue of redundancy parameters in method

- store/pom.xml
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
- store/src/test/java/org/apache/rocketmq/store/dledger/MessageStoreTestBase.java
Upgrade dledger version and support preferred leader
Upgrade dledger version and support preferred leader / batch replication
XXXX
> [ISSUE #2217] Upgrade dledger version

- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
> [ISSUE #2170] Update BrokerOuterAPI

- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyTest.java
fix [issue#2172](https://github.com/apache/rocketmq/issues/2172)
XX
XXXX
> [ISSUE#2172] Fix the issue of ArrayIndexOutOfBoundsException

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
1. issue #2067 , need more detailed log to find why the path is invalid.
1. added 3 log statement
XXXX
> [ISSUE #2067] Add logs when collecting disk space usage

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
issue https://github.com/apache/rocketmq/issues/2245
DefaultLitePullConsumer expose  some config related to recalculatePullFromWhichNode
XXXX
> [ISSUE #2245] Expose config defaultBrokerId and connectBrokerByUser for DefaultLitePullConsumer

- .github/PULL_REQUEST_TEMPLATE.md
> doc(rocketmq) add a recommendation to PR template

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
issue #2280
Fix commit log path not exists
XXXX
> [ISSUE #2280] Disk ratio return -1.0 when cluster deployed on DLedger mode

- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
> [ISSUE#2293] Add clientId in warn logs of MQClientInstance

- client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java
- client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageTraceHookImpl.java
- client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageTraceHookImpl.java
Fixes #1473 
add clientHost to trace message
XXXX
> [ISSUE #1473] trace message`s clientHost was wrong

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/LitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
…pl class and test suit
fix about issue#2152, and add isRuning method for indacate consumer is still running
XX
XXXX
> [ISSUE #2152] Add isRunning method in DefaultLitePullConsumer

- client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java
- client/src/main/java/org/apache/rocketmq/client/trace/TraceView.java
- client/src/test/java/org/apache/rocketmq/client/trace/TraceDataEncoderTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/TraceViewTest.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommand.java
- tools/src/test/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommandTest.java
Add a query message trace command in mqadmin.
Add a query message trace command in mqadmin.
> [ISSUE #1770] Add a query message trace command in mqadmin.

- docs/en/Example_Filter.md
modify the error character of the  Example_Filter.md
XX
XXXX
> [ISSUE #2299]modify the error character of the  Example_Filter.md

- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
Use mock method instead of blocking method, for time-consuming
XX
XXXX
> [ISSUE #2152] Use mock style in unit test for time-consuming

- distribution/benchmark/runclass.sh
- example/src/main/java/org/apache/rocketmq/example/benchmark/AclClient.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
Issue #2300 
1.add support for acl
2.add msgTraceEnabled option for producer and consumer
3.fix Algorithm HmacSHA1 not available using openjdk
XXXX
> [ISSUE #2300] Enhancement: Benchmark support acl and msg trace

- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
Use `CopyOnWriteArrayList` to avoid thread safety issues.
replace `Vector` with `CopyOnWriteArrayList<>()` and remove useless imports.
> [ISSUE# 2325] Use CopyOnWriteArrayList to avoid possible thread safety issues.

- distribution/benchmark/tproducer.sh
Issue #2366
fix tproducer start failed with parameter w
XXXX
> [ISSUE #2366] Fix tproducer start faild with parameter w

- client/src/main/java/org/apache/rocketmq/client/producer/selector/SelectMessageQueueByHash.java
- client/src/test/java/org/apache/rocketmq/client/producer/selector/SelectMessageQueueByHashTest.java
fix SelectMessageQueueByHash in case hashcode is Integer.MIN
> [ISSUE #2421] Fix SelectMessageQueueByHash in case hashcode is Integer.MIN

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
Fix error in ipCheck method
Use method InetAddressValidator-isValidInet4Address()  instead of previous IP validation logic to support class D and Class E IPV4 addresses 
XXXX
> [ISSUE #2374] Fix error in ipCheck method

- logging/src/main/java/org/apache/rocketmq/logging/inner/LoggingBuilder.java
fix DefaultLayout SimpleDateFormat Pattern from 'yyyy-MM-dd HH:mm:ss,sss' to 'yyyy-MM-dd HH:mm:ss,SSS'
> [ISSUE#2468] Fix DefaultLayout SimpleDateFormat Pattern

- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
> [ISSUE #2412] Support to add TAG when producing message

- client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
- client/src/test/java/org/apache/rocketmq/client/producer/selector/SelectMessageQueueRetryTest.java
> [ISSUE #2223] Polish the selectOneMessageQueue method

- common/src/test/java/org/apache/rocketmq/common/message/MessageClientIDSetterTest.java
Temporary fix on Mac OS when pid greater than short type max value
XX
XXXX
> [ISSUE# #2491] Temporary fix on Mac OS when pid greater than short type max value

- pom.xml
fix Apache Commons Beanutils 安全漏洞 CVE-2019-10086  
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-10086
XXXXX
XX
XXXX
> Update Apache Commons Beanutils version

- remoting/pom.xml
netty-tcnative-boringssl-static really need? or upgrade it to the latest to fix CVE-2019-16869, CVE-2018-8020 ...
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty-tcnative-boringssl-static</artifactId>
<version>1.1.33.Fork26</version>
</dependency>
XXXXX
XX
XXXX
> Remove useless netty-tcnative-boringssl-static dependencies

- client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java
Ref-Issues：#2588
There is duplicate invoke of countDownLatch.countDown . L279 and L286
> [ISSUE #2588] Duplicate invoke of countdown in processReplyMessage

- LICENSE
- NOTICE
- distribution/LICENSE-BIN
- distribution/NOTICE-BIN
fix #2576 
update NOTICE and fix typo in license
1)update NOTICE  year to 2021
2)fix typo in license
> [ISSUE #2576] update NOTICE and fix typo in license

- remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstractTest.java
- remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java
remove unused imports in remoting test
remove unused imports
no need
> [ISSUE #2642] Remove unused imports

- distribution/bin/runserver.sh
fix runserver.sh error in dash env
add a condition to verify $JAVA_MAJOR_VERSION variable not null，for avoid cannt get major version
XXXX
> [ISSUE #2551] fix runserver.sh error in dash env

- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
> [ISSUE #2622] Change variable name 'lockTreeMap' to 'treeMapLock'

- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
> [ISSUE #2647] Fix classloader conflict in client-module test case.

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
issue #2663 
isSpaceFull use new storePathPhysic when enableDledgerCommitlog
XXXX
> [ISSUE #2663] [Store] Fix isSpaceFull print file path not exist log When deployed on DLedger mode

- .travis.yml
> [ISSUE #2650]  Make ulimit unlimited when execute ci

- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreShutDownTest.java
> [ISSUE #2645] Fix unit case NPE in DefaultMessageStoreShutDownTest#testDispatchBehindWhenShutdown

- broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
> [ISSUE #2677]update varible name

- client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
- client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java
- client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
- client/src/test/java/org/apache/rocketmq/client/common/ThreadLocalIndexTest.java
> [ISSUE #2652] change the method name to incrementAndGet

- client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
> [ISSUE #2730]fix Multiple instances in the same application share MQClientInstance

- broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManager.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/DeleteSubscriptionGroupRequestHeader.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/DeleteSubscriptionGroupCommand.java
> [ISSUE #2748]fix deleteSubscriptionGroup not remove consumer offset

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/GetMessageResult.java
- store/src/main/java/org/apache/rocketmq/store/MessageStore.java
- store/src/main/java/org/apache/rocketmq/store/pop/AckMsg.java
- store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java
- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
This is "store" submodule of contribution for RIP-19
Provides some fundamental changes for other submodule.
> [RIP-19] Pop Consuming (submodule "store")

- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
polish
replace with Math.min method call
XXXX
> [ISSUE #2729] Replace with Math.min method call

- example/src/main/java/org/apache/rocketmq/example/ordermessage/Producer.java
> [ISSUE #2801]Fix NamesrvAddr connot set in Producer

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
fix messageArrivingListener NPE
for issue #2816
> [ISSUE #2816] fix messageArrivingListener NPE

- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
> [ISSUE #2538]Optimize log output when message trace saving fails

- common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
remove redundant package imports.
for issue-#2805
> [ISSUE #2805] remove redundant package imports

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImplTest.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/SetConsumeModeSubCommand.java
> [RIP-19] Pop Consuming (tools)

- test/src/test/java/org/apache/rocketmq/test/base/IntegrationTestBase.java
- test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopSubCheckIT.java
- test/src/test/java/org/apache/rocketmq/test/smoke/NormalMessageSendAndRecvIT.java
> [RIP-19] Pop Consuming (integration test)

- distribution/bin/runserver.sh
> [ISSUE #2846]fix -E might not port to other systems

- broker/src/test/java/org/apache/rocketmq/broker/processor/PopBufferMergeServiceTest.java
- docs/en/Feature.md
- example/pom.xml
- example/src/main/java/org/apache/rocketmq/example/simple/PopPushConsumer.java
> [RIP-19]Pop consumer docs

- test/pom.xml
Fix #2872
Add maven plugin for test sub module to delete unnecessary files.
XXXX
> [ISSUE #2872] remove log files created by integration test when mvn clean

- test/pom.xml
- test/src/test/resources/log4j.xml
> [ISSUE #2872] move log files created by integration test to target dir

- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
Fix the problem of failing to build consumption index when sending batch messages, resulting in inability to consume.
1. Asynchronous batch write: add queueOffset in the inner layer of lock.
2. Synchronous writing: serialize the message in the outer layer of the lock, and supplement the queueOffset in the inner layer of the lock.
修复前 Batch message benchmark 测试:
修复后 Batch message benchmark 校验:
> [ISSUE #2865] Batch message send bug fix

- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
issue #2868 
refresh properties string  before write message into store.
XXXX
> [ISSUE #2868]Fix ORIGIN_MESSAGE_ID field not write into commitlog

- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
> fix pop consumer ci error

- example/src/main/java/org/apache/rocketmq/example/simple/PopPushConsumer.java
> Polish pop consume comment

- common/src/test/java/org/apache/rocketmq/common/UtilAllTests.java
- pom.xml
I've analysed your codebase and noticed that `org.apache.rocketmq.common.UtilAll` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
> Add unit tests for org.apache.rocketmq.common.UtilAll

- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- broker/src/main/java/org/apache/rocketmq/broker/mqtrace/SendMessageHook.java
- broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
- common/src/main/java/org/apache/rocketmq/common/hook/FilterCheckHook.java
- filter/src/main/java/org/apache/rocketmq/filter/parser/SimpleCharStream.java
- logging/src/main/java/org/apache/rocketmq/logging/inner/Level.java
- test/src/main/java/org/apache/rocketmq/test/util/FileUtil.java
- test/src/main/java/org/apache/rocketmq/test/util/MQWait.java
- test/src/main/java/org/apache/rocketmq/test/util/RandomUtil.java
- test/src/main/java/org/apache/rocketmq/test/util/RandomUtils.java
- test/src/main/java/org/apache/rocketmq/test/util/VerifyUtils.java
- test/src/test/java/org/apache/rocketmq/test/client/consumer/tag/MulTagSubIT.java
- test/src/test/java/org/apache/rocketmq/test/client/consumer/tag/TagMessageWithMulConsumerIT.java
- tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java
Find some code style issue,
Remove duplicated and redundant code.
Change several c style code declaration to java style.
Remove some modifer for interface
And some code can be simplified, just return the boolean variable not need to use tertiary operator.
XXXX
> Fix some code style issue and remove redundant code

- distribution/bin/runbroker.cmd
- distribution/bin/runserver.cmd
fixed "error=Algorithm HmacSHA1 not available" when use ACL on windows.
> fixed startup script on windows

- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
> Revert "[ISSUE #2865] Batch message send bug fix"

- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java
- pom.xml
- test/src/main/java/org/apache/rocketmq/test/util/data/collect/impl/ListDataCollectorImpl.java
Improve unit test stability
1. `org.apache.rocketmq.client.trace.DefaultMQConsumerWithOpenTracingTest#testPullMessage_WithTrace_Success` has a race condition that when countDownLatch in callback executed, `countDownLatch.await` will pass, but `finishSpan` is not surely executed because it executed after callback, so `tracer.finishedSpans` will not have data if `finishSpan` is executed a little late after `countDownLatch.await`, and test will fail. Since there is no sutable assert point to make sure that `finishSpan` is executed, i add a `waitAtMost` to retry this assert for one second.
2. The init methods of `DefaultMQPushConsumerTest` & `DefaultMQConsumerWithOpenTracingTest` mock something after `consumer.start`, but `consumer.start` …
> Fix test stability

- pom.xml
fastjson version is too old.
https://github.com/apache/rocketmq/issues/2911
XX
XXXX
> [ISSUE #2911]update fastjson version from 1.2.69 to 1.2.76

- tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicRouteSubCommand.java
For-[#2698](https://github.com/apache/rocketmq/issues/2698)
> [ISSUE #2698] TopicRouteSubCommand enhancement

- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
…es to send
Add property of benchmark`s producer that specifies how many messages to send, when sending a specified number of message, send over.
XX
XXXX
> [ISSUE #2615]Add property of benchmark`s producer that specifies how many messages to send

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
- store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
issue #2683 
Add delay message stats to brokerStatsManager
XXXX
> [ISSUE #2683] Add delay message stats to brokerStatsManager

- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
check kv config should not be null.  otherwise broker may fail to start.  see https://github.com/apache/rocketmq/issues/2935
XX
XXXX
> [ISSUE #2935] check kv config should not be null. otherwise broker may fail to start

- client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java
Fix bug in ThreadLocalIndex#getAndIncrement
> [ISSUE #2783]Fix bug in ThreadLocalIndex

- distribution/bin/dledger/fast-try.sh
fix fast-try.sh fail to run in ubuntu
XX
XXXX
> [ISSUE #2926] fix fast-try.sh fail to run in ubuntu

- client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByUniqueKeySubCommand.java
> [ISSUE #2735] QueryMsgByUniqueKey tool should return all messages with same unique key

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullRequest.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePullImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
- client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
> [ISSUE #2708] Client may submit wrong offset when network instability

- docs/cn/operation.md
fix a mistake on operation doc
XXXXX
XX
XXXX
> [#2947] Fix a mistake on operation doc

- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommand.java
The client switch the enableMsgTrace and specifies traceTopic. QueryMsgTraceById can be queried by specifying customerTraceTopic with the -t parameter
XX
XXXX
> [ISSUE #2556] The queryMsgTraceById command supports specifying the customerTraceTopic

- tools/src/main/java/org/apache/rocketmq/tools/command/message/SendMessageCommand.java
Add message tracing switch in sendMessage command of mqadmin
> [ISSUE #2990] Add message tracing switch in sendMessage command of mqadmin

- docs/cn/Configuration_System.md
Add a Chinese version of Configuration_System.md
XX
XXXX
> [ISSUE #2997] Add a Chinese version of Configuration_System.md

- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
#3019 
Fix the issue of sending statistics in batch messages.
- Change the type of the batch message sending parameter msgNum from long to int.
- Set msgNum in appendResult to the actual number of messages.
Before fixing:
After modification:
> [ISSUE 3019] Fixed bug with batch-sent message statistics

- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
issue #3009 
add delay message option
XXXX
> [ISSUE #3009]test(benchmark): support delay message test

- distribution/benchmark/batchproducer.sh
- example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java
- Add benchmark test for batch message sending.
- Add BetchProducer.
> [ISSUE #2873] add benchmark for batch message

- distribution/release.xml
#3068 remove jaeger tracing dependency in release package
XX
XXXX
> [ISSUE #3068] remove jaeger tracing dependency in release

- docs/cn/design.md
> [Doc] wrong word in design.md

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
fix Print log format is incorrect in NettyRemotingAbstract class
> [ISSUE #3089] fix Print log format is incorrect in NettyRemotingAbstract class

- store/src/main/java/org/apache/rocketmq/store/SelectMappedBufferResult.java
> [ISSUE #3110]Fix: remove useless code 

- store/src/main/java/org/apache/rocketmq/store/MappedFile.java
Fix the incorrect judegment  'writePos - lastCommittedPosition > commitLeastPages' in the method 'commit0' of class 'MappedFile'
> [ISSUE #3099] Fix the incorrect judegment  'writePos - lastCommittedPosition > commitLeastPages' in the method 'commit0' of class 'MappedFile'

- docs/cn/Example_Batch.md
- docs/cn/Example_Delay.md
> [ISSUE #3063] add Chinese version of Example_Delay.md

- docs/en/client/java/API_Reference_DefaultMQProducer.md
> [ISSUES #3055]add some doc of the API_Reference_DefaultMQProducer of English.

- docs/cn/Deployment.md
> [ISSUE #3037]Add a Chinese version of Deployment.md

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
#603
log exception stack in ConsumeMessageConcurrentlyService.run() and ConsumeMessageOrderlyService.run().
XXXX
> [ISSUE #603] Log exception stack

- docs/cn/Example_Simple_cn.md
> Add SyncProducer Example

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
> [ISSUE #3128] fix the delete global white addresses

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
> [ISSUE #3154 ]delete the unuse code

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Polish lite pull consumer code style
Modify DefaultLitePullConsumerImpl class
XXXX
> [ISSUE #3046]:Polish lite pull consumer code style

- example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
> [ISSUE #3164]Fix the checkstyle error

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImpl.java
This PR is to fix possible offset rollback problem mentioned in ISSUE #2708 and are not perfectly solved by https://github.com/apache/rocketmq/pull/2948 
XX
XXXX
> [ISSUE #2708] fix offset rollback when fetch offset from broker exception

- example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
#3162 add msgTraceEnable config in transaction producer benchmark
XX
XXXX
> [ISSUE #3162 ]add msgTraceEnable config in transaction producer benchmark

- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
#3023 
The statistical data obtained through mqadmin is inconsistent with the results printed in store.log. Through source code analysis, it is determined that the statistical results obtained through mqadmin are smaller than the actual data, and the statistical results are between 0-60s.
- When initializing putMessageDistributeTime every 1s, record the current statistical result lastPutMessageDistributeTime.
- When the statistical result is obtained through mqadmin, the lastPutMessageDistributeTime is returned.
After repair：
> [ISSUE #3023] Fix the inconsistency of putMessageDistributeTime statistics

- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
fix issue 2055
https://github.com/apache/rocketmq/issues/2055#issue-627309782
add null pointer check before implicit conversion
> [ISSUE #2055] Fix NPE in SendMessageProcessor.handleRetryAndDLQ

- docs/cn/msg_trace/user_guide.md
- docs/en/msg_trace/user_guide.md
Add message tracing switch in sendMessage command of mqadmin 
XX
XXXX
> [ISSUE #2990] Add message tracing switch in sendMessage command of mqadmin, and add document

- broker/src/main/java/org/apache/rocketmq/broker/pagecache/ManyMessageTransfer.java
- broker/src/main/java/org/apache/rocketmq/broker/pagecache/OneMessageTransfer.java
- broker/src/main/java/org/apache/rocketmq/broker/pagecache/QueryMessageTransfer.java
- pom.xml
- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyLogger.java
Fix https://github.com/apache/rocketmq/issues/3031
Upgrade netty-all dependency version to 4.1.65.Final
> [ISSUE #3031] Upgrade netty-all dependency version to 4.1.65.Final

- .travis.yml
> [ISSUE #3185]remove the arm machine test in travis ci

- distribution/bin/runbroker.cmd
- distribution/bin/runbroker.sh
- distribution/bin/runserver.cmd
- distribution/bin/runserver.sh
> [ISSUE #3030]Remove the -Xmn JVM parameter when using G1.

- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
在pr[#3120](https://github.com/apache/rocketmq/pull/3120)中，修复了consumer并发启动、停止过程中产生幽灵consumer的造成消费进度错误的问题。
其中同学Zanglei06建议我把producer注册和摘除方法也加上同步，虽然产生幽灵producer对业务影响不大但是考虑到程序的严谨性提交了此pr.
> [ISSUE #3183]add synchronization for producer on method registerProducer & unregisterProducer 

- tools/src/main/java/org/apache/rocketmq/tools/command/acl/UpdateAccessConfigSubCommand.java
> [ISSUE #3177]updateAclConfig in all brokers.

- broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
1. Since "requestHeader" is nullable, we should check if it is null before deference
2. Add missed '@Override' annotation on 'getStoreHost'
#3196 
XX
XXXX
> [ISSUE #3196] Check if "requestHeader" is null before "requestHeader.getTopic()"

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettySystemConfig.java
> [ISSUE #3200] Fix code style in 'NettySystemConfig.java'

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
make free disk value more accurate
#3192
#3192
#3192
> [ISSUE #3192] make free disk value more accurate

- broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
- broker/src/test/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessorTest.java
Optimise parse performance for SendMessageRequestHeaderV2
> [ISSUE 2883] [Part G] Optimise parse performance for SendMessageRequestHeaderV2

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/main/java/org/apache/rocketmq/client/producer/RequestFutureTable.java
> [ISSUE #3199]two timed task for RequestFutureTable

- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
- common/src/main/java/org/apache/rocketmq/common/message/Message.java
- common/src/main/java/org/apache/rocketmq/common/protocol/NamespaceUtil.java
- common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java
- common/src/test/java/org/apache/rocketmq/common/utils/IOTinyUtilsTest.java
- filter/src/main/java/org/apache/rocketmq/filter/expression/UnaryExpression.java
- filter/src/main/java/org/apache/rocketmq/filter/parser/ParseException.java
- filter/src/main/java/org/apache/rocketmq/filter/parser/TokenMgrError.java
- filter/src/test/java/org/apache/rocketmq/filter/ParserTest.java
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
- store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByUniqueKeySubCommand.java
1. Replace the class 'StringBuffer' by 'StringBuilder' 
2. Add missed '@override' annotation
3. Add braces to 'if' statement
4. Add test for `UtilAll#list2String`
#3203 
XX
XXXX
> [ISSUE 3203] Replace the class 'StringBuffer' by 'StringBuilder'

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
> [ISSUE #3215] polish litePullConsumer seek logic #3216

- example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
> [ISSUE #3284]Optimizing benchmark code

- README.md
close #3340 
Increase multilingual client repository link
Improve documentation
Make it easier for users to find relevant documents
XXXX
> [ISSUS #3340] (doc)add hyperlink for client repos in the introduction.

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQLitePullConsumerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
> [ISSUE #3326] fix send trace fail if broker set tls.server.mode=enforcing

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
related issue #3245 **Make sure set the target branch to `develop`**
#3245 
Use df's algorithm to calculate the disk used ratio
#3245 
> [ISSUE #3245] Use df algorithm to calculate the disk used ratio

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/AddWritePermOfBrokerRequestHeader.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/AddWritePermOfBrokerResponseHeader.java
- docs/cn/operation.md
- docs/en/CLITools.md
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
- namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerTest.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/AddWritePermSubCommand.java
- tools/src/test/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtTest.java
- tools/src/test/java/org/apache/rocketmq/tools/command/namesrv/AddWritePermSubCommandTest.java
> [ISSUE #1848] Add write perm admin command 

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
- common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
- common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java
- common/src/test/java/org/apache/rocketmq/common/stats/StatsItemSetTest.java
- store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
- store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
improve performance
[ISSUE 3194] [PART C] Replace AtomicLong with LongAdder in StatsItem.java to improve performance
> [ISSUE 3194] [PART C] Replace AtomicLong with LongAdder in StatsItem.java to improve performance

- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
issue #2436 
create DLQ topic with default perm read & write
> [ISSUE #2436] DLQ topic default perm change

- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
> [ISSUE #3361]DefaultMQProducer's constructor can call the overloaded constructor.

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
retrying by customizing response code #2726, users can control retrying by themselves
> [ISSUE #2726] retrying by customizing response code

- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/GetConsumerConfigSubCommand.java
- tools/src/test/java/org/apache/rocketmq/tools/command/consumer/GetConsumerConfigSubCommandTest.java
> [ISSUE #2964] Add a query consumer config command in mqadmin.

- common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
- store/src/test/java/org/apache/rocketmq/store/ScheduleMessageServiceTest.java
Fix #1869
Delay message can't be consumed when delay offset in delayOffset.json is wrong
Correct delay offset when ScheduleMessageService init and timer task running.
XXXX
> [ISSUE #1869] Delay message can't be consumed when delay offset in delayOffset.json is wrong

- acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
- example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
- Format the two classes AclUtils and PullConsumer
#3379
XXXX
> [ISSUE #3379] Fix formatting errors

- common/src/test/java/org/apache/rocketmq/common/RemotingUtilTest.java
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
For #503 
Add a convert2IPString for convert host to ip.
XXXX
> [ISSUE #503] NOT_CONSUME_YET not righht in RocketMQ Console

- broker/src/main/java/org/apache/rocketmq/broker/loadbalance/MessageRequestModeManager.java
> [ISSUE #3371]Part A: Fix stack overflow exception when set message mode

- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
Fix issue #3288
cache **UtilAll#getPid** result to avoid duplicate calls. 
XXXX
> [ISSUE #3288] Fix producer always timeouts while sending first message

- store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java
Just revert the merge error with previous commits in #3357 
Revert 2 lines in org.apache.rocketmq.store.MappedFileQueue#doLoad
> [ISSUE #3467] Fail fast on loading files with error mappedFileSize

- example/src/main/java/org/apache/rocketmq/example/benchmark/AclClient.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
> [ISSUE #3487] Benchmark supports custom AK/SK

- example/src/main/java/org/apache/rocketmq/example/simple/PullConsumer.java
it is a minor question,I advise fix it.
executors.execute(new Runnable() {
public void doSomething(List<MessageExt> msgs) {
//do you business
}
> fix notes wrong (#3543)

- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
to solve the issue #3562 
Changed "Print all config item" to "Print all config items"
> ISSUE #3562

- README.md
close #3550 , fix typo in readme.file.
> [ISSUE #3550] doc:fix typo in readme

- example/src/main/java/org/apache/rocketmq/example/quickstart/Consumer.java
to solve issue #3558 
removed typos and spelling errors from comments in quickstart.
> [ISSUE #3558]

- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
For issue #3571 
1. Use `parallelStream` to compute cumulative values in a large set(`StoreStatsService#putMessageTopicTimesTotal`, `StoreStatsService#putMessageTopicSizeTotal`).
2. Renaming variables `lockXXX` to `xxxLock` in class `StoreStatsService`.
> [ISSUE #3571] optimizing: For a big set, replace sequential iteration addition with a parallel stream when calculating cumulative result.

- example/src/main/java/org/apache/rocketmq/example/ordermessage/Consumer.java
to solve issue #3560 
Removed if-else statements of `ROLLBACK` and `COMMIT`
> [ISSUE #3560] remove deprecated status in the orderly consumer examples.

- tools/src/main/java/org/apache/rocketmq/tools/command/offset/CloneGroupOffsetCommand.java
Fix CloneGroupOffsetCommand, can clone consumerOffset to target group
use consumerOffset instead of brokerOffset
> [ISSUE #3551] Fix admin cloneoffset

- client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java
- client/src/test/java/org/apache/rocketmq/client/trace/TraceDataEncoderTest.java
> [ISSUE #3394] fix duplicate keys in trace message

- store/src/main/java/org/apache/rocketmq/store/CommitLogDispatcher.java
- store/src/main/java/org/apache/rocketmq/store/MessageArrivingListener.java
Fix #3604 
Some important interface methods add comment
> [ISSUE #3604] Some important interface methods add comment

- client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/test/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStoreTest.java
issue: https://github.com/apache/rocketmq/issues/3603
fetch and commit offset need to  use master broker firstly 
> [ISSUE #3603] Fix(client): fetch and commit offset need to use master broker firstly

- client/src/main/java/org/apache/rocketmq/client/Validators.java
- client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java
- common/src/main/java/org/apache/rocketmq/common/topic/TopicValidator.java
> [ISSUE 3585] [Part F] eliminate regex match in topic/group name check

- broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
close #3602 
add AdminBrokerProcessor Test
> [ISSUE #3602] add AdminBrokerProcessor Test

- broker/src/test/java/org/apache/rocketmq/broker/processor/SendMessageProcessorTest.java
…rTest#testProcessRequest_WithMsgBack failed
XXXXX
XX
XXXX
> [ISSUE #3627]org.apache.rocketmq.broker.processor.SendMessageProcessorTest#testProcessRequest_WithMsgBack failed

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializable.java
- remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RemotingCommandTest.java
- remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializableTest.java
fix illegal message attack
Check when decoding the protocol 
Yes
> [Issue #3474] Fix illegal message attack

- store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
org apache. rocketmq. broker. processor. SendMessageProcessorTest#testProcessRequest_ Withmsgback will report NPE when topic or group is empty. This PR is used to fix this.
This problem introduced in https://github.com/apache/rocketmq/pull/3619
> fix npe of SendMessageProcessorTest

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
- broker/src/test/java/org/apache/rocketmq/broker/filter/MessageStoreWithFilterTest.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
- store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java
- store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreShutDownTest.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
- store/src/test/java/org/apache/rocketmq/store/HATest.java
- store/src/test/java/org/apache/rocketmq/store/ScheduleMessageServiceTest.java
- store/src/test/java/org/apache/rocketmq/store/dledger/MessageStoreTestBase.java
- store/src/test/java/org/apache/rocketmq/store/schedule/ScheduleMessageServiceTest.java
- store/src/test/java/stats/BrokerStatsManagerTest.java
see #3637 
Add enableQueueStat in BrokerConfig
> [ISSUE #3637] Add enableQueueStat in BrokerConfig so we can disable stat of queue level.

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializable.java
- remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RemotingCommandTest.java
- remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializableTest.java
fix code style of PR #3475 
import rmq_codeStyle.xml, format related code
Yes
> [Issue #3649] fix code style of PR #3475

- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
issue #2383 
export putMessageFailedTimes metric through broker status.
XXXX
> [ISSUE #2383] [Enhancement]Export putMessageFailedTimes with broker status

- client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
- test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
- test/src/test/java/org/apache/rocketmq/test/client/producer/querymsg/QueryMsgByKeyIT.java
bug fix, solve message hash conflict in index file
[Github issue](https://github.com/apache/rocketmq/issues/3613)
fix org.apache.rocketmq.store.DefaultMessageStore
> [ISSUE 3613] bug fix, solve message hash conflict in index file

- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByMachineRoom.java
> [ISSUE #3539] Add parameter verification

- acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
- acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/SetConsumeModeSubCommand.java
https://github.com/apache/rocketmq/issues/3505
- Merged the command code in the pop_consumer branch.
- Fix parameter conflict
- Add clientRebalanceEnable in benchmark
- Modify acl unit test to solve the problem of lack of license
XXXX
> [ISSUE #3505] Fix parameter conflict

- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
to fix the problem in [ISSUE #3673](https://github.com/apache/rocketmq/issues/3673)
> [ISSUE #3673] fix resetOffsetByTimestampOld() topicRouteMap maintain broker-queueNums relationship

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
- broker/src/test/java/org/apache/rocketmq/broker/topic/TopicConfigManagerTest.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/pom.xml
- common/src/main/java/org/apache/rocketmq/common/TopicAttributes.java
- common/src/main/java/org/apache/rocketmq/common/TopicConfig.java
- common/src/main/java/org/apache/rocketmq/common/attribute/Attribute.java
- common/src/main/java/org/apache/rocketmq/common/attribute/AttributeParser.java
- common/src/main/java/org/apache/rocketmq/common/attribute/BooleanAttribute.java
- common/src/main/java/org/apache/rocketmq/common/attribute/EnumAttribute.java
- common/src/main/java/org/apache/rocketmq/common/attribute/LongRangeAttribute.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/CreateTopicRequestHeader.java
- common/src/test/java/org/apache/rocketmq/common/attribute/AttributeParserTest.java
- common/src/test/java/org/apache/rocketmq/common/attribute/AttributeTest.java
- store/src/main/java/org/apache/rocketmq/store/util/QueueTypeUtils.java
- tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java
Link #3679 
En: As RocketMQ grows, topics will have more traits. Adding a well-designed Attributes sheet can greatly improve TopicConfig's description capabilities.
For example, whether the ConsumeQueue type of a Topic is BatchCQ or SimpleCQ, whether the Deletion strategy of a Topic is Delete or Compact, and even the topi-level preservation time are all attributes of a Topic. Adding TopicConfig variables endlessly is obviously not an elegant approach.
Ch: 随着RocketMQ的发展，现有的TopicConfig在一定程度上已经没有办法表达清楚一个Topic真实的特质。增加一个设计精良的Attributes属性表可以极大程度提高TopicConfig的描述能力。
比如，一个Topic的ConsumeQueue类型是BatchCQ还是SimpleCQ，一个Topic的Deletion策略是Delete还是Compact，甚至Topic级别的保存时间等，都是属于Topic的一个Attribute，无休止得增加TopicConfig变量显然不是一个优雅的做法。
Follow this checklist to help us …
> [ISSUE #3679] Support topic attributes

- docs/cn/best_practice.md
- docs/en/Configuration_Client.md
optimize namesrv default address docs
optimize namesrv default address docs
XXXX
> optimize namesrv default address docs

- broker/src/test/java/org/apache/rocketmq/broker/topic/TopicConfigManagerTest.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/TopicAttributes.java
- common/src/test/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingTest.java
- common/src/test/java/org/apache/rocketmq/common/statictopic/TopicQueueMappingUtilsTest.java
- store/src/main/java/org/apache/rocketmq/store/PutMessageContext.java
- store/src/main/java/org/apache/rocketmq/store/TopicQueueLock.java
- store/src/main/java/org/apache/rocketmq/store/util/QueueTypeUtils.java
- store/src/test/java/org/apache/rocketmq/store/queue/ConsumeQueueTest.java
- store/src/test/java/org/apache/rocketmq/store/queue/QueueTestBase.java
- test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
> [ISSUE #3702] fix check style

- docs/en/Design_Query.md
For issue #3692 
Modify the title content about the message query documentation.
> [ISSUE #3692] docs: Modify the title content about the message query documentation.

- tools/src/main/java/org/apache/rocketmq/tools/command/connection/ConsumerConnectionSubCommand.java
#3696 
The optimized display:
XX
XXXX
> [ISSUE #3696]Optimize the query consumer connection display

- .travis.yml
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
spelling error
fix class[RemotingHelper]  method[exceptionSimpleDesc] var[element] spelling error
fix class[RemotingHelper]  method[exceptionSimpleDesc] var[element] spelling error
fix class[RemotingHelper]  method[exceptionSimpleDesc] var[element] spelling error
> [ISSUE #3685] Fix param spelling error

- tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetadataCommand.java
> [ISSUE #3709] Fix the problem that the result of requesting information from multiple addresses does not overlap when exporting Metadate.

- common/src/main/java/org/apache/rocketmq/common/attribute/CQType.java
- store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java
- store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java
- store/src/main/java/org/apache/rocketmq/store/queue/QueueOffsetAssigner.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
Correct min logic offset for BCQ.
1. add CorrectLogicOffsetService to periodically correct min logic offset; refactor QueueOffsetAssigner.
2. Refactor QueueOffsetAssigner.
> [ISSUE #3708] add CorrectLogicOffsetService to periodically correct min logic offset

- NOTICE
> Updated Notice file to 2022

- broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
#3498 
Use polling to calculate queueId
XXXX
> [ISSUE #3498] Make messages in reviveTopic more evenly written to different queues

- test/src/main/java/org/apache/rocketmq/test/lmq/benchmark/BenchLmqStore.java
fix build error in RIP-28 at getmQclientFactory
change to getmQclientFactory
mvn compile -DskipTests
> fix build error in RIP-28 at getmQclientFactory

- common/src/main/java/org/apache/rocketmq/common/protocol/body/ConsumerRunningInfo.java
- tools/src/main/java/org/apache/rocketmq/tools/command/broker/BrokerConsumeStatsSubCommad.java
- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/stats/StatsAllSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicListSubCommand.java
Specific GID and TID cannot be displayed for MQ instance with namespace
> [ISSUE #3642] Display GID and Topic with namespace

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
> [ISSUE #3755] change the level to warn when ack failed

- logging/src/main/java/org/apache/rocketmq/logging/inner/LoggingBuilder.java
- logging/src/main/java/org/apache/rocketmq/logging/inner/LoggingEvent.java
- pom.xml
Some info in log may contain new lines, can be constructed by user, which may cause confusion.
XX
XXXX
> Avoid new lines in log

- docs/en/Example_Transaction.md
> [ISSUE #3774] docs: Polish the document 'Example_Transaction.md'.

- broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java
- broker/src/test/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessorTest.java
#3521 
- When popShareQueueNum exceeds the number of clients, each client can POP consume all the queues.
- Add unit test.
XXXX
> [ISSUE #3521] Fix the risk of memory overflow caused by excessive popShareQueueNum

- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAConnection.java
- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
- store/src/test/java/org/apache/rocketmq/store/ScheduleMessageServiceTest.java
#3449 
- Configure whether to enable asynchronous delivery
- Configure the maximum number of pending requests for message delivery
- Construct the PutResultProcess class to manage each asynchronous delivery request.
- Construct HandlePutResultTask to process the result of a single level delivery request.
> [ISSUE #3449] Delayed message supports asynchronous delivery

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
For #3724 
Polish the unit test of class ConsumeMessageConcurrentlyService
> [ISSUE #3724]: Polish the unit test of class ConsumeMessageConcurrentlyService

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java
- client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyServiceTest.java
For issue #3789
- **Unit tests**
- **Pictures below.**
> [ISSUE #3789] optimize: Tag the name of  consuming thread whith consumeGroup.

- common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
> [ISSUE #3786] fix: The length of properties value should be checked before converting them to short.

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
> fix ISSUE 2812

- pom.xml
https://github.com/apache/rocketmq/issues/3816
upgrade log4jv2 to v2.17.1
pom change
CI build
> [Issue-3816] upgrade log4jv2 to 2.17.1

- client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragelyTest.java
> [ISSUE #3674] add tests for AllocateMessageQueueAveragely

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
[#3832](https://github.com/apache/rocketmq/issues/3832)
XXXX
> [ISSUE ##3832] in order to improve the performance by change the variable location of queueId

- client/src/test/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImplTest.java
- client/src/test/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImplTest.java
> [Issue 3674] add tests for computePullFromWhereWithException

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/FlushDiskWatcher.java
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
- store/src/test/java/org/apache/rocketmq/store/FlushDiskWatcherTest.java
#3827 Improve Performance of Transactional Message
> [ISSUE #3827]Improve Performance of transactional message and schedule message

- client/src/main/java/org/apache/rocketmq/client/MQHelper.java
> depreciated unused class

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
> [ISSUE #3887 ] fix validate fail after update acl

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
> [ISSUE #3898]fix the spell in MQClientAPIImpl

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
Fix #3877 
Remove unnecessary Exception thrown by MQClientAPIImpl#createSubscriptionGroup
XXXX
> [ISSUE #3877] Remove unnecessary Exception thrown by MQClientAPIImpl#createSubscriptionGroup

- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
- store/src/test/java/org/apache/rocketmq/store/StoreStatsServiceTest.java
> [ISSUE #3859] enhance the cal of latency for putting message

- README.md
> [ISSUE #3915] readme add rocketmq connect link

- store/src/main/java/org/apache/rocketmq/store/MappedFile.java
> [ISSUE #3900] Fix that wrong dir is created when using mult-dirs storage

- .github/ISSUE_TEMPLATE/issue_template.md
Make the issue template more friendly and correct grammar issues identified.
NA
NA
> Improve Issue Template

- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/LanguageCode.java
- remoting/src/test/java/org/apache/rocketmq/remoting/protocol/LanguageCodeTest.java
Add language support for Rust
Add language code 12
N/A
> Add language code for Rust

- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
- namesrv/src/test/java/org/apache/rocketmq/namesrv/NamesrvStartupTest.java
> [ISSUE #3950] Anonymous new Callable()  replaced with lambda

- broker/src/main/java/org/apache/rocketmq/broker/offset/LmqConsumerOffsetManager.java
- broker/src/test/java/org/apache/rocketmq/broker/offset/LmqConsumerOffsetManagerTest.java
fix #3957 LmqConsumerOffsetManager deserialize error
unit test
> [ISSUE #3957] fix #3957 LmqConsumerOffsetManager deserialize error

- README.md
For #3970 
Add the link to Apache RocketMQ MQTT in the readme.md
XXXX
> docs: Add the link to Apache RocketMQ MQTT in the readme.md

- test/pom.xml
- test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java
- test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
- test/src/test/java/org/apache/rocketmq/test/client/producer/batch/BatchSendIT.java
- test/src/test/java/org/apache/rocketmq/test/client/producer/order/OrderMsgRebalanceIT.java
- test/src/test/java/org/apache/rocketmq/test/container/AddAndRemoveBrokerIT.java
- test/src/test/java/org/apache/rocketmq/test/container/BrokerFailoverIT.java
- test/src/test/java/org/apache/rocketmq/test/container/BrokerMemberGroupIT.java
- test/src/test/java/org/apache/rocketmq/test/container/ContainerIntegrationTestBase.java
- test/src/test/java/org/apache/rocketmq/test/container/GetMaxOffsetFromSlaveIT.java
- test/src/test/java/org/apache/rocketmq/test/container/GetMetadataReverseIT.java
- test/src/test/java/org/apache/rocketmq/test/container/PullMultipleReplicasIT.java
- test/src/test/java/org/apache/rocketmq/test/container/PushMultipleReplicasIT.java
- test/src/test/java/org/apache/rocketmq/test/container/RebalanceLockOnSlaveIT.java
- test/src/test/java/org/apache/rocketmq/test/container/ScheduleSlaveActingMasterIT.java
- test/src/test/java/org/apache/rocketmq/test/container/ScheduledMessageIT.java
- test/src/test/java/org/apache/rocketmq/test/container/SendMultipleReplicasIT.java
- test/src/test/java/org/apache/rocketmq/test/container/SlaveBrokerIT.java
- test/src/test/java/org/apache/rocketmq/test/container/SyncConsumerOffsetIT.java
- test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
Add ITs for BrokerContainer
Modify test module
XXXX
> [RIP-31] Add ITs for BrokerContainer

- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
Fix using wrong offset when deliver in ScheduleService
XX
XXXX
> [ISSUE# 3966] Fix using wrong offset when deliver in ScheduleService

- container/src/main/java/org/apache/rocketmq/container/BrokerContainerStartup.java
- remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingUtil.java
> [ISSUE #3992] code optimizations about BrokerContainerStartup.class

- broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
> [ISSUE #3503] fix the consumeOffset will be set as 0 when getMessage returns null

- client/src/main/java/org/apache/rocketmq/client/log/ClientLogger.java
> [ISSUE #4000]Fix the warn log input in command tools

- tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerStatusSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/PrintMessageSubCommand.java
#4002
The optimized display:
XX
XXXX
> [ISSUE #4002]Optimize some mqadmin command execution results output

- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
- store/src/test/java/org/apache/rocketmq/store/StoreStatsServiceTest.java
For #3924 
- Change the method `StoreStatsService#initPutMessageDistributeTime()` to **private**.
- Raname the method `StoreStatsService#initPutMessageDistributeTime()` to  `StoreStatsService#resetPutMessageDistributeTime()`
> [ISSUE #3924] It may be better to change the method StoreStatsService#initPutMessageDistributeTime() to private.

- broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
> [ISSUE #4028] wrong log output

- broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- filter/src/main/java/org/apache/rocketmq/filter/util/BloomFilter.java
- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
- test/src/main/java/org/apache/rocketmq/test/util/DuplicateMessageInfo.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/PrintMessageByQueueCommand.java
Unnecessary  toString methods deleted
XX
XXXX
> [ISSUE #4040] Unnecessary  toString methods deleted

- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
#4048 
Make storePathCommitLog base on storePathRootDir
XXXX
> [ISSUE #4048] Make storePathCommitLog base on storePathRootDir

- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreCleanFilesTest.java
- store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java
https://github.com/apache/rocketmq/issues/3699
XX
XXXX
> [ISSUE #3699] fix unit test

- docs/cn/acl/user_guide.md
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/SubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/acl/DeleteAccessConfigSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/acl/GetAccessConfigSubCommand.java
- tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommand.java
#4035
Chage the following sub command of mqadmin:
```
deleteAccessConfig -> deleteAclConfig
getAccessConfigSubCommand -> getAclConfig
QueryMsgTraceById -> queryMsgTraceById
```
The old names can still be used for compatiblilty
XX
XXXX
> [ISSUE #4035] rename some commands

- client/src/main/java/org/apache/rocketmq/client/trace/TraceDispatcher.java
- docs/cn/acl/user_guide.md
- docs/cn/msg_trace/user_guide.md
- Fix for link: md file regard 'full width text' as part of link. Replace link with '#';
- Highlight java code in docs/cn/msg_trace/user_guide.md;
- fix typo in TraceDispatcher;
> [Document] Update user_guide.md: Fix for link.

- store/pom.xml
Update dledger version to 0.2.4
Update dledger version to 0.2.4
XXXX
> [ISSUE #4110] Update dledger version to 0.2.4

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
> [ISSUE #4125] Anonymous new Runnable() can be replaced with lambda

- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AbstractAllocateMessageQueueStrategy.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearby.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragely.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragelyByCircle.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByConfig.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByMachineRoom.java
- client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueConsistentHash.java
- client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByConfigTest.java
- client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueByMachineRoomTest.java
> [ISSUE #3940]Optimize AllocateMessageQueueStrategy

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
> [ISSUE #4129] Fix typo in CommitLog.java

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
> fix some error

- store/src/main/java/org/apache/rocketmq/store/schedule/ScheduleMessageService.java
> [ISSUE #4033] fix async deliver msg will resend forever when serivce not avliable

- acl/src/main/java/org/apache/rocketmq/acl/common/SessionCredentials.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java
- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java
- store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
clean up code 
Since it's a small change, I don't think it's necessary to add an issue
> MINOR:cleanup code

- store/src/main/java/org/apache/rocketmq/store/index/IndexFile.java
- store/src/main/java/org/apache/rocketmq/store/index/IndexService.java
- store/src/test/java/org/apache/rocketmq/store/index/IndexFileTest.java
file lock is not used, so we can remove it
XX
XXXX
> Remove file lock related code snippets in index file

- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
> [ISSUE #4123] Explicit type argument can be replaced with <> for RouteInfoManager

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
#4175 
When modify topic from slave, return a error response
> [ISSUE #4175] Prevent update topic on slave

- broker/src/main/java/org/apache/rocketmq/broker/plugin/MessageStoreFactory.java
remove the final modifier of a method which is already in a final class
XX
XXXX
> [ISSUE #4160]remove the final modifier of a method which is already in a final class

- tools/src/main/java/org/apache/rocketmq/tools/command/broker/SendMsgStatusCommand.java
> [ISSUE #4165] add new line in sendMsgStatus

- example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java
#4187 
* Add asyncEnable option in producer benchmark
* When async publish enabled, send message asynchronously
sync with 32 threads
async with 1 thread
> [ISSUE #4187]Support async publish in producer benchmark

- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
> [ISSUE #4183] When the reportSlaveMaxOffset method fails, end the current loop early

- client/src/main/java/org/apache/rocketmq/client/trace/TraceContext.java
Prevent int overflow
#4181 Minor improvement to prevent int overflow in `TraceContext`.
对 `TraceContext` 中`#compareTo(TraceContext)` 方法进行优化避免后续可能支持超长周期定时消息或者开发者魔改开发时触发 int 溢出问题。
https://mp.weixin.qq.com/s/JSjaF--EPRZHgI1037hJ-w 也提到了部分开发者会定制”任意时间，超长生命周期“的定时消息。
XX
XXXX
> [ISSUE #4181] Prevent int overflow in `TraceContext`

- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- common/src/main/java/org/apache/rocketmq/common/protocol/body/MessageRequestModeSerializeWrapper.java
- common/src/test/java/org/apache/rocketmq/common/protocol/body/MessageRequestModeSerializeWrapperTest.java
> [ISSUE #4056] Sync message request mode from master

- apis/src/main/java/org/apache/rocketmq/apis/consumer/MessageListener.java
- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/client/ClientHousekeepingService.java
- broker/src/main/java/org/apache/rocketmq/broker/dledger/DLedgerRoleChangeHandler.java
- broker/src/main/java/org/apache/rocketmq/broker/loadbalance/AssignmentManager.java
- broker/src/main/java/org/apache/rocketmq/broker/longpolling/LmqPullRequestHoldService.java
- broker/src/main/java/org/apache/rocketmq/broker/longpolling/PullRequestHoldService.java
- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
- broker/src/main/java/org/apache/rocketmq/broker/topic/TopicQueueMappingCleanService.java
- broker/src/main/java/org/apache/rocketmq/broker/transaction/AbstractTransactionalMessageCheckListener.java
- broker/src/main/java/org/apache/rocketmq/broker/transaction/TransactionalMessageCheckService.java
- broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
- container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java
- container/src/main/java/org/apache/rocketmq/container/BrokerPreOnlineService.java
- container/src/main/java/org/apache/rocketmq/container/InnerBrokerController.java
- container/src/test/java/org/apache/rocketmq/container/BrokerContainerTest.java
- store/src/main/java/org/apache/rocketmq/store/AllocateMappedFileService.java
- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java
- store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAClient.java
- store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAConnection.java
- store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java
- store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAConnectionStateNotificationService.java
- store/src/test/java/org/apache/rocketmq/store/ha/HAServerTest.java
> [ISSUE #4192] Fix log split not work for dLedger in container

- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
> [ISSUE #4211] Fix diskMaxUsedSpaceRatio does not take effect in dLedger

- openmessaging/src/main/java/io/openmessaging/rocketmq/utils/BeanUtils.java
remove the final modifier of a field which is already in a final class
XX
XXXX
> [ISSUE #4237] REMOVE unnecessary final modifier

- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
use function computeIfAbsent replace if
use function computeIfAbsent replace if
> [ISSUE #4239] Use function computeIfAbsent replace if

- common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java
- common/src/main/java/org/apache/rocketmq/common/protocol/route/BrokerData.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
In rip-29, we hope to use topic route cache to speed up route query, but in fact, in large-scale clusters (300 + brokers, 10000 + topics every broker), this optimization will affect registration and cause nameserver crash. So I remove the topic route cache and add switches for some performance-consuming calls.
Remove the topic route cache and add switches for some performance-consuming calls.
XXXX
> [ISSUE #4245] Remove the topic route cache in nameserver

- store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
Remove redundant `queue`
XX
XXXX
> [Optimization] Remove redundant queue

- broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
> [ISSUE #4072] fix totalPollingNum count error

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/BrokerPreOnlineService.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- container/src/main/java/org/apache/rocketmq/container/BrokerContainerConfig.java
- container/src/main/java/org/apache/rocketmq/container/InnerBrokerController.java
- container/src/main/java/org/apache/rocketmq/container/InnerSalveBrokerController.java
- container/src/test/java/org/apache/rocketmq/container/BrokerContainerTest.java
- container/src/test/java/org/apache/rocketmq/container/BrokerPreOnlineTest.java
- test/src/test/java/org/apache/rocketmq/test/container/ContainerIntegrationTestBase.java
Move the capability of slaveActingMaster from container module to broker module
XX
XXXX
> [ISSUE#4233] Move the capability of slaveActingMaster from container module to broker module

- client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
- client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionTraceHookImpl.java
- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQLitePullConsumerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java
- client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java
- common/pom.xml
- common/src/main/java/org/apache/rocketmq/common/MixAll.java
- common/src/main/java/org/apache/rocketmq/common/UtilAll.java
- common/src/main/java/org/apache/rocketmq/common/compression/CompressionType.java
- common/src/main/java/org/apache/rocketmq/common/compression/Compressor.java
- common/src/main/java/org/apache/rocketmq/common/compression/CompressorFactory.java
- common/src/main/java/org/apache/rocketmq/common/compression/Lz4Compressor.java
- common/src/main/java/org/apache/rocketmq/common/compression/ZlibCompressor.java
- common/src/main/java/org/apache/rocketmq/common/compression/ZstdCompressor.java
- common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
- common/src/main/java/org/apache/rocketmq/common/sysflag/MessageSysFlag.java
- common/src/test/java/org/apache/rocketmq/common/compression/CompressionTest.java
- common/src/test/java/org/apache/rocketmq/common/sysflag/CompressionFlagTest.java
- pom.xml
refer to https://github.com/apache/rocketmq/issues/4203
1. Add zstd / lz4 compressor
2. fix some spelling error
XXXX
> [ISSUE #4203] Support zstd/lz4 compression to improve send/receive performance

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
remove redundant code in consume and producer implement
replace addAll method to hashset constructure
> [ISSUE #3857] refact getPublishTopicList method and subscriptions method redundant code

- distribution/bin/runbroker.sh
> [ISSUE #4261] Add -Xmn parameter when jdk version is less than 8

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
#4277
Replace test file path separators
> [ISSUE #4227] fix ACL tests on Windows

- .travis.yml
- README.md
Add protocols to readme and delete the description of language clients
XX
XXXX
> [ISSUE #4284] Add protocols to readme and delete the description of language clients

- README.md
> [ISSUE #4286] add link of rocketmq-site to readme

- README.md
Add  a description of RocketMQ Dashboard and RocketMQ Connect
XXXXX
XX
XXXX
> [ISSUE #4291] Add  some description text to README

- README.md
fix 4283
Add an description in readme .
> Fix 4283 and add an description in readme. 

- README.md
> fix: delete a feature in Readme

- store/src/main/java/org/apache/rocketmq/store/MappedFile.java
[[ISSUE #3962] Fix variable name in MappedFile#isAbleToCommit()](https://github.com/apache/rocketmq/issues/3962)
Change the variable name from "flush" to "commit" in MappedFile#isAbleToCommit()
> [ISSUE #3962] Fix variable name in MappedFile#isAbleToCommit()

- broker/src/main/java/org/apache/rocketmq/broker/loadbalance/MessageRequestModeManager.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
> [ISSUE #4270]Log parameter error and optimize code

- docs/en/operation.md
Fix typo in the broker's log path
Fix typo in the broker's log path
XXXX
> Fix typo in the broker's log path

- store/src/main/java/org/apache/rocketmq/store/ha/HAConnection.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
> [ISSUE #4315] Optimize ha module's code

- store/src/main/java/org/apache/rocketmq/store/MappedFile.java
Anonymous new PrivilegedAction can be replaced with lambda 
XX
XXXX
> [ISSUE #4320] Anonymous new PrivilegedAction can be replaced with lambda

- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
fix for statement does not loop
fix for statement does not loop
XXXX
> [ISSUE #4317] Fix for statement does not loop

- store/src/main/java/org/apache/rocketmq/store/index/IndexHeader.java
**Make some variables in IndexHeader to be final.**
XX
XXXX
> [ISSUE #4318]make some variables to be final in IndexHeader

- README.md
- broker/src/main/java/org/apache/rocketmq/broker/plugin/MessageStoreFactory.java
> [ISSUE #4287]add detail descriptions to readme

- client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
- client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
- client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
> [ISSUE #4327] Init collection size

- broker/src/main/java/org/apache/rocketmq/broker/transaction/jdbc/JDBCTransactionStore.java
- broker/src/main/java/org/apache/rocketmq/broker/util/ServiceProvider.java
- common/src/test/java/org/apache/rocketmq/common/protocol/header/FastCodesHeaderTest.java
- openmessaging/src/main/java/io/openmessaging/rocketmq/utils/BeanUtils.java
- remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
> [ISSUE #4335] Replace deprecated api

- example/src/main/java/org/apache/rocketmq/example/openmessaging/SimpleProducer.java
- example/src/main/java/org/apache/rocketmq/example/openmessaging/SimplePullConsumer.java
- example/src/main/java/org/apache/rocketmq/example/openmessaging/SimplePushConsumer.java
> [ISSUE #4323] Optimized openmessaging example code

- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java
remove redundancy group name check of null
remove  null check about groupName in method  org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#checkConfig .
org.apache.rocketmq.client.Validators#checkGroup has contain null check about group name
add test cace for org.apache.rocketmq.client.Validators#checkGroup, if group name not null, test case will failed
------------------------------------------------------
> [ISSUE #4362] remove redundancy group name check of null in method org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#checkConfig

- broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java
- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java
- store/src/main/java/org/apache/rocketmq/store/ha/GroupTransferService.java
- store/src/main/java/org/apache/rocketmq/store/ha/HAService.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
- store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
- store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/EpochFileCacheTest.java
Modify the definition of syncStateSet in AutoSwitchHASerivce, and introduce the confirmOffset mechanism.
XXXX
> [Summer of code] Shrink and expand InSyncStateSet

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
> [ISSUE #4171]Fix tryQueryAssignment() in RebalanceImpl

- broker/pom.xml
- client/pom.xml
- example/pom.xml
- pom.xml
- store/pom.xml
- test/pom.xml
It is necessary to format the cluttered  code of maven dependencies management.
> Formatting code of maven dependencies management

- pom.xml
- test/pom.xml
> [ISSUE #4372] Make it compile with Java9+

- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- common/src/main/java/org/apache/rocketmq/common/namesrv/ControllerConfig.java
- controller/pom.xml
- namesrv/pom.xml
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
- pom.xml
- store/pom.xml
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Fix some bugs in controller mod
XX
XXXX
> [Summer of code] Fix some bugs in controller mode.

- common/src/main/java/org/apache/rocketmq/common/MixAll.java
Optimize for `MixAll#printObjectProperties`
Determine in advance whether `onlyImportantField` is true and field is annotated by `ImportantField`.
> [ISSUE #4391]optimize for printObjectProperties

- example/src/main/java/org/apache/rocketmq/example/schedule/ScheduledMessageConsumer.java
- example/src/main/java/org/apache/rocketmq/example/schedule/ScheduledMessageProducer.java
> [ISSUE #4323] Schedule example add the default NamesrvAddr

- distribution/bin/mqcontroller
- distribution/bin/mqcontroller.cmd
- distribution/bin/mqshutdown
- distribution/conf/logback_controller.xml
Add sh conf for startup controller
XXXX
> [Summer of code] Add sh conf for controller

- docs/cn/RocketMQ_Example.md
- docs/en/Example_Delay.md
在文档基本样例_ 延时消息队列中
可能是因为疏忽 未添加consumer/producer.setNamesrvAddr("localhost:9876"); 这可能会导致初学者产生困惑
并最终导致验证失败
In Example_Delay
maybe because of carelessness,
there is no code to specify name server addresses.
//producer.setNamesrvAddr("localhost:9876");  
//consumersetNamesrvAddr("localhost:9876"); 
This may cause confusion and lead to failure to verification. 
XX
XXXX
> Something in docs may cause confusion

- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/GetMetaDataResponseHeader.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerMetaDataCommand.java
Add admin tool to get controller cluster metadata
XXXX
> [Summer of code] Add admin tool getControllerMetadata

- controller/src/main/java/org/apache/rocketmq/controller/BrokerHeartbeatManager.java
- controller/src/main/java/org/apache/rocketmq/controller/Controller.java
- controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
- controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java
- controller/src/test/java/org/apache/rocketmq/controller/impl/controller/ControllerManagerTest.java
- controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DefaultBrokerHeartbeatManagerTest.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ControllerRequestProcessor.java
- pom.xml
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
1.Reuse dledger's remotingServer in controller mode.
2.Fix some bugs when controller deployed standAlone.
XXXX
> [Summer of code] Reuse dledger remotingServer in controller mode.

- example/src/main/java/org/apache/rocketmq/example/namespace/ProducerWithNamespace.java
- example/src/main/java/org/apache/rocketmq/example/namespace/PullConsumerWithNamespace.java
- example/src/main/java/org/apache/rocketmq/example/namespace/PushConsumerWithNamespace.java
> [ISSUE #4323] Optimized namespace example code

- example/src/main/java/org/apache/rocketmq/example/quickstart/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
> [ISSUE #4323] Quickstart adds the default NamesrvAddr

- example/src/main/java/org/apache/rocketmq/example/batch/SimpleBatchProducer.java
- example/src/main/java/org/apache/rocketmq/example/batch/SplitBatchProducer.java
> [ISSUE #4323] Batch example add the default NamesrvAddr

- example/src/main/java/org/apache/rocketmq/example/broadcast/PushConsumer.java
> [ISSUE #4323] Broadcast example add the default NamesrvAddr

- example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingProducer.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingPushConsumer.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/OpenTracingTransactionProducer.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/TraceProducer.java
- example/src/main/java/org/apache/rocketmq/example/tracemessage/TracePushConsumer.java
> [ISSUE #4323] tracemessage example add the default NamesrvAddr

- example/src/main/java/org/apache/rocketmq/example/transaction/TransactionProducer.java
> [ISSUE #4323] Transaction example add the default NamesrvAddr

- pom.xml
Update dledger version to 0.2.6
XX
XXXX
> [ISSUE #4416] Update dledger version to 0.2.6

- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
Record haconnection's lastCaughtUpTimeMs in haService's map
XXXX
> [Summer of code] Record haconnection's lastCaughtUpTimeMs in haService's map

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java
- common/src/main/java/org/apache/rocketmq/common/MixAll.java
fix #4365 Treat multiple file paths into one fulln 2022/5/24 上午10:04 
XX
XXXX
> [ISSUE #4365]  acl PlainPermissionManager key file paths set to same

- common/src/main/java/org/apache/rocketmq/common/subscription/CustomizedRetryPolicy.java
- common/src/main/java/org/apache/rocketmq/common/subscription/ExponentialRetryPolicy.java
- common/src/main/java/org/apache/rocketmq/common/subscription/GroupRetryPolicy.java
- common/src/main/java/org/apache/rocketmq/common/subscription/RetryPolicy.java
- common/src/test/java/org/apache/rocketmq/common/subscription/CustomizedRetryPolicyTest.java
- common/src/test/java/org/apache/rocketmq/common/subscription/ExponentialRetryPolicyTest.java
- common/src/test/java/org/apache/rocketmq/common/subscription/GroupRetryPolicyTest.java
Expand RocketMQ Topic/Group attributes
Add RetryPolicy interface
> [ISSUE #4384] Add RetryPolicy interface

- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
- example/src/main/java/org/apache/rocketmq/example/namespace/PullConsumerWithNamespace.java
- example/src/main/java/org/apache/rocketmq/example/namespace/PushConsumerWithNamespace.java
- pom.xml
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Fix incorrect indentation issue
Upgrade maven-checkstyle-plugin to 3.1.2
> [ISSUE #4419] Upgrade maven-checkstyle-plugin to 3.1.2

- broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
Fix ha controller bugs
XX
XXXX
> Fix ha controller bugs

- acl/src/main/java/org/apache/rocketmq/acl/AccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessValidator.java
- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessControlFlowTest.java
- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- acl/src/test/resources/update_global_white_addr/conf/acl/empty.yml
- acl/src/test/resources/update_global_white_addr/conf/acl/plain_acl.yml
- acl/src/test/resources/update_global_white_addr/conf/plain_acl.yml
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/UpdateGlobalWhiteAddrsConfigRequestHeader.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/acl/UpdateGlobalWhiteAddrSubCommand.java
> [#4151]Add option p to the updateGlobalWhiteAddr command.

- broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/NotifyBrokerRoleChangedRequestHeader.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/ElectMasterResponseHeader.java
- controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerInfo.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
Let controller inform broker that role changed.
XXXX
> [Summer of code] Let controller inform broker that role changed.

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/hacontroller/ReplicasManager.java
- broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java
- common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/MessageStore.java
- store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Make broker do not online before get brokerId and master-slave relationship
Make broker do not online before get brokerId and master-slave relationship
XXXX
> Make broker do not online before get brokerId and master-slave relationship

- controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerControllerStateMachine.java
Let controller become role state after append initial logs
XXXX
> [Summer of code] Let controller become role state after append initial logs

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
> [ISSUE #4455] add a schedule task to update namesrv address

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- docs/cn/operation.md
- docs/en/CLITools.md
- docs/en/operation.md
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/broker/DeleteExpiredCommitLogSubCommand.java
- tools/src/test/java/org/apache/rocketmq/tools/command/broker/DeleteExpiredCommitLogSubCommandTest.java
Add a mqadmin command to delete expired commitlog files
Add DeleteExpiredCommitLogSubCommand to invoke existing `executeDeleteFilesManually()` in `CleanCommitLogService`
> [ISSUE #4037] Add DeleteExpiredCommitLogSubCommand

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/main/java/org/apache/rocketmq/store/MultiDispatch.java
- store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
> [ISSUE #4058] DLedgerCommitLog support LMQ

- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/GetRouteInfoRequestHeader.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
Fix https://github.com/apache/rocketmq/issues/4471
> Generate legal JSON response conditionally

- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
> [Summer of code] Fix comment

- common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java
- distribution/conf/controller/quick-start/namesrv.conf
- docs/cn/controller/deploy.md
- docs/cn/controller/quick_start.md
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Add deploy and upgrade guide document for controller mode
1. Add deploy and upgrade guide document for controller mode
2. Rename enableStartupController to  enableControllerInNamesrv
XXXX
> Add deploy and upgrade guide document for controller mode

- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
> [ISSUE #4507] fix message trace throws exception #4507

- client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
> [ISSUE #4489]Some trace messages not being sent to the broker in time before producer shutdown.

- common/src/main/java/org/apache/rocketmq/common/protocol/route/BrokerData.java
an elegant `equals` using apache-commons
> [ISSUE #4513] elegant equals using apache-commons

- store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
- store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
- store/src/main/java/org/apache/rocketmq/store/MessageStore.java
- store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java
- store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueInterface.java
- store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java
- store/src/main/java/org/apache/rocketmq/store/queue/FileQueueLifeCycle.java
- store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java
- store/src/test/java/org/apache/rocketmq/store/HATest.java
- store/src/test/java/org/apache/rocketmq/store/dledger/MessageStoreTestBase.java
Optimizing the Code for ConsumeQueue abstraction.
1. Delay the start of some heavy components in DefaultMessageStore.
2. Make ConsumeQueue and BatchConsumeQueue program to an interface: MessageStore, not an implementation: DefaultMessageStore.
3. Transfer methods that should not belong to FileQueueLifeCycle to ConsumeQueueInterface.
4. Configurable method doCheckReputOffsetFromCq.
Pass UTs.
> [ISSUE #4435] Code optimization for ConsumeQueue abstraction.

- store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java
> [ISSUE #4528] fix test failed sometimes

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientManager.java
- client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
- client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
- client/src/main/java/org/apache/rocketmq/client/producer/MQProducer.java
- client/src/main/java/org/apache/rocketmq/client/producer/ProduceAccumulator.java
- client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
- client/src/test/java/org/apache/rocketmq/client/producer/ProduceAccumulatorTest.java
- common/src/main/java/org/apache/rocketmq/common/message/MessageBatch.java
> [ISSUE #3717] Auto batching in producer in branch/5.0.0-beta

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
> [ISSUE #4544] Print aclConf

- broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/ForwardRequestProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/QueryMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
- broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
> [ISSUE #4515] Remove implement

- .travis.yml
- test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java
- test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
- test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
Fix the unstable test StaticTopicIT
> Fix static topic test, await the client metadata to be refreshed

- store/src/main/java/org/apache/rocketmq/store/CommitLog.java
- store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
- store/src/test/java/org/apache/rocketmq/store/HATest.java
…alse
Fix bug that return IN_SYNC_REPLICAS_NOT_ENOUGH when enableSlaveActingMaster is false
XX
XXXX
> Fix bug that return IN_SYNC_REPLICAS_NOT_ENOUGH when enableSlaveActingMaster is false

- store/pom.xml
Adapt the log4j2 in DLedger 0.2.7, which needs to be excluded while being in RocketMQ.
1. Remove slf4j-log4j12 exclusion in store/pom.xml.
2. Add exclusions for the log4j2 dependencies within DLedger 0.2.7.
> Modify Dependency Exclusions for DLedger 0.2.7

- acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
> [ISSUE #4579] Fix compare different types

- tools/src/main/java/org/apache/rocketmq/tools/command/queue/QueryConsumeQueueCommand.java
> [ISSUE #4597] Fix inaccurate judgement

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java
Issue #4579 
Follow #4580 Add unit test
XX
XXXX
> [ISSUE #4579] Add unit test

- tools/src/main/java/org/apache/rocketmq/tools/command/cluster/ClusterListSubCommand.java
Fix the wrong format output of clusterlist command
XX
XXXX
> [ISSUE  #4607] Fix the wrong format output of clusterlist command

- client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
> [ISSUE #4606] Build trace msgs for DefaultLitePullConsumer when poll is called

- broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
> [ISSUE #4617] Correct log info

- client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageTraceHookImpl.java
> [ISSUE #4167] Fix typo

- test/src/test/java/org/apache/rocketmq/test/statictopic/StaticTopicIT.java
> Try to make CI test more stable

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- acl/src/test/resources/conf/plain_acl_bak.yml
Add plain_acl_bak.xml for reset at test case start.
> [ISSUE #4624] Add plain_acl_bak.xml for reset at test case start.

- common/src/main/java/org/apache/rocketmq/common/EpochEntry.java
- common/src/main/java/org/apache/rocketmq/common/utils/CheckpointFile.java
- common/src/test/java/org/apache/rocketmq/common/utils/CheckpointFileTest.java
Add CRC32 verification when saving checkpoint file
> [ISSUE #4626] Add CRC32 verification when saving checkpoint file

- acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
- broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerTest.java
Follow #4167 
Add unit test (ConsumerManagerTest)
XX
XXXX
> [ISSUE #4167] Add unit test (ConsumerManagerTest)

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/RequestTask.java
> [ISSUE #4630] Fix RequestTask's stopRun field concurrency issues(#4631)

- proxy/src/main/java/org/apache/rocketmq/proxy/service/transaction/AbstractTransactionService.java
- proxy/src/main/java/org/apache/rocketmq/proxy/service/transaction/TransactionDataManager.java
- proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/SendMessageActivityTest.java
- proxy/src/test/java/org/apache/rocketmq/proxy/service/transaction/TransactionDataManagerTest.java
If client not commit or rollback transaction at the first time, will lead to proxy cannot end transaction in the future
For example
```java
Producer producer = provider.newProducerBuilder()
.setTopics("test")
.setTransactionChecker(messageView -> {
// will lead to check for many times
return TransactionResolution.COMMIT;
})
.setClientConfiguration(clientConfiguration)
.build();
for (int i = 0; i < 1; i++) {
Message message = provider.newMessageBuilder()
.setTopic("test")
.setBody("body".getBytes(StandardCharsets.UTF_8))
.build();
Transaction transaction = producer.beginTransaction();
producer.send(message, transaction);
// not commit or rollback
}
```
So, use the last TransactionData saved in TransactionDataManager
XX
XXXX
Follow this …
> fix: use the last TransactionData for the same transactionId

- common/src/main/java/org/apache/rocketmq/common/protocol/header/PullMessageResponseHeader.java
Do not check nullable field in PullMessageResponseHeader
Remove getAndCheckNotNull for nullable fileld
> Do not check nullable field in PullMessageResponseHeader

- broker/src/main/java/org/apache/rocketmq/broker/loadbalance/AssignmentManager.java
- client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapper.java
> [ISSUE #4062] pop consumer does not require static topic

- docs/cn/QuorumACK.md
- docs/cn/README.md
- docs/cn/controller/deploy.md
- docs/cn/controller/design.md
- docs/cn/controller/quick_start.md
- docs/cn/dledger/deploy_guide.md
- docs/cn/dledger/quick_start.md
Polish documents enables users to better understand HA mode
Polish documents enables users to better understand HA mode
XXXX
> [ISSUE #4662] Polish documents enables users to better understand HA mode

- broker/src/main/java/org/apache/rocketmq/broker/plugin/AbstractPluginMessageStore.java
Add the implementations of missing in AbstractPluginMessageStore to ensure compatibility
Add the implementations of missing in AbstractPluginMessageStore to ensure compatibility
XXXX
>  [ISSUE #4681]Add the implementations of missing in AbstractPluginMessageStore to ensure compatibility

- pom.xml
Enable dependencyConvergence in maven enforcer plugin.
Related link: https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html
> Enable dependencyConvergence in maven enforcer plugin

- proxy/src/main/java/org/apache/rocketmq/proxy/service/transaction/ClusterTransactionService.java
- proxy/src/test/java/org/apache/rocketmq/proxy/service/transaction/ClusterTransactionServiceTest.java
fix brokerAddr to brokerName mapping is not right in ClusterTransactionService for proxy when has multiple clusters
XX
XXXX
> fix: brokerAddr to brokerName mapping is not right when has multiple clusters

- controller/src/main/java/org/apache/rocketmq/controller/ControllerStartup.java
> [ISSUE #4700]Optimize print information when the  rocketmqHome variable not set

- proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java
- proxy/src/test/java/org/apache/rocketmq/proxy/service/transaction/ClusterTransactionServiceTest.java
> [ISSUE #4712] add maxConnectionIdle for grpc server

- proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java
Channelz is an essential observation tools for gRPC... See https://grpc.io/blog/a-short-introduction-to-channelz/ 
We need it to enhance visibility into the gRPC server.
XXXX
This PR fixes https://github.com/apache/rocketmq/issues/4665
> Support ChannelZ to observe gRPC server

- controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
Fix #4734 
- Fix DLedgerController startScheduling concurrency problem
XXXX
> [ISSUE #4734]Fix DLedgerController startScheduling concurrency problem

- broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
Fix #4736 
- Optimize ReplicasManager#start method retry logic
XXXX
> [ISSUE #4736] Optimize ReplicasManager#start method retry logic

- broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
Fix #4741 
- Optimize ReplicasManager constructor, remove redundant code
XXXX
> [ISSUE #4741]Optimize ReplicasManager constructor, remove redundant code

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
- broker/src/main/java/org/apache/rocketmq/broker/dledger/DLedgerRoleChangeHandler.java
- broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
- broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
- common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java
- store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
- store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
close #4732 
Enable new timer message to adapt to ha switching and brokerContainer
Enable new timer message to adapt to ha switching and brokerContainer
XXXX
> [ISSUE #4732] Make new timer message can adapt to HA and brokerContainer

- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/DefaultGrpcMessingActivity.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManager.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/PopMessageResultFilterImpl.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java
- proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManagerTest.java
- proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java
- test/src/test/java/org/apache/rocketmq/test/grpc/v2/GrpcBaseIT.java
1. reserve requestTimeout/2 to poll message, so the real poll time to pop broker = max(0, min(30s, remaining-requestTimeout/2))
2. fix bug of some configs cannot push to client
XX
XXXX
> change time for polling method and fix bug in clientSettingsManager for proxy

- controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java
Fix #4750 
-- Fix ControllerRequestProcessor#processRequest handle CONTROLLER_GET_SYNC_STATE_DATA code return RemotingCommand incorrect
XXXX
> [ISSUE #4750] Fix ControllerRequestProcessor#processRequest handle CONTROLLER_GET_SYNC_STATE_DATA return incorrect

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
close #4738 
- Semantic some variables value in BrokerController#initializeBrokerScheduledTasks method
XXXX
> [ISSUE #4738] Semantic period variables value in BrokerController#initializeBrokerScheduledTasks method

- common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java
- common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
- test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Fix #4748 
- ControllerConfig.enableControllerInNamesrv attribute move to NamesrvConfig
XXXX
> [ISSUE #4748] Add attribute enableControllerInNamesrv to NamesrvConfig

- proxy/src/main/java/org/apache/rocketmq/proxy/config/MetricCollectorMode.java
- proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManager.java
- proxy/src/test/java/org/apache/rocketmq/proxy/config/MetricCollectorModeTest.java
> Use string as the configuration parameter type of metrics collector mode

- .asf.yaml
> [ISSUE #4755] Some improvement about branch management

- .asf.yaml
Update  info in .asf.yaml
Update .asf.yaml
> Update Description in .asf.yaml

- broker/src/test/resources/logback-test.xml
- controller/src/test/resources/logback-test.xml
- distribution/conf/logback_broker.xml
- distribution/conf/logback_controller.xml
- distribution/conf/logback_namesrv.xml
- distribution/conf/logback_proxy.xml
- distribution/conf/logback_tools.xml
- proxy/src/test/resources/rmq-proxy-home/conf/logback_proxy.xml
- test/src/test/resources/logback-test.xml
- test/src/test/resources/rmq-proxy-home/conf/logback_proxy.xml
> [ISSUE #4706] fix console printed log format is incorrect

- remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
close #4751 
-  Optimize NettyRemotingAbstract#processRequestCommand code
XXXX
> [ISSUE #4751] Optimize NettyRemotingAbstract#processRequestCommand code

- broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
- broker/src/main/java/org/apache/rocketmq/broker/BrokerPreOnlineService.java
- store/src/main/java/org/apache/rocketmq/store/timer/TimerCheckpoint.java
- store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
- store/src/test/java/org/apache/rocketmq/store/timer/TimerCheckPointTest.java
- store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
- test/src/test/java/org/apache/rocketmq/test/container/GetMetadataReverseIT.java
- test/src/test/java/org/apache/rocketmq/test/container/ScheduleSlaveActingMasterIT.java
- test/src/test/java/org/apache/rocketmq/test/container/ScheduledMessageIT.java
Timer Message adapts to slaveActingMaster mode
Timer Message adapts to slaveActingMaster mode
XXXX
>  [ISSUE #4758] Timer Message adapts to slaveActingMaster mode

- controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java
close #4745 
- Check controllerDLegerPeers and controllerDLegerSelfId attributes before create DLedgerServer
XXXX
> [ISSUE #4745]Check controllerDLegerPeers and controllerDLegerSelfId attributes before create DLedgerServer

- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/DefaultGrpcMessingActivity.java
- proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivity.java
- proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivityTest.java
remove handle from receiptHandleProcessor when forwardMessageToDLQ
XX
XXXX
> [ISSUE #4783] remove handle from receiptHandleProcessor when forwardMessageToDLQ

- namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
> [ISSUE #4698]NamesrvStartup code optimize

- distribution/bin/controller/fast-try-namesrv-plugin.sh
- distribution/conf/controller/cluster-3n-namesrv-plugin/namesrv-n0.conf
- distribution/conf/controller/cluster-3n-namesrv-plugin/namesrv-n1.conf
- distribution/conf/controller/cluster-3n-namesrv-plugin/namesrv-n2.conf
close #4781 
- Add config file for controller run as Namesrv plugin
- add fast-plugin.sh for quick start controller as Namesrv plugin
XXXX
> [ISSUE #4781] Add config file for controller run as Namesrv plugin

- distribution/bin/controller/fast-try-independent-deployment.sh
- docs/cn/controller/quick_start.md
close #4788 
- Improvement controller quick_start.md file
- create a fast-try-independent-deployment.sh file for fast start controller ndependent deployment
XXXX
> [ISSUE #4788] Improvement controller quick_start.md file

- tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerMetaDataSubCommand.java
Fix #4789 
- Fix mqadmin CL print format is incorrect
XXXX
> [ISSUE #4789] Fix mqadmin CL print format is incorrect

- example/src/main/java/org/apache/rocketmq/example/filter/TagFilterConsumer.java
- example/src/main/java/org/apache/rocketmq/example/operation/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Consumer.java
- example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java
> remove unless exception

- common/src/main/java/org/apache/rocketmq/common/protocol/body/BrokerMemberGroup.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
Fix #4794 
- Fix deserialize ElectMasterResponseHeader attribute value of brokerMemberGroup is null
XXXX
> [ISSUE #4794] Fix deserialize ElectMasterResponseHeader attribute value of brokerMemberGroup is null

- example/src/main/java/org/apache/rocketmq/example/filter/TagFilterConsumer.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
- namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
- namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java
- namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerTest.java
- namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager_NewTest.java
> [ISSUE #4522] Fix topic route info not found in some case

- client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
- common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/ElectMasterRequestHeader.java
- controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
- controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java
- controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
- tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
- tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
- tools/src/main/java/org/apache/rocketmq/tools/command/controller/ReElectMasterSubCommand.java
close #4791 
- Add elect master command for admin CLI
XXXX
> [ISSUE #4791] Add elect master command for admin CLI

- pom.xml
- proxy/pom.xml
- proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java
using caffeine replace guava cache
using caffeine replace guava cache
TopicRouteService class 
> using caffeine replace guava cache
