store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
Fix #4818 
- Fix AutoSwitchHAService code formate incorrect
XXXX
=> [ISSUE #4818] Fix AutoSwitchHAService code formate incorrect

store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java
**Make sure set the target branch to develop**
**What is the purpose of the change**
MappedFileQueue: if the initial cursor of listIterator equals zero,the previous element will always null.
MappedFile: use AtomicIntegerFieldUpdater instead of AtomicInteger.
**Brief changelog**
**Verifying this change**
DefaultMappedFile class
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR.
=> fix code bug & optimize the memory usage in DefaultMappedFile

distribution/conf/logback_namesrv.xml
=> Add Controller's log to Namesrv when enableControllerInNamesrv=true.

common/src/main/java/org/apache/rocketmq/common/admin/ConsumeStats.java, common/src/main/java/org/apache/rocketmq/common/admin/TopicStatsTable.java, common/src/main/java/org/apache/rocketmq/common/protocol/body/TopicList.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
close [ISSUE #4842](https://github.com/apache/rocketmq/issues/4842)
=> [ISSUE #4842]fix thread-safety problem of admin tools

docs/cn/controller/design.md
close #4845 
- Fix Controller design.md typo
XXXX
=> [ISSUE #4845] Fix Controller design.md typo

controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java
close #4847 
- Optimize DefaultBrokerHeartbeatManager#onBrokerHeartbeat mehtod code logic
XXXX
=> [ISSUE #4847]Optimize DefaultBrokerHeartbeatManager#onBrokerHeartbeat mehtod code logic

acl/src/test/java/org/apache/rocketmq/acl/common/AclSignerTest.java
add missing assertions of some test cases
=> add missing assertions of some test cases

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
close #4868 
- Remove unnecessary words from CommitLog#asyncPutMessage method comments
XXXX
=> [ISSUE #4868]Remove unnecessary words from CommitLog#asyncPutMessage method comments

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
close #4584 
Add new persist method to update consume offset to remote server.
=> [ISSUE #4584] Add new persist method to update consume offset to remote server.

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
=> [ISSUE #4838] send async，time is not counted until the task is executed 

docs/cn/concept.md, docs/en/Concept.md
fix #1942  push consumer doc error
=> [ISSUE #1942] Fix push consumer doc error

.asf.yaml, .github/workflows/build.yaml, .github/workflows/license-checker.yaml
=> [ISSUE #4870] Enhance the mergeability: add status checker about the protected branch

.github/workflows/maven.yaml, store/BUILD.bazel, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/test/java/org/apache/rocketmq/store/HATest.java, store/src/test/java/org/apache/rocketmq/store/timer/StoreTestUtils.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
Make HATest cases capable of running in parallel.
XX
XXXX
=> Make HATest cases capable of running in parallel.

broker/src/test/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessorTest.java, client/BUILD.bazel, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java
=> Fix flaky tests

client/BUILD.bazel, controller/BUILD.bazel, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java
=> Fix test label 

.github/workflows/bazel.yml, .github/workflows/coverage.yml, .github/workflows/maven.yaml
=> [ISSUE #4879] Enable GitHub Action dependency caching for coverage

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
Fix #4857 
- Fix broker can't auto register to controller again
XXXX
=> [ISSUE #4857] Fix broker can't auto register to controller again

.asf.yaml
Update required status check before merging
XX
XXXX
=> [ISSUE 4870]Update required status check

proxy/src/main/java/org/apache/rocketmq/proxy/config/Configuration.java
Fix the indentation error reported by Checkstyle.
1. Fix indentation of code within Configuration.java
=> Fix Indentation Error Reported by Checkstyle

test/BUILD.bazel
Fix https://github.com/apache/rocketmq/issues/4885
XX
XXXX
=> [ISSUE 4885]Refine test size of test module

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java
This pull request fixes https://github.com/apache/rocketmq/issues/4568
=> [ISSUE #4568]Improve performance of consume queue

controller/src/test/java/org/apache/rocketmq/controller/impl/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java
close #4873 
-Optimize controller module test cases execution time
optimize before
optimize after
=> [ISSUE #4873]Optimize controller module test cases execution time

controller/src/test/java/org/apache/rocketmq/controller/impl/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java
Fix #4889 
-Fix controller test:DLedgerControllerTest#testChangeControllerLeader
XXXX
=> [ISSUE #4889]Fix controller test:DLedgerControllerTest#testChangeControllerLeader

tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java
Fix NPE in CommandUtil
Fix NPE in CommandUtil
XXXX
=> [ISSUE #4894] Fix NPE in CommandUtil

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
Increase the retry interval of registration failure to prevent frequent log output
Increase the retry interval of registration failure to prevent frequent log output
XXXX
=> [ISSUE #4897] Increase the retry interval of registration failure to prevent frequent log output

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
=> [ISSUE #4841] Fix the reply message is the original request msg.

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/RequestCode.java, common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/namesrv/controller/CleanControllerBrokerDataRequestHeader.java, controller/src/main/java/org/apache/rocketmq/controller/Controller.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/event/CleanBrokerDataEvent.java, controller/src/main/java/org/apache/rocketmq/controller/impl/event/EventSerializer.java, controller/src/main/java/org/apache/rocketmq/controller/impl/event/EventType.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerInfo.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/SyncStateInfo.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/CleanControllerBrokerDataSubCommand.java
close #4817 
- Add a command to clear broker data from controller for CLI
as following picture
=> [ISSUE #4817] Add a command to clear broker data from controller for CLI

.asf.yaml
Close #4906
Add required pull request reviews rule for develop branch
XX
XXXX
=> [ISSUE #4906] Add required pull request reviews rule for develop branch

tools/src/main/java/org/apache/rocketmq/tools/command/broker/SendMsgStatusCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/consumer/SetConsumeModeSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerMetaDataSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportConfigsCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetadataCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetricsCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/CheckMsgSendRTCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/offset/CloneGroupOffsetCommand.java, tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicClusterSubCommand.java
Make all admin command descriptions begin with capital letters
XX
XXXX
=> [ISSUE #4911] Make all admin command descriptions begin with capital letters

store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueExtTest.java, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java, store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java, store/src/test/java/org/apache/rocketmq/store/HATest.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/MixCommitlogTest.java, store/src/test/java/org/apache/rocketmq/store/ha/FlowMonitorTest.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java, store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeMessageTest.java
close #4904
-Optimize store module test cases to reduce execution time
XXXX
=> [ISSUE #4904]Optimize store module test cases to reduce execution time

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
Fix wrong log output in TimerMessageStore
Close #4921
XX
XXXX
=> [ISSUE #4921] Fix wrong log output in TimerMessageStore

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
close #4920 
- Fix comment word typo
XXXX
=> [ISSUE #4920]Fix comment word typo

.github/workflows/bazel.yml
Restore use of pull request target for bazel github action pipeline
Fix https://github.com/apache/rocketmq/issues/4923
XX
XXXX
=> [ISSUE 4923] Restore use of pull_request_target

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
1. fix the wrong typo about DLedger
issue: https://github.com/apache/rocketmq/issues/4929
XXXXX
XX
XXXX
=> [ISSUE#4929]: fix the wrong typo about DLedger

common/src/main/java/org/apache/rocketmq/common/LifecycleAwareServiceThread.java, srvutil/pom.xml, srvutil/src/main/java/org/apache/rocketmq/srvutil/FileWatchService.java, srvutil/src/test/java/logback-test.xml, srvutil/src/test/java/org/apache/rocketmq/srvutil/FileWatchServiceTest.java
Fix https://github.com/apache/rocketmq/issues/4926
XX
XXXX
=> [ISSUE 4926]Fix FileWatchServiceTest

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageUtil.java, broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java, common/src/main/java/org/apache/rocketmq/common/AbstractBrokerRunnable.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerStartup.java, logging/src/main/java/org/apache/rocketmq/logging/InternalLoggerFactory.java, logging/src/main/java/org/apache/rocketmq/logging/Slf4jLoggerFactory.java, pom.xml, srvutil/src/test/java/org/apache/rocketmq/srvutil/FileWatchServiceTest.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMetrics.java, test/src/main/java/org/apache/rocketmq/test/listener/AbstractListener.java, test/src/main/java/org/apache/rocketmq/test/listener/rmq/concurrent/RMQDelayListener.java, test/src/main/java/org/apache/rocketmq/test/listener/rmq/concurrent/RMQNormalListener.java, test/src/main/java/org/apache/rocketmq/test/listener/rmq/order/RMQOrderListener.java, test/src/main/java/org/apache/rocketmq/test/schema/SchemaDefiner.java, test/src/main/java/org/apache/rocketmq/test/schema/SchemaTools.java, test/src/main/java/org/apache/rocketmq/test/util/FileUtil.java, test/src/test/java/org/apache/rocketmq/test/schema/SchemaTest.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/topic/RemappingStaticTopicSubCommand.java, tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorService.java
=> [ISSUE #4934] Checking for violations as part of build

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
=> [ISSUE#4936] Fix invalid log output after the master and slave broker are started on the empty disk in controller mode

store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeQueueTest.java
The assertion of time used is not stable in github actions
=> [ISSUE #4943] not to assert time cost in test case

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerControllerStateMachine.java
issue: https://github.com/apache/rocketmq/issues/4950
XXXXX
XX
XXXX
=> [ISSUE#4950] fix wrong typo about DLedger

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/BaseActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivityTest.java
1. write client settings in lock to solve concurrency problems
2. optimize the process of error handle
XX
XXXX
=> Fix concurrency problems in ClientActivity of proxy

proxy/src/main/java/org/apache/rocketmq/proxy/service/message/ClusterMessageService.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/message/ClusterMessageServiceTest.java
return INVALID_RECEIPT_HANDLE when cannot find the broker of handle
XX
XXXX
=> [ISSUE #4953] return INVALID_RECEIPT_HANDLE when cannot find the broker of handle

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/SendMessageActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/SendMessageActivityTest.java
validate userProperties contain control character or not
XX
XXXX
=> [ISSUE #4955] validate userProperties contain control character or not

proxy/src/main/java/org/apache/rocketmq/proxy/common/MessageReceiptHandle.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/test/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroupTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java
1. fix the concurrency problems when renew and ack/changeInvisibleTime at the same time
2. retry renew for a limited times when some error occurred
3. code refactor for ReceiptHandleProcessor
XX
XXXX
=> [ISSUE #4938, ISSUE #4939] fix the concurrency problems and limit the times of renew when some error occurred in ReceiptHandleProcessor

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
=> [ISSUE #4963] Prepare to release RocketMQ 5.0.0 version

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/BatchUnRegisterService.java
=> using take replace poll

store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java
=> [ISSUE #4670] Modify the package path and fix typo

.github/workflows/bazel.yml, .github/workflows/maven.yaml
=> [ISSUE #4968] Add windows/macos into build matrix

store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java
close #4964 
-  Adjust BrokerStatsManagerTest class package
XXXX
=> [ISSUE #4964] Adjust BrokerStatsManagerTest class package

client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
=> [ISSUE #4972] Fix DefaultLitePullConsumerTest#testConsumerCommitSyncWithMQOffset

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvController.java, test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java, test/src/test/resources/logback-test.xml
Fix issue https://github.com/apache/rocketmq/issues/4974
XX
XXXX
=> [ISSUE: 4974]Fix name server client config when OS picks up available port

proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/transaction/EndTransactionActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/TransactionProcessorTest.java
Close #4982 
Remove useless import in proxy module
Remove useless import in proxy module
XXXX
=> [ISSUE #4982] Remove useless import in proxy module

store/src/main/java/org/apache/rocketmq/store/timer/TimerMetrics.java
Fix #4985 
- Fix TimerMetrics#persist tmpFile can't rename to configFile
XXXX
=> [ISSUE #4985]Fix TimerMetrics#persist tmpFile can't rename to configFile

docs/cn/dledger/quick_start.md, docs/en/dledger/quick_start.md
close #4993 
- Polish the documents for mq Dledger Quick Deployment
XXXX
=> [ISSUE #4993]Polish the documents for mq Dledger Quick Deployment

broker/src/test/java/org/apache/rocketmq/broker/BrokerPathConfigHelperTest.java
close #4995 
- Fix test case:BrokerPathConfigHelperTest#testGetLmqConsumerOffsetPath
XXXX
=> [ISSUE #4995]Fix test case:BrokerPathConfigHelperTest#testGetLmqConsumerOffsetPath

acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java, common/src/main/java/org/apache/rocketmq/common/AclConfig.java, common/src/main/java/org/apache/rocketmq/common/PlainAccessConfig.java
=> [ISSUE #4585] PlainPermissionManagerTest add unit test

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
=> fix wrong log warning

broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
=> [ISSUE #4977] Fix BrokerOuterAPITest#test_register_timeout

common/src/main/java/org/apache/rocketmq/common/Configuration.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java
Want the properties to be ordered and easy to view after the config persisted.
XX
XXXX
=> Sort the property when persist config.

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/BatchUnregistrationService.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, test/src/test/java/org/apache/rocketmq/test/smoke/NormalMessageSendAndRecvIT.java
Fix https://github.com/apache/rocketmq/issues/4979
Fix netty warning; https://blog.csdn.net/diaobatian/article/details/90696757
Fix naming typo of batch unregistration service
XX
XXXX
=> [ISSUE #4979] Fix flaky integration test NormalMessageSendAndRecvIT

common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java, tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/api/TrackType.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByIdSubCommand.java, tools/src/test/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtTest.java
#4487 
The patch(#4488) submitted before has not been merged for a long time, resulting in a conflict with the current code. If the online modification conflict is not careful, the code submission may be wrong. Therefore, the previous PR is closed and a new one is submitted based on the current code
XX
XXXX
=> [ISSUE #4487]The trackType is wrong when the consumer in broadcasting subscription

.github/workflows/stale.yml
Fixes #4905. Note: This pull request is a draft now.
The close of stale issues/PRs could be divided into two phases:
1. Label the necessary issues/PRs.
2. Enable Github Action to clear the stale issues/PRs.
**This pull request is expected to be merged after phase1**.
releated:
* [actions/stale](https://github.yanqishui.work/actions/stale)
=> [ISSUE #4905] Close stale issues/PRs

.github/workflows/stale.yml
=> [ISSUE #5010] Remove 'high priority' from exempt-issue-labels

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionPositionMgr.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionService.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionStore.java, store/src/main/java/org/apache/rocketmq/store/kv/MessageFetcher.java, store/src/main/java/org/apache/rocketmq/store/queue/SparseConsumeQueue.java, store/src/test/java/org/apache/rocketmq/store/StoreTestBase.java, store/src/test/java/org/apache/rocketmq/store/kv/CompactionLogTest.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/message/DumpCompactionLogCommand.java
optimize #3799
when rebuild slave, then slave will replicate message from master.
=> Support replicate between master and slave

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
=> [ISSUE #5022]Optimize DefaultMQAdminExtImpl

common/src/main/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtils.java, common/src/test/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtilsTest.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/channel/ChannelManager.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, store/src/main/java/org/apache/rocketmq/store/queue/QueueOffsetAssigner.java
close #4999 
- Optimize ConcurrentMap#computeIfAbsent  performance on jdk1.8 a workaround
Optimization result reference #4999  JMH test
=> [ISSUE #4999]Optimize ConcurrentMap#computeIfAbsent  performance on jdk1.8 a workaround

controller/pom.xml, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerControllerStateMachine.java, pom.xml, store/pom.xml
Close #5056 
Bump DLedger to 0.3.0
Bump DLedger to 0.3.0
XXXX
=> [ISSUE #5056] Bump DLedger to 0.3.0

common/src/main/java/org/apache/rocketmq/common/protocol/ResponseCode.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java
close #5036 
- Optimize controller module Response code
XXXX
=> [ISSUE #5036]Optimize controller module Response code

example/src/main/java/org/apache/rocketmq/example/simple/Producer.java
close #4941 
-  Producer example add the default NamesrvAddr
XXXX
=> [ISSUE #4941] Producer example add the default NamesrvAddr

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
=> [ISSUE #5059] Remove redundant try&catch in RouteInfoManage

broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
Close #5063 
Polish the put message result process in SendMessageProcessor and EndTransactionProcessor
XX
XXXX
=> [ISSUE #5063] Polish the put message result process in SendMessageProcessor and EndTransactionProcessor

broker/src/main/java/org/apache/rocketmq/broker/processor/DefaultPullMessageResultHandler.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PullMessageProcessorTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
=> [ISSUE #5066] Fix only individual queues are consumed in high tps scenarios

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
=> [ISSUE #5070] Fix the problem of abnormal statistics under Bcq

pom.xml
Close #5081 
Bump DLedger to 0.3.1
XX
XXXX
=> [ISSUE #5081] Bump DLedger to 0.3.1

.licenserc.yaml, distribution/bin/mqbroker, distribution/bin/mqshutdown, distribution/conf/rmq-proxy.json, proxy/BUILD.bazel, proxy/src/main/java/org/apache/rocketmq/proxy/CommandLineArgument.java, proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/Configuration.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIFactory.java, proxy/src/test/java/org/apache/rocketmq/proxy/ProxyStartupTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/message/LocalMessageServiceTest.java, proxy/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, test/src/test/java/org/apache/rocketmq/test/grpc/v2/GrpcBaseIT.java
Nowadays, proxy can only be configured by configuration file, it is not convenient to use.
Proxy can config these parameters on the command line
- `-n` `--namesrvAddr`, the nameserver addr
- `-pc` `--proxyConfigPath`, the path of proxy config file
- `-pm` `--proxyMode`, proxy run in local or cluster mode
- `-bc` `--brokerConfigPath`, the path of broker config file when proxy run in local mode
Meanwhile, we can start local mode proxy with mqbroker like `sh bin/mqbroker -n 127.0.0.1:9876 -c /path/to/broker.properties --enable-proxy`, and shutdown by `sh bin/mqshutdown broker`
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the …
=> [ISSUE #5069] polish the startup of proxy; can specify parameters on the command line of proxy

WORKSPACE
=> Sync commons-lang3 version for Bazel

broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java
=> [ISSUE #5104] Clean property PROPERTY_TIMER_DELAY_MS if not timer message

broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
close #5047 
- Modify MessageStoreConfig attribute maxTopicLength default value
- remove duplicated code in HookUtils
XXXX
=> [ISSUE #5047]Modify MessageStoreConfig attribute maxTopicLength default value

distribution/conf/logback_broker.xml, distribution/conf/logback_namesrv.xml, remoting/pom.xml, remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/RemotingCodeDistributionHandler.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/RemotingCodeDistributionHandlerTest.java
[ISSUE #5095] [Remoting-A] Support logging rpc distribution in remoting protocol
=> [ISSUE #5095] [Remoting-A] Support logging rpc distribution in remoting protocol

acl/BUILD.bazel, acl/pom.xml, acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java, acl/src/test/java/org/apache/rocketmq/acl/plain/AclTestHelper.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessControlFlowTest.java
Fix https://github.com/apache/rocketmq/issues/5116
XX
XXXX
=> [ISSUE #5116]Make PlainAccessControlFlowTest portable

acl/BUILD.bazel, acl/src/test/java/org/apache/rocketmq/acl/plain/AclTestHelper.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java, acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java
Fix https://github.com/apache/rocketmq/issues/5119
Make the remaining test case hermetic and portable
XXXX
=> [ISSUE #5119]Infra enhancement project: Fix remaining test cases in ACL module

tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java
=> [ISSUE #5135] Format ERROR_MESSAGE string

tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
=> [ISSUE #5136]  remove unnecessary parameters

README.md
Update readme file rocketmq version
version: 4.9.3 - 4.9.4
Verifyed
=> [ISSUE #5130] Use the latest rocketmq version as example in readme file

common/src/main/java/org/apache/rocketmq/common/MixAll.java, docs/cn/README.md, namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/kvconfig/KVConfigManager.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHook.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
a  new PR  for   https://github.com/apache/rocketmq/pull/4635
=> [ISSUE #4634] fix code style in namesrv module

README.md
=> [ISSUE #5163] Update the description of readme about remoting-command based SDK

.github/workflows/stale.yml
=> Increase quantity of operation in Github Action of stale

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
=> [ISSUE #5177] Fix NPE in AclUtils#combineBytes

client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java, client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
=> [ISSUE #5179] Math.abs() method call redundant, judgment and repeated assignment  

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
close #5051 
- Remove GroupCommitService#run synchronized code chunk
XXXX
=> [ISSUE #5051]Remove GroupCommitService#run synchronized code chunk

README.md
=> [ISSUE #5191] Update badge

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivityTest.java
=> [ISSUE #5195] write data directly when there is no topicsList of publishing

.asf.yaml, .bazelrc, .github/workflows/bazel.yml
Fix https://github.com/apache/rocketmq/issues/5201
XX
XXXX
=> [ISSUE #5201]Use pull request to replace pull request target

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
=> [ISSUE #5152] Change the error log level to error

client/pom.xml, client/src/test/java/org/apache/rocketmq/client/ValidatorsTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMachineRoomNearByTest.java, client/src/test/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueConsitentHashTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyServiceTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImplTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/RebalanceLitePullImplTest.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImplTest.java, client/src/test/java/org/apache/rocketmq/client/producer/selector/SelectMessageQueueRetryTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
=> [ISSUE #5206] Enable checkstyle for test code （rocketmq-client）

common/pom.xml, common/src/test/java/org/apache/rocketmq/common/MixAllTest.java, common/src/test/java/org/apache/rocketmq/common/RegisterBrokerBodyTest.java, common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/ClusterInfoTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/GroupListTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/NamespaceUtilTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/QueryConsumeTimeSpanBodyTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/body/ConsumerRunningInfoTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/body/MessageRequestModeSerializeWrapperTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/body/QueryConsumeQueueResponseBodyTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/body/SubscriptionGroupWrapperTest.java, common/src/test/java/org/apache/rocketmq/common/protocol/topic/OffsetMovedEventTest.java, common/src/test/java/org/apache/rocketmq/common/sysflag/CompressionFlagTest.java, common/src/test/java/org/apache/rocketmq/common/topic/TopicValidatorTest.java, common/src/test/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtilsTest.java, common/src/test/java/org/apache/rocketmq/common/utils/IOTinyUtilsTest.java
=> [ISSUE #5212] Enable checkstyle for test code （rocketmq-common）

docs/cn/controller/quick_start.md
close #5210 
- Fix controller quick start document some command error
XXXX
=> [ISSUE #5210]Fix controller quick start document some command error

store/pom.xml, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueExtTest.java, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java, store/src/test/java/org/apache/rocketmq/store/MultiDispatchTest.java, store/src/test/java/org/apache/rocketmq/store/StoreStatsServiceTest.java, store/src/test/java/org/apache/rocketmq/store/StoreTestBase.java, store/src/test/java/org/apache/rocketmq/store/StoreTestUtil.java, store/src/test/java/org/apache/rocketmq/store/ha/HAClientTest.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java, store/src/test/java/org/apache/rocketmq/store/index/IndexFileTest.java, store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeMessageTest.java, store/src/test/java/org/apache/rocketmq/store/queue/QueueTestBase.java, store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerLogTest.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMetricsTest.java
=> [ISSUE #5221] Enable checkstyle for test code (rocketmq-store)

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java, store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueInterface.java
=> [ISSUE #5162] Fix bug about DefaultMessageStore maxFilterMessageCount calculating

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Fix the issue of incorrect tps statistics of the slave node under BCQ
Close #5238
Fix the issue of incorrect tps statistics of the slave node under BCQ
XXXX
=> [ISSUE #5238] Fix the issue of incorrect tps statistics of the slave node under BCQ

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
=> [ISSUE #4658] remove redundant logic

distribution/bin/runbroker.sh, distribution/bin/runserver.sh
=> [ISSUE #5020] Add find_java_home function to tool script

logging/pom.xml, logging/src/test/java/org/apache/rocketmq/logging/InnerLoggerFactoryTest.java, logging/src/test/java/org/apache/rocketmq/logging/inner/AppenderTest.java, logging/src/test/java/org/apache/rocketmq/logging/inner/LayoutTest.java, logging/src/test/java/org/apache/rocketmq/logging/inner/LevelTest.java, logging/src/test/java/org/apache/rocketmq/logging/inner/LoggerTest.java, logging/src/test/java/org/apache/rocketmq/logging/inner/MessageFormatterTest.java
=> [ISSUE #5205] Enable checkstyle for test code (rocketmq-logging)

client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
=> [ISSUE #5265] Adjust nested logic to reduce nums of check queryMsg

distribution/bin/mqbroker
=> [ISSUE #5267] fix command line arguments parse error in mqbroker

test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java, tools/src/main/java/org/apache/rocketmq/tools/command/controller/CleanControllerBrokerDataSubCommand.java
Fix the issue that AutoSwitchRoleIntegrationTest is flaky
Close #5274 
Fix the issue that AutoSwitchRoleIntegrationTest is flaky
XXXX
=> [ISSUE #5274] Fix the issue that AutoSwitchRoleIntegrationTest is flaky

distribution/bin/mqshutdown
=> [ISSUE #5270] exit with 1 when there is no process to shutdown

broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java, container/src/main/java/org/apache/rocketmq/container/BrokerContainerStartup.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java, remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyClientConfigTest.java
=> [ISSUE #5285] Support vm arguments to set useTLS value.

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
close #5278 
- Modify MessageStoreConfig#isTransientStorePoolEnable method comment document
XXXX
=> [ISSUE #5278]Modify MessageStoreConfig#isTransientStorePoolEnable method comment document

example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java
=> [ISSUE #5281]Unify the command line input parameters in all pressure testing programs

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/src/test/java/org/apache/rocketmq/container/BrokerContainerTest.java, controller/pom.xml, logging/pom.xml, namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/ClusterTestRequestProcessorTest.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java, pom.xml, proxy/pom.xml, remoting/pom.xml, store/pom.xml, test/pom.xml, tools/pom.xml
=> [ISSUE #5204] Enable checkstyle for test code (all module)

proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/route/ClusterTopicRouteServiceTest.java
=> [ISSUE #5305] fix proxy TopicRouteService cache bug

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
=> [ISSUE #5291] Optimize the NettyRemotingServer.

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
=> [5315]disable commit offset if not enable autocommit

common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/ClusterTestRequestProcessorTest.java
=> [ISSUE #5322] improving SDK topic route availability

docs/cn/BrokerContainer.md
Close #5339 
`该值只在quotaPercentForDiskPartition小于1时生效` should be `该值只在replicasPerDiskPartition大于1时生效`
XXXX
=> [ISSUE #5339] Fix BrokerContainer document error

WORKSPACE, common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java, pom.xml, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcConverter.java
Parse  DLQ information as message's system properties.
Upgrade rocketmq-proto version to 2.0.1, and adapt to parse DLQ information.
DLQ information passed to client as message's system properties.
=> Upgrade proto version to 2.0.1, and adapt to parse dlq information.

proxy/src/test/java/org/apache/rocketmq/proxy/processor/ConsumerProcessorTest.java
Add unit test for ConsumerProcessor
For lockBatchMQ method
=> Add unit test for ConsumerProcessor

WORKSPACE, controller/src/main/java/org/apache/rocketmq/controller/ControllerStartup.java, example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java, example/src/main/java/org/apache/rocketmq/example/operation/Consumer.java, example/src/main/java/org/apache/rocketmq/example/operation/Producer.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java, pom.xml, test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java, tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java, tools/src/main/java/org/apache/rocketmq/tools/command/queue/QueryConsumeQueueCommand.java, tools/src/test/java/org/apache/rocketmq/tools/command/acl/UpdateAccessConfigSubCommandTest.java
close #5324 
- Replace deprecated class PosixParser with DefaultParser for CLI
XXXX
=> [ISSUE #5324]Replace deprecated class PosixParser with DefaultParser for CLI

WORKSPACE
close #5370 
- Upgrade commons-cli version to 1.5.0 in WORKSPACE
XXXX
=> [ISSUE #5370]Upgrade commons-cli:commons-cli to 1.5.0

broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
Fix [#5376](https://github.com/apache/rocketmq/issues/5376)
XX
XXXX
=> [ISSUE #5376] Fix use of broker config timerMaxDelaySec

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
=> [ISSUE #5374]Fix unregister cause the new master removed.

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
Fixes apache/rocketmq#5372
remove unnecessary second call on fileWatchService's shutdown method
=> [ISSUE #5372] remove second call on fileWatchService's shutdown method

broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManagerTest.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/protocol/header/ExtraInfoUtil.java, common/src/test/java/org/apache/rocketmq/common/protocol/header/ExtraInfoUtilTest.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/main/java/org/apache/rocketmq/test/factory/ConsumerFactory.java, test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BasePop.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BasePopOrderly.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/ChangeInvisibleTimeMidMsgOrderlyIT.java
=> [ISSUE #5364] [RIP 51] Support changeInvisibleTime for pop orderly

dev/merge_rocketmq_pr.py
[ISSUE #5381 ] Optimize merge_rocketmq_pr.py comments in develop branch
Fixes #5381 
XX
XXXX
=> [ISSUE #5381]Optimize merge_rocketmq_pr.py comments in develop branch

test/src/test/java/org/apache/rocketmq/test/container/TransactionMessageIT.java
Fix #5393
Fix the issue that TransactionMessageIT can not pass CI
Fix the issue that TransactionMessageIT can not pass CI
=> [ISSUE #5393] Fix the issue that TransactionMessageIT can not pass CI

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/failover/EscapeBridgeTest.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BasePopNormally.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopBigMessageIT.java
=> [ISSUE #5402] not to decompress the messageBody when get retry messages in PopReviveService

store/BUILD.bazel, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java
Link #5331
https://github.com/apache/rocketmq/actions/runs/3311538539/jobs/5467110216
```
Tests in error: 
ConsumeQueueTest.testPutMessagePositionInfoMultiQueue:349 NullPointer
```
XX
XXXX
=> [ISSUE #5331]Fix ConsumeQueueTest stable sleep cause NPE.

broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/MessageQueueOpContext.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalOpBatchService.java, broker/src/test/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridgeTest.java, broker/src/test/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImplTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
RocketMQ Transaction Message Improvement Of Batch OP Message
doc:https://github.com/apache/rocketmq/wiki/RIP-50-RocketMQ-Transaction-Message-Improvement
Batch OP Message
XXXX
=> [ISSUE #5386][RIP-50]RocketMQ Transaction Message Improvement Of Batch OP Message

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
=> [ISSUE #5408] can skip ack when cannot find matching ck for a long time

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
=> [ISSUE #5310]Admin tool queryMessage signature check failed

tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java
fix #5426 
- Fix mqadmin updateTopic CLI result print format problem
XXXX
=> [ISSUE #5426] Fix mqadmin updateTopic CLI result print format problem

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java
close #5413 
- Modify AutoSwitchHAClient currentReceivedEpoch attribute long type to int
XXXX
=> [ISSUE #5413] Modify AutoSwitchHAClient currentReceivedEpoch attribute long type to int

broker/BUILD.bazel, broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsConstant.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/NopLongCounter.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/NopLongHistogram.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/NopLongUpDownCounter.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/NopObservableLongGauge.java, broker/src/main/java/org/apache/rocketmq/broker/processor/DefaultPullMessageResultHandler.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java, store/BUILD.bazel, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopBigMessageIT.java
=> implement broker stats metrics and request metrics

broker/src/test/java/org/apache/rocketmq/broker/filter/MessageStoreWithFilterTest.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java, remoting/src/test/java/org/apache/rocketmq/remoting/TlsTest.java, store/src/test/java/org/apache/rocketmq/store/ConsumeQueueTest.java, store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java, store/src/test/java/org/apache/rocketmq/store/dledger/MixCommitlogTest.java, store/src/test/java/org/apache/rocketmq/store/kv/CompactionLogTest.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
Fix https://github.com/apache/rocketmq/issues/5344
XX
XXXX
=> [ISSUE #5344] Fix Windows and Mac CI pipelines

.asf.yaml
Fix https://github.com/apache/rocketmq/issues/5458
XX
XXXX
=> [ISSUE #5458] Enable checks on Windows and MacOS

client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
Fix order consumer's lock issue when first start.
Add lock when the order consumer first start.
=> Fix order consumer's lock issue when first start

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java, store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
close #5446 
- Modify ScheduleMessageService's log name RocketmqStore to RocketmqBroker
XXXX
=> [ISSUE #5446]Modify ScheduleMessageService's log name RocketmqStore to RocketmqBroker

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, docs/cn/client/java/API_Reference_DefaultMQProducer.md
Fix error core-concept url. Link issue https://github.com/apache/rocketmq/issues/5358 .
Fix error core-concept url.
Fix error core-concept url.
=> [ISSUE #5358]Fix error core-concept url

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java
close #5482 
-  Remove ClientRequestProcessor#getRouteInfoByTopic method invalid logic judgment
XXXX
=> [ISSUE #5482] Remove ClientRequestProcessor#getRouteInfoByTopic method invalid logic judgment

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
=> Remove unnecessary retries in sendMessageBack

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsConstant.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerAttr.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/ProducerAttr.java
=> [ISSUE #5449] [RIP-46] add client connection and consume lag metrics

broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
Fix https://github.com/apache/rocketmq/issues/5509
XX
XXXX
=> [ISSUE #5509]Use Mockito to directly throw TimeoutException through set-up

common/src/main/java/org/apache/rocketmq/common/utils/NetworkUtil.java, common/src/test/java/org/apache/rocketmq/common/NetworkUtilTest.java
=> [ISSUE #5512] Skip the unnecessary network interfaces.

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/BrokerHousekeepingService.java
close #5499 
- Remove BrokerHousekeepingService unused static attribute log
XXXX
=> [ISSUE #5499]Remove BrokerHousekeepingService unused static attribute log

docs/cn/Example_CreateTopic.md, docs/en/Example_CreateTopic.md
=> [ISSUE #5506] Add create topic in docs

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java, proxy/src/main/java/org/apache/rocketmq/proxy/metrics/ProxyMetricsManager.java, proxy/src/test/java/org/apache/rocketmq/proxy/ProxyStartupTest.java
fix #5511 
- Fix Proxy start up throw NullPointerException
XXXX
=> [ISSUE #5511]Fix Proxy start up throw NullPointerException

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
closes https://github.com/apache/rocketmq/issues/5526
=> [ISSUE #5526] Fix : the topic attribute will be replace by null

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
fix the problem of issue https://github.com/apache/rocketmq/issues/5532
fix DefaultMQAdminExt setting socksProxy has no effect problem
XXXX
=> [ISSUE #5532] fix: DefaultMQAdminExt setting socksProxy has no effect

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
close #5157 
- Optimize AutoSwitchHAConnection HandShake's data protocol
XXXX
=> [ISSUE #5157]Optimize AutoSwitchHAConnection HandShake's data protocol

store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeQueueTest.java
Fix https://github.com/apache/rocketmq/issues/5534
XX
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklists (the last one is not necessary)before requesting the community to review your PR`.
=> [ISSUE #5534]Relax timeout of BatchConsumeQueueTest

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
close #5544 
- Replace DLedgerServer#getdLedgerLeaderElector deprecated method with DLedgerServer#getDLedgerLeaderElector 
XXXX
=> [ISSUE #5544]Replace DLedgerServer#getdLedgerLeaderElector deprecated method

proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java
Fix ConsumerProcessor lockBatchMQ future allOf data race issue
=> [ISSUE #5542] Fix ConsumerProcessor lockBatchMQ future allOf data race issue

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
close #5558
Fix typos in DLedgerController
XXXX
=> [Issue #5558] Fix typos in DLedgerController

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
=> [ISSUE #5560]Method parameters are passed in the wrong order

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerInfo.java
close #5572 
Remove useless introduction in BrokerInfo
XXXX
=> [Issue #5572]Remove useless introduction in BrokerInfo

broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #5448] optimize metrics in pop processor

common/src/main/java/org/apache/rocketmq/common/UtilAll.java
close #5576 
- Optimize UtilAll#getPid method
XXXX
=> [ISSUE #5576]Optimize UtilAll#getPid method

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Close #5577 
Optimize the build of sendMessageContext and avoid unnecessary repeated request parsing
XX
XXXX
=> [ISSUE #5577] Optimize the build of sendMessageContext and avoid unnecessary repeated request parsing

tools/src/main/java/org/apache/rocketmq/tools/command/offset/ResetOffsetByTimeOldCommand.java
=> [ISSUE #5562]Reset consumeOffset execution logic In a catch block，and is not executed under normal circumstances

test/src/main/java/org/apache/rocketmq/test/util/VerifyUtils.java, test/src/test/java/org/apache/rocketmq/test/delay/NormalMsgDelayIT.java
=> [ISSUE #5309] fix flaky test NormalMsgDelayIT

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/processor/SendMessageProcessorTest.java, common/src/main/java/org/apache/rocketmq/common/AbortProcessException.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
Close #5593 
Enable AbortProcessException to interrupt RPCHook
XX
XXXX
=> [ISSUE #5593] Enable AbortProcessException to interrupt RPCHook

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/controller/ReplicasManagerTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/UtilAll.java, controller/src/main/java/org/apache/rocketmq/controller/BrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/BrokerLiveInfo.java, controller/src/main/java/org/apache/rocketmq/controller/elect/impl/DefaultElectPolicy.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerControllerStateMachine.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DefaultBrokerHeartbeatManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java, pom.xml, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/controller/RegisterBrokerToControllerRequestHeader.java, tools/src/main/java/org/apache/rocketmq/tools/command/offset/ResetOffsetByTimeOldCommand.java
Tracking issue: #5585 
Upgrade dledger version
XXXX
=> [ISSUE #5585] Upgrade dledger version

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/MetadataManagerType.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/SnapshotAbleMetadataManager.java
Close #5585 
Add snapshotable metadata manager interface
XXXX
=> [ISSUE #5585]Add snapshotable metadata manager interface

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
close #5602 
- Remove useless log attribute from BrokerConfig
XXXX
=> [ISSUE #5602] Remove useless log attribute from BrokerConfig

controller/pom.xml
=> Fix dleger logging issue

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java, tools/src/main/java/org/apache/rocketmq/tools/admin/common/AdminToolsResultCodeEnum.java
#4487
add broadcast consumption judgment in examineConsumeStatsConcurrent method
XX
XXXX
=> [ISSUE #4487]The trackType is wrong when the consumer in broadcasting subscription.

store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java
fix TimerMessageStoreTest testTimerFlowControl  unit tests
=> Fix TimerMessageStoreTest testTimerFlowControl test

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
Close #5595 
Add validateSystemTopicWhenUpdateTopic
=> [ISSUE #5595] Add validateSystemTopicWhenUpdateTopic

broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
Fix https://github.com/apache/rocketmq/issues/5616
XX
XXXX
=> [ISSUE #5616] Fix POP checkpoint record accessor typo

distribution/release.xml
fix #5623 
- Fix can't load org.sfl4j.LoggerFactory when use mqnamesrv start
XXXX
=> [ISSUE #5623]Fix can't load org.sfl4j.LoggerFactory when use mqnamesrv start

store/BUILD.bazel
Fix https://github.com/apache/rocketmq/issues/5621
XX
XXXX
=> [ISSUE #5621] Bazel: Enable all tests in store module

WORKSPACE, broker/BUILD.bazel, namesrv/BUILD.bazel, test/BUILD.bazel
Fix https://github.com/apache/rocketmq/issues/5617
XX
XXXX
=> [ISSUE #5617] Fix Bazel warning & dependency

proxy/src/main/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIExt.java
Add else handle for notification
=> Add else handle for notification

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
Close #5634
Persist consumer offset should not be disabled when auto commit is turned off
Revert #5316
XX
XXXX
=> [ISSUE #5634] Persist consumer offset should not be disabled when auto commit is turned off

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java, test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
Close #5637 
Try to make AutoSwitchRoleIntegrationTest more stable
XX
XXXX
=> [ISSUE #5637] Try to make AutoSwitchRoleIntegrationTest more stable

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerInfo.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/SyncStateInfo.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/manager/ReplicasInfoManagerTest.java
Close #5585
Implement SnapshotAbleMetadataManager for ReplicasInfoManager
XXXX
=> [ISSUE #5585] Implement SnapshotAbleMetadataManager for ReplicasInfoManager #5601

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/statemachine/DLedgerControllerStateMachine.java, controller/src/main/java/org/apache/rocketmq/controller/impl/statemachine/StatemachineSnapshotFileGenerator.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/statemachine/StatemachineSnapshotFileGeneratorTest.java
[ISSUE #5585] 
Implement controller statemachine snapshot file generator
XXXX
=> [ISSUE #5585]  Implement controller statemachine snapshot file generator

client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullMessageService.java
close #5647
- Polish PullMessageService some methods parameter name
XXXX
=> [ISSUE #5647]Polish PullMessageService some methods parameter name

controller/src/main/java/org/apache/rocketmq/controller/impl/statemachine/DLedgerControllerStateMachine.java
close #5585 
Implement the snapshot interface in controller statemachine
XXXX
=> [ISSUE #5585] Implement statemachine snapshot interface

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/util/HookUtils.java, broker/src/test/java/org/apache/rocketmq/broker/util/HookUtilsTest.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java, common/src/main/java/org/apache/rocketmq/common/message/MessageExt.java, common/src/main/java/org/apache/rocketmq/common/message/MessageExtBatch.java, common/src/main/java/org/apache/rocketmq/common/message/MessageExtBrokerInner.java, common/src/main/java/org/apache/rocketmq/common/message/MessageVersion.java, common/src/test/java/org/apache/rocketmq/common/message/MessageDecoderTest.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalMessageService.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/MessageExtEncoder.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java, test/src/test/java/org/apache/rocketmq/test/retry/PopConsumerRetryIT.java
=> [ISSUE #5568] Support long length group and topic for pop mode consumption

broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java
Close #5644
Fix bug that make static topic ITs unable to pass
Fix bug that make static topic ITs unable to pass
XXXX
=> [ISSUE #5644] Fix bug that make static topic ITs unable to pass

proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java
=> [ISSUE #5583] fix test ReceiptHandleProcessorTest#testRenewReceiptHandleWhenTimeout

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopInflightMessageCounter.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopInflightMessageCounterTest.java
close #5654
calculate inflight messages for pop roughly
XX
XXXX
=> [ISSUE #5654] calculate inflight messages for pop

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerGroupInfo.java, broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerScannerTest.java, broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/ClusterServiceManager.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestSource.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/heartbeat/ConsumeType.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RequestSourceTest.java
=> [ISSUSE #5589] record subscription from request

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java
Fix #5651 
- Fix unable to send messages normally due to HA disconnection
XXXX
=> [ISSUE #5651]Fix unable to send messages normally due to HA disconnection

example/src/main/java/org/apache/rocketmq/example/schedule/TimerMessageConsumer.java, example/src/main/java/org/apache/rocketmq/example/schedule/TimerMessageProducer.java
close #5670 
- Add a note to the example of TimerMessage example
XXXX
=> [ISSUE #5670]Add a note to the example of TimerMessage example

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java
close #5668 
- Polish AutoSwitchHAClient and AutoSwitchHAConnection Comments
XXXX
=> [ISSUE #5668]Polish AutoSwitchHAClient and AutoSwitchHAConnection Comments

test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java, test/src/test/java/org/apache/rocketmq/test/offset/LagCalculationIT.java
=> [ISSUE #5660] optimize LagCalculationIT

controller/src/main/resources/rmq.controller.logback.xml, proxy/src/main/resources/rmq.proxy.logback.xml
close #5676 
- Support for dynamic Logging in proxy and controller modules
XXXX
=> [ISSUE #5676]Support for dynamic Logging in proxy and controller modules

distribution/bin/controller/fast-try-independent-deployment.cmd, distribution/bin/controller/fast-try-namesrv-plugin.cmd, distribution/bin/controller/fast-try.cmd, distribution/bin/runbroker.cmd, distribution/bin/runserver.cmd
close #5673 
- Add the windows platform script as the controller quick start
- Add the windows platform script as the controller independent deployment
- Add the windows platform script as the controller as namesrv plugin
XXXX
=> [ISSUE #5673]Add the windows platform script as the controller quick start

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
close #5686 
- Polish ReplicasInfoManager comment and static log attribute
XXXX
=> [ISSUE #5686]Polish ReplicasInfoManager comment and static log attribute

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/BrokerMemberGroup.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/controller/CleanControllerBrokerDataRequestHeader.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/controller/ElectMasterRequestHeader.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/controller/ElectMasterResponseHeader.java
close #5692 
- Polish Controller headers toString
XXXX
=> [ISSUE #5692]Polish Controller headers toString

common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
close #5585 
Add two dledger snapshot configs for controller
XXXX
=> [ISSUE #5585] Add two dledger snapshot configs for controller

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsConstant.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, store/src/main/java/org/apache/rocketmq/store/metrics/DefaultStoreMetricsConstant.java
=> [ISSUE #5701] [RIP-46] Introduce retry topic and lag estimation for lag calculation.

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/statemachine/DLedgerControllerStateMachine.java, controller/src/main/java/org/apache/rocketmq/controller/impl/statemachine/StatemachineSnapshotFileGenerator.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/controller/impl/DLedgerControllerTest.java
CLose #5585 
Add tests for controller snapshot
XXXX
=> [#ISSUE 5585] Add tests for controller snapshot

test/src/main/java/org/apache/rocketmq/test/util/VerifyUtils.java
=> [ISSUE #5726] verifyDelay should break the loop when matched the delayed message

docs/en/client/java/API_Reference_DefaultMQProducer.md
close #5730 
- Translate chinese to english in API_Reference_DefaultMQProducer.md document
XXXX
=> [ISSUE #5730]Translate chinese to english in API_Reference_DefaultMQProducer.md document

distribution/release.xml
close #5724 
- Add proxy module log xml to distribution directory
XXXX
=> [ISSUE #5724]Add proxy module log xml to distribution directory

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #5778] fix bug in compensateSubscribeData

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/LitePullConsumer.java
close https://github.com/apache/rocketmq/issues/5763
XX
XXXX
=> [ISSUE #5763] add the default subscribe * tag method

WORKSPACE, proxy/BUILD.bazel, store/src/test/java/org/apache/rocketmq/store/HATest.java
Signed-off-by: Li Zhanhui <lizhanhui@gmail.com>
Fix https://github.com/apache/rocketmq/issues/5783
XX
XXXX
=> [ISSUE #5783] Fix compilation warning

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
close #5780 
- Replace DLedgerServer's deprecated getdLedgerLeaderElector method with getDLedgerLeaderElector 
XXXX
=> [ISSUE #5780]Replace DLedgerServer's deprecated getdLedgerLeaderElector method with getDLedgerLeaderElector

docs/en/controller/deploy.md
close #5785 
- Translation controller deploy.md chinese document to english document
XXXX
=> [ISSUE #5785]Translation controller deploy.md chinese document to english document

WORKSPACE, pom.xml, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java, test/src/test/java/org/apache/rocketmq/test/grpc/v2/GrpcBaseIT.java
close #5787
Support long polling in rocketmq proxy in the protocol
=> Support long polling in rocketmq proxy in the protocol

docs/en/controller/deploy.md, docs/en/controller/quick_start.md
=> [ISSUE #5791]Fix controller deploy.md and quick_start.md link not correct

distribution/bin/mqadmin.cmd, distribution/bin/mqbroker.cmd, distribution/bin/mqcontroller.cmd, distribution/bin/mqnamesrv.cmd, distribution/bin/mqproxy.cmd
close #5741 
- Specifiy logback configuration file in cmd command line for windows platform
XXXX
=> [ISSUE #5741]Specifiy logback configuration file in cmd command line for windows platform

common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializable.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
close #5802 
- Optimize HashMap and HasSet invoke resize method
XXXX
=> [ISSUE #5802]Optimize HashMap and HashSet invoke resize method

store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
close #5809 
- Replace synchronized with ReentrantReadWriteLock in AutoSwitchHAService
XXXX
=> [ISSUE #5809]Replace synchronized with ReentrantReadWriteLock in AutoSwitchHAService

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #5813] Fix topic queue lock not unlock in pop consumption mode

docs/en/QuorumACK.md
Fix #5821 , remove unnecessary Chinese in QuorumACK.md document.
=> [ISSUE #5821] Remove unnecessary Chinese in QuorumACK.md document.

broker/src/test/java/org/apache/rocketmq/broker/longpolling/PullRequestHoldServiceTest.java
=> [ISSUE #5819] fix flaky test PullRequestHoldServiceTest

.asf.yaml
Remove bazel-compile from required status checks temporarily
Code cannot be merged due to the current failure of bazel-compile
Remove bazel-compile from required status checks temporarily
XXXX
=> Remove bazel-compile from required status checks temporarily

README.md
=> [ISSUE #5829] fix codecov url in README

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
close #5704 
- Optimize nameserver start when enableControllerInNamesrv of NamesrvConfig is false
XXXX
=> [ISSUE #5704]Optimize nameserver start when enableControllerInNamesrv of NamesrvConfig is false

broker/src/main/java/org/apache/rocketmq/broker/offset/BroadcastOffsetManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java, store/src/main/java/org/apache/rocketmq/store/SelectMappedBufferResult.java, store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java, store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java, store/src/main/java/org/apache/rocketmq/store/plugin/AbstractPluginMessageStore.java, store/src/test/java/org/apache/rocketmq/store/queue/BatchConsumeMessageTest.java
=> [ISSUE #5837] Deprecate MessageStore#checkInDiskByConsumeOffset

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java
=> [ISSUE #5839] Code.ILLEGAL_POLLING_TIME is not compatible with gRPC Client <=5.0.2

tools/src/main/java/org/apache/rocketmq/tools/command/broker/BrokerStatusSubCommand.java, tools/src/test/java/org/apache/rocketmq/tools/command/broker/BrokerStatusSubCommandTest.java
…meter is configured for the brokerStatus command.(#5817)
close #5816 
XX
XXXX
=> [ISSUE #5816] fix the issue that No response is returned when no parameter is configured for the brokerStatus command 

broker/src/main/java/org/apache/rocketmq/broker/processor/DefaultPullMessageResultHandler.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageBridge.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java, store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java
Close #5832 
Fix consumerCount increasing rapidly without sending message
XXXX
=> [ISSUE #5832] Fix consumerCount increasing rapidly without sending message

broker/src/main/java/org/apache/rocketmq/broker/longpolling/NotificationRequest.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
close #5847
Fix wake up in NotificationProcessor
=> [ISSUE #5847] Fix wake up in NotificationProcessor

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java
Remove unnecessary verification logic in consumerSendMsgBack method
Close #5868
Remove unnecessary verification logic in consumerSendMsgBack method
XXXX
=> [ISSUE #5869] Remove unnecessary verification logic in consumerSendMsgBack method

proxy/src/main/java/org/apache/rocketmq/proxy/service/ClusterServiceManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/transaction/ClusterTransactionService.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/transaction/ClusterTransactionServiceTest.java
=> [ISSUE #5862] remove offline producer group in Proxy

store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
close #5804 
- Optimize BrokerStatsManager#incTopicPutLatency create statsKey
XXXX
=> [ISSUE #5804]Optimize BrokerStatsManager#incTopicPutLatency create statsKey

common/src/main/java/org/apache/rocketmq/common/constant/LoggerName.java, namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java, style/rmq_checkstyle.xml
close #5708 
- Fix NamesrvStartup can't print config when use -p command
XXXX
=> [ISSUE #5708]Fix NamesrvStartup can't print config when use -p command

pom.xml, tieredstore/BUILD.bazel, tieredstore/pom.xml, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/common/TieredMessageStoreConfig.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/FileSegmentMetadata.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/QueueMetadata.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/TieredStoreMetadataManager.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/TieredStoreMetadataSerializeWrapper.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/TieredStoreMetadataStore.java, tieredstore/src/main/java/org/apache/rocketmq/store/tiered/metadata/TopicMetadata.java, tieredstore/src/test/java/org/apache/rocketmq/store/tiered/metadata/MetadataStoreTest.java
=> [ISSUE #5863] implement tiered store metadata

store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
Ignore testChangeRoleManyTimes in AutoSwitchHATest util it is stable
Ignore testChangeRoleManyTimes in AutoSwitchHATest util it is stable
XXXX
=> [ISSUE #5872] Ignore testChangeRoleManyTimes in AutoSwitchHATest util it is stable

common/src/main/java/org/apache/rocketmq/common/message/MessageClientIDSetter.java
=> [ISSUE #5880]Remove useless attribute TOPIC_KEY_SPLITTER in MessageClientIDSetter class

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
Support notify retry message and fix bugs in NotificationProcessor
* Fix hasMsg logic in NotificationProcessor
* Add notify in PopReviveService and order ack situation
* Refector wakeup logic
=> [ISSUE #5847] Refector logic in NotificationProcessor

common/src/main/java/org/apache/rocketmq/common/help/FAQUrl.java
close #5885 
- Fix FAQurl's class FAQ url incorrect
XXXX
=> [ISSUE #5885]Fix FAQurl's class FAQ url incorrect

container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java
=> [ISSUE #5897] Polish exception info when broker has already been added to broker container

container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java
=> [ISSUE #5900] Fix the problem of can not remove the broker successfully when a shutdown failure

broker/src/main/resources/rmq.broker.logback.xml, controller/src/main/resources/rmq.controller.logback.xml, proxy/src/main/resources/rmq.proxy.logback.xml, tools/src/main/resources/rmq.tools.logback.xml
=> [ISSUE #5902] Fix logback warning

common/src/main/java/org/apache/rocketmq/common/MixAll.java
=> [ISSUE #5905] fix config file disappear after vm crash

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
Close #5916 
Fix availableNamesrvAddrMap can not remove old nameserver address
Fix availableNamesrvAddrMap can not remove old nameserver address
XXXX
=> [ISSUE #5916] Fix availableNamesrvAddrMap can not remove old nameserver address

pom.xml
=> Update rocketmq-logging to 1.0.1

pom.xml
fix old version plugin bug, link: https://blogs.apache.org/maven/entry/apache-maven-assembly-plugin-version
=> Upgrade maven assembly plugin version to 3.4.2

common/src/main/java/org/apache/rocketmq/common/MixAll.java
=> [ISSUE #5961]refactor: simplify getPID

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
Fix lmqTopicQueueTable initialization
XX
XXXX
=> [ISSUE #5965] Fix lmqTopicQueueTable initialization

store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java, store/src/main/java/org/apache/rocketmq/store/queue/QueueOffsetAssigner.java
Fix lmqTopicQueueTable initialization
XX
XXXX
=> Fix lmqTopicQueueTable initialization

container/pom.xml, controller/pom.xml, pom.xml, store/pom.xml
Fixes #5890, Take over the logging of standard SLF4J and redirect it into the shaded SLF4J.
=> Fix dledger logging

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
#5860 
https://github.com/apache/rocketmq-dashboard/issues/137
XX
XXXX
=> [ISSUE #5860] set the value of order when create or update topic

common/src/main/java/org/apache/rocketmq/common/UtilAll.java
=> [ISSUE #5924]Optimize UtilAll#sleep method

controller/src/main/resources/rmq.controller.logback.xml
Make the internal logs related to the dledger in the controller print to a file separately
XX
XXXX
=> [ISSUE #5971] Make the internal logs related to the dledger in the controller print to a file separately

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
=> [ISSUE #5969] Remvoe duplicate deleteUnusedStats in admin processor

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java, example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java, store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java, store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java
=> [ISSUE #5942]Fix the produce count include the quantity of the system topic

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicQueueMappingUtils.java
Fix #5999 
- Fix the TopicQueueMappingUtils comments typo
XXXX
=> [ISSUE #5999]Fix the TopicQueueMappingUtils comments typo

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingSerializable.java
close #5996
optimize the RemotingSerializable class code
XXXX
=> [ISSUE #5996]optimize the RemotingSerializable class code

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/PopMetricsConstant.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/PopMetricsManager.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/PopReviveMessageType.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java, store/src/main/java/org/apache/rocketmq/store/metrics/DefaultStoreMetricsConstant.java, store/src/main/java/org/apache/rocketmq/store/metrics/DefaultStoreMetricsManager.java, store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsConstant.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManager.java
=> [ISSUE #5994] [RIP-46] add pop and timer metrics

broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopBufferMergeServiceTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopInflightMessageCounterTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java, store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java
=> [ISSUE #6012] change the type of queueId to int of PopCheckPoint

proxy/pom.xml, proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java
…tarts
Close https://github.com/apache/rocketmq/issues/5941
XX
XXXX
=> [ISSUE #5941] Fix the problem that acl is not loaded when the proxy starts

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
Remove more system topic for getUserTopicConfig api.
Remove more system topic for getUserTopicConfig api.
=> [ISSUE #5975] Fix getUserTopicConfig Impl contains system topic

namesrv/src/main/resources/rmq.namesrv.logback.xml
=> [ISSUE #6021] Fix nameserver logback configuration warning

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
=> [ISSUE #6010]refactor: avoid redundant condition judgment in loop

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
Remove useless if judgement
XXXXX
XX
XXXX
=> [ISSUE #6007]Remove useless if judgement

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
close #6019 
simplified the PlainAccessResource parse method
XXXX
=> [ISSUE #6019] simplified the PlainAccessResource parse method

common/src/main/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtils.java
=> [ISSUE #5907]optimize try catch to prevent ConcurrentHashMapUtils init failed

common/src/main/java/org/apache/rocketmq/common/help/FAQUrl.java
close #5979
- Fix FAQ url incorrect in FAQUrl class
XXXX
=> [ISSUE #5979]Fix FAQ url incorrect in FAQUrl class

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
close #6043
optimize the DefaultLitePullConsumerImpl isSetEqual method code
XXXX
=> [ISSUE #6043] optimize the DefaultLitePullConsumerImpl isSetEqual method code

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/RegisterBrokerBody.java
=> [ISSUE #6055]refactor: replace loop with `putAll` and typo fix

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
close  #6051 
remove redundant variable definitions
XXXX
=> [ISSUE  #6051] remove redundant variable definitions

.github/PULL_REQUEST_TEMPLATE.md
fix #6036 
- Optimize the PULL_REQUEST_TEMPLATE.md
XXXX
=> [ISSUE #6036]Optimize the PULL_REQUEST_TEMPLATE.md

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, test/src/test/java/org/apache/rocketmq/test/smoke/NormalMessageSendAndRecvIT.java
=> [ISSUE #5884] Concurrent check CommitLog messages

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Change MQVersion.CURRENT_VERSION to V5_0_1
=> [ISSUE #6030] Prepare to release Apache RocketMQ 5.0.1

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/OptionalSSLProtocolNegotiator.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProtocolProxyHandler.java
=> [ISSUE #6047] Support TLS permissive mode for 5.x client

README.md
fix #6069
- Fix README.md DLedger Controller link url incorrect
XXXX
=> [ISSUE #6069]Fix README.md DLedger Controller link url incorrect

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
=> [ISSUE #6030] Prepare to release Apache RocketMQ 5.1.0

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, remoting/src/main/java/org/apache/rocketmq/remoting/metrics/RemotingMetricsManager.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/TieredMessageStoreConfig.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/container/TieredContainerManager.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManager.java
=> Minor improvement for logs and metrics

test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleBase.java
close #6073
remove static reference
XXXX
=> [ISSUE #6073] remove static reference

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
close #6077 
fix issues that messageStore could be null
XXXX
=> [ISSUE #6077] fix issues that messageStore could be null

client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
close #6080
delete MQAdminImpl meaningless null check
XXXX
=> [ISSUE #6080] delete MQAdminImpl meaningless null check

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
close #6082 
simplify MQClientAPIImpl processSendResponse code
XXXX
=> [ISSUE #6082] simplify MQClientAPIImpl processSendResponse code

tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
changed a typo is thread not thead
Fix #6084
Changed a typo in DefaultMQAdminExtImpl
XX
XXXX
=> [ISSUE #6084] fixed a typo

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
fix #6085 
fix a typo in DLedgerController
XX
XXXX
=> [ISSUE #6085] Fix a typo

proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java
* Add proxyConfig enableAclRpcHookForClusterMode because not all the proxy needs to bring acl info
The default value is false.
=> [ISSUE #5941] Add proxyConfig enableAclRpcHookForClusterMode

NOTICE, acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
Merge the pre-release branch into develop.
* Release 5.1.0
* Update copyright
=> [ISSUE #6030] Merge the pre-release branch into develop

client/src/main/resources/rmq.client.logback.xml
=> [ISSUE #6103] Add AsyncAppender support for client logging

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
close #6101 
remove rebundant code
XXXX
=> [ISSUE #6101] remove rebundant code

test/src/test/java/org/apache/rocketmq/test/autoswitchrole/AutoSwitchRoleIntegrationTest.java
=> [ISSUE #6125] Ignore AutoSwitchRoleIntegrationTest temporarily because it is still flaky

controller/src/main/resources/rmq.controller.logback.xml
=> [ISSUE #6147] Detach RocketmqTraffic from controller_default log

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/RemotingCodeDistributionHandler.java
=> [ISSUE #6138] skip log empty remoting code distribution

.asf.yaml
=> [ISSUE #6138] Add back the protection of the master branch

acl/src/main/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyFactory.java, acl/src/test/java/org/apache/rocketmq/acl/common/PermissionTest.java, acl/src/test/java/org/apache/rocketmq/acl/plain/RemoteAddressStrategyTest.java
=> [ISSUE #6159] fix typos

.github/workflows/pr-e2e-test.yml, .github/workflows/push-ci.yml
=> [ISSUE #6161] Match apache actions policy, use apache/rocketmq-test-tool in workflow

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/RegisterBrokerBody.java
close #6057 
modify magic number code
XXXX
=> [ISSUE #6057] modify magic number code

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
fix #6117
- Optimize NettyRemotingServer EventLoopGroup create
XXXX
=> [ISSUE #6117]Optimize NettyRemotingServer EventLoopGroup create

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcConverter.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ProducerProcessor.java
=> [ISSUE #6192] Set a default value when UniqID is empty in Proxy

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java
close #6119 
replace ScheduleMessageService method reference
XXXX
=> [ISSUE #6119] replace ScheduleMessageService method reference

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
close #6131 
simplified ConsumeReviveObj code
XXXX
=> [ISSUE #6131] simplified ConsumeReviveObj code

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
close #6182
remove invalid null check code
XXXX
=> [ISSUE #6182] remove invalid null check code

README.md
add rocketmq-eventbridge to README.md
doc:add rocketmq-eventbridge to README.md
=> doc:add rocketmq-eventbridge to README.md

store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java
close #6246 
optimize AcceptSocketService#run
XXXX
=> [ISSUE #6246] optimize AcceptSocketService#run

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
1. fix wrong value of MessageStoreConfig#storePathEpochFile 
issue: https://github.com/apache/rocketmq/issues/6250
fix #<xxx> 
XX
XXXX
=> ISSUE[ #6250]: fix wrong value of MessageStoreConfig#storePathEpochFile

common/src/main/java/org/apache/rocketmq/common/message/MessageType.java
=> [ISSUE #6157] fix incompatibility between 4.x and 5.x in message trace

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcConverter.java
=> [ISSUE #6266] get MessageId from UNIQ_KEY firstly when build system message

WORKSPACE
=> [ISSUE #6280] Remove rbe_default digest check

README.md
fix #6133 
- Update the version information to 5.1.0 in README.md
XXXX
=> [ISSUE #6133]Update the version information to 5.1.0 in README.md

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java, store/src/main/java/org/apache/rocketmq/store/metrics/DefaultStoreMetricsManager.java
=> [ISSUE #6169] Fix NPE when timerWheel disabled

store/src/main/java/org/apache/rocketmq/store/TransientStorePool.java
=> [ISSUE #6283] Fix the bug that single replica cannot flush data when transientStorePoolEnable is true

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/RemotingProtocolServer.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/ConsumerManagerActivity.java
fix https://github.com/apache/rocketmq/issues/6294
add GET_CONSUMER_CONNECTION_LIST to proxy
=> Support proxy to get consumer connection list

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
fix #6302 
- Fix DefaultMQPushConsumerImpl code style
XXXX
=> [ISSUE #6302]Fix DefaultMQPushConsumerImpl code style

pom.xml
=> [ISSUE #6318] Upgrade dledger version to 0.3.1.1

proxy/src/main/java/org/apache/rocketmq/proxy/config/ConfigurationManager.java
=> [ISSUE #6311] Fixed the proxy configuration path null value problem

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
fix #6331 
- Optimlize DefaultMQPushConsumerImpl#subscribe method
XXXX
=> [ISSUE #6331]Optimlize DefaultMQPushConsumerImpl#subscribe method

proxy/src/test/java/org/apache/rocketmq/proxy/config/ConfigurationManagerTest.java
=> [ISSUE #6328] fix ConfigurationManagerTest

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
=> [ISSUE #6339] set message's flag in popRevive

store/src/main/java/org/apache/rocketmq/store/metrics/DefaultStoreMetricsManager.java
fix #6347
use mutable list to avoid start fail when enable tiered store
enable tiered store, and start up
=> [ISSUE #6347] fix: use mutable list to avoid start fail when enable tiered store

broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
fix ISSUE #6380 ,Optimize switch cases in BrokerOuterAPI.
Optimize switch cases in BrokerOuterAPI.
simplified the logic of processing response codes' switch cases.
=> [ISSUE #6380] Optimize switch cases in BrokerOuterAPI.

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
fix #6372
ew scheduledExecutor clean consume queue 
no
=> [ISSUE #6372] new scheduledExecutor clean consume queue

client/src/main/resources/rmq.client.logback.xml, distribution/benchmark/runclass.sh
=> [ISSUE #6365] fix no log in benchmark

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
Add break to the exception of WHEEL_TIMER_NOT_ENABLE.
fix #6390 
add a break into the switch.
=> [ISSUE #6390] Add break to the exception of WHEEL_TIMER_NOT_ENABLE.

distribution/bin/runbroker.sh, distribution/bin/runserver.sh, distribution/bin/tools.sh
=> [ISSUE #6026] Fix the problem that the custom JAVA_HOME environment variable does not take effect

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
fix #6396 
-Fix DefaultMQPushConsumer javadoc typo
XXXX
=> [ISSUE #6396]Fix DefaultMQPushConsumer javadoc typo

client/src/main/java/org/apache/rocketmq/client/hook/ConsumeMessageContext.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceContext.java, client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/ConsumeMessageTraceHookImpl.java, client/src/test/java/org/apache/rocketmq/client/trace/TraceDataEncoderTest.java
=> [ISSUE #4612] fix trace not complete

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/test/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManagerTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/BrokerReplicasInfo.java
GetSyncStateSet prints replica's alive status
fix ISSUE #6392 
print whether the broker is alive or not.
XXXX
=> [ISSUE #6392]GetSyncStateSet prints replica's alive status

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java, store/src/main/java/org/apache/rocketmq/store/index/IndexFile.java, store/src/main/java/org/apache/rocketmq/store/index/IndexHeader.java
1. add more visual comments
fix #6406  
XX
XXXX
=> [ISSUE #6406] Add more visual comments on `IndexFile` & `IndexHeader` & `ConsumeQueue`

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/BrokerReplicasInfo.java
fix ISSUE #6421 
1. Add the alive status into the constructor.
2. Make the name/set method/get method unified.
BrokerReplicasInfo.java
=> [ISSUE #6421]fix the encode bug.

broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageUtil.java, broker/src/test/java/org/apache/rocketmq/broker/processor/EndTransactionProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageUtilTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/ResponseCode.java
fix #6402 
opt transaction message check
If you specify a custom first check time CheckImmunityTimeInSeconds,And the commit/rollback request whose validity period exceeds CheckImmunityTimeInSeconds and is not checked back will be processed and failed
XXXX
=> [ISSUE #6402]opt transaction message check

common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java, controller/src/main/java/org/apache/rocketmq/controller/BrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/Controller.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/helper/BrokerLifecycleListener.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/heartbeat/DefaultBrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/BrokerReplicaInfo.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/manager/SyncStateInfo.java, controller/src/test/java/org/apache/rocketmq/controller/ControllerManagerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/DLedgerControllerTest.java, controller/src/test/java/org/apache/rocketmq/controller/impl/DefaultBrokerHeartbeatManagerTest.java
=> [ISSUE #6382] Periodically check for inactive masters

docs/cn/Example_Compaction_Topic_cn.md, docs/en/Example_Compaction_Topic.md, store/src/main/java/org/apache/rocketmq/store/kv/CompactionService.java, store/src/main/java/org/apache/rocketmq/store/kv/MessageFetcher.java
=> [ISSUE #6386] Some improvements for compactionTopic

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/MultiProtocolRemotingServer.java
=> [ISSUE #6438] Optimizing the memory usage of MultiProtocolRemotingServer

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/MultiProtocolRemotingServer.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/remoting/RemotingProtocolHandler.java
=> [ISSUE #6449] Fix NPE in MultiProtocolRemotingServer

broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
=> [ISSUE #6424] Make topicConfig updating atomically

proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ConfigurationManager.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java
=> [ISSUE #6399]When the proxy starts, the log displays the configuration details

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageFetcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/TieredStoreExecutor.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/container/TieredContainerManager.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/container/TieredIndexFile.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredDispatcherTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageFetcherTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageStoreTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/container/TieredContainerManagerTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegmentTest.java
=> [ISSUE #6454] Fix unsafe shutdown process in tiered storage

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
close #6459
Add rpc validatation for gRPC in PlainAccessResource
=> [ISSUE #6459] Add rpc validatation for gRPC in PlainAccessResource

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
fix #6400  
remove `BrokerConfig.maxDelayTime`
=> [ISSUE #6400] remove unnecessary config BrokerConfig.maxDelayTime

broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
fix #6466 
- Add ForbiddenType when Broker process PullMessage return no permission
XXXX
=> [ISSUE #6466]Add ForbiddenType when Broker process PullMessage return no permission

common/src/main/java/org/apache/rocketmq/common/ServiceThread.java
fix #6474 
- Optimize ServiceThread log print
XXXX
=> [ISSUE #6474]Optimize ServiceThread log print

example/src/main/java/org/apache/rocketmq/example/simple/PushConsumer.java
=> [ISSUE #6462] Optimize PushConsumer code and logic

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/MessageStore.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionStore.java, store/src/main/java/org/apache/rocketmq/store/plugin/AbstractPluginMessageStore.java, store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java
=> [ISSUE #6430] Scan topic.json to find compactionTopic and copy it

docs/cn/Example_Compaction_Topic_cn.md, docs/en/Example_Compaction_Topic.md
=> [ISSUE #6445] Fix the attribute of the compaction topic doc

store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java
=> [ISSUE #6478] fix outTPS in mqadmin when using compactionTopic

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java
=> [ISSUE #6484] Revert inappropriate modification

broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, common/src/main/java/org/apache/rocketmq/common/ServiceThread.java, common/src/test/java/org/apache/rocketmq/common/ServiceThreadTest.java
fix #6488 
- Use ServiceThread#shutdown to replace the deprecated ServiceThread#stop method
XXXX
=> [ISSUE #6488]Use ServiceThread#shutdown to replace the deprecated ServiceThread#stop method

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
=> [ISSUE #6263] use true address from channel

docs/cn/controller/deploy.md, docs/cn/controller/persistent_unique_broker_id.md
fix #6492
Polish persistent unique broker id document
XXXX
=> [ISSUE #6492] Polish persistent unique broker id document

broker/src/main/java/org/apache/rocketmq/broker/dledger/DLedgerRoleChangeHandler.java
fix #6501 
- Replace deprecated DLedgerServer#getdLedgerStore method
XXXX
=> [ISSUE #6501]Replace deprecated DLedgerServer#getdLedgerStore method

store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java
fix #6523 
- Schematic diagram of adding BatchConsumeQueue storage unit
XXXX
=> [ISSUE #6523]Schematic diagram of adding BatchConsumeQueue storage unit

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionService.java, store/src/main/java/org/apache/rocketmq/store/kv/CompactionStore.java
fix #6529 
XX
XXXX
1. change the compactionTopic dispatch process from asynchronous to synchronous
2. compactionTopic dispatch performance improvement
=> [ISSUE #6529] Some improvements for compactionTopic

common/src/main/java/org/apache/rocketmq/common/utils/NetworkUtil.java
bug:
broker ip addr(IPV4) get fail  after broker start up; fix:
add compare ,continue  when ip is start with '0.' ; like :
The broker[broker-a, 0.0.1.1:10911] boot success. serializeType=JSON and name server is 127.0.0.1:9876;
fix:
close https://github.com/apache/rocketmq/issues/6436
fix #<xxx> 
XX
XXXX
- [] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. …
=> [ISSUE #6436] Fix broker boot succes but get wrong ip address

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
close #6299 
remove TimerFlushService#run duplicate code
XXXX
=> [ISSUE #6299] remove TimerFlushService#run duplicate code

.asf.yaml, .github/workflows/maven.yaml
=> Upgrade the image to the latest version

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
Remove unnecessary code
XXXXX
XX
XXXX
=> [ISSUE #6001]Remove unnecessary code

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/channel/RemotingChannel.java
=> [ISSUE #6547] Some RemotingChannel calls need to be forwarded to the original Channel

.github/workflows/bazel.yml
Fixes https://github.com/apache/rocketmq/issues/6560
=> Update the image of bazel-build to ubuntu-latest

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
fix #6579 
Prevent the properties of trace message from exceeding the maximum value of short
XXXX
=> [ISSUE #6579] Prevent the properties of trace message from exceeding the maximum value of short

store/src/main/java/org/apache/rocketmq/store/AppendMessageCallback.java
=> [ISSUE #6584]Fix AppendMessageCallback comments typo

store/src/main/java/org/apache/rocketmq/store/queue/SparseConsumeQueue.java
=> [ISSUE #6587] fix getMax() in SparseConsumeQueue

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionChecker.java
=> [ISSUE #6594] skip verification when admin user

broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java
=> [ISSUE #6627] Fix ConsumerLagCalculator#processAllGroup retry topic NPE

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
=> [ISSUE #6660]: fix semaphoreAsyncSendSize init error

broker/src/main/java/org/apache/rocketmq/broker/processor/ClientManageProcessor.java
Fixes #6686 
- Remove ClientManageProcessor#heartBeat repeat judgment
=> [ISSUE #6686]Remove ClientManageProcessor#heartBeat repeat judgment

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java, store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java
Fixes #6665
1. Optimize the process of truncateInvalidMsgs()
2. Reset the confirmOffset while truncating.
3. Add more logs while expanding syncStateSet.
Using openchaos.
=> [ISSUE #6665]Optimize the process of truncateInvalidMsgs()

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
Fixes #6684 
removed the code which is not used.
modified the file.
=> [ISSUE #6684] Removed the Unused code and Update AclUtils.java

docs/cn/acl/RocketMQ_Multiple_ACL_Files_设计.md
=> [ISSUE #6693]Fix the description of the acl directory in the document is incorrect

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java, broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/RunningFlags.java, store/src/test/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHATest.java
=> [ISSUE #6706] brokerPermission cannot stop messages flow in unwritable brokers

pom.xml
=> [ISSUE #6701] bump opentelemetry version to 1.26.0

client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java
fix https://github.com/apache/rocketmq/issues/6516
=> [ISSUE #6516] Remove redundant code from ThreadLocalIndex

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #6785
Prepare to release version 4.9.6
=> [ISSUE #6758] Prepare to release version 4.9.6

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #6572
Prepare to release RocketMQ 5.1.1
=> [ISSUE #6752] Prepare to release RocketMQ 5.1.1

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare release rocketmq-all-5.1.1

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare for next development iteration

broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
Fixes #6771 
- Merge some cases in PullMessageProcessor#composeResponseHeader method
- add comments for method
=> [ISSUE #6771]Merge some cases in PullMessageProcessor#composeResponseHeader method

README.md
Fixes #6774 
- Update README.md rocketmq version to 5.1.1
=> [ISSUE #6774]Update README.md rocketmq version to 5.1.1

example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Consumer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java, example/src/main/java/org/apache/rocketmq/example/benchmark/TransactionProducer.java
Fixes #6803 
Add reportInterval option for benchmark script.
Optimize the 'sendTps' metric in the TransactionProducer script.
=> [ISSUE #6803] Benchmark support reportInterval option

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
=> [ISSUE #6819] Rename brokerHeartbeatExecutorService executorService name

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java, common/src/main/java/org/apache/rocketmq/common/UtilAll.java, common/src/main/java/org/apache/rocketmq/common/metrics/MetricsExporterType.java, common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java, controller/pom.xml, controller/src/main/java/org/apache/rocketmq/controller/BrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/ControllerManager.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, controller/src/main/java/org/apache/rocketmq/controller/impl/heartbeat/DefaultBrokerHeartbeatManager.java, controller/src/main/java/org/apache/rocketmq/controller/metrics/ControllerMetricsConstant.java, controller/src/main/java/org/apache/rocketmq/controller/metrics/ControllerMetricsManager.java, controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/metrics/ProxyMetricsManager.java
=> [ISSUE #6777]Support metric in controller

controller/BUILD.bazel
1. build controller with bazel
Fixes #6845
=> [ISSUE #6845] build controller with bazel

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java
=> Fix incorrect naming

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #6861 
Modify CURRENT_VERSION to 5.1.2
=> [ISSUE #6861] Modify CURRENT_VERSION to 5.1.2

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java, store/src/test/java/org/apache/rocketmq/store/DefaultMessageStoreTest.java
Change-Id: I1ebf4748c26c42efb058c11a8b5084b69213892c
Fixes #6800
=> [ISSUE #6800] fix: change the config variable isEnableBatchPush to enableBatchPush 

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
prepare to release Apache RocketMQ 5.1.2
=> [maven-release-plugin] prepare release rocketmq-all-5.1.2

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java
fix #6576
In `MQClientAPIImpl#processPopResponse`, check if popping LMQ message, and construct `sortMap` and `queueIdKey`, `queueOffsetKey`, `index` using LMQ message properties.
=> [ISSUE #6576] Fix pop lmq message

filter/src/main/java/org/apache/rocketmq/filter/expression/ComparisonExpression.java, filter/src/main/java/org/apache/rocketmq/filter/parser/ParseException.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.jj, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParserConstants.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParserTokenManager.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SimpleCharStream.java, filter/src/main/java/org/apache/rocketmq/filter/parser/Token.java, filter/src/main/java/org/apache/rocketmq/filter/parser/TokenMgrError.java, filter/src/test/java/org/apache/rocketmq/filter/ExpressionTest.java, filter/src/test/java/org/apache/rocketmq/filter/ParserTest.java
Fixes #6863
For a long time, Alibaba Group has used SQL CONTAINS expressions internally to support complex business filtering logic.
Now we plan to introduce this feature into open source.
The newly added code is covered by a large number of unit tests, and we have also conducted end-to-end testing to ensure everything works fine.
=> [ISSUE #6863] SQL expression CONTAINS support

tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageFetcherTest.java
Fixes #6929
Temporarily ignoring testQueryMessageAsync testing on the Linux platform
=> [ISSUE#6929] Temporarily ignoring testQueryMessageAsync testing on the Linux platform

filter/src/main/java/org/apache/rocketmq/filter/expression/ComparisonExpression.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.jj, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParserConstants.java, filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParserTokenManager.java, filter/src/test/java/org/apache/rocketmq/filter/ExpressionTest.java
=> [ISSUE #6916] support startsWith and endsWith in sql filter.

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #6935 
Prepare to release Apache RocketMQ 5.1.3
=> [ISSUE #6935] Prepare to release Apache RocketMQ 5.1.3

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/doc.yml, .github/ISSUE_TEMPLATE/enhancement_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Fixes #6945
- Add doc issue template
=> [ISSUE #6945] Add doc issue template

common/src/main/java/org/apache/rocketmq/common/state/StateEventListener.java, proxy/src/main/java/org/apache/rocketmq/proxy/RenewTask.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/RenewEvent.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/DefaultGrpcMessingActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/MessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/receipt/ReceiptHandleManager.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ChangeInvisibleDurationActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/producer/ForwardMessageToDLQActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ConsumerProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/receipt/ReceiptHandleManagerTest.java
Fixes #6974
Abstract the state of ReceiptProcessor into ReceiptHandleManager
unit test
=> [ISSUE #6974] Feature/refector receipt processor

store/src/main/java/org/apache/rocketmq/store/timer/Slot.java
Fixes #6960 
- Added Slot formatting sketch comments
=> [ISSUE #6960]Added Slot formatting sketch comments

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java
fix receive message activity attempt id not correct
=> fix receive message activity attempt id not correct

client/src/main/java/org/apache/rocketmq/client/impl/MQClientManager.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/producer/MQProducer.java, client/src/main/java/org/apache/rocketmq/client/producer/ProduceAccumulator.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java, client/src/test/java/org/apache/rocketmq/client/producer/ProduceAccumulatorTest.java, common/src/main/java/org/apache/rocketmq/common/message/MessageBatch.java
#3717 
Realize the autobatch function in the producer.
=> [ISSUE #3717][RIP-27] Auto batching in producer

client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIFactory.java
Fixes #7068
Fix failed to create syncer topic when the proxy was just started。
=> [ISSUE #7068] Fix failed to create syncer topic when the proxy was just started

broker/src/main/java/org/apache/rocketmq/broker/filter/ExpressionForRetryMessageFilter.java
Fixes #7039 
return true directly when the subscription type is TAG
=> [ISSUE #7039] fix: fix retry message filter when subtype is TAG

common/src/main/java/org/apache/rocketmq/common/constant/PermName.java
Fixes #7102
Making perm equal to 0 is valid
=> [ISSUE #7102] Making perm equal to 0 is valid

docs/cn/operation.md
=> [ISSUE #6962]operation.md Format adjustment

srvutil/src/main/java/org/apache/rocketmq/srvutil/ServerUtil.java
=> [Feature 7155] add errlog when cmd err

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
Fixes #7176, correct mismatched logs.
=> [ISSUE #7176] Correct mismatched logs

tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java
=> [ISSUE #7192] Correct typos

broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BasePopNormally.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/BatchAckIT.java
=> [ISSUE #7205] support batch ack for pop orderly

broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
Fixes #7124 
- Fix the typos in the code comments
=> [ISSUE #7124] Fix the typos in the code comments

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java, store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java, store/src/main/java/org/apache/rocketmq/store/MultiPathMappedFileQueue.java
=> [ISSUE #7228] Converge the use of some important variables for some class

client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExt.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/AbstractProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/BatchAckResult.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/MessagingProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/ClusterMessageService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalMessageService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/MessageService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/message/ReceiptHandleMessage.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/BaseProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ConsumerProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/mqclient/MQClientAPIExtTest.java
=> [ISSUE #7223] Support batch ack for grpc client in proxy

tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java
=> [ISSUE #7250] Beautify command rocksDBConfigToJson output

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageFetcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredFileSegment.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredStoreProvider.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/stream/CommitLogInputStream.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/stream/FileSegmentInputStream.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/stream/FileSegmentInputStreamFactory.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageStoreTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredFlatFileTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredIndexFileTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/MockFileSegmentInputStream.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/TieredFileSegmentInputStreamTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/TieredFileSegmentTest.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/memory/MemoryFileSegment.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/memory/MemoryFileSegmentWithoutCheck.java
=> [ISSUE#7280] Fix and refactor handle commit exception in tiered storage

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
=> [ISSUE #7289] Fixed asynchronous send backpressure capability

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFileManager.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicBlackListFilter.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicFilter.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicBlackListFilterTest.java
=> [ISSUE #7308] Adding topic blacklist and filter in tiered storage module

controller/src/main/java/org/apache/rocketmq/controller/impl/manager/ReplicasInfoManager.java
Fixes #7293
Fix NPE when alter sync state set
=> [ISSUE #7293] Fix NPE when alter sync state set

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultTolerance.java, client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java, client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/MessageQueueView.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java
=> [ISSUE #7319] Optimize fault-tolerant mechanism for sending messages and hot update switch

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
=> [ISSUE #7343] Rollback modifications to registerProcessor

.bazelrc, test/src/test/java/org/apache/rocketmq/test/route/CreateAndUpdateTopicIT.java
Set experimental_ui_max_stdouterr_bytes to 10MB in bazel
=> Set experimental_ui_max_stdouterr_bytes to 10MB in bazel

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
=> [ISSUE #7351] Allow mqadmin to operate slave nodes

WORKSPACE, broker/BUILD.bazel, broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java, broker/src/main/resources/rmq.broker.logback.xml, common/BUILD.bazel, common/pom.xml, controller/BUILD.bazel, controller/src/main/java/org/apache/rocketmq/controller/metrics/ControllerMetricsManager.java, pom.xml, proxy/BUILD.bazel, proxy/src/main/java/org/apache/rocketmq/proxy/metrics/ProxyMetricsManager.java, proxy/src/main/resources/rmq.proxy.logback.xml, tieredstore/BUILD.bazel
Replace loggingMetricExporter with OtlpJsonLoggingMetricExporter.
=> Replace loggingMetricExporter with OtlpJsonLoggingMetricExporter.

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare release rocketmq-all-5.1.4

store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java
=> [ISSUE #7389] Fix the problem that getLastMappedFile function affects performance

proxy/src/main/java/org/apache/rocketmq/proxy/ProxyStartup.java, proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServer.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java
=> [ISSUE #7393] Add timeout configuration for grpc server

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
=> [ISSUE #7400] Fix getBrokerEpochSubCommand NPE

proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncer.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncerTest.java
=> [ISSUE #7429] clean channel map when CLIENT_UNREGISTER in proxy

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
=> [ISSUE #7412] Fix pop revive message error when the checkpoint is a reput one

controller/src/test/java/org/apache/rocketmq/controller/impl/DLedgerControllerTest.java
Fixes #7431
Fix flaky test of DLedgerControllerTest#testBrokerLifecycleListener
=> [ISSUE #7431] Fix flaky test of DLedgerControllerTest#testBrokerLifecycleListener

README.md
Fixes #7433 
- Update the version in the README.md document to 5.1.4
=> [ISSUE #7433]Update the version in the README.md document to 5.1.4

broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #7453] Fix the problem in constructing the GetMessageResult

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Fixes #7505
Do not validate the length when deleting a topic
=> [ISSUE #7505] Do not validate the length when deleting a topic

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
=> [ISSUE #7501] The broker supports idempotence in creating topics

store/src/main/java/org/apache/rocketmq/store/RunningFlags.java
=> [ISSUE #7574] Fix RunningFlags conflict

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
=> [ISSUE #7579]Fix globalWhiteRemoteAddressStrategy cocurrent bug

store/src/test/java/org/apache/rocketmq/store/HATest.java
=> [ISSUE #7627] Fix flaky test testSemiSyncReplicaWhenAdaptiveDegradation

pom.xml
=> [ISSUE #7636] Bump snakeyaml from 1.32 to 2.0

pom.xml
=> [ISSUE #7637] Bump grpc from 1.50.0 to 1.53.0

client/src/main/java/org/apache/rocketmq/client/consumer/store/ControllableOffset.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/OffsetStore.java, client/src/main/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStore.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullMessageService.java, client/src/test/java/org/apache/rocketmq/client/consumer/store/RemoteBrokerOffsetStoreTest.java
Fixes #7634
Introduce ControllableOffset to remove the unnecessary suspension for OFFSET_ILLEGAL.
unit test
=> [ISSUE #7634] Introduce controllableOffset to prevent unnecessary suspension when OFFSET_ILLEGAL

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java, pom.xml
[4.9.x]Bump snakeyaml version from 1.32 to 2.0
=> [4.9.x]Bump snakeyaml version from 1.32 to 2.0

common/src/main/java/org/apache/rocketmq/common/MixAll.java
=> [ISSUE #7659]Trim property

proxy/src/main/java/org/apache/rocketmq/proxy/common/ProxyContext.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/context/ContextNode.java, proxy/src/main/java/org/apache/rocketmq/proxy/common/context/ContextVariable.java, proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/GrpcMessagingApplication.java, proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java, proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/AbstractRemotingActivity.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/relay/ProxyChannel.java, proxy/src/test/java/org/apache/rocketmq/proxy/ContextNodeTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/common/ProxyContextTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/BaseActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/channel/GrpcClientChannelTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManagerTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/message/LocalMessageServiceTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/mqclient/ProxyClientRemotingProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManagerTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/sysmessage/HeartbeatSyncerTest.java
Fixes #7707
Refector ProxyContext with link node implementation
Unit test
=> [ISSUE #7707] Refector Context with link node implementation

broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java, broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOrderInfoManager.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java, client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java, common/src/main/java/org/apache/rocketmq/common/consumer/ReceiptHandle.java, common/src/test/java/org/apache/rocketmq/common/KeyBuilderTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ConsumerProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/processor/ProducerProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/message/LocalMessageServiceTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ExtraInfoUtil.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/header/ExtraInfoUtilTest.java, test/src/test/java/org/apache/rocketmq/test/container/PopSlaveActingMasterIT.java
Fixes #7543
Add enableRetryTopicV2 brokerConfig
Unit test
=> [ISSUE #7543] Add enableRetryTopicV2 brokerConfig

broker/src/main/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManager.java
=> [ISSUE #7658] Fix bug of  timer message metrics with setDelayTimeMs

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java
Fixes #7747 
- Simplify code checks using Optional in ClientRequestProcessor#getRouteInfoByTopic method
=> [ISSUE #7747]Simplify code checks using Optional in ClientRequestProcessor#getRouteInfoByTopic method

broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExt.java, client/src/main/java/org/apache/rocketmq/client/rpchook/NamespaceRpcHook.java, client/src/test/java/org/apache/rocketmq/client/rpchook/NamespaceRpcHookTest.java, common/src/main/java/org/apache/rocketmq/common/MixAll.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/LockBatchMqRequestHeader.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/UnlockBatchMqRequestHeader.java
Fixes #7699
Refector NamespaceRpcHook
=> [ISSUE #7699] Refector NamespaceRpcHook

client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java, client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java
Fixes #7713
fix: MQFaultStrategy check queue if writable, and do not change MessageQueue itself
depends on these test case
=> [ISSUE #7713] MQFaultStrategy check queue if writable

test/src/test/java/org/apache/rocketmq/test/offset/LagCalculationIT.java
Fixes #7765
each broker controller init subscriptionData & consumerFilterData  for  ExpressionMessageFilter
i have test it local
=> [ISSUE #7765] Fix unit test testEstimateLag

NOTICE
=> Update copyright year to 2024

client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java
=> [ISSUE #7812] Remove reachable flag in brokers' available judgement.

client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java, client/src/test/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStoreTest.java
Fixes #7740
Cherry pick #7745 from 4.9.x
=> [ISSUE #7740] Optimize LocalFileOffsetStore

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #7795
Prepare to release apache rocketmq 4.9.8
=> [ISSUE #7795] Prepare to release apache rocketmq 4.9.8

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
Fixes #7793
More than three months have passed since the release of the last version 5.1.4. During this period, a large number of issues have been fixed to improve stability. In addition, important features such as support for million-level queues and jraft support for the controller have also been integrated into the trunk. Therefore, we are in the process of preparing to release Apache RocketMQ 5.2.0
=> [ISSUE #7793] Prepare to release apache rocketmq 5.2.0

acl/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare release rocketmq-all-5.2.0

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java, remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
=> [ISSUE #7833] Fix invokeImpl() in RemotingAbstract

README.md
Fixes #7840 
- Update the version in the README.md document to 5.2.0
=> [ISSUE #7840]Update the version in the README.md document to 5.2.0

acl/pom.xml, broker/pom.xml, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, client/pom.xml, common/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, logging/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tools/pom.xml
Promptly return a response when the validation parameters cannot be modified
Promptly return a response when the validation parameters cannot be modified
=> [4.9.x] Promptly return a response when the validation parameters cannot be modified

proxy/src/main/java/org/apache/rocketmq/proxy/service/route/ClusterTopicRouteService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/LocalTopicRouteService.java, proxy/src/main/java/org/apache/rocketmq/proxy/service/route/ProxyTopicRouteData.java
Fixes #7875
Add constructor for ProxyTopicRouteData
=> [ISSUE #7875] Add constructor for ProxyTopicRouteData

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/SendMessageRequestHeader.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/SendMessageRequestHeaderV2.java
Fixes #7871
Fix unboxing npe in SendMessageRequestHeader
=> [ISSUE #7871] Fix unboxing npe in SendMessageRequestHeader

docs/cn/controller/deploy.md
Fixes #7881
Add parameter configuration explanations for jRaft controller
=> [ISSUE #7881] Add parameter configuration explanations for jRaft controller

docs/cn/Debug_In_Idea.md, docs/en/Debug_In_Idea.md
avoid confusion
no code change
=> fix document typo

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java
Fixes #7923
exclude the master that are currently down.
=> [ISSUE #7923] Exclude the master that are currently down.

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
Fixes #7988
Set enableTrace default to false
=> [ISSUE #7988] Set enableTrace default to false

README.md
Fixes [#8020](https://github.com/apache/rocketmq/issues/8020)
fix document(README) typo
=> [ISSUE #8020] fix document typo

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
=> [ISSUE #8032] Set checkDupInfo value from config

client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
=> [ISSUE#6398] Remove duplicate code in TopicPublishInfo

store/src/main/java/org/apache/rocketmq/store/AllocateMappedFileService.java
Fixes #8044 
- Add Override annotation for AllocateMappedFileService#run
=> [ISSUE #8044]Add Override annotation for AllocateMappedFileService#run

BUILD.bazel, WORKSPACE, broker/BUILD.bazel, client/BUILD.bazel, client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java, client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java, pom.xml, proxy/src/test/java/org/apache/rocketmq/proxy/service/mqclient/ProxyClientRemotingProcessorTest.java, proxy/src/test/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManagerTest.java
=> [ISSUE #8095] Fix some flaky tests on Mac's workflow

client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java, client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopOrderlyService.java, client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java, common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItem.java, controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java, test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopConsumer.java, test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java, test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java, test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopSubCheckIT.java
Fixes #8096
use `{}` to replace `%s` `%d`
=> [ISSUE #8096] fix log placeholder

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
=> [ISSUE #8105] fix typo about udpate user

tieredstore/README.md
=> [ISSUE #5923] Fix tiered store README.md error about Configuration

auth/src/main/java/org/apache/rocketmq/auth/authentication/manager/AuthenticationMetadataManagerImpl.java
=> [ISSUE #8108] Fix check MetadataProvider when enable acl2.0

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/DefaultMetadataStore.java
Fixes #8049 
xxx
Create a topic and delete it without production.
=> [ISSUE #8049] Fix tiered storage delete topic NPE in default metadata store

tieredstore/README.md
=> [ISSUE #5923] Fix tiered store README.md error

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java
Fixes #8124 
avoid scheduled tasks exiting because of unknown exceptions
=> [ISSUE #8124] Avoid scheduled tasks exiting because of unknown exceptions

client/src/test/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExtTest.java
=> [ISSUE #8079] Add unit test for MQClientAPIExtTest

docs/cn/BrokerContainer.md
=> [ISSUE #8155] Fix doc typo

common/src/main/java/org/apache/rocketmq/common/ConfigManager.java
=> [ISSUE #8162]Optimize the logging printout for the ConfigManager#loadBak method

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
=> [ISSUE #8222] Fix spelling errors in comments

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
=> [ISSUE #8241] Remove duplicate code

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImplTest.java
=> [ISSUE #8197] Support fast filter message by tag in tiered storage

tools/src/test/java/org/apache/rocketmq/tools/command/topic/UpdateTopicListSubCommandTest.java
=> [ISSUE #8278]fix fail test

container/src/test/java/org/apache/rocketmq/container/BrokerPreOnlineServiceTest.java
=> [ISSUE #8285] Add more test coverage for BrokerPreOnlineService

client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
=> [ISSUE #8276] Merge duplicate code in DefaultMQProducer constructor

test/src/main/java/org/apache/rocketmq/test/util/data/collect/impl/ListDataCollectorImpl.java, test/src/main/java/org/apache/rocketmq/test/util/data/collect/impl/MapDataCollectorImpl.java
=> [ISSUE #7941]Increase annotation

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java, client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java, client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java, client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java
=> [ISSUE #7988] merge "Refector client trace" to 4.9.x

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java, srvutil/src/main/java/org/apache/rocketmq/srvutil/AclFileWatchService.java
=> [ISSUE #8274] Optimize some codestyles and fix some warnings

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
=> [ISSUE #8377] Prepare to release Apache RocketMQ 5.3.0

client/src/main/java/org/apache/rocketmq/client/trace/TraceConstants.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/EndTransactionOpenTracingHookImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageOpenTracingHookImpl.java, client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java
=> [ISSUE #8396] Fix typo in TraceConstants

namesrv/src/main/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHook.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHookTest.java, namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java
=> [ISSUE #8345] add some tests for nameserver

client/src/test/java/org/apache/rocketmq/client/impl/consumer/ProcessQueueTest.java
=> [ISSUE #8458] Add more test coverage for ProcessQueue

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
=> [ISSUE #8472] Fix pop message delay due to not notify message arriving after suspend

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
=> [ISSUE #8490] Fix getMaxReconsumeTimes calculation error in concurrent consumption mode

client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopOrderlyServiceTest.java
=> [ISSUE #8496] Add more test coverage for ConsumeMessagePopOrderlyService

common/src/test/java/org/apache/rocketmq/common/compression/CompressionTypeTest.java
=> [ISSUE #8514] Fix bazel-compile (ubuntu-latest) ci run failure

client/src/test/java/org/apache/rocketmq/client/impl/consumer/PullAPIWrapperTest.java
=> [ISSUE #8517] Add more test coverage for PullAPIWrapper

client/src/test/java/org/apache/rocketmq/client/impl/consumer/PullMessageServiceTest.java
=> [ISSUE #8517] Add more test coverage for PullMessageService

client/src/test/java/org/apache/rocketmq/client/consumer/store/ControllableOffsetTest.java
=> [ISSUE #8547]  Add more test cases of ControllableOffset

auth/src/test/java/org/apache/rocketmq/auth/migration/AuthMigratorTest.java
=> [ISSUE #8551] Add more test coverage for AuthMigrator

auth/src/test/java/org/apache/rocketmq/auth/authorization/strategy/StatefulAuthorizationStrategyTest.java, auth/src/test/java/org/apache/rocketmq/auth/migration/AuthMigratorTest.java
=> [ISSUE #8562] Add more test coverage for StatefulAuthorizationStrategy

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java, client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
=> fix missing brokerName in sendMessageBack request

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java, broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerTest.java
=> [ISSUE #8483] Optimize unnecessary broker reverse notification (notifyConsumerIdsChanged) in broadcast mode

broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
=> fix producer groupChannelTable memory leak

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java
[ISSUE #8688] fix typo, release the write lock in forceUpload()
=> [ISSUE #8688] fix typo, release the write lock in forceUpload()

.github/workflows/pr-ci.yml, .github/workflows/pr-e2e-test.yml, .github/workflows/push-ci.yml, .github/workflows/snapshot-automation.yml
=> [ISSUE #8691] Fix PR-CI errors

store/src/main/java/org/apache/rocketmq/store/CommitLog.java, store/src/main/java/org/apache/rocketmq/store/MessageExtEncoder.java
=> [ISSUE #8693] Fix checking MultiDispatchMessage when appending commitlog

test/src/test/java/org/apache/rocketmq/test/base/BaseConf.java
=> Fix typo in BaseConf

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIFactory.java, common/src/main/java/org/apache/rocketmq/common/utils/AsyncShutdownHelper.java
=> [ISSUE #8705] Make MQClientAPIFactory shutdown async

.github/workflows/push-ci.yml
=> Update performance benchmark test tool

controller/src/main/java/org/apache/rocketmq/controller/impl/DLedgerController.java
=> [ISSUE #8769] Fix doc typo

broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java, openmessaging/src/main/java/io/openmessaging/rocketmq/promise/DefaultPromise.java, store/src/main/java/org/apache/rocketmq/store/AllocateMappedFileService.java, store/src/main/java/org/apache/rocketmq/store/util/PerfCounter.java
=> [ISSUE #8782] Fix log typo

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java, client/src/main/java/org/apache/rocketmq/client/consumer/PopStatus.java, common/src/main/java/org/apache/rocketmq/common/utils/ServiceProvider.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/ForbiddenType.java
=> [ISSUE #8786] Fix doc typo

broker/src/test/java/org/apache/rocketmq/broker/longpolling/PopLongPollingServiceTest.java
=> [ISSUE #8796] Add more test coverage for PopLongPollingService

broker/src/main/java/org/apache/rocketmq/broker/controller/ReplicasManager.java
=> [ISSUE #8816] Fix log typo.

remoting/src/main/java/org/apache/rocketmq/remoting/rpc/RpcClientImpl.java
=> [ISSUE #8824] Fix IllegalStateException caused by logical errors

broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
=> fix: remove unnecessary synchronized to improve concurrency

pom.xml
Fixes #8833
update netty-all version to fix CVE-2023-34462
=> [ISSUE #8833] Update netty-all version to 4.1.114 to fix CVE-2023-34462

pom.xml
Fixes #8833 
Fix CVE-2023-34462 and CVE-2024-29025
=> [ISSUE #8833] Update netty version to 4.1.114 to fix CVE-2023-34462

.github/workflows/coverage.yml, .github/workflows/integration-test.yml, .github/workflows/maven.yaml, .github/workflows/snapshot-automation.yml, store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueOffsetTable.java, store/src/test/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueOffsetTableTest.java
verifying forEach works properly for long topic-name
To #8829
=> [ISSUE #8829]feat: add test case to RocksDBConsumeQueueOffsetTable

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java, remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializableTest.java
This reverts commit 327abe5d6eb0b74f48867821447e2f0718509a42.
=> Revert "fix RequestCode overflowed issues:8868 (#8871)"

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
Fixes #8885 
Resolve the issue of inaccurate CK number statistics
=> [ISSUE #8885] Resolve the issue of inaccurate CK number statistics

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java
Fixes #8889
handle namespace outside the loop.
No test.
=> [ISSUE #8889] handle namespace outside the loop

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
=> [ISSUE #8921] Add isWakeCommitWhenPutMessage  for AIO

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Fixes #8925
Fix the bug of update user for ACL 2.0
=> [ISSUE #8925]Fix the bug of update user for ACL 2.0

remoting/src/test/java/org/apache/rocketmq/remoting/rpc/RpcClientImplTest.java
=> [ISSUE #8901] Add more test coverage for RpcClientImpl

broker/src/main/java/org/apache/rocketmq/broker/longpolling/NotifyMessageArrivingListener.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopCommandCallback.java, broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopLongPollingService.java, broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/longpolling/PopLongPollingServiceTest.java, common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java, remoting/src/main/java/org/apache/rocketmq/remoting/CommandCallback.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
=> [ISSUE #8947] Notify pop request before calculate consumer lag

proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java
=> [ISSUE #8877] Refactor lock in ReceiptHandleGroup  to make the lock can be properly released when future can not be completed.

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java, client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java
=> [ISSUE #9009] Optimize message accumulation display and Metrics in DefaultPullConsumer

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java, client/src/main/java/org/apache/rocketmq/client/producer/ProduceAccumulator.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageOpenTracingHookImpl.java, client/src/main/java/org/apache/rocketmq/client/trace/hook/SendMessageTraceHookImpl.java, common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java
=> [ISSUE #9015] Sync SysFlag and message body inflation status; allow omit of message body

broker/src/main/java/org/apache/rocketmq/broker/client/net/Broker2Client.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PollingInfoProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java, broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java, broker/src/test/java/org/apache/rocketmq/broker/client/net/Broker2ClientTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java, broker/src/test/java/org/apache/rocketmq/broker/processor/PeekMessageProcessorTest.java, remoting/src/main/java/org/apache/rocketmq/remoting/protocol/ResponseCode.java
Fixes #9028 
Some SYSTEM_ERROR codes are not meaningful, which can cause confusion when handling online issues.
=> [ISSUE #9028]Adjust some error code for SYSTEM_ERROR

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
=> [ISSUE #9121] Fix CRC32 Check Failing When Value is 0

store/src/main/java/org/apache/rocketmq/store/ConsumeQueueExt.java
N/A
This PR fixes a typo in the `ConsumeQueueExt` class comments:
- Changed "week" to "weakly" to accurately describe the reliability.
No functional code was changed, only comments were updated. Therefore, no new tests were required. All existing tests should pass without issue.
=> fix(comment): correct typos in ConsumeQueueExt class.

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java
=> [ISSUE#9160] Ensure the requestCode increments sequentially

filter/src/main/java/org/apache/rocketmq/filter/parser/SelectorParser.java
Fixes #9201
- if (true) return patterns are redundant and misleading
- Unreachable throw statements clutter code and may cause static analysis warnings
- Cleanup improves code readability and maintainability
Just modify the code format, not the logic
=> [ISSUE #9201] cleanup dead code patterns and improve readability and maintainability.

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
=> [ISSUE #9203] Replace numbers with static variables defined in RequestCode

broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java
=> [ISSUE #9217] Fix broker's inflight and available message counts incorrect when the pop consumer service is enabled

common/src/main/java/org/apache/rocketmq/common/MQVersion.java
=> [ISSUE #9227] Prepare to release Apache RocketMQ 5.3.2

acl/pom.xml, auth/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare release rocketmq-all-5.3.2

README.md
=> [ISSUE #9266] Update the Quick Start version in README to the latest

client/src/main/java/org/apache/rocketmq/client/impl/consumer/PullMessageService.java
about  #1918  
add some log,catch pull message service thread run method by Throwable
=> [ISSUE #1918] Catch throwable in PullMessageService thread run method

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/AbstractRemotingActivity.java
=> Prxoy remoting compatible batch message

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/GrpcServerBuilder.java
=> [Bug #9331] Found one info log lose parameters during proxy startup

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
=> [ISSUE #9360] Fix some services are not shut down when the broker goes offline

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java, client/src/test/java/org/apache/rocketmq/client/impl/consumer/ProcessQueueTest.java
=> [ISSUE #9375] Make client trace thread can be closed correctly

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java, tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java, tieredstore/src/test/java/org/apache/rocketmq/tieredstore/index/IndexStoreServiceTest.java
=> [ISSUE #9379] Fix timeStoreTable delete logic in IndexService

auth/pom.xml, broker/pom.xml, client/pom.xml, common/pom.xml, container/pom.xml, controller/pom.xml, distribution/pom.xml, example/pom.xml, filter/pom.xml, namesrv/pom.xml, openmessaging/pom.xml, pom.xml, proxy/pom.xml, remoting/pom.xml, srvutil/pom.xml, store/pom.xml, test/pom.xml, tieredstore/pom.xml, tools/pom.xml
=> [maven-release-plugin] prepare release rocketmq-all-5.3.3

proxy/src/main/resources/rmq.proxy.logback.xml
Fixes #8629 
Add RocketmqTraffic appender to rmq.proxy.logback.xml
=> [ISSUE #8629] Add proxy RocketmqTraffic logger appender to separate traffic logs

README.md
=> [ISSUE #9414]Updated the Quick Start version in README to the 5.3.3

broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
Fixes #9403
Fix the issue of metadata synchronization failure between master and slave when the topic has attributes
=> [ISSUE #9403] Fix the issue of metadata synchronization failure between master and slave when the topic has attributes

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java
=> [ISSUE #9379] Set compact timestamp when timeStoreTable empty

broker/src/main/java/org/apache/rocketmq/broker/pop/PopConsumerRocksdbStore.java
=> [ISSUE #9418] Fix ColumnFamilyHandle not close in PopConsumerRocksdbStore

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java, broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerTest.java
=> [ISSUE #9443] Fix add wrong value to topicGroupTable in ConsumerManager

common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java, store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueOffsetTable.java, store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java, store/src/main/java/org/apache/rocketmq/store/rocksdb/ConsumeQueueRocksDBStorage.java
=> [ISSUE #9454] Make sure topic can be deleted when using RocksDB CQ

broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConsumerOffsetManagerV2.java
=> [ISSUE #9489]fix: clean pull offset in #removeOffset

store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java
=> [ISSUE #9501] correcting mismatched comments

store/src/main/java/org/apache/rocketmq/store/queue/CombineConsumeQueueStore.java
=> [ISSUE #9254] Fix combineCQ extra search commitLog files for recovery

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
Fixes #9534
Remove the meaningless brokerVersion
=> [ISSUE #9534] Remove the meaningless brokerVersion
