apache/rocketmq

acl/pom.xml
broker/pom.xml
client/pom.xml
common/pom.xml
container/pom.xml
controller/pom.xml
distribution/pom.xml
example/pom.xml
filter/pom.xml
namesrv/pom.xml
openmessaging/pom.xml
pom.xml
proxy/pom.xml
remoting/pom.xml
srvutil/pom.xml
store/pom.xml
test/pom.xml
tieredstore/pom.xml
tools/pom.xml

prepare release rocketmq-all-5.1.3
[maven-release-plugin] prepare release rocketmq-all-5.1.3

[maven-release-plugin] prepare release rocketmq-all-5.1.3

---

docs/cn/controller/design.md

The word ‘falgs’ in [docs/cn/controller/design.md] is wrong.So change it to 'falgs'.

[ISSUE #6943] fix docs typo in docs/cn/controller/design.md #6943

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/MessageStoreFetcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageFetcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredIndexFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManager.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/inputstream/TieredCommitLogInputStream.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageFetcherTest.java

If cq dispatch < local store min offset, do self-healing logic for storage and rebuild automatically
由于文件损坏或者非预期原因导致 cq dispatch < local store min offset, 添加存储自愈的逻辑, 自动重建

[ISSUE #6933] Support delete expired or damaged file in tiered storage and optimize fetch code

---

WORKSPACE
pom.xml
proxy/src/main/java/org/apache/rocketmq/proxy/common/MessageReceiptHandle.java
proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/MessagingProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java
proxy/src/test/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroupTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/processor/ConsumerProcessorTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java

[ISSUE #6754] Support reentrant orderly consumption for proxy

---

proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroup.java
proxy/src/test/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroupTest.java

add removeOne method for ReceiptHandleGroup

---

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/ContextStreamObserver.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/DefaultGrpcMessingActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/GrpcMessagingApplication.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/GrpcMessingActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManager.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ClientProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/MessagingProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/ClientManagerActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/ConsumerManagerActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/PullMessageActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/channel/RemotingChannelManager.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/client/ClientActivityTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/common/GrpcClientSettingsManagerTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/remoting/activity/PullMessageActivityTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/remoting/channel/RemotingChannelManagerTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/LockBatchRequestBody.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/UnlockBatchRequestBody.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/NotificationRequestHeader.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/QueryConsumerOffsetRequestHeader.java

[ISSUE #6964] use the correct context in telemetry; polish the code structure

---

README.md

Fixes #6982 
- Update the version in the README.md document to 5.1.3

[ISSUE #6982]Update the version in the README.md document to 5.1.3

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java

Fixes #7008 
Fix the issue of protocol parsing failure when using haproxy and tls together

[ISSUE #7008] Fix the issue of protocol parsing failure when using haproxy and tls together

---

.github/ISSUE_TEMPLATE/bug_report.yml

Fixes #7005
The bug label relies on manual identification rather than automatic application

[ISSUE #7005] The bug label relies on manual identification rather than automatic application

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

[ISSUE #7013]polish ColdDataCheckService's logic

---

proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java

Fixes #6979
When two different clients request the same proxy, it is possible that their opaque values are the same. In this case, message repetition or message loss may occur.
just run case with multi consumers

[ISSUE #6979] fix opaque will be duplicate in multi client scene

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

[ISSUE #7031] fix PoP caused broker memory leak bug

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

Fixes #7029 
Add a config to determine whether pop response should return the actual retry topic or tamper with the original topic

[ISSUE #7029] Add a config to determine whether pop response should return the actual retry topic or tamper with the original topic

---

common/src/main/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtils.java
common/src/test/java/org/apache/rocketmq/common/utils/ConcurrentHashMapUtilsTest.java

Fixes #6879
Test Case
```
@Test
public void computeIfAbsent() {
ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();
//        map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->"42"));
ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key -> map.computeIfAbsent("BBBB", key2 -> "42"));
}
```
Solution
```
public static <K, V> V computeIfAbsent(ConcurrentMap<K, V> map, K key, Function<? super K, ? extends V> func) {
Objects.requireNonNull(func);
if (isJdk8) {
V v = map.get(key);
if (null == v) {
// v = map.computeIfAbsent(key, func);
// this bug fix methods maybe cause `func.apply` multiple calls.
v = func.apply(key);
if (null == v) {
return null;
}
final V res = map.putIfAbsent(key, v);
if (null != res) {
// if pre value present, means other thread put value …
```

[ISSUE #6879] ConcurrentHashMapUtils fails to solve the loop bug in JDK8

---

proxy/src/main/java/org/apache/rocketmq/proxy/common/RenewEvent.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManager.java

passing the renew event type to create the correct context

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredDispatcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageFetcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/CompositeFlatFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredCommitLog.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFileManager.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsConstant.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredCommitLogTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManagerTest.java
tieredstore/src/test/resources/rmq.logback-test.xml

[#ISSUE 7035] Fix correct min offset behavior in tiered storage

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java

[ISSUE #7047] NettyRemotingClient#invokeOneway throw Exception with address

---

docs/cn/msg_trace/user_guide.md

The word 'RockeMQ' in doc is wrong.So fixed it to 'RocketMQ'.

[ISSUE #7063] doc: fix typo in user_guide.md

---

proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java

https://github.com/apache/rocketmq/issues/7075
Set addressableMessageQueueSet = buildAddressableSet(ctx, mqSet);
addressableMessageQueueSet can be null when Function buildAddressableSet catch exception
Map<String, List> messageQueueSetMap = buildAddressableMapByBrokerName(addressableMessageQueueSet);
in function buildAddressableMapByBrokerName, null will cause NTE
print log and do not add null to addressableMessageQueueSet

fix: npe in lockBatchMQ and unlockBatchMQ

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java
namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java
test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java
test/src/test/java/org/apache/rocketmq/test/dledger/DLedgerProduceAndConsumeIT.java
test/src/test/java/org/apache/rocketmq/test/route/CreateAndUpdateTopicIT.java

Fixes #7052 
Ensuring consistency between broker and nameserver data when deleting a topic

[ISSUE #7052] Ensuring consistency between broker and nameserver data when deleting a topic

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

…channel
Change-Id: I29741cf55ac6333bfa30fef755357b78a22b1325
Fixes #7056

[ISSUE #7056]fix: avoid close success channel if invokeSync most time cost on get connection for channel

---

README.md

Update the CD command in the ReadMe
Currently, the name of the file is incorrect that is mentioned in the readme needs to update with the correct file name.

[ISSUE #7091] Update the cd command in README

---

proxy/src/main/java/org/apache/rocketmq/proxy/common/ReceiptHandleGroupKey.java
proxy/src/main/java/org/apache/rocketmq/proxy/common/RenewEvent.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManager.java
proxy/src/test/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManagerTest.java

Fixes #7104
Add ReceiptHandleGroupKey for RenewEvent
unit test

[#ISSUE 7104] Add ReceiptHandleGroupKey for RenewEvent

---

common/src/main/java/org/apache/rocketmq/common/attribute/TopicMessageType.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/route/RouteActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/validator/DefaultTopicMessageTypeValidator.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/validator/TopicMessageTypeValidator.java

Fixes #7109
Currently, many users are using a single topic to send messages of different types. However, in the future, there is a desire to exert strict control over message types. Message type validation has already been implemented in the Proxy component. To support the transition of existing users to the Proxy architecture, a new message type called "MIXED" should be introduced to facilitate the migration process.
1. create a topic with MIXED message type.
2. send messages with different message type, and verify the result.
3. receive messages in currently and orderly mode, and verify the result.

[ISSUE #7109] support the mixed topic type

---

acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessControlFlowTest.java
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java

[ISSUE #7138] Temporarily ignoring plainAccessValidator test

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java

[ISSUE 7117] check message is in memory or not when init consumer offset for pop

---

broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
example/src/main/java/org/apache/rocketmq/example/quickstart/Consumer.java
example/src/main/java/org/apache/rocketmq/example/quickstart/Producer.java

[ISSUE #7146]  Log output error needs to be corrected

---

acl/pom.xml
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessControlFlowTest.java
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessValidatorTest.java
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainPermissionManagerTest.java

Fixes #7129
Some test cases of rocketmq-acl change system property to set their own configurations, but make them not run in parallel. This 'fix' just disable the parallel execution at runtime to pass related workflows, and further refactoring is needed to support separation contexts of different test cases.

[ISSUE #7129] fix resource collisions in acl tests

---

proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java

Fixes #7169
Change it to 100000 for high current metadata access.
No need

Change metadataThreadPoolQueueCapacity to 100000

---

tools/src/main/java/org/apache/rocketmq/tools/command/topic/RemappingStaticTopicSubCommand.java

Fixes #7183, correct mismatched commandDesc.

[ISSUE #7183] Correct mismatched commandDesc

---

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalMessageService.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ExtraInfoUtil.java

[ISSUE #7001] Fix IndexOutOfBoundsException when process pop response

---

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerGroupInfo.java

Fixes #7189
The current implementation of the updateSubscription method in the code has a potential issue with the time complexity of the loop. The loop iterates over the subscription table to check if a topic exists in the subscription list. This results in a time complexity of O(n) for each iteration.
To optimize the time complexity, we can introduce an additional HashSet to store the new topics. By doing so, we can perform a constant time (O(1)) lookup instead of iterating over the subscription table in the loop. This will significantly reduce the time complexity of the loop.
No need.

[ISSUE #7189] Optimize time complexity of loop in ConsumerGroupInfo#updateSubscription

---

store/src/main/java/org/apache/rocketmq/store/AllocateMappedFileService.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/TransientStorePool.java

[ISSUE #7201] Remove the DefaultMessageStore.class dependency in TransientStorePool

---

distribution/bin/mqbroker

no issue
Update mqbroker to use runbroker.sh instead of runserver.sh when enabling `--enable-proxy` this allow JVM `heap` and `gc` configuration using broker's settings instead of other common serverices'(proxy,namenode, etc). our main purpose, like the filename `mqbroker` suggest, is to start broker (which embeds a proxy), so use broker's config is reasonable
chinese version
mqbroker的--enable-proxy选项是启动内嵌了proxy的broker，而不是内嵌broker的proxy，而且broker的工作量和重要程度大于proxy，所以使用broker的gc和heap配置更合适
after the change, started broker using configs in  runbroker.sh and work well

Update mqbroker to use runbroker.sh instead of runserver.sh when enabling --enable-proxy

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
remoting/src/test/java/org/apache/rocketmq/remoting/TlsTest.java

Fixes #7042 
Test Cases Contains Both TLS Request and Non-TLS Request send by client when Server in DISABLED TLS Mode.

[ISSUE #7042] throw UnsupportedOperationException after client using TLS Request but Server in Disabled Mode.

---

broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java

Fixes #7203 
In https://github.com/apache/rocketmq/issues/6931, we set table reference to the same object for setSubscriptionGroupTable method, but in https://github.com/apache/rocketmq/pull/7092, this part of the content was rolled back and needs to be changed back.

[ISSUE #7203] Set table reference the same object for setSubscriptionGroupTable method

---

tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java
tools/src/test/java/org/apache/rocketmq/tools/command/metadata/KvConfigToJsonCommandTest.java

Fixes https://github.com/apache/rocketmq/issues/7142
- case get topic config
`mqadmin RocksDBConfigToJson -p /home/xxx/store/config/topics -t topics`
```
"topicConfigTable":{
"SCHEDULE_TOPIC_XXXX":{
"readQueueNums":18,
"perm":6,
"writeQueueNums":18,
"topicFilterType":"SINGLE_TAG",
"topicName":"SCHEDULE_TOPIC_XXXX",
"attributes":{},
"order":false,
"topicSysFlag":0
},
"RMQ_SYS_TRANS_HALF_TOPIC":{
"readQueueNums":1,
"perm":6,
"writeQueueNums":1,
"topicFilterType":"SINGLE_TAG",
"topicName":"RMQ_SYS_TRANS_HALF_TOPIC",
"attributes":{},
"order":false,
"topicSysFlag":0
},
// ...
}
```
- case get subscription config
`mqadmin RocksDBConfigToJson -p /home/xxx/store/config/subscriptionGroups -t subscriptionGroups`
```
{
"subscriptionGroupTable":{
"CID_ONSAPI_OWNER":{
"retryMaxTimes":16, …
```

[ISSUE #7142] Add command `RocksDBConfigToJson` to inspect rocksdb content

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredIndexFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredIndexFileTest.java

[#ISSUE 7222] Bug fix and refactoring of the Indexfile in tiered storage

---

proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java

Rename ProxyConfig ExpiredInSeconds to RefreshSeconds
Fixes #7246
Add expireAfterAccess for cache

[ISSUE #7246] Add expireAfterAccess for cache

---

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java

Fixes #7271 
- Optimize the configuration for setting the quantity of TimerDequeuePutMessageService

[ISSUE #7271]Optimize the configuration for setting the quantity of TimerDequeuePutMessageService

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java

[issue](https://github.com/apache/rocketmq/issues/7111)

[ISSUE #7111] Remove responseFuture from the responseTable when exception occurs

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java

Fixes #7208 
when deleting topic, search for its pop retry topic and delete them
unit test was added

[ISSUE #7208] fix: when deleting topic  also delete its pop retry topic

---

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java

[ISSUE #7302] Fix singleTopicRegister code deleted in merge

---

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java

[ISSUE #7334] `registerIncrementBrokerData` for single topic update

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
test/src/test/java/org/apache/rocketmq/test/route/CreateAndUpdateTopicIT.java

[ISSUE #7326] Split the request to register to the nameserver

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
store/src/main/java/org/apache/rocketmq/store/TopicQueueLock.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java

Fixes #7318
Add the configuration of topicQueueLock number to better support different queue nums scenarios

[ISSUE #7318] Add the configuration of topicQueueLock number to better support different  queue nums scenarios

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredFlatFileTest.java

[ISSUE #7345] Fix wrong result of searchOffset in tiered storage

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/TieredFlatFileManager.java

这个提交是对分级存储实现的一些细节改进
1. 清理文件时不清理未初始化的文件。
2. 简化 recover 流程中元数据的加载
Fixes #6633

[ISSUE #6633] Not clear uninitialized files and fix metadata recover

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageFetcher.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageStoreTest.java

[ISSUE #7363] Fix get message from tiered storage return incorrect next begin offset

---

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java
store/src/main/java/org/apache/rocketmq/store/timer/TimerMetrics.java
store/src/main/java/org/apache/rocketmq/store/timer/TimerRequest.java
store/src/test/java/org/apache/rocketmq/store/timer/TimerMetricsTest.java

Fixes #7381
When entering the time wheel, if it is judged that it can be dequeued, its enqueue time is set to infinity, which means that it has never entered the time wheel.
Skip messages with an infinite enqueue time when counting metrics.

[ISSUE #7381] Fix the problem of inaccurate timer message metric

---

tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportConfigsCommand.java

[ISSUE #7398] Fix ExportConfigsCommand NPE

---

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/channel/RemotingChannel.java

Fixes #7410
The proxy does not handle exceptions from the requesting client.
1. the proxy request to client for get consumer running info.
2. the client deal with the request by timeout.
3. the proxy will retrun the result for caller.

[ISSUE #7410]Handle the Exception when the Proxy requests the client failed.

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicBlackListFilter.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicFilter.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/TieredStoreTopicBlackListFilterTest.java

https://github.com/apache/rocketmq/issues/7313    This is link for my issue.
Fixes #7313
There was an Enhancement change needed to change method name from  addTopicToWhiteList of this TieredStoreTopicBlackListFilter class should be renamed to addTopicToBlackList .
In three places it was required to change the name which I have done.
**Note: This was my first ever contributions if you need some changes or if I committed mistake please do say and give feedback**
I have tried running the file and are running.

[ISSUE 7313]  Enhancement Optimization Method name

---

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

* add heartbeat when channel connect
Fixes #7323
Add ChannelEventListener for MQClientAPIImpl

[ISSUE #7296] Add ChannelEventListener for MQClientAPIImpl

---

controller/src/test/java/org/apache/rocketmq/controller/impl/DLedgerControllerTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/ResponseCode.java
remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java

Fixes #7330
Add `goaway` response code when the server is shutting down and client reconnection and transparent retry mechanism.
Existing unit test.

[ISSUE #7330] Add goaway and reconnection mechanism

---

common/src/main/java/org/apache/rocketmq/common/message/Message.java

These getter and setter methods indeed cause the JSON serialization of the Message subclasses to fail.

add getter for class Message ,fix json serialize bug

---

common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java

Fixes #7444
Fix testCalculateFileSizeInPath test can not rerun in same environment

[ISSUE #7444] Fix testCalculateFileSizeInPath test can not rerun in same environment

---

common/src/main/java/org/apache/rocketmq/common/constant/LoggerName.java
controller/src/main/java/org/apache/rocketmq/controller/ControllerStartup.java
controller/src/main/resources/rmq.controller.logback.xml

[ISSUE #7425] Add RoccketmqControllerConsole log to print config to console

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicConfigAndQueueMapping.java

TopicConfigAndQueueMapping extends from the TopicConfig class but does not override the toString method. This results in situations where they appear equal when printed, but in reality, the equals method returns false. T his can be highly confusing for anyone observing this behavior.
close  #7451

[ISSUE #7451] Override toString for TopicConfigAndQueueMapping

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

* add waitChannelFuture for goaway
* add body for retry channel
Fixes #7330
Fix channel connect issue for goaway
exist unit test

[ISSUE #7330] Fix channel connect issue for goaway

---

container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java

AddBroker removes parsing configuration from body

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java
remoting/src/test/java/org/apache/rocketmq/remoting/protocol/header/FastCodesHeaderTest.java

[ISSUE #7454] Utilizing cache to avoid duplicate parsing

---

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java

Check the input yaml and the path in ACL

---

broker/src/main/java/org/apache/rocketmq/broker/client/ClientHousekeepingService.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
container/src/main/java/org/apache/rocketmq/container/ContainerClientHouseKeepingService.java
controller/src/main/java/org/apache/rocketmq/controller/BrokerHousekeepingService.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/BrokerHousekeepingService.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/ClientHousekeepingService.java
remoting/src/main/java/org/apache/rocketmq/remoting/ChannelEventListener.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyEventType.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

* introduce a new event NettyEventType.ACTIVE,
* implement channelActive interface for NettyRemotingClient#NettyConnectManageHandler
* add onChannelActive for ChannelEventListener interface.
Fixes #7493
Introduce a new event NettyEventType.ACTIVE for ChannelEventListener

[ISSUE #7493] Introduce a new event NettyEventType.ACTIVE

---

container/src/main/java/org/apache/rocketmq/container/BrokerContainer.java
container/src/main/java/org/apache/rocketmq/container/BrokerContainerConfig.java

[ISSUE #7497] Extract the frequency of calling updateNamesrvAddr into a configuration

---

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
common/src/main/java/org/apache/rocketmq/common/message/MessageExtBrokerInner.java
common/src/main/java/org/apache/rocketmq/common/utils/MessageUtils.java
test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/PopMessageAndForwardingIT.java

Fixes #7531
Add Integration test.

[ISSUE #7531] Clear POP_CK when sending messages

---

common/src/main/java/org/apache/rocketmq/common/message/MessageExtBrokerInner.java
store/src/main/java/org/apache/rocketmq/store/CommitLog.java
store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/MessageExtEncoder.java
store/src/main/java/org/apache/rocketmq/store/MultiDispatch.java
store/src/main/java/org/apache/rocketmq/store/queue/AbstractConsumeQueueStore.java
store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueInterface.java
store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStoreInterface.java
store/src/main/java/org/apache/rocketmq/store/queue/MultiDispatchUtils.java
store/src/main/java/org/apache/rocketmq/store/queue/QueueOffsetOperator.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueue.java
store/src/test/java/org/apache/rocketmq/store/AppendCallbackTest.java
store/src/test/java/org/apache/rocketmq/store/AppendPropCRCTest.java
store/src/test/java/org/apache/rocketmq/store/MultiDispatchTest.java
store/src/test/java/org/apache/rocketmq/store/kv/CompactionLogTest.java

Fixes #7511 
topicQueueLock cannot guarantee that the offset of LMQ is set correctly, so the offset maintenance of LMQ is placed in the critical section protected by putMessageLock.

[ISSUE #7511]Lock granularity issue causing LMQ message loss

---

tieredstore/README.md
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/TieredMessageStoreConfig.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredCommitLogTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegmentTest.java

ISSUE #5923 add README.md file to explain how to use tiered storage.  
There was a simple configuration error

Fix tiered store README.md error about Configuration

---

common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java

Fixes #7418
This MR offers an alternative approach to #7445 (5d492c338258d07613103e6ae16df4c6fa5b3838). 
Instead of manually setting up the directory `testCalculateFileSizeInPath` needs and then recursively deleting it, it uses JUnit's `TemporaryFolder` `@Rule` to handle all of this work, and allows the code to concentrate on the business logic.
Running `mvn install` passes now, as well as running this test manually from IntelliJ

Fix unstable UtilAllTest#testCalculateFileSizeInPath on Windows

---

common/src/main/java/org/apache/rocketmq/common/UtilAll.java
common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalRemotingCommand.java

Make codebase JDK 9+ compatible
fix #7551

[ISSUE #7551] Reuse helper methods from Netty to free direct byte buffer

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/TieredMessageStoreConfig.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegment.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/TieredCommitLogTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/provider/posix/PosixFileSegmentTest.java

[ISSUE #5923] Revert "Fix tiered store README.md error about Configuration (#7436)"
This reverts commit 70dc93abbcb9bf161378d66fcaca55bedc78b905.
for issue #5923
There is a widely use of filePath in the rocketmq project. The rename operation which not only brings compatibility issues but also conflicts with the naming style of the rocketmq project. It is recommended to revert this change.

[ISSUE #5923] Revert "Fix tiered store README.md error about Configuration (#7436)"

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/PopProcessQueue.java

Fixes #7570
Add default value as current time for lastPopTimestamp.
Run `PopConsumer`, there are no errors in the client log.
```log
2023-11-17 10:26:42.442 INFO  [66096] [NettyClientPublicExecutor_5] [o.a.r.c.i.ClientRemotingProcessor#?:?] - receive broker's notification[x.x.x.x:10931], the consumer group: CID_JODIE_1 changed, rebalance immediately
2023-11-17 10:26:42.475 INFO  [66096] [main] [RocketmqRemoting#?:?] - createChannel: connect remote host[x.x.x.x:10911] success, AbstractBootstrap$PendingRegistrationPromise@bf1ec20(success)
2023-11-17 10:26:42.475 INFO  [66096] [NettyClientWorkerThread_3] [RocketmqRemoting#?:?] - NETTY CLIENT PIPELINE: ACTIVE, x.x.x.x:10911
2023-11-17 10:26:42.475 WARN  [66096] [NettyEventExecutor] [o.a.r.c.i.f.MQClientInstance#?:?] - …
```

[ISSUE #7570] fix: add default value for lastPopTimestamp

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
client/src/main/java/org/apache/rocketmq/client/producer/TransactionMQProducer.java
example/src/main/java/org/apache/rocketmq/example/transaction/TransactionProducer.java

[ISSUE #7567] transactionProducer get the topic route before sending the message

---

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
broker/src/main/java/org/apache/rocketmq/broker/filter/ExpressionForRetryMessageFilter.java
broker/src/main/java/org/apache/rocketmq/broker/longpolling/NotifyMessageArrivingListener.java
broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopLongPollingService.java
broker/src/main/java/org/apache/rocketmq/broker/metrics/ConsumerLagCalculator.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java
common/src/test/java/org/apache/rocketmq/common/KeyBuilderTest.java
tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java
tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorService.java

Fixes #7543
Use new retry topic to solve pop retry topic message notification and split group from retry topic.
Unit test.

[ISSUE #7543] Retry topic v2 in pop

---

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java

[ISSUE #7577] SlaveActingMaster Timer Message retry without escape logic

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java
common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java
controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java
controller/src/test/java/org/apache/rocketmq/controller/ControllerRequestProcessorTest.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/RequestProcessorTest.java

Add validation in broker/namesrv configure updating command.

Add validation in broker/namesrv configure updating command.

---

container/src/main/java/org/apache/rocketmq/container/BrokerContainerConfig.java
container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java

Add validation in broker container configure updating command

Add validation in broker container configure updating command

---

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java
common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java

Add set method for config black list in broker/namesrv/controller config.

Add set method for config black list in broker/namesrv/controller config.

---

namesrv/src/test/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManagerNewTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/TopicList.java

[ISSUE #7534] use high performance concurrent set to replace copyonwriteset

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java

Fixes #7545, Fix set mapped file to null cause file can not destroy in tiered storage index

[ISSUE #7545] Fix set mapped file to null cause file can not destroy

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
common/src/main/java/org/apache/rocketmq/common/message/MessageAccessor.java
store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java

Fixes #7601
Fix #7601's exception and master use slave's TimerCheckPoint。
Use #7601's reproduce step to test.

[ISSUE #7601] Fix slave acting master bug

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/GetMessageResultExt.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/TieredFileSegment.java

…format
Fixes #7585
When pull messages from the cache of tiered storage, always return a copy of the byte buffer instead of the buffer itself.
从分级存储的缓存获取消息时，将返回消息 buffer 的副本而不是 buffer 本身。

[ISSUE #7585] Always return duplicate buffer when filter message and fix log format

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java
namesrv/src/test/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessorTest.java

[4.9.x] Add validation in broker/namesrv configure updating command

---

common/src/main/java/org/apache/rocketmq/common/KeyBuilder.java
common/src/test/java/org/apache/rocketmq/common/KeyBuilderTest.java

Fixes #7543
Use "+" as the new separator for retry topic.

[ISSUE #7543] Use "+" as the new separator for retry topic

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java

Fixes #7543
only call a single type of retry topic in pop

[ISSUE #7543] only call a single type of retry topic in pop

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java

Fixes #7646
Optimize pull onException logging

[ISSUE #7646] Optimize pull onException logging

---

namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java

1、判断isPrimeSlave条件添加当前broker列表是否包含leader节点的判断
2、添加注释
Fixes #7626

[ISSUE #7626] Topic perm was mistakenly changed to 4 in dledger mode

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

Fixes #7656
ConfirmOffset directly takes the max offset when allAckInSyncStateSet is false

[ISSUE #7656] ConfirmOffset directly takes the max offset when allAckInSyncStateSet is false

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RemotingCommand.java

Fixes #7679 
- Optimize the serialization of RemotingCommand processTimer property

[ISSUE #7679]Optimize the serialization of RemotingCommand processTimer property

---

client/src/main/java/org/apache/rocketmq/client/impl/ClientRemotingProcessor.java

[ISSUE #7676] use clientDecode for consuming message directly

---

pom.xml

Fixes #7680
Bump guava version from 31.1-jre to 32.0.1-jre

[ISSUE #7680] Bump guava version from 31.1-jre to 32.0.1-jre

---

store/src/main/java/org/apache/rocketmq/store/MappedFileQueue.java
store/src/test/java/org/apache/rocketmq/store/MappedFileQueueTest.java

bugfix: CopyOnWriteArray#listIterator do not support remove action when iterating

[ISSUE #7684] Fix iterator.remove() bug

---

store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java

Fixes #7689 
Upon restart, it is necessary to compensate for messages after the confirmOffset by moving the cq offset backwards. It must be ensured that these messages remain unconsumable before the confirmOffset is reached.

[ISSUE #7689] In Controller mode, messages may lost due to sharing the same cq offset

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java

Add sendHeartbeatToBroker
Fixes #7642
Add return value for sendHeartbeat related method

[ISSUE #7642] Add return value for sendHeartbeat related method

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/MQConsumerInner.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceService.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java

Fixes #7644
* Add tryRebalance for return value
* Optimize order rebalance performance
* Add rebalanceImmediately when offset illegal

[ISSUE #7644] Optimize client rebalance

---

common/src/main/java/org/apache/rocketmq/common/utils/BinaryUtil.java

Fixes #7702
When parsing the PPV2 protocol and setting the TLS contents as gRPC attributes, gRPC will log the following messages. To avoid excessive logging, filter out content that does not conform to ASCII.
1. Open the ppv2 protocol
2. Send ppv2 message with tls data [61, 12, 109]
3. Check the log

[ISSUE #7702]Fix ascii check for ppv2 tls.

---

common/src/main/java/org/apache/rocketmq/common/ControllerConfig.java

Fixes #7697
add two set methods for field metricsExporterType in order to make config 'metricsExporterType' work.
1.add a config "metricsExporterType = PROM" for controller
2.open localhost:5557/metrics and can get metrics info.

[ISSUE #7697]Fix can't open controller metricsExporter.

---

common/src/main/java/org/apache/rocketmq/common/UtilAll.java
common/src/test/java/org/apache/rocketmq/common/UtilAllTest.java

Fixes #7710
The PR is for a bug the ACL, which caused the problem of deleting the last item of the topic/group perms or the global white list.
The bug is due to the flaw of UtilAll#split func which didn't handle the blank string case properly.
So I've fixed it.
This change have been tested by unit test and the bug have been tested on local.
I've also searched the usages of the changed method globally.
I'm sure the bug has been fixed and has no influence on any other functions of the project.

[ISSUE #7710] Handle blank string for UtilAll#split to fix the bugs of ACL

---

common/src/main/java/org/apache/rocketmq/common/utils/BinaryUtil.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/ProxyAndTlsProtocolNegotiator.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java

Fixes #7752
The tlvs value in ppv2 has the space character can not pass the ascii check.
So the value should be trims before the ascii check.
Send message with the byte value start with (byte)2, it will not be filtered.

Fix ppv2 tls ascii start with (byte)2

---

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java

Fix #7355 
rocketmq in dledger mode will recover correctly from an abnormal downtime
Run DLedgerCommitlogTest.testDLedgerAbnormallyRecover()

fix dledger recover abnormally may lost consume queue of tail

---

store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java

Fixes #7760
Missing set method, resulting in the configuration unable to be corrected by the configuration file.

[ISSUE #7760] make timerSkipUnknownError can be set by config file

---

common/src/main/java/org/apache/rocketmq/common/utils/BinaryUtil.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/ProxyAndTlsProtocolNegotiator.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/MultiProtocolRemotingServer.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/HAProxyMessageForwarder.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProtocolProxyHandler.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/ProxyAndTlsProtocolNegotiatorTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/HAProxyMessageForwarderTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/Http2ProtocolProxyHandlerTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingServer.java
remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingServerTest.java

Fixes #7774
In the PPV2 protocol, TLV data is generally customized and needs to have the capability for extension.
customize the PPV2 TLV data, and extends the handler for data.

[ISSUE #7774] Make the handle of ppv2 tlv more extendable 

---

proxy/src/main/java/org/apache/rocketmq/proxy/common/ContextVariable.java
proxy/src/main/java/org/apache/rocketmq/proxy/common/ProxyContext.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/GrpcMessagingApplication.java

Fixes #7781
Get namespace from gRPC x-mq-namespace header.

[ISSUE #7781] Get namespace from gRPC header

---

client/src/main/java/org/apache/rocketmq/client/latency/MQFaultStrategy.java

Fixes #7779 
when selectOneMessageQueue, return clone object instead of the original messageQueue

fix the selectOneMessageQueue to avoid change messageQueue permanently

---

client/src/main/java/org/apache/rocketmq/client/common/ThreadLocalIndex.java
client/src/test/java/org/apache/rocketmq/client/common/ThreadLocalIndexTest.java

Remove the redundant code
Fixes #7785
Remove the redundant code because Math.abs does not return negative numbers
```java
@Test
public void testResultOfResetIsGreaterThanOrEqualToZero() {
ThreadLocalIndex localIndex = new ThreadLocalIndex();
localIndex.reset();
assertThat(localIndex.incrementAndGet() > 0).isTrue();
}
```

[ISSUE #7785] Remove the redundant code

---

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java

Fixes #7777
- Optimize the logic of DefaultRequestProcessor#getTopicsByCluster to avoid unnecessary deserialization

[ISSUE #7777]Optimize the logic of DefaultRequestProcessor#getTopicsByCluster to avoid unnecessary deserialization

---

client/src/main/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStore.java
client/src/test/java/org/apache/rocketmq/client/consumer/store/LocalFileOffsetStoreTest.java

Fixes #7740
1. Incremental update file when doing persist.
2. Complete _removeOffset_ method in LocalFileOffsetStore.

[ISSUE #7740] Optimize LocalFileOffsetStore

---

distribution/bin/tools.sh

Fixes [#7786](https://github.com/apache/rocketmq/issues/7786)
修复了在jre环境下，mqadmin命令执行时，会报错JAVA_HOME未设置的错误！详情和复现，可以见 [#7786](https://github.com/apache/rocketmq/issues/7786)
报错信息：
```bash
readlink: missing operand
Try 'readlink --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
ERROR: Please set the JAVA_HOME variable in your environment, We need java(x64)! !!
```
测试结果，可以见 [#7786](https://github.com/apache/rocketmq/issues/7786)

[ISSUE #7786] Optimize the execution logic of tool.sh in the JRE environment

---

WORKSPACE
common/src/main/java/org/apache/rocketmq/common/JraftConfig.java

Fixes #7791
Polish the code for jraft controller

[ISSUE #7791] Polish the code for jraft controller

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ProcessQueue.java

…back
Fixes #7538 
when then consumer callback updates msg body, the msgSize calculated in processqueue is wrong, pull is blocked by ratelimit forever. 
```java
consumer.registerMessageListener((MessageListenerConcurrently) (msgs, context) -> {
msgs.get(0).setBody(new byte[0]);
return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
});
```

[ISSUE #7538] fix wrong cachedMsgSize if msg body is changed in consumer callback

---

broker/src/main/java/org/apache/rocketmq/broker/plugin/PullMessageResultHandler.java
broker/src/main/java/org/apache/rocketmq/broker/processor/DefaultPullMessageResultHandler.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java

Fixes #7622
Revise the measurement method of GROUP_GET_LATENCY to reveal its intended semantics

[ISSUE #7622] Revise the measurement method of GROUP_GET_LATENCY to reveal its intended semantics

---

proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java

Fixes #7803
Add try catch for lock and unlock

[ISSUE #7803] Add try catch for lock and unlock

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java

Fixes #7813
由于StartDetectorEnable 在构造函数里面只初始化了一次，所以后续再set的时候， 已经不会生效了。

[ISSUE #7813] setStartDetectorEnable Not effective

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java
remoting/src/test/java/org/apache/rocketmq/remoting/netty/NettyRemotingClientTest.java

Fixes #7822 
update getHostAndPort method in NettyRemotingClient.
code covered

[ISSUE #7822] fix NettyRemotingClient can't connect to IPv6 address.

---

pom.xml

Fixes #7831 
Fix exclusions in rat-check configuration.
Run `mvn apache-rat:check` and check the output.

[ISSUE #7831] make rat-check successful

---

broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopLongPollingService.java
broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

Fixes #7821
Add notifyLast flag for PopLongPollingService

[ISSUE #7821] Add notifyLast flag for PopLongPollingService

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

Fixes #7815
Use createChannelAsync for async invoke rpc

[ISSUE #7815] Use createChannelAsync for async invoke rpc

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java

Fixes #7851 
The `SubscriptionGroupConfig`'s equals and hashCode methods doesn't count `consumeMessageOrderly` field in.

[ISSUE #7851] Fix hashcode and equals methods of SubscriptionGroupConfig

---

broker/src/main/java/org/apache/rocketmq/broker/processor/EndTransactionProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/EndTransactionProcessorTest.java

Missing statistics when transaction messages are committed
Add statistics for the production of transaction messages.
Test cases are updated

Add statistics for the production of transaction messages.

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

[ISSUE #7868] Use entrySet to close channel

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

[ISSUE #7853] Fix the manualDeleteFileSeveralTimes count

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java

Fixes #7845 
- Simplify the AbstractSendMessageProcessor#buildMsgContext code using Optional

[ISSUE #7845]Simplify the AbstractSendMessageProcessor#buildMsgContext code using Optional

---

common/src/main/java/org/apache/rocketmq/common/namesrv/DefaultTopAddressing.java

[ISSUE #7904] use string builder to concat string

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

[ISSUE #7902] fix:reput thread may quit by throwing error

---

broker/src/main/java/org/apache/rocketmq/broker/client/rebalance/RebalanceLockManager.java

https://github.com/apache/rocketmq/issues/7926
Delete the unnecessary 'else' statement
Only code style changed

[ISSUE #7926] Delete the unnecessary 'else' statement

---

namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java

Fixes [#7932](https://github.com/apache/rocketmq/issues/7932)
Adhere to Java's modifier order specification.
Only modifier order changed.

[ISSUE #7932] Rectify the modifier order in namesrv

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/routeinfo/RouteInfoManager.java

I only modified the log printed, the modification isn't complicated, so I didn't submit an issue.
I was reading the code about namesrv and broker, and i found some ambiguous logs, this pr is to fix them.
Nonthing logical is modified, i think there is no need for a test.

Fix some ambiguous logs

---

acl/src/main/java/org/apache/rocketmq/acl/common/Permission.java
acl/src/test/java/org/apache/rocketmq/acl/common/PermissionTest.java

Fixes #7929 
Add some request codes to the permission verification for the admin role

[ISSUE #7929] Add some request codes to the permission verification for the admin role

---

test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/NotificationIT.java

Fix notification integration test in pop consume mode

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

when transientStorePoolEnable not enable, we should not add commit bytes
Fixes #7836

[ISSUE #7836] flush_behind_bytes wrong in transientStorePoolEnable not enable

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java

[ISSUE #7951] return the full statsInfo when read and write queues  are inconsistent

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImplTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatMessageFileTest.java

[ISSUE #7878] Fix query message offset return wrong offset with boundary type

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileInterface.java

Add interface comment for query offset operation with boundary type

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/SelectBufferResult.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java

[ISSUE #7974] Add repeatedly read same offset log to find unexpected situations

---

store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueTable.java

[Enhancement] use BoundaryType in binarySearchInCQByTime #7961
use BoundaryType in binarySearchInCQByTime instead of absolute value comparison.
When performing a range query, pass BoundaryType.LOWER to get the left boundary msg offset,  pass  BoundaryType.UPPER to get the right boundary msg offset
I wrote a test case, the timestamp 1711351134289 does not match an exact offset, when we call mqAdminExt.searchLowerBoundaryOffset(), it returns  the offset whose storeTime is the smallest storeTime that is greater than the target storeTime. When we call mqAdminExt.searchUpperBoundaryOffset(), it returns  the offset whose storeTime is the biggest storeTime that is smaller than the target storeTime.
```java
@Test
public void searchOffsetTest() throws MQBrokerException, RemotingException, …
```

[ISSUE #7961] use BoundaryType in binarySearchInCQByTime

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java

simple and clear change, not creating an issue
```
log.warn("The consume request count exceeds threshold {}, so do flow control, consume request count={}, flowControlTimes={}", consumeRequestCache.size(), consumeRequestFlowControlTimes);
```
missing first parameter, so out put is corrupt
```
2024-03-26 13:48:53.235 WARN  [15008] [PullMsgThread-test20] [o.a.r.c.i.c.DefaultLitePullConsumerImpl#run:903] - The consume request count exceeds threshold 101, so do flow control, consume request count=1, flowControlTimes={}
```
after change 
```
log.warn("The consume request count exceeds threshold {}, so do flow control, consume request count={}, flowControlTimes={}",
(int)Math.ceil((double)defaultLitePullConsumer.getPullThresholdForAll()/defaultLitePullConsumer.getPullBatchSize()), …
```

Consume request count threshold log fix

---

client/BUILD.bazel
client/pom.xml
client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/TopicRouteService.java

[ISSUE #7983]Use java optional

---

store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java

In normal cases, the number of messages of the deletion type is equal to the number of messages that should be deleted. When out of queue, add one for the deletion type and subtract one for the message that should be deleted. This ensures that the metric is accurate when deletion fails

[ISSUE #7979]Fix timerWheel message metric

---

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithOpenTracingTest.java
client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQConsumerWithTraceTest.java
client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithOpenTracingTest.java
client/src/test/java/org/apache/rocketmq/client/trace/DefaultMQProducerWithTraceTest.java
client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithOpenTracingTest.java
client/src/test/java/org/apache/rocketmq/client/trace/TransactionMQProducerWithTraceTest.java

Fixes #7988
* build trace dispatcher in start method
* setNamespaceV2 for dispatcher
* disable trace for inner traceProducer

[ISSUE #7988] Refector client trace

---

proxy/src/main/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataService.java
proxy/src/test/java/org/apache/rocketmq/proxy/service/metadata/ClusterMetadataServiceTest.java

[ISSUE #7958] Fix proxy always return the first broker in findOneBroker

---

broker/src/main/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessorTest.java

Fixes #7963 
Check the existence of consumer group in command updateConsumerOffset. Return SUBSCRIPTION_GROUP_NOT_EXIST if the group has been deleted.
UT

[ISSUE #7963] Check consumer group existence in updateConsumerOffset

---

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
client/src/main/java/org/apache/rocketmq/client/consumer/MQPullConsumer.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java

Fixes #8023
Add expression filtering capability to the pullBlockIfNotFound method of pull consumer

[ISSUE #8023] Add expression filtering capability to the pullBlockIfNotFound method of pull consumer

---

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
acl/src/test/java/org/apache/rocketmq/acl/plain/PlainAccessResourceTest.java

Fixes #7909 
Require the SUB permission of retry topic,not the producer group.
UT

[#ISSUE 7909] Fix send retry message permission check

---

.github/workflows/coverage.yml
.github/workflows/maven.yaml
auth/src/test/java/org/apache/rocketmq/auth/authentication/AuthenticationEvaluatorTest.java
auth/src/test/java/org/apache/rocketmq/auth/authentication/manager/AuthenticationMetadataManagerTest.java
auth/src/test/java/org/apache/rocketmq/auth/authorization/AuthorizationEvaluatorTest.java
auth/src/test/java/org/apache/rocketmq/auth/authorization/manager/AuthorizationMetadataManagerTest.java

Fixes #8075
add codecov token in coverage.yml from https://app.codecov.io/github/apache/rocketmq/settings
skip tests for auth module that can't pass on mac because of rocksdbjni error
Coverage / calculate-coverage (pull_request) Successful in 24m

build: fix workflow and skip failed test for auth module on mac

---

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java

Fixes #7848 
Parse property PROPERTY_INNER_MULTI_DISPATCH and property PROPERTY_INNER_MULTI_QUEUE_OFFSET.
unit test

[ISSUE #7848] Fix exception when pop messages with multiple LMQ indexes

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFileTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatFileStoreTest.java

[ISSUE #8076] Fix correct min cq offset when delete tiered storage CommitLog

---

common/src/main/java/org/apache/rocketmq/common/attribute/TopicMessageType.java
common/src/test/java/org/apache/rocketmq/common/attribute/TopicMessageTypeTest.java

Fixes #8098
Parse as DELAY message if property TIMER_DELAY_MS present.
UT

[ISSUE #8098] Fix parsing delay message type from property

---

auth/src/main/java/org/apache/rocketmq/auth/authentication/provider/DefaultAuthenticationProvider.java
auth/src/main/java/org/apache/rocketmq/auth/authorization/provider/DefaultAuthorizationProvider.java

Fixes #8100
Make the doAuditLog method protected in authentication and authorization.
Nothing.

[ISSUE #8100] Expose print audit log function

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SimpleSubscriptionData.java
remoting/src/test/java/org/apache/rocketmq/remoting/protocol/subscription/SimpleSubscriptionDataTest.java

Fixes #8103
Fix SimpleSubscriptionData equal
unit test

[ISSUE #8103] Fix SimpleSubscriptionData equal

---

filter/src/test/java/org/apache/rocketmq/filter/FilterSpiTest.java

Fixes #8092 
The test `org.apache.rocketmq.filter.FilterSpiTest#testRegister` is non-idempotent, as it passes in the first run but fails in the second run in the same JVM. The test fails in subsequent runs in the same environment because it registers a `NothingFilter` without unregistering it. The repeated run will then throw a `Filter already exist` error. A fix is recommended as unit tests shall be idempotent, and state pollution shall be mitigated so that newly introduced tests do not fail in the future due to polluted shared states.
```
java.lang.IllegalArgumentException: Filter spi type(Nothing) already exist!
at org.apache.rocketmq.filter.FilterFactory.register(FilterFactory.java:44)
at org.apache.rocketmq.filter.FilterSpiTest.testRegister(FilterSpiTest.java:53)
at …
```

[ISSUE #8092] Fixed non-idempotent test

---

client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImplTest.java

Fixes #8090 
1. 优化了DefaultLitePullConsumerImpl#isSetEqual方法，减少了循环次数和不正确的判断。并添加了isSetEqual方法的单元测试
2. 订正了一个单词拼写错误
How Did You Test This Change?
添加了单元测试验证isSetEqual方法是否符合预期

[ISSUE #8090] Optimize isSetEqual for DefaultLitePullConsumerImpl

---

auth/src/main/java/org/apache/rocketmq/auth/authentication/builder/DefaultAuthenticationContextBuilder.java
auth/src/main/java/org/apache/rocketmq/auth/authorization/builder/DefaultAuthorizationContextBuilder.java

Fixes #8046
Fix authentication context build for no extFields
start producer/consumer without ak/sk

[ISSUE #8046] Fix authentication context build for no extFields

---

client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java

[ISSUE #5838] retry to send when broker returns SYSTEM_BUSY

---

client/src/main/java/org/apache/rocketmq/client/consumer/rebalance/AllocateMessageQueueAveragely.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java

[ISSUE #8118] Remove redundant mod in client

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalancePushImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/latency/LatencyFaultToleranceImpl.java
client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java

[ISSUE #8145] Optimize some code style in client module

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java

Fixes #8148
variable typo
variable typo

[ISSUE #8148] Fix variable typo

---

broker/src/main/java/org/apache/rocketmq/broker/filter/CommitLogDispatcherCalcBitMap.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java

[ISSUE#8142] Show time of create topic and subScriptionGroup

---

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java

[ISSUE #8164] Log more accurate for the MQClientInstance#doRebalance

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
example/src/main/java/org/apache/rocketmq/example/benchmark/BatchProducer.java
example/src/main/java/org/apache/rocketmq/example/benchmark/Producer.java

Fixes #8166 
Configure production compression at the producer instance level instead of at the process level.
Producer configure the compression type with "ZSTD", and send message who's body over 4KB, debug the compression type producer use is ZSTDCompressor.

[ISSUE #8166]optimize: make compression type configurable in producer clinet level

---

example/src/main/java/org/apache/rocketmq/example/operation/Consumer.java

Fixes #8182 
Change the variable name 'group' to 'subGroup' and change the variable name 'subscription' to 'subExpression'
Start namesvr and broker, set namesvr in the code, set parameters, then run producer and consumer, run well, and the message can be sent and consumed

[ISSUE #8182] Modify variable names to enhance readability #8182

---

client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java

[ISSUE #8168] fix: There's no need to retry when async produce already timeout

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/FileRegionEncoder.java
remoting/src/test/java/org/apache/rocketmq/remoting/netty/FileRegionEncoderTest.java

Reverts apache/rocketmq#7694
fixes #8205

Revert "[ISSUE #7757] Use `CompositeByteBuf` to prevent memory copy."

---

broker/src/main/java/org/apache/rocketmq/broker/processor/SendMessageProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/SendMessageProcessorTest.java

[ISSUE #8053] Return SYSTEM_BUSY if PutMessageStatus is OS_PAGE_CACHE_BUSY

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

[ISSUE #8235]Add @Override annotation for handleDiskFlush method

---

acl/src/main/java/org/apache/rocketmq/acl/plain/PlainAccessResource.java
auth/src/main/java/org/apache/rocketmq/auth/authorization/builder/DefaultAuthorizationContextBuilder.java

[ISSUE 8230]fix the acl for NotifyClientTerminationRequest because group can be null

---

docs/cn/msg_trace/user_guide.md

Fix typo 'message' in user_guide.md

[ISSUE #8245]Fix typo in user_guide.md

---

broker/src/main/java/org/apache/rocketmq/broker/longpolling/NotifyMessageArrivingListener.java
broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopLongPollingService.java
broker/src/main/java/org/apache/rocketmq/broker/longpolling/PopRequest.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

[ISSUE #8269] Support pop consumption filter in long polling service

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

Fixes #8268
Fix pop orderly commitOffset when NO_MATCHED_MESSAGE

[ISSUE #8268] Fix pop orderly commitOffset when NO_MATCHED_MESSAGE

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/CreateTopicListRequestBody.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/CreateTopicListRequestHeader.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicListSubCommand.java
tools/src/test/java/org/apache/rocketmq/tools/command/topic/UpdateTopicListSubCommandTest.java

[ISSUE #8265] Implement Batch Creation of Topics in RocketMQ Admin

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
store/src/test/java/org/apache/rocketmq/store/ReputMessageServiceTest.java

Fixes #8239 
Under the condition of synchronous disk flushing, unflushed messages should be unacknowledged messages. Such messages should not be consumed prematurely, as this would lead to the consumption offset moving forward, resulting in potential phantom reads and message loss on the consumer side.
Therefore, in this PR, the dispatch offset of the ConsumeQueue is restricted to be before the disk flush offset to prevent consumers from experiencing phantom reads.
Add a UT

[ISSUE #8239] Fix the issue of potential message loss after a crash under synchronous disk flushing configuration.

---

.github/workflows/pr-e2e-test.yml
.github/workflows/push-ci.yml
.github/workflows/snapshot-automation.yml

Some actions have environment dependencies, and firing them from a personal repository is not only a waste of resources but also not successful.

Restrict some actions to be triggered only in the official repository

---

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java

[ISSUE #8227] Repeated merging in the constructor

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java

* change pop log level to debug when all the revive messages are handled
Fixes #8281
change pop log level to debug when all the revive messages are handled

[ISSUE #8281] Optimize pop log level

---

common/src/main/java/org/apache/rocketmq/common/message/MessageDecoder.java

[ISSUE #8293]Remove the redundant code from the MessageDecoder#encodeMessage method

---

broker/src/main/java/org/apache/rocketmq/broker/latency/BrokerFastFailure.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

Fixes #7466
Added fast failure in adminBrokerThreadPoolQueue
mvn test

[ISSUE #7466] Added fast failure in adminBrokerThreadPoolQueue (#7466)

---

client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java

Fixes https://github.com/apache/rocketmq/issues/8300 .
before:
after:

[ISSUE #8300] Add more test coverage for DefaultMQProducer

---

common/src/main/java/org/apache/rocketmq/common/thread/ThreadPoolMonitor.java
proxy/src/main/resources/rmq.proxy.logback.xml

[ISSUE #8291] format proxy watermark output

---

client/src/test/java/org/apache/rocketmq/client/producer/selector/DefaultMQProducerImplTest.java

[ISSUE #8324] Add more test coverage for DefaultMQProducerImpl

---

proxy/src/main/java/org/apache/rocketmq/proxy/processor/ConsumerProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalMessageService.java

Reverts apache/rocketmq#7687
In cluster mode, when the proxy sets borntime, and there is a clock synchronization issue between the proxy and the broker, it could cause the requests sent by the proxy to the broker to return POLLING_TIMEOUT, ultimately leading to request failures.

Revert "[ISSUE #7686] The bornTime is not set when using the popMessage API in cluster mode."

---

client/src/test/java/org/apache/rocketmq/client/impl/MQClientAPIImplTest.java

[ISSUE #8343] Add more test coverage for MQClientAPIImpl

---

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java

Fixes #8336
Adjust the default value of ackMessageThreadPoolNums to 16 to prevent performance bottlenecks during high traffic

[ISSUE #8336] Adjust the default value of ackMessageThreadPoolNums to 16 to prevent performance bottlenecks during high traffic

---

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java

Fixes #8352
Fix CLIENT_REGISTER behavior in ConsumerManager#registerConsumer

[ISSUE #8352] Fix CLIENT_REGISTER behavior in ConsumerManager#registerConsumer

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/latency/BrokerFastFailure.java
broker/src/test/java/org/apache/rocketmq/broker/latency/BrokerFastFailureTest.java

Fixes #8348
Allow custom fast-failure queues to be added in BrokerFastFailure

[ISSUE #8348] Allow custom fast-failure queues to be added in BrokerFastFailure

---

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
common/src/main/java/org/apache/rocketmq/common/MixAll.java
common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/ProxyTopicRouteData.java

[ISSUE #8298] optimize some code format or style

---

client/src/test/java/org/apache/rocketmq/client/impl/MQAdminImplTest.java

[ISSUE #8360] Add more test coverage for MQAdminImpl

---

acl/pom.xml
auth/pom.xml
broker/pom.xml
client/pom.xml
common/pom.xml
container/pom.xml
controller/pom.xml
distribution/pom.xml
example/pom.xml
filter/pom.xml
namesrv/pom.xml
openmessaging/pom.xml
pom.xml
proxy/pom.xml
remoting/pom.xml
srvutil/pom.xml
store/pom.xml
test/pom.xml
tieredstore/pom.xml
tools/pom.xml

[maven-release-plugin] prepare release rocketmq-all-5.3.0

---

client/src/test/java/org/apache/rocketmq/client/impl/admin/MqClientAdminImplTest.java

[ISSUE #8375] Add more test coverage for MqClientAdminImpl

---

client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExt.java
client/src/test/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExtTest.java

Enhancement #8365
add remoting client non-oneway updateConsumerOffset function
add some new unit test

[ISSUE #8365] add remoting client non-oneway updateConsumerOffset function

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java

[ISSUE #8372] Add more test coverage for AdminBrokerProcessor

---

broker/src/test/java/org/apache/rocketmq/broker/processor/QueryMessageProcessorTest.java

[ISSUE #8392] add tests for QueryMessageProcessor

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

… a channel, no longer acquire a read lock.
Fixes #8366 
`ChannelWrapper.getChannel()` needs to hold the read lock. When determining if `ChannelWrapper` is the wrapper for a channel, no longer acquire a read lock.

[ISSUE #8366] Eliminate deadlocks during the client shutdown process.

---

broker/src/test/java/org/apache/rocketmq/broker/processor/ConsumerManageProcessorTest.java

[ISSUE #8400] add tests for ConsumerManageProcessor

---

client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImplTest.java

[ISSUE #8411] Add more test coverage for DefaultMQPushConsumerImpl

---

common/src/test/java/org/apache/rocketmq/common/BrokerConfigSingletonTest.java

add test case for  BrokerConfigSingleton in commom module
Fixes #8413 
add test case for  BrokerConfigSingleton in commom module by using tongyi tools.
run test case successfull.

[ISSUE #8413]add some test cases for commom module

---

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java
store/src/main/java/org/apache/rocketmq/store/logfile/MappedFile.java
store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java
store/src/main/java/org/apache/rocketmq/store/queue/SparseConsumeQueue.java

Fixes #8405
Add the ability to write ConsumeQueue using fileChannel to prevent JVM crashes in some situations

[ISSUE #8405] Add the ability to write ConsumeQueue using fileChannel to prevent JVM crashes in some situations

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
broker/src/test/java/org/apache/rocketmq/broker/processor/PopMessageProcessorTest.java

- fix #8402 
- fix typo and make method public access

[ISSUE #8402] Fix init retry topic offset incorrect when EscapeBridge enabled

---

broker/src/test/java/org/apache/rocketmq/broker/slave/SlaveSynchronizeTest.java

[ISSUE #8421]add more test coverage for SlaveSynchronize

---

common/src/test/java/org/apache/rocketmq/common/AclConfigTest.java

[Enhancement] Add test cases for org.apache.rocketmq.common.AclConfig #8417
Fixes #8417
add some test cases for org.apache.rocketmq.common.AclConfig.
run test case successfull.

[ISSUE #8417]add some test cases for org.apache.rocketmq.common.AclConfig

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java

[ISSUE #8409] Fix tiered storage roll file logic if committing the last part of a file failed

---

client/src/test/java/org/apache/rocketmq/client/impl/ClientRemotingProcessorTest.java

[ISSUE #8437] Add more test coverage for ClientRemotingProcessor

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreFile.java

Fix broker return two messages when query message and index service bug
Fixes #8438

[ISSUE #8438] Fix broker return two messages when query message and index service bug

---

client/src/test/java/org/apache/rocketmq/client/impl/factory/MQClientInstanceTest.java

[ISSUE #8446] Add more test coverage for MQClientInstance

---

controller/src/main/java/org/apache/rocketmq/controller/impl/heartbeat/DefaultBrokerHeartbeatManager.java
controller/src/main/java/org/apache/rocketmq/controller/impl/heartbeat/RaftBrokerHeartBeatManager.java

Fixes #8454
active brokers number should be initailized to 1 in broker heartbeat manager.
wait to add test cases for this two class.

[ISSUE #8454] Active brokers number should be initailized to 1 in broker heartbeat manager.

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

Fixes #8448
CommitLog class function doAppend Annotation optimize
Don't need test

[ISSUE #8448] commitlog class annotation optimize

---

client/src/main/java/org/apache/rocketmq/client/ClientConfig.java
client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java
client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java
client/src/main/java/org/apache/rocketmq/client/trace/TraceDataEncoder.java

Fixes #8429
当客户端消息生成或者消费tps较高时，轨迹消息batch量会比较大，由于之前没限制batch size，当batch size太大时候会出现轨迹消息丢失
When the TPS (Transactions Per Second) of client message generation or consumption is high, the batch size of trajectory messages can become quite large. Due to the lack of a batch size limit previously, when the batch size becomes too large, there is a probabilistic loss of trajectory messages.

[ISSUE #8429] Fix trace message loss when traffic is heavy

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/RequestResponseFuture.java

[ISSUE #8261]Avoid unnecessary waiting when a response is successfully returned

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyService.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java

[ISSUE #8332] fix: ack msg which has reached maxReconsumeTimes

---

distribution/bin/runbroker.cmd

https://github.com/apache/rocketmq/issues/7731
Fixes #7731 
the problem of runBroker.cmd cannot start is that  in windows env, we need  double quotation marks to variable environment path.

[ISSUE #7731] Fix runBroker.cmd cannot start on Windows (#7731)

---

client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyServiceTest.java

[ISSUE #8465] Add more test coverage for ConsumeMessagePopConcurrentlyService

---

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

Fixes #8432
Make autoDeleteUnusedStats default to true

[ISSUE #8432] Make autoDeleteUnusedStats default to true

---

common/src/main/java/org/apache/rocketmq/common/stats/Stats.java
store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
store/src/test/java/org/apache/rocketmq/store/stats/BrokerStatsManagerTest.java

Fixes #8463
Some statistical items should also be deleted to prevent memory leakage when a topic or group is deleted

[ISSUE #8463] Some statistical items should also be deleted to prevent memory leakage when a topic or group is deleted

---

client/src/test/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyServiceTest.java

We are not fixing existing issues in this commit.
Changes proposed in this pull request:
We put all the initialization of the mocks and variables into the method body of @BeforeAll and @AfterAll. There are two tests in the test class ConsumeMessageConcurrentlyServiceTest. However, these two tests are not affecting each other.
The test runtime can jump from 2.771 s to 1.768 s after applying the changes when run on our machine.
We just ran this test class in any order and it passes. We ran this test class 10 times and it also passes. We also ran all tests in client module 10 times, and there are no changes for the test results.

only initialize all the variables once to speed up test ConsumeMessageConcurrentlyServiceTest

---

broker/BUILD.bazel
broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java
broker/src/main/java/org/apache/rocketmq/broker/out/BrokerOuterAPI.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java
broker/src/test/java/org/apache/rocketmq/broker/failover/EscapeBridgeTest.java
broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java
store/src/main/java/org/apache/rocketmq/store/pop/PopCheckPoint.java

Enhancement #8460 
1.  provide extra information to the call chain of remote message reading
2. an exponential backoff and ending condition of CK rewrite

[ISSUE #8460] Improve the pop revive process when reading biz messages from a remote broker

---

broker/src/test/java/org/apache/rocketmq/broker/processor/PeekMessageProcessorTest.java

[ISSUE #8495]add more test coverage for PeekMessageProcessor

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/MessageStoreConfig.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileStore.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexService.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImplTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFileTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/index/IndexStoreServiceTest.java

[ISSUE #8481] Improve delete and rolling strategy for tiered storage modules
Fixes #8481

[ISSUE #8481] Improve delete and rolling strategy for tiered storage modules

---

broker/src/test/java/org/apache/rocketmq/broker/metrics/BrokerMetricsManagerTest.java

Fixes #8486  
Add more test coverage.
Before:
After:
All tests passed.
PS: TONGYI Lingma provided code generation and programming support.

[ISSUE #8486]Add more test coverage for BrokerMetricsManager

---

broker/src/test/java/org/apache/rocketmq/broker/offset/RocksDBLmqConsumerOffsetManagerTest.java

[Enhancement] Add more test coverage for RocksDBLmqConsumerOffsetManager
Fixes #8500
Add more test coverage for RocksDBLmqConsumerOffsetManager
run test case successfull.
PS: TONGYI Lingma provided code generation and programming support.

[ISSUE #8500] Add more test coverage for RocksDBLmqConsumerOffsetManager

---

.github/workflows/pr-e2e-test.yml
.github/workflows/push-ci.yml

Fixes [#8510 ](https://github.com/apache/rocketmq/issues/8510)
This pull request updates the Test E2E golang job in th push-ci and pr-e2e-test  pipeline by adding a command to install the correct version of Go directly in the startup script. The previous setup was causing issues due to the Go version being too low, which led to compatibility problems during the execution of Go e2e tests.

[ISSUE #8510] Fix CI Failure in Test E2E Golang Job of PUSH-CI and PR-E2E-TEST

---

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/ClientManagerActivity.java

Fixes #8517
client send UNREGISTER_CLIENT request twice may cause proxy NPE
check channel is null before use it, if channel is null, log warn instead of NPE

[ISSUE #8517] Fix client send UNREGISTER_CLIENT request twice may cause proxy NPE

---

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java
broker/src/test/java/org/apache/rocketmq/broker/failover/EscapeBridgeTest.java
broker/src/test/java/org/apache/rocketmq/broker/processor/PopReviveServiceTest.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

Enhancement https://github.com/apache/rocketmq/issues/8460, part-2
advice from @lizhimins 
1. do retry when TieredMessageStore returns GetMessageStatus.OFFSET_FOUND_NULL
2. add a switch whether to continue to rewrite CK after max times

[ISSUE #8460] Improve the pop revive process when reading biz messages from a remote broker - part2

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java

[ISSUE #8532] Fix flush metadata when commit file because of full file

---

pom.xml

Fixes #8531
Update jaeger-thrift, exclude unnecessary tomcat-embed-core
```
[INFO] +- io.jaegertracing:jaeger-thrift:jar:1.8.1:compile
[INFO] |  \- org.apache.thrift:libthrift:jar:0.15.0:compile
[INFO] |     \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
```

[ISSUE #8531]Update jaeger-thrift, exclude unnecessary tomcat-embed-core

---

client/src/main/java/org/apache/rocketmq/client/trace/TraceBean.java
common/src/main/java/org/apache/rocketmq/common/UtilAll.java
common/src/main/java/org/apache/rocketmq/common/utils/NetworkUtil.java

Fix the following three as
1，TraceBean： private static final String LOCAL_ADDRESS = UtilAll.ipToIPv4Str(UtilAll.getIP()); getIP mayby ipv6
2，NetworkUtil：if (ip.startsWith("127.0") || ip.startsWith("192.168") || ip.startsWith("0."))；Check whether Intranet errors exist
Fixes #8289

[ISSUE #8289] Fixed network bugs and merged networkutil code

---

.github/workflows/bazel.yml
.github/workflows/maven.yaml
.github/workflows/rerun-workflow.yml

Fixes [#8544](https://github.com/apache/rocketmq/issues/8544)
This pull request introduces a retry mechanism in the unit test pipeline to automatically retry failed unit tests up to two times. 
- The retry mechanism relies on GitHub Actions with write permissions to trigger a new workflow run. As a result, only users with write access will be able to utilize the retry mechanism.This limitation is documented in the [GitHub Actions documentation](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/re-running-workflows-and-jobs)
- Contributors without write permissions will not be able to trigger retries if their tests fail during a pull request. This could lead to cases where their pull requests require manual intervention from maintainers if a …

[ISSUE #8544] Add a retry mechanism to the unit test pipeline

---

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java

Fixes #8534
Since the topic of the current timer message is not registered with ns, there is a problem with queryMessage queries directly through the SDK. The dashboard also does not allow you to select this topic

[ISSUE #8534] Supports timer message queries

---

.github/workflows/bazel.yml
.github/workflows/maven.yaml
.github/workflows/rerun-workflow.yml

Fixes [#8564](https://github.com/apache/rocketmq/issues/8565)
This PR updates the workflow to explicitly set GH_TOKEN with actions: write permission, ensuring that the retry mechanism can trigger after a workflow failure

[ISSUE #8565] Set specific permissions to trigger the workflow retry mechanism

---

broker/src/test/java/org/apache/rocketmq/broker/offset/RocksDBOffsetSerializeWrapperTest.java
namesrv/src/test/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHookMoreTest.java
namesrv/src/test/java/org/apache/rocketmq/namesrv/route/ZoneRouteRPCHookTest.java

[ISSUE #8553] Add UnitTest of OffsetSerialize

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

Fixes #8549
ipv6 enabled in broker, pickupStoreTimestamp size should be 20

[ISSUE #8549] Ipv6 enabled in broker, pickupStoreTimestamp size should be 20

---

proxy/src/main/java/org/apache/rocketmq/proxy/service/receipt/DefaultReceiptHandleManager.java

[ISSUE #8555] Make ctx constructed in scheduleRenewTask

---

.github/workflows/maven.yaml
broker/src/main/java/org/apache/rocketmq/broker/RocksDBConfigManager.java
broker/src/main/java/org/apache/rocketmq/broker/offset/RocksDBConsumerOffsetManager.java
broker/src/main/java/org/apache/rocketmq/broker/subscription/RocksDBSubscriptionGroupManager.java
broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
broker/src/main/java/org/apache/rocketmq/broker/topic/RocksDBTopicConfigManager.java
broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java
broker/src/test/java/org/apache/rocketmq/broker/subscription/RocksdbGroupConfigTransferTest.java
broker/src/test/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManagerTest.java
broker/src/test/java/org/apache/rocketmq/broker/topic/RocksdbTopicConfigManagerTest.java
broker/src/test/java/org/apache/rocketmq/broker/topic/RocksdbTopicConfigTransferTest.java
broker/src/test/java/org/apache/rocketmq/broker/topic/TopicConfigManagerTest.java
common/src/main/java/org/apache/rocketmq/common/ConfigManager.java
common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java
common/src/main/java/org/apache/rocketmq/common/config/ConfigRocksDBStorage.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java

[ISSUE #8058] Support for upgrading metadata in json to rocksdb (#8045)

---

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java

[ISSUE #8573] Correct mismatched comments

---

docs/cn/SlaveActingMasterMode.md

fix document typo in SlaveActingMasterMode.md.Change RoccketMQ to RocketMQ.

fix document typo in SlaveActingMasterMode.md

---

.github/workflows/maven.yaml

Fixes [#8544 ](https://github.com/apache/rocketmq/issues/8544)
This PR reintroduces the retry mechanism for the CI workflow, which was inadvertently removed due to a merge conflict

[ISSUE #8544] Restore retry mechanism in unit test pipeline

---

broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessorTest.java
example/src/main/java/org/apache/rocketmq/example/simple/LMQProducer.java
example/src/main/java/org/apache/rocketmq/example/simple/LMQPullConsumer.java
example/src/main/java/org/apache/rocketmq/example/simple/LMQPushConsumer.java
example/src/main/java/org/apache/rocketmq/example/simple/LMQPushPopConsumer.java

Fixes #8137
Support server-side rebalance for light message queues.
Add light message queue consume demos.
UT, local test

[ISSUE #8137] Support pop consumption for light message queue

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
broker/src/test/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManagerTest.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/body/SubscriptionGroupList.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java
tools/src/main/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupListSubCommand.java
tools/src/test/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupListSubCommandTest.java

[ISSUE #8576] Support Creating or Updating Subscription Groups in Batch

---

client/src/test/java/org/apache/rocketmq/client/producer/selector/SelectMessageQueueByRandomTest.java

[ISSUE #8586] Add more test coverage for SelectMessageQueueByRandom

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

[ISSUE #8592] Not notify long polling request when pop orderly consume blocked

---

common/src/main/java/org/apache/rocketmq/common/utils/NetworkUtil.java

Fixes [#8607](https://github.com/apache/rocketmq/issues/8607) 
This PR addresses an issue in the `NetworkUtil` class where the loopback address (`127.0.0.1`) might be mistakenly selected when all available IP addresses are internal. The fix involves ensuring that loopback addresses are excluded when traversing `localInetAddressList`.
[The test workflow](https://github.com/chi3316/rocketmq/actions/runs/10615521348)

[ISSUE #8607] Exclude loopback addresses when iterating over local network interfaces

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
store/src/test/java/org/apache/rocketmq/store/dledger/MessageStoreTestBase.java

Fixes #8601
When isPopShouldStop hit，unlock queueLockManager
review the code

[ISSUE #8601]When isPopShouldStop hit,unlock queueLockManager

---

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java
client/src/test/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImplTest.java

[ISSUE #8584] fix missing brokerName in sendMessageBack request

---

.github/workflows/maven.yaml
store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java
store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java
store/src/test/java/org/apache/rocketmq/store/dledger/MixCommitlogTest.java

Fixes [#8623 ](https://github.com/apache/rocketmq/issues/8623)
This PR temporarily skips specific unit tests on macOS due to observed failures related to high IO operations in the CI environment. These issues are causing tests to fail inconsistently, particularly on GitHub's macOS runners.

[ISSUE #8623] Temporarily skip flaky unit tests on macOS

---

.github/workflows/bazel.yml
.github/workflows/maven.yaml

Fixes [#8596 ](https://github.com/apache/rocketmq/issues/8596)
Removed the redundant mvn test step and the separate JVM crash log check from the CI workflow. These changes simplify the process and improve efficiency.

[ISSUE #8596] Remove redundant mvn test and log check steps from CI workflow

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerCommitlogTest.java
store/src/test/java/org/apache/rocketmq/store/dledger/DLedgerMultiPathTest.java
store/src/test/java/org/apache/rocketmq/store/dledger/MixCommitlogTest.java

…ddress can be configured.
Fixes #8609

[ISSUE #8609] Add the BrokerConfig updateNameServerAddrPeriod

---

.github/workflows/integration-test.yml
pom.xml
test/src/test/java/org/apache/rocketmq/test/client/consumer/pop/NotificationIT.java
test/src/test/java/org/apache/rocketmq/test/grpc/v2/ClusterGrpcIT.java
test/src/test/java/org/apache/rocketmq/test/grpc/v2/LocalGrpcIT.java

Fixes [#8643 ](https://github.com/apache/rocketmq/issues/8643)
This PR adds a new integration testing pipeline to the current testing workflow. The pipeline will run in parallel with the unit test pipeline, ensuring that integration tests are executed without impacting the overall CI efficiency.
[The test workflows](https://github.com/chi3316/rocketmq/actions/workflows/integration-test.yml)

[ISSUE #8643] Add an integration testing pipeline to current CI workflow

---

client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java

[ISSUE #8599] Fix send fail without retry when get GO_AWAY twice

---

broker/src/test/java/org/apache/rocketmq/broker/client/net/Broker2ClientTest.java

[ISSUE #8640] Add more test coverage for Broker2Client

---

broker/src/test/java/org/apache/rocketmq/broker/controller/ReplicasManagerRegisterTest.java

[ISSUE #8649] Fix Generate coverage report ci error

---

broker/src/main/java/org/apache/rocketmq/broker/subscription/LmqSubscriptionGroupManager.java
broker/src/main/java/org/apache/rocketmq/broker/subscription/RocksDBLmqSubscriptionGroupManager.java

Fixes #8647 
If it is a group of lmq, return true directly during the check.

[ISSUE #8647] Fix the issue where lmq cannot update consumer offset

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

[ISSUE #8657] Make retry topic pop probability configurable

---

.github/workflows/integration-test.yml
client/src/test/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumerTest.java
client/src/test/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumerTest.java
test/src/test/java/org/apache/rocketmq/test/client/consumer/balance/NormalMsgDynamicBalanceIT.java

Fixes [#8668 ](https://github.com/apache/rocketmq/issues/8668)
- Added a step to upload test reports in the integration testing pipeline to handle large log files that need to be manually downloaded for review.
- Fixed instability issues with several unit tests in the macOS CI pipeline.
- Addressed occasional failures in certain integration test cases.

[ISSUE #8668] Improve CI pipeline reliability with better log viewing and test fixes

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/index/IndexStoreServiceTest.java

[ISSUE #8653] Fix index service upload last file when broker shutdown and fetcher check in tiered storage

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

Change-Id: I9dd6a4e6074cf0e16fab51cdda57e37b116636ed
Fixes #8660 
Since the `findConsumeQueue` will create the ConsumeQueue info if not exist, we should not use it in read only functions to avoid create not exist topic consume queue by accident.

[ISSUE #8660] feat: should use read only getConsumeQueue instead of findConsumeQueue in read only func

---

broker/src/test/java/org/apache/rocketmq/broker/client/rebalance/RebalanceLockManagerTest.java

[ISSUE #8665] Add more test coverage for RebalanceLockManager

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

[ISSUE #8669] Fix crc 32 overflow when lmq

---

auth/src/main/java/org/apache/rocketmq/auth/authorization/builder/DefaultAuthorizationContextBuilder.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/protocol/http2proxy/HAProxyMessageForwarder.java

[ISSUE #8259] fix parse ipv6 from address in haproxy

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

Fixes #8599 
1.    Reconnect condition may not be satisfied when rolling update proxy because of the reconnect interval 60 seconds
2.   Sending retry request without extFields may fail
1.  Fix send fail with receiving GO_AWAY when rolling update proxy
3. Add channel id in logs
4. Send retry request with extFields when receiving GO_AWAY

[ISSUE #8599] Fix send fail with receiving GO_AWAY when rolling update proxy and add channel id in logs

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java

When the defaultLitePullConsumer executes the setPullThreadNums method to set the number of threads, the thread pool has already been created, so the thread pool is placed in start to delay creation.

[ISSUE #8695] fix DefaultLitePullConsumer PullThreadNums Parameter not effective.

---

auth/src/main/java/org/apache/rocketmq/auth/authorization/factory/AuthorizationFactory.java

[ISSUE #8613] fix start failed when acl2.0 authentication enabled and authorization disabled

---

.github/workflows/pr-e2e-test.yml
.github/workflows/push-ci.yml
.github/workflows/snapshot-automation.yml

Fixes [#8707](https://github.com/apache/rocketmq/issues/8707)
After upgrading @actions/upload-artifact to v4, @actions/download-artifact wasn't updated, causing issues with downloading artifacts. This PR upgrades both actions to v4, resolving the issue and allowing the artifact to be downloaded successfully.

[ISSUE #8707] Fix artifact download failure in CI after action upgrade

---

test/src/test/java/org/apache/rocketmq/test/route/CreateAndUpdateTopicIT.java

[ISSUE #8718] Fix flaky CreateAndUpdateTopicIT

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
docs/cn/best_practice.md
docs/en/Configuration_Client.md

[ISSUE #8604] Fix doc typo

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

…ient is no longer in use, a new channel connection will be created.
Fixes #8712

[ISSUE #8712] Set namesrvAddrChoosed to null if choosed addr is not exist.

---

.github/workflows/bazel.yml
.github/workflows/maven.yaml
.github/workflows/rerun-workflow.yml

Fixes [#8742 ](https://github.com/apache/rocketmq/issues/8742)
- Modified the retry mechanism to use the workflow_run event instead of manual rerun.
- Resolved permission issues preventing retry on PR submission.
- Improved automation and stability of unit tests.
I tested the change by submitting a PR to my own repository and deliberately introducing errors to check if the retry mechanism would trigger. The result was successful, confirming that the retry function works as intended.
[The test workflow](https://github.com/chi3316/rocketmq/actions/runs/11009360256/job/30568890778?pr=3)

[ISSUE #8742] Enhance unit test retry mechanism to trigger on PR submission

---

tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java

[ISSUE #8740] fix rocksDBConfigToJson command

---

.github/workflows/pr-e2e-test.yml

Fixes [#8747 ](https://github.com/apache/rocketmq/issues/8747)
This PR resolves the issue with downloading artifacts in the PR E2E workflow by updating the script for downloading the rocketmq artifact. The previous error has been fixed to ensure the workflow runs correctly.
It can download artifacts correctly. [The test workflow](https://github.com/chi3316/rocketmq/actions/runs/11025091707/job/30619381260)

[ISSUE #8747] Fix PR E2E artifact download issue

---

tools/src/main/java/org/apache/rocketmq/tools/command/message/PrintMessageSubCommand.java

Fixes #8784
PrintMessageSubCommand support lmq

[ISSUE #8784] PrintMessageSubCommand support lmq

---

proxy/src/main/java/org/apache/rocketmq/proxy/common/utils/GrpcUtils.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/interceptor/AuthenticationInterceptor.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/interceptor/HeaderInterceptor.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/pipeline/AuthenticationPipeline.java

Add Utils for put header to gRPC Metadata to avoid duplicate data.
Fixes #8790

[ISSUE #8790] Add Utils for put header to Metadata to avoid duplicate data

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PeekMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/ReplyMessageProcessor.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQBroadCastConsumer.java
test/src/main/java/org/apache/rocketmq/test/clientinterface/AbstractMQConsumer.java

[ISSUE #8798] Fix typo

---

broker/src/main/java/org/apache/rocketmq/broker/offset/LmqConsumerOffsetManager.java

Fixes #8804 
implement the clean offset,then we invoke deleteSubscriptionGroup ,we can clean

[ISSUE #8804] clean offset when remove group offset

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java
client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java

Fixes #8806
1. Delay the creation of the ProducerAccumulator until startup. Since instanceName will change at startup, and unitName should already be set at this time.
2. Due to delaying the ProducerAccumulator to create, in order to allow users to set the parameters of batchMaxDelayMs, batchMaxbytes, and totaled BatchMaxbytes in the Producer Accumulator before executing the start method (Because I am worried that some users may set these parameters before executing start), three properties have been added to the DefaultMQProducer. After the ProducerAccumulator is initialized, it is assigned to the ProducerAccumulator.
I have tested locally and confirmed that it will not be sent to other RocketMQ clusters, and the parameter settings can take effect.

[ISSUE #8806] Fix autoBatch bug when connecting multiple RocketMQ clusters.

---

.github/workflows/push-ci.yml

Fixes [#8810 ](https://github.com/apache/rocketmq/issues/8810)
This PR modifies the workflow to ensure that the e2e and benchmark deployments are independent. If one deployment fails, it no longer blocks the execution of the other deployment's tasks.
[The test workflow](https://github.com/chi3316/rocketmq/actions/runs/11285198990)

[ISSUE #8810] Fix independent execution of e2e and benchmark deployments

---

store/src/main/java/org/apache/rocketmq/store/ConsumeQueue.java
store/src/main/java/org/apache/rocketmq/store/RocksDBMessageStore.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueue.java
store/src/test/java/org/apache/rocketmq/store/queue/ConsumeQueueTest.java

[ISSUE #8764] Implement consume lag estimation in cq rocksdb store

---

broker/src/main/java/org/apache/rocketmq/broker/failover/EscapeBridge.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AckMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java
broker/src/test/java/org/apache/rocketmq/broker/processor/ChangeInvisibleTimeProcessorTest.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalMessageService.java
proxy/src/test/java/org/apache/rocketmq/proxy/service/message/LocalMessageServiceTest.java
test/src/test/java/org/apache/rocketmq/test/base/IntegrationTestBase.java

Fixes #8780
Implement asynchronous storage of ack/ck messages in pop consume to enhance performance

[ISSUE #8780] Implement asynchronous storage of ack/ck messages in pop consume to enhance performance

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopBufferMergeService.java

[ISSUE #8835]When ck is in the buffer, incomplete ack will lead to message duplication.

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ResetOffsetRequestHeader.java

Fixes #8820
The class `ResetOffsetRequestHeader` set wrong `@RocketMQResource` value in fields `topic`, `group`.
No test.

fix variables match annotation (@RocketMQResource)

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
common/src/main/java/org/apache/rocketmq/common/statistics/StatisticsBriefInterceptor.java
common/src/main/java/org/apache/rocketmq/common/statistics/StatisticsItemScheduledIncrementPrinter.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/statictopic/TopicQueueMappingUtils.java
store/src/main/java/org/apache/rocketmq/store/timer/TimerLog.java
test/src/main/java/org/apache/rocketmq/test/util/MQAdminTestUtils.java
test/src/test/java/org/apache/rocketmq/test/client/consumer/broadcast/order/OrderMsgBroadcastIT.java

Fixes #8848
Some `log` messages contains typo. Like `TopicQueueMappingUtils`, `StatisticsItemScheduledIncrementPrinter`.
No test.

[ISSUE #8848] Fix log typo

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyLogger.java

Fixes #8850
The `NettyBridgeLogger#trace` method should call `Logger#trace`, but it call `Logger#info` method.
No test.

[ISSUE #8850] Use correct log method

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java

[ISSUE #8772] Remove lock mq step in broadcasting mode rebalancing

---

broker/src/main/java/org/apache/rocketmq/broker/RocksDBConfigManager.java
broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBConsumerOffsetManager.java
broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBSubscriptionGroupManager.java
broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBTopicConfigManager.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/offset/RocksdbTransferOffsetAndCqTest.java
broker/src/test/java/org/apache/rocketmq/broker/subscription/RocksdbGroupConfigTransferTest.java
broker/src/test/java/org/apache/rocketmq/broker/topic/RocksdbTopicConfigManagerTest.java
broker/src/test/java/org/apache/rocketmq/broker/topic/RocksdbTopicConfigTransferTest.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
common/src/main/java/org/apache/rocketmq/common/CheckRocksdbCqWriteResult.java
common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java
common/src/main/java/org/apache/rocketmq/common/config/ConfigRocksDBStorage.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/CheckRocksdbCqWriteProgressRequestHeader.java
store/src/main/java/org/apache/rocketmq/store/RocksDBMessageStore.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
store/src/main/java/org/apache/rocketmq/store/rocksdb/RocksDBOptionsFactory.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/command/queue/CheckRocksdbCqWriteProgressCommand.java

Fixes #8822
1. Consolidate several parameters related to double-write CQ, now only retaining storeType and rocksdbCQWriteEnable, simplifying the configuration process.
2. Add configuration support for RocksDB CompressionType, while maintaining the default configuration unchanged.
3. Modifiy the implementation of checkRocksdbCqWriteProgress utility class, add asynchronous calling method to prevent long check times from blocking the admin thread.
描述：
1. 将几个和双写cq相关的参数进行了合并，目前只保留storeType和rocksdbCQWriteEnable，简化了配置流程
2. 增加了Rocksdb CompressionType的配置，默认配置不变
3. 修改了checkRocksdbCqWriteProgress 工具类实现，增加异步调用的方式，防止check时间太久阻塞admin线程

[ISSUE #8822] Double write cq, reduce unnecessary switches

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java
remoting/src/test/java/org/apache/rocketmq/remoting/protocol/RocketMQSerializableTest.java

Fixes #8868
**Description:**  
The following message request codes exceed the maximum value for a short integer (32767), resulting in an overflow. The original values are as follows:
```java
public static final int POP_MESSAGE = 200050;
public static final int ACK_MESSAGE = 200051;
public static final int BATCH_ACK_MESSAGE = 200151;
public static final int PEEK_MESSAGE = 200052;
public static final int CHANGE_MESSAGE_INVISIBLETIME = 200053;
public static final int NOTIFICATION = 200054;
public static final int POLLING_INFO = 200055;
```
**Actual Values After Overflow:**  
Due to the overflow, the actual values of these constants are:
```java
public static final int POP_MESSAGE = 3442;
public static final int ACK_MESSAGE = 3443;
public static final int BATCH_ACK_MESSAGE = 3543;
public …
```

fix RequestCode overflowed issues:8868

---

broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConfigStorage.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConsumerOffsetManagerV2.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/SubscriptionGroupManagerV2.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/ConsumerOffsetManagerV2Test.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/SubscriptionGroupManagerV2Test.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/TopicConfigManagerV2Test.java

to #8892 
Add unit test cases to ConfigManagerV2

[ISSUE #8892] Add test cases to config manager v2

---

store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAService.java

Fixes [#issue_id](https://github.com/apache/rocketmq/issues/8875)
在一些异常场景，可以模拟对ha端口的探活测试，由于conn.start会马上启动线程，在足够快失败的场景，会先执行removeConnection动作，而后再执行addConnection动作，最终造成connection泄漏，滞留 HaService 的connectionList里面，累积造成内存溢出风险。
使用python脚本进行ha端口10912的高频探活验证是否还存在内存泄漏
import sys
import socket
import time
sys.path.append(".")
def tcp_health_check(host, port):
now = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
try:
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(1)
sock.connect((host, port))
sock.sendall(now.encode())
print("{}TCP连接成功:{}:{}".format(now,host,port))
sock.close()
return True
except socket.error as e:
print("TCP连接失败: {}".format(e))
if sock:
sock.close()
return False
def main():
host = '127.0.0.1'  
port = 8081  
while True:
result = …

[ISSUE #8875] Fix HAConnection leak

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java

[ISSUE #8725]clean DefaultMQPushConsumer after start fail

---

broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConfigStorage.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/SubscriptionGroupManagerV2.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/TopicConfigManagerV2.java

Two minor changes are included:
1, no need to update data version while reload; 
2, config-storage fdatasync on write proves to be too expensive, turn it off
To #8829

[ISSUE #8829] Keep data version while reload and XXXConfigManagerV2 turns off sync

---

distribution/bin/runbroker.cmd
distribution/bin/runbroker.sh

Fixes #8808
JDK21 Unrecognized VM option 'UseBiasedLocking', ADD `-XX:+IgnoreUnrecognizedVMOptions` to make JDK21 happy.
start mqbroker,it works.

[ISSUE #8808] Resolve unsupported 'UseBiasedLocking' VM Option for JDK21

---

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
acl/src/main/java/org/apache/rocketmq/acl/plain/PlainPermissionManager.java
auth/src/main/java/org/apache/rocketmq/auth/authentication/chain/DefaultAuthenticationHandler.java

Change the compare method for acl signature to improve the security.
Fixes #8882
Use the MessageDigest.isEqual method instead of the StringUtils.equals method.

[ISSUE #8882]Change the compare method for acl signature to improve the security.

---

docs/cn/RocketMQ_Example.md

fixed typo worlds 'finalString'
Fixes just typo problem 'finalString' without issue
Fixes just typo problem 'finalString' without issue
Fixes just typo problem 'finalString' without issue

fixed typo of RocketMQ_Example.md

---

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/MultiProtocolTlsHelper.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/TlsHelper.java

Fixes #8906
Handle string toUpperCase outside the loop
No test.

[ISSUE #8906] Handle string toUpperCase outside the loop

---

remoting/src/main/java/org/apache/rocketmq/remoting/common/RemotingHelper.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java
remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingClient.java

Fixes #8599
1. Throw exception when receiving GO_AWAY twice to close channel.
2. Throw exception when receiving GO_AWAY and nor enableReconnectForGoAway

[ISSUE #8599] Throw exception when receiving GO_AWAY twice to close channel.

---

common/src/main/java/org/apache/rocketmq/common/constant/PermName.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/route/RouteActivity.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/route/RouteActivityTest.java

Fixes #8917
When the queue lacks permission, return queues to allow the client to upload a heartbeat for gRPC Topic route interface.

[ISSUE #8917]Topic route return none permission message queues for gRPC client 

---

common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java

Fixes #8909 
Move nullcheck ahead
No test.

[ISSUE #8909] Move nullcheck ahead

---

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java

[#ISSUE 8945] Remove unnecessary operations from the critical section

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

[ISSUE #8953] Improve IO for asynchronous delivery processes

---

store/src/main/java/org/apache/rocketmq/store/queue/AbstractConsumeQueueStore.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java

fix: avoid memory overhead when there is large number of LMQ CQ

---

client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java
client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java

[ISSUE #8933] feat: DefaultPullConsumer add balance switch.

---

WORKSPACE
pom.xml
proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/producer/SendMessageActivity.java

[ISSUE #8929] Proxy adds message body empty check when send in grpc protocol

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/PosixFileSegment.java

[ISSUE #8955] Fix message buffer not release and dispatch thread exit in tiered storage 
Fixes #8955

[ISSUE #8955] Fix message buffer not release and dispatch thread exit in tiered storage

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
store/src/main/java/org/apache/rocketmq/store/stats/LmqBrokerStatsManager.java

Fixes #8972
The current LMQ statistics are not enabled by default, presumably due to the large volume of data. However, there are times when we might need to obtain LMQ statistics. Therefore, a switch, enableLmqStats, has been added to control the collection of LMQ statistics at runtime

[ISSUE #8972] Adding the EnableLmqStats option allows monitoring of LMQ statistics at runtime

---

common/src/main/java/org/apache/rocketmq/common/utils/IPAddressUtils.java
proxy/src/main/java/org/apache/rocketmq/proxy/common/Address.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/GetTopicRouteActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/route/ProxyTopicRouteData.java
proxy/src/test/java/org/apache/rocketmq/proxy/common/AddressTest.java

Automatic recognition of address scheme in Topic Route by host.
Fixes #8961

[ISSUE #8961] Automatic recognition of address scheme in Topic Route by host

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java

Set default broker name when revive found ack without broker name field
POP CK 新旧格式兼容，为了尽可能的减少消费重复，当没有 brokerName 在 ack 信息里的时候自动补全
Fixes #8460

[ISSUE #8460] Set default broker name when revive found ack without broker name field

---

.github/workflows/pr-e2e-test.yml
.github/workflows/push-ci.yml

Fixes [#8982 ](https://github.com/apache/rocketmq/issues/8982)
This PR updates the pipeline script to dynamically install the latest stable version of Go, ensuring compatibility with dependencies.

[ISSUE #8982] Dynamically install latest Go version for e2e pipeline

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessorTest.java

Fixes #8984
Get topic type attribute by key "+message.type"
UT

[ISSUE #8984] Fix the broker switch enableMixedMessageType doesn't work

---

container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java

Fixes #8950 
Remove Redundant nullcheck
No test.

[ISSUE #8950] Remove Redundant nullcheck of configPath

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java

[ISSUE #8966] Feat: add remote address information to acl perm error

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConfigHelper.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConfigStorage.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/ConsumerOffsetManagerV2.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/SubscriptionGroupManagerV2.java
broker/src/main/java/org/apache/rocketmq/broker/config/v2/TopicConfigManagerV2.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/ConsumerOffsetManagerV2Test.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/SubscriptionGroupManagerV2Test.java
broker/src/test/java/org/apache/rocketmq/broker/config/v2/TopicConfigManagerV2Test.java
broker/src/test/java/org/apache/rocketmq/broker/offset/RocksdbTransferOffsetAndCqTest.java
common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java
common/src/main/java/org/apache/rocketmq/common/config/ConfigHelper.java
common/src/main/java/org/apache/rocketmq/common/config/ConfigRocksDBStorage.java
store/src/main/java/org/apache/rocketmq/store/CommitLog.java
store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksGroupCommitService.java
store/src/main/java/org/apache/rocketmq/store/rocksdb/RocksDBOptionsFactory.java

fix: multiple patches during long running tests for LMQ over RocksDB

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java

[ISSUE #9014] Fix clusterAclConfigVersion command execution failed

---

store/src/main/java/org/apache/rocketmq/store/stats/LmqBrokerStatsManager.java

Extracted the duplicated logic of replacing group and topic with LMQ_PREFIX based on configuration into a common method, improving code structure and maintainability.
Fixes [#9033](https://github.com/apache/rocketmq/issues/9033)
Refactor the LmqBrokerStatsManager class by extracting the common logic that modifies the group and topic values into a private helper method.

refactor(LmqBrokerStatsManager): Refactor Redundant Code in LmqBrokerStatsManager

---

store/src/test/java/org/apache/rocketmq/store/timer/TimerMessageStoreTest.java

Fixes [#9042 ](https://github.com/apache/rocketmq/issues/9042)
This PR resolves a compilation error caused by an outdated method parameter in `TimerMessageStoreTest`. The `createTimerMessageStore` method's parameters were updated previously, but a later PR did not rebase to the latest code, leading to mismatched method calls.

[ISSUE #9042] Update createTimerMessageStore call with new parameter

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java

[ISSUE #9021] Correct the error message of acl command

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/MessageStore.java
store/src/main/java/org/apache/rocketmq/store/plugin/AbstractPluginMessageStore.java

[ISSUE #8988] Support dispatchBehindMilliseconds

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java

[ISSUE #9054]Optimize log print when client consume message in pop mode

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

[ISSUE #9002]when bytebuffer is not enough, do not throw exception

---

auth/src/main/java/org/apache/rocketmq/auth/authorization/builder/DefaultAuthorizationContextBuilder.java

When a client fails to consume multiple times, a message is sent to the retry topic. If ACL 2.0 is used, querying the routing of the retry topic may result in a permission denied issue.
Fixes #9072
When obtaining the routing for the retry topic, authentication is performed according to the Group's permissions, and there is no need to separately authorize the retry topic.

[ISSUE 9072]Fix the permission check for retry topic to get topic route.

---

client/src/main/java/org/apache/rocketmq/client/impl/consumer/RebalanceImpl.java

[ISSUE #8957] Remove excess traffic and fix cache inconsistencies

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/GroupCommitContext.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileInterface.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/common/GroupCommitContextTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImplTest.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatMessageFileTest.java

[ISSUE #9069] Fix the IndexFile ConcurrentModificationException in tiered storage

---

common/src/main/java/org/apache/rocketmq/common/message/Message.java
common/src/main/java/org/apache/rocketmq/common/message/MessageConst.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ProducerProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/remoting/activity/SendMessageActivity.java

Fixes #9075
Avoid message type validate in message sync scenario.

[ISSUE #9075]Avoid message type validate in message sync scenario.

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImplTest.java

[ISSUE #9080] Fix tranfer logic when get large messages from cache in tiered storage

---

broker/src/main/java/org/apache/rocketmq/broker/processor/RecallMessageProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/processor/RecallMessageProcessorTest.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
test/src/test/java/org/apache/rocketmq/test/base/IntegrationTestBase.java

[ISSUE #8974] add feature switch of recalling, disable by default.

[ISSUE #8974] add feature switch of recalling, disable by default.

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java

[ISSUE #9080] Not hold final message store config in fetcher

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java

[ISSUE #9025] [RIP-73] Fix reset offset not effective in Pop Consumption

---

broker/src/main/java/org/apache/rocketmq/broker/pop/PopConsumerRocksdbStore.java
store/src/main/java/org/apache/rocketmq/store/rocksdb/RocksDBOptionsFactory.java

[ISSUE #9025] [RIP-73] Modify Pop Consumption rocksdb init config

---

broker/src/main/java/org/apache/rocketmq/broker/pop/PopConsumerService.java
broker/src/test/java/org/apache/rocketmq/broker/pop/PopConsumerServiceTest.java

Fixes #9106 
When revive is needed to be retried, the original PopConsumerRecord object and the retry one should be independent of each other.
Unit Test.

[ISSUE #9106] Fix revive backoff retry not effective in Pop Consumption based on rocksdb

---

broker/src/main/java/org/apache/rocketmq/broker/coldctr/ColdDataCgCtrService.java
broker/src/test/java/org/apache/rocketmq/broker/coldctr/ColdDataCgCtrServiceTest.java

Fixes #9108 , use fastjson2 to replace fastjson1.

[ISSUE #9108] Refactor ColdDataCgCtrService#getColdDataFlowCtrInfo

---

broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java

fixes #9064 
事务消息， 回查判断RMQ_SYS_TRANS_HALF_TOPIC消息是否在RMQ_SYS_TRANS_OP_HALF_TOPIC 中，优化判断方式。之前代码是先判断Map.containsKey，然后进行removeKey，新的方式是直接removeKey ！= null。之前如果Map.containsKey为真，还需要进行额外的一步removeKey操作，新的方式removeKey！= null，即判断了Map是否存在key，又移出了对应的key，提升了一点点性能。
﻿
Transactional messages: The process involves checking whether messages in RMQ_SYS_TRANS_HALF_TOPIC exist in RMQ_SYS_TRANS_OP_HALF_TOPIC, with an optimized approach for verification. Previously, the code first used Map.containsKey to check existence and then performed removeKey. The new approach directly uses removeKey != null.
In the previous method, if Map.containsKey returned true, an additional removeKey operation was required. In contrast, the new approach both checks if the key exists in the Map and removes the corresponding key in …

[ISSUE #9064] Optimize transaction message callback check logic

---

broker/src/main/java/org/apache/rocketmq/broker/slave/SlaveSynchronize.java
broker/src/test/java/org/apache/rocketmq/broker/slave/SlaveSynchronizeAtomicTest.java

The https://github.com/apache/rocketmq/pull/6426 has fixed topicConfig update atomic problem, but the SubscriptionGroupConfig and MessageRequestMode has not been fixed. So I submit a PR to fix them!

[ISSEU #6426] Fix slave broker SubscriptionGroupConfig and MessageRequestMode updating atomically

---

broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBConsumerOffsetManager.java
broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBSubscriptionGroupManager.java
broker/src/main/java/org/apache/rocketmq/broker/config/v1/RocksDBTopicConfigManager.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/RequestCode.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ExportRocksDBConfigToJsonRequestHeader.java
remoting/src/test/java/org/apache/rocketmq/remoting/protocol/header/ExportRocksDBConfigToJsonRequestHeaderTest.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminExt.java
tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetadataInRocksDBCommand.java
tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java

[ISSUE #9111] Support export broker RocksDB Config to json file

---

common/src/main/java/org/apache/rocketmq/common/config/AbstractRocksDBStorage.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueOffsetTable.java

[ISSUE #8895] Fix NPE when broker shutdown and optimize the log

---

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/AckMessageActivity.java

[ISSUE #9128] Fix NPE when gRPC client ack message immediately after changing proxy

---

broker/src/test/java/org/apache/rocketmq/broker/topic/TopicQueueMappingCleanServiceTest.java

[ISSUE #8728] Add more test coverage for TopicQueueMappingCleanService

---

remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyRemotingAbstract.java

Invoke async should handle raw exception instead of CompletionException

---

docs/cn/Deployment.md
docs/en/Deployment.md

issue url：https://github.com/apache/rocketmq/issues/9155
Brief change log
- Modified the text content in the Deployment. md file
->

[ISSUE #9155][2025-01-23] update doc Deployment Context

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/ExportRocksDBConfigToJsonRequestHeader.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/header/GetConsumeStatsRequestHeader.java
remoting/src/test/java/org/apache/rocketmq/remoting/protocol/header/GetConsumeStatsRequestHeaderTest.java
tools/src/test/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtTest.java

[ISSUE #9152] Broker getConsumeStats supports inputting multiple topics

---

broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManager.java

Fixes #9149
When resetting offsets, it is equally required to persist the offset information for subscription relationships that have never been online, to support scenarios where offset synchronization is needed for backup clusters.

[ISSUE #9149]Assign offset in offsetTable even if the subscription key not exist.

---

acl/src/main/java/org/apache/rocketmq/acl/common/AclUtils.java
acl/src/test/java/org/apache/rocketmq/acl/common/AclUtilsTest.java
acl/src/test/resources/acl_hook/plain_acl.yml

Fixes #9156,  use fastjson2 to replace fastjson1.

[ISSUE #9156] Use fastjson2 in AclUtils#getAclRPCHook

---

store/src/test/java/org/apache/rocketmq/store/lock/AdaptiveLockTest.java

[ISSUE #9177] Fix unstable tests in AdaptiveLockTest.testAdaptiveLock 

---

broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManager.java
broker/src/test/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManagerTest.java
common/src/main/java/org/apache/rocketmq/common/MixAll.java
store/src/test/java/org/apache/rocketmq/store/lock/AdaptiveLockTest.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java

[ISSUE #9172] Clean pull offset and reset offset when delete subscription group

---

namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/ClientRequestProcessor.java

Fixes #9182 
When needCheckNamesrvReady is set to false, this method will always response **name server not ready**.

[ISSUE #9182] Fix NameServer will be not ready forever when set needWaitForService to true

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

Fixes #9176
开启Authorization后，`org.apache.rocketmq.auth.authorization.builder.DefaultAuthorizationContextBuilder#buildContextByAnnotation`，会对PopMessageRequestHeader做一次decode并且更新缓存，但此cache不携带bornTime字段，POPMessageProcessor处理请求时从cache中获取错误的Header，导致`requestHeader.isTimeoutTooMuch()` 校验全部超时，无法消费消息。
add `bordTime`

[ISSUE #9176] Fix pop message header missing fields when enable ACL 2.0

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

When there is a time difference between the client and the server, it can cause issues with suspending long-polling POP requests.

Revert "[ISSUE #9176] Fix pop message header missing fields when enable ACL 2.0"

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

[ISSUE #8589] Optimize RocksDB CQ shutdown when using DoubleWriteCQ

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/TieredMessageStoreTest.java

[ISSUE #9213] Fix get the earliest time error when data is clean up in tiered storage

---

broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
client/src/main/java/org/apache/rocketmq/client/consumer/NotifyResult.java
client/src/main/java/org/apache/rocketmq/client/impl/mqclient/MQClientAPIExt.java
test/src/main/java/org/apache/rocketmq/test/client/rmq/RMQPopClient.java

[ISSUE #9196] Broker return pop stats when receive notification

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerPathConfigHelper.java
broker/src/test/java/org/apache/rocketmq/broker/BrokerPathConfigHelperTest.java

[ISSUE #9221] Extract some common code in BrokerPathConfigHelper

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java

[ISSUE #9184] Optimize QueueLockManager#tryLock method in Pop

---

example/src/main/java/org/apache/rocketmq/example/simple/PopConsumer.java

[ISSUE #9223] Pop consumer example add the default NamesrvAddr

---

client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQProducerImpl.java
client/src/main/java/org/apache/rocketmq/client/producer/DefaultMQProducer.java

… response
Fixes #8997
当broker处于半死不活的状态时（gc，os内存不足等等原因），此时表现无法及时响应客户端的请求。
针对客户端同步发送消息，默认是带有重试策略的。可是此种情况下，客户端可能并没有重试的机会。
详见[分析](https://blog.csdn.net/a417930422/article/details/103489927)。
新增的参数sendMsgMaxTimeoutPerRequest，默认情况下不会影响现有的重试逻辑。
模拟broker暂停的情况，并针对各种情况进行了[测试](https://blog.csdn.net/a417930422/article/details/103489927#test)，情况如下：

[ISSUE #8997] Ensure there is an opportunity to send a retry message when broker no response

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java

[ISSUE #9233] Query message in tiered storage may fail for the first correct index file was not selected

---

broker/src/main/java/org/apache/rocketmq/broker/pop/PopConsumerContext.java
broker/src/main/java/org/apache/rocketmq/broker/pop/PopConsumerService.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PopMessageProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/pop/PopConsumerContextTest.java
broker/src/test/java/org/apache/rocketmq/broker/pop/PopConsumerServiceTest.java

[ISSUE #9246] Support init offset mode in PopConsumerService

---

broker/src/test/java/org/apache/rocketmq/broker/BrokerOuterAPITest.java

This PR increases the sleep duration in invokeSync() from 20ms to 100ms to improve test stability. The previous 20ms timeout was too short, causing intermittent failures due to minor execution delays. By increasing it to 100ms, we ensure consistent timeout behavior, reducing test flakiness and better simulating real-world network latencies. This change aligns with RocketMQ's expected behavior, making the test more reliable across multiple runs.
Fixes #6654

Fix unstable test: BrokerOuterAPITest.test_needRegister_timeout

---

broker/src/main/java/org/apache/rocketmq/broker/schedule/ScheduleMessageService.java

5.3.2版本，延迟消息，投递失败，投递设置的开始offset有误。
具体issues地址：https://github.com/apache/rocketmq/issues/9249

[ISSUE #9249] When delivery fails, there is an incorrect start offset in the delivery settings

---

store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java
store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java

…ckpoint
Fixes #9241 RocksDBConsumeQueueStore do not need update storeCheckpoint

[ISSUE #9241] RocksDBConsumeQueueStore do not need to update storeCheckPoint

---

broker/src/main/java/org/apache/rocketmq/broker/processor/QueryAssignmentProcessor.java

[ISSUE #9244] Avoid writing dirty data in consumption mode

---

client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java

Clarified that the key of the brokerAddrTable map is the brokerName, not brokerClusterName, to prevent ambiguity.
Closes #8701

[ISSUE #8701] Fix documentation for brokerAddrTable property in MQClientInstance.java

---

docs/en/Configuration_Client.md
docs/en/Configuration_System.md

- Updated Configuration_Client.md and Configuration_System.md to include compatibility information for RocketMQ 5.x.
- Clarified addressing modes and client configuration options.
- Improved formatting for better readability.
- As per the issue request, we have identified and included details regarding RocketMQ 5.x server configuration, ensuring users 
have up-to-date guidance.
Fixes #8243

[ISSUE #8243] Update Configuration Docs for RocketMQ 5.x Compatibility

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

[ISSUE #9259] Remove duplicate flushing operation of StoreCheckpoint

---

store/src/main/java/org/apache/rocketmq/store/index/IndexService.java
store/src/test/java/org/apache/rocketmq/store/index/IndexServiceTest.java

Fixes [#issue_id](https://github.com/apache/rocketmq/issues/7948)
Adjust the creation location of the phyOffsets
Write necessary unit-test

[ISSUE #7948] Prevent invoking the queryMessage method lead to OOM

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java
tieredstore/src/test/java/org/apache/rocketmq/tieredstore/file/FlatMessageFileTest.java

[ISSUE #9271] Enhance tiered storage getQueueOffsetByTimeAsync

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java

[ISSUE #9282] Optimize BrokerController#printWaterMark

---

store/src/main/java/org/apache/rocketmq/store/CommitLog.java

Fixes #9304 
In the ColdDataCheckService#isMsgInColdArea() method, when forcibly casting the consume queue to ConsumeQueue, an error will be thrown if its type is not ConsumeQueue.

[ISSUE #9304] Resolve cold data read control issue in DefaultMessageStore

---

common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItem.java
common/src/main/java/org/apache/rocketmq/common/stats/MomentStatsItemSet.java
common/src/main/java/org/apache/rocketmq/common/stats/StatsItem.java
common/src/main/java/org/apache/rocketmq/common/stats/StatsItemSet.java
store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java

Fixes #9300 
StatsItemSet and MomentStatsItem record a large amount of statistics for topics and consumers. Currently, they are only cleaned up when the resource is deleted. If a resource is abandoned by the user but not actually deleted, this statistical information will remain in memory indefinitely.

[ISSUE #9300] Periodic cleanup of inactive items in StatsItemSet

---

broker/src/main/java/org/apache/rocketmq/broker/mqtrace/ConsumeMessageContext.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java
store/src/main/java/org/apache/rocketmq/store/GetMessageResult.java

Fixes #9286 
The SQL filtering is causing excessive CPU consumption, and the current system does not record the filtered message information for subscription groups. Therefore, there is a need to add this statistical information to facilitate the evaluation of resource consumption for each subscription group in the future.

[ISSUE #9286] Counting the filtered message when filter by SQL92

---

store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

Fixes #9284 
When pulling the message with an overflow of one, there may be an issue with not updating the behind information.

[ISSUE #9284] When pullMessage overflow one, should refresh recordDiskFallBehind data

---

broker/src/main/java/org/apache/rocketmq/broker/coldctr/ColdDataCgCtrService.java
broker/src/main/java/org/apache/rocketmq/broker/processor/PullMessageProcessor.java
broker/src/main/java/org/apache/rocketmq/broker/subscription/SubscriptionGroupManager.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java
common/src/main/java/org/apache/rocketmq/common/MixAll.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

…l consumer when pullmessage
Fixes #9279
1. When the "rejectPullConsumerEnable" configuration is enabled, restrict pull requests when pulling messages.
2. Automatic creation and addition of switch recognition for subscription groups to prevent abuse of system subscriptions.

[ISSUE #9279] Restrict system subscription group creation and add pull request rejection policy

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
remoting/src/main/java/org/apache/rocketmq/remoting/protocol/admin/TopicStatsTable.java
store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java
tools/src/main/java/org/apache/rocketmq/tools/admin/DefaultMQAdminExtImpl.java
tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicStatusSubCommand.java

Fixes #9297 
The server currently collects statistics on the topic put TPS, but this information isn’t available through the command line tool. It is recommended to add it to TopicStatusSubCommand by introducing a new display of the topic TPS information for users to view.

[ISSUE #9297] Supports outputting topic put TPS in TopicStatusSubCommand

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AbstractSendMessageProcessor.java

Fixes #9302 
Currently, when setting msgType in SendMessageContext, only normal messages and ordered messages are distinguished. Transactional messages and delayed messages are not differentiated.
In subsequent implementations of the send message hook, it won't be possible to differentiate the actual message type.

[ISSUE #9302] SendMessageContext add message type

---

broker/src/main/java/org/apache/rocketmq/broker/client/DefaultConsumerIdsChangeListener.java

[ISSUE #9115] Optimize the broker's reverse notification for consumerId change

---

broker/src/main/java/org/apache/rocketmq/broker/client/ClientChannelAttributeHelper.java
broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java
broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
broker/src/test/java/org/apache/rocketmq/broker/client/ProducerManagerTest.java
client/src/main/java/org/apache/rocketmq/client/impl/MQClientManager.java
client/src/main/java/org/apache/rocketmq/client/impl/factory/MQClientInstance.java
common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java

support reject producer when not transaction producer
Fixes #9288 
1. The current broker retains all producer channel information, which can consume a significant amount of resources when there are a large number of producers. In non-transactional message scenarios, the producer channel information is not useful. It would be beneficial to consider adding a switch to not record PID information in these scenarios.
2. Support fast channel event processing to improve the speed of disconnection.

[ISSUE #9288] Support the disablement of producer registration and fast channel shutdown

---

proxy/src/main/java/org/apache/rocketmq/proxy/service/sysmessage/AbstractSystemMessageSyncer.java

In proxy cluster mode, if specified a system topic cluster, it can not create system topics to all the brokers in 'systemTopicClusterName' cluster if already existed.
Fixes #9326

Make sure to create system topics to all the brokers in 'systemTopicClusterName' cluster

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreFile.java

[ISSUE #9358] Timediff should multiply 1000 when query message from tiered storage

---

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java

Fixes #9351
Add a simple cache in ConsumerManager to avoid traversing the map for each query
In our internally maintained version of RocketMQ, this functionality and performance have been verified.

[ISSUE #9351] Add topic-group mapping in queryTopicConsumeByWho command

---

broker/src/main/java/org/apache/rocketmq/broker/BrokerController.java
broker/src/main/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManager.java
broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
broker/src/test/java/org/apache/rocketmq/broker/offset/ConsumerOffsetManagerTest.java

[ISSUE #9369] Fix reset offset commit pull offset when use pop consumer service

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java
tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java

[ISSUE #9371] Delete ConsumeQueue index before CommitLog in tiered storage

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreService.java

[ISSUE #9233] Fix query time boundary calculation in tiered storage

---

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java

Fixes #9377
1. shutdown traceExecutor gracefully when shutdown AsyncTraceDispatcher;
2. optimize flush(), no need to check size of appenderQueue, submitted tasks will be executed.
test

[ISSUE #9377]fix 'send trace data can fail if shutdown producer  immediately'

---

proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivity.java
proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageResponseStreamWriter.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageActivityTest.java
proxy/src/test/java/org/apache/rocketmq/proxy/grpc/v2/consumer/ReceiveMessageResponseStreamWriterTest.java

[ISSUE #9253] Make the message visible earlier when response process encounters errors

---

broker/src/main/java/org/apache/rocketmq/broker/processor/PopReviveService.java

Fixes #8651 
Lag is maxQueueOffset plus nextPullOffset

[ISSUE #8651] Fix revive topic process lag metric calculation

---

proxy/src/main/java/org/apache/rocketmq/proxy/remoting/RemotingProtocolServer.java

Fixes #8232 
Register processsors after thread pool initialization.

[ISSUE #8232] Fix the issue that proxy remoting thread pool isolation does not take effect

---

store/src/main/java/org/apache/rocketmq/store/MessageExtEncoder.java
store/src/test/java/org/apache/rocketmq/store/AppendCallbackTest.java
store/src/test/java/org/apache/rocketmq/store/BatchPutMessageTest.java

[ISSUE #9416] Fix batch send messages have the same message id when consumed

---

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java
broker/src/test/java/org/apache/rocketmq/broker/client/ConsumerManagerTest.java

Fixes wrong value in topic-group cache when registerConsumer  #9352 
In our use case, we used other methods to manage topic-group mapping, so we missed the test here.
In this PR, the unit test is improved, which not only verifies whether the returned result is empty, but also verifies whether the specific value is correct.

[ISSUE #9352] Fix wrong value in topic-group cache

---

broker/src/main/java/org/apache/rocketmq/broker/processor/AdminBrokerProcessor.java
common/src/main/java/org/apache/rocketmq/common/MixAll.java
common/src/test/java/org/apache/rocketmq/common/MixAllTest.java
container/src/main/java/org/apache/rocketmq/container/BrokerContainerProcessor.java
controller/src/main/java/org/apache/rocketmq/controller/processor/ControllerRequestProcessor.java
namesrv/src/main/java/org/apache/rocketmq/namesrv/processor/DefaultRequestProcessor.java

Fixes #9439
utilize MixAll.isWindows for platform-specific escaping
Affected files:
- `MixAll.java`: utilize MixAll.isWindows for platform-specific escaping
The above is before the modification, you can see the bug. The following is after the modification, you can see the program returns normally.

[ISSUE #9439] Add escape for win in the method returning broker configuration

---

client/src/main/java/org/apache/rocketmq/client/trace/AsyncTraceDispatcher.java

in k8s cluster, when deploy a workload,  in pod A  the app is starting. then deploy again right now, pod A will be destoryed. sometimes error log: java.lang.IllegalStateException: Shutdown in progress
In Idea, we break a point on this line, then start the app. then click shutdown, will reproduce this.

Fix IllegalStateException during app shutdown caused by premature shutdown trigger

---

common/src/main/java/org/apache/rocketmq/common/utils/NetworkUtil.java
common/src/test/java/org/apache/rocketmq/common/utils/IPAddressUtilsTest.java
store/src/main/java/org/apache/rocketmq/store/DefaultMessageStore.java

Fixes #9497 
to solve getEarliestMessageTime throw expception problem in ipv6 env
[](https://github.com/apache/rocketmq/pull/8567)
1. in unit test, test various ipv6, like [2001:0db8:85a3:0000:0000:8a2e:0370:7334%eth0]
2. test in ipv6 envirment and ipv4, no exception throw

[ISSUE #9497] Fix IndexOutOfBoundsException in getEarliestMessageTime when running in IPv6 environment

---

proxy/src/main/java/org/apache/rocketmq/proxy/config/ProxyConfig.java
proxy/src/main/java/org/apache/rocketmq/proxy/service/cert/TlsCertificateManager.java

This PR makes the watch interval for TLS certificate and key files configurable in the Proxy module.
Previously, the interval was hardcoded to 1 hour, which is not flexible for different production environments. A new configuration property tlsCertWatchIntervalMs has been introduced in ProxyConfig with a default value of 1 hour (60 * 60 * 1000ms), which is more reasonable for most use cases.
Fixes #8920

[ISSUE #8920] Make TLS certificate watch interval configurable

---

store/src/main/java/org/apache/rocketmq/store/lock/AdaptiveBackOffSpinLockImpl.java

[ISSUE #9530]opti: Reduce unnecessary memory allocation in adaptiveBackOffSpinLock

---

broker/src/main/java/org/apache/rocketmq/broker/topic/TopicConfigManager.java

Fixes #9520 
Remove unnecessary topicConfig data version change when enable split registration

[ISSUE #9520] Remove unnecessary topicConfig data version change when enable split registration

---

tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java

[ISSUE #9544] Must correct file size when init the file segment

---

auth/src/main/java/org/apache/rocketmq/auth/authorization/chain/AclAuthorizationHandler.java
auth/src/test/java/org/apache/rocketmq/auth/authorization/AuthorizationEvaluatorTest.java

Fixes https://github.com/apache/rocketmq/issues/9539

[ISSUE #9539] Fix compare policy entry logic in ACL 2.0

---

remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java

Fixes https://github.com/apache/rocketmq/issues/9555

[ISSUE #9555 ]fix the npe in the hashCode method when subscriptionDataSet is null

---

broker/src/main/java/org/apache/rocketmq/broker/client/ConsumerManager.java

[ISSUE #9553] Improve performance by avoiding repeated get(key)

---

proxy/src/main/java/org/apache/rocketmq/proxy/processor/DefaultMessagingProcessor.java
proxy/src/main/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessor.java
proxy/src/test/java/org/apache/rocketmq/proxy/processor/ReceiptHandleProcessorTest.java

Fixes #7837 
1. Complete ReceiptHandleProcessor's start() and shutdown()
2. Complete DefaultMessagingProcessor‘s start() and shutdown()
UT

Fix start() and shutdown() of DefaultMessagingProcessor
